- src/sandstorm/sandstorm-http-bridge.c++
I was seeing errors when git made large POST requests using `Transfer-Encoding: chunked`.
In its current form, `sandstorm-http-bridge` forwards these requests with neither the Content-Length nor the Transfer-Encoding header set -- instead it indicates the end of the content by calling `shutdownWrite()`. Unfortunately, this scheme does not seem to be recognized by the servers in my apps; they truncate such requests and return early, which causes further problems when `RequestStreamImpl`'s `stream` gets written to after it gets moved into the `HttpParser`, triggering a segfault.
This patch implements chunked transfer encoding and prevents early responses from causing problems.
I think git is our first client to test this code path at all. I think that all of our other apps that use …
> use chunked encoding for upload streams of unknown length; use refcounted stream

- shell/server/proxy.js
git provides no simple way to add an "Authorization: Bearer" header to HTTP requests. We could push to add support for it -- see [this thread](http://article.gmane.org/gmane.comp.version-control.git/261965) for some discussion -- but in the meantime we need another way to allow a git client to communicate with a grain.
This patch allows any incoming API request with "user-agent" header matching "git/*" to pass its token as a basic-auth password field. The username field is ignored.
This scheme fits nicely with git's support for caching credentials. The user can choose a username, say "myrepo", for the token, and then configure git like this:
```
[remote "origin"]
url = https://myrepo@alpha-api.sandstorm.io/repo.git
```
and now the token can be cached using any of git's "credential …
> allow basic auth for git

- src/sandstorm/run-bundle.c++
This should fix non-root operation on newer Linux kernels.
> run-bundle: Write "deny" to setgroups

- shell/client/shell.html
- shell/shared/demo.js
- shell/shared/install.js
- shell/shared/shell.js
See commit log.
Sorry that I force pushed; it means that GitHub won't unify this with https://github.com/sandstorm-io/sandstorm/pull/212 .
> Create /appdemo/ to launch a demo instance of an app

- shell/shared/demo.js
> Tell the client about UserActions so it knows when not to create them

- tests/package.json
- tests/tests/grain.js
Hopefully this will fix our intermittent issues with this test
> Add a wait to the test that starts a grain

- shell/server/startup.js
- shell/shared/db.js
- src/sandstorm/run-bundle.c++
> Reset OAuth automatically when BASE_URL changes or manually from command line

- shell/shared/db.js
> Make WILDCARD_HOST configuration more robust.

- Vagrantfile
The purpose of this change is to stop using the VirtualBox-native
file sharing system, which seems to be both slower and less POSIX-y
than NFS.
> Adjust Vagrantfile to do file sharing via NFS

- src/sandstorm/http-bridge.capnp
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/sandstorm-http-bridge.capnp
... so that apps using sandstorm-http-bridge get proper access to SessionContexts.
> Implement ApiForwarder 

- shell/client/shell.html
- shell/shared/grain.js
Also adds a postMessage endpoint for "setTitle" which allows apps to
explicitly set their title. This is prepended onto the normal title.
Fixes #165
> Sets the window title for the grain template

- shell/server/pre-meteor.js
> Changed DNS error messages to be more clear based on the error code

- src/sandstorm/run-bundle.c++
Fixes #269.
I think this is strictly superior to #278. Here we match on the entire command string, so we don't risk accidentally killing `sandstorm-supersoaker` or whatever.
> Use /proc/<pid>/cmdline in killall() implementation.

- shell/server/backup.js
> Filter out irregular files from backup

- src/sandstorm/spk.c++
> Remove files that are not found when running `spk dev`

- shell/shared/demo.js
- shell/shared/install.js
Along with https://github.com/sandstorm-io/sandstorm-website/pull/53,
this fixes #292
> Change install to redirect to appdemo for non logged in users

- install.sh
This commit shows how Sandcats support will be added to the installer.
If people have feedback, let me know. I intend to continue to revise this over the next few days, including making some changes to the Sandcats backend to support it, and then ship it by the end of the week.
Please *don't* merge this yet! But please feel free to review.
> Add basic Sandcats support to installer

- shell/client/shell.html
- shell/shared/db.js
- shell/shared/install.js
- shell/shared/shell.js
> Add appMarketingVersion to the right of user actions

- Makefile
Yeah, apologies for not catching this in my previous pull request.
I only tested the failure case, not the success case.
> Only fail the build if that is actually needed

- src/sandstorm/supervisor.c++
- src/sandstorm/supervisor.h
(I'm making this a pull request so that it goes through Jenkins, since otherwise I'm not completely confident that this didn't break something.)
> Refactor supervisor to allow some limited reuse as a library

- .dockerignore
- Dockerfile.dev
- install.sh
Also fix a few common bugs for users that try to build with Dockerfile.dev.
> Fix issue 322

- tests/README.md
- tests/package.json
The Selenium version we're pinned at is broken for newer versions of Firefox: https://code.google.com/p/selenium/issues/detail?id=8399
> Update selenium version and instructions on how to start it. Line wrap the README.

- shell/shared/testing.js
- tests/tests/grain.js
This fixes the problem where running the tests multiple times on the same database would fail.
> Clear mock user data before running test suite. Use 'upsert' for creating mock users.

- shell/client/shell.css
- shell/client/shell.html
- shell/shared/admin.js
- shell/shared/shell.js
- shell/shared/signup.js
> Add admin configurable dialogs for the splash page and signup

- install.sh
Server mode emphasizes (but does not require) integration with the
Sandcats.io dynamic DNS service.
Dev mode emphasizes dev accounts and requires root by default, for
spk dev to work.
MAIL_URL configuration is gone.
> Rewrite install.sh to clarify server vs. dev mode

- install.sh
@ocdtrekkie asked on IRC, so I thought I'd add this info to the script.
> Explain why we want root for autosetup

- install.sh
Until now, these were owned by root, which meant the Sandstorm bundle
would crash when trying to access them (with EACCESS), resulting in
the frontend restarting. Presumably this would lead to a loop where
the frontend crashes & restarts every 60 seconds.
> Adjust Sandcats conf file permissions

- src/sandstorm/run-bundle.c++
> run-bundle: fix up sandcats permissions

- src/sandstorm/run-bundle.c++
> Fix issue where mongo passwords start with '-'

- find-meteor-dev-bundle.sh
- shell/run-dev.sh
Some assumptions about PWD or meteor install location were made.  This cleans
those up.
> Meteor dev scripts: work from any folder

- shell/client/shell.css
- shell/client/shell.html
- shell/server/hack-session.js
- shell/shared/admin.js
- shell/shared/shell.js
- shell/shared/signup.js
Added it as a tab in the admin settings page. Also moved invite users into a tab.
> Add admin user management

- install.sh
> Strip trailing slash off for DEFAULT_WILDCARD in install.sh

- shell/client/shell.html
- shell/packages/sandstorm-email/email.js
- shell/shared/admin.js
> Use input smtpUrl instead of configureed one when sending test email

- shell/lib/db.js
Submitting this by itself to make sure that it meshes with other powerbox plans, before I build anything on top of it.
> Schema for contacts.

- src/sandstorm/spk.c++
While there, take the opportunity to replace ChildProcess with Subprocess from util.
> spk pack: pass --threads=0 to xz for (possibly)-faster compression

- .gitignore
- CHANGELOG.md
- Makefile
- README.md
- shell/.meteor/packages
- shell/client/shell.css
- shell/client/shell.html
- shell/shared/shell.js
> Add changelog and display it on Sandstorm about page

- Makefile
- installer-tests/Vagrantfile
- installer-tests/automatic-dev-install-on-jessie.t
- installer-tests/full-server-install-on-jessie-with-userns-sysctl.t
- installer-tests/install-without-root.t
- installer-tests/run_tests.py
Now that the installer tests pass when I run them on Jenkins, I'm going to merge them.
This pull request is here to notify the team that I'm doing that.
> Installer tests pass on Jenkins

- shell/shared/grain.js
Fixes a couple of minor issues @dwrensha pointed out in https://github.com/sandstorm-io/sandstorm/pull/471
> Fix a misnamed field and wrong comment

- shell/client/shell.css
- shell/client/shell.html
- shell/server/proxy.js
- shell/shared/admin.js
- shell/shared/stats.js
Merge usage stats into this page.
Add log page that tails sandstorm.log (#467)
Prompt for configuration when enabled an unconfigured OAuth service (#451)
> Various changes to admin page

- shell/server/pre-meteor.js
Should help with our error monitoring
> Return a 404 when a grain cannot be found

- shell/packages/sandstorm-accounts-oauth/oauth_common.js
- shell/packages/sandstorm-accounts-oauth/package.js
- shell/shared/admin.js
Deps has been deprecated since https://github.com/meteor/meteor/commit/8e7cd297bf5addd96ffba9b5309e471ffb8fe79a.
> Deps -> Tracker

- README.md
Thanks to @sunu for reporting this on IRC.
> Fix link to packaging tutorial

- install.sh
- installer-tests/Vagrantfile
- installer-tests/fail-on-32-bit-system.t
- installer-tests/prepare-for-tests.sh
- installer-tests/run_tests.py
* Add an installer test, and
* Fix it, with @zarvox 's help
> Detect architecture before running userns test program

- shell/server/proxy.js
This is useful for the case where a grain crashes too fast to be able to
open the debug log. It works like `getWwwFileHack` in that the
supervisor is started, but the main UIView is never started.
> Allow viewing the log of a grain without starting the UIView

- shell/client/shell.html
Re #531
I hope a PR doesn't take you more time than updating the text yourself, in which case I'll just sit back and enjoy all the improvements to Sandstorm ;)
> Clarify that SMTP server must be a relay

- shell/server/backup.js
> Ensure grain is deleted if a restore fails

- shell/packages/accounts-email-token/token_server.js
> Trim whitespace from email tokens

- docs/administering.md
- docs/administering/demo.md
- docs/administering/email.md
- docs/developing.md
- docs/developing/email-from-apps.md
- docs/developing/raw-packaging-guide.md
- mkdocs.yml
This migrates some of the docs that used to live on the wiki.
> Migrating more docs

- shell/public/offer-template.html
- shell/server/hack-session.js
- shell/server/proxy.js
- shell/shared/grain.js
> Get offer templates working for anonymous users.

- shell/.meteor/packages
- shell/.meteor/versions
- shell/client/shell.css
- shell/client/shell.html
- shell/packages/sandstorm-accounts-ui/login_buttons.html
- shell/packages/sandstorm-accounts-ui/login_buttons.js
- shell/packages/sandstorm-accounts-ui/login_buttons.less
- shell/packages/sandstorm-accounts-ui/login_buttons_dropdown.html
- shell/packages/sandstorm-accounts-ui/login_buttons_dropdown.js
- shell/packages/sandstorm-ui-topbar/package.js
- shell/packages/sandstorm-ui-topbar/topbar.html
- shell/packages/sandstorm-ui-topbar/topbar.js
- shell/shared/grain.js
- shell/shared/shell.js
- tests/apps/ip-networking.js
- tests/apps/powerbox.js
- tests/tests/grain.js
(Not ready for merge yet.)
The topbar package allows topbar controlls to be dynamically registered and unregistered, and provides a way to actually embed those registrations syntactically within other templates.
This refactoring is incomplete:
- The mobile view is broken.
- Tests are probably wildly broken due to element IDs changing.
- A lot of dead code is still lying around.
With that said, the desktop view *should* look and behave as it did before this change.
> [WIP] Add dynamic topbar package, refactor UI to use it.

- shell/server/permissions.js
> Fix bug in resharing.

- shell/shared/devAccounts.js
- tests/commands/loginDevAccount.js
- tests/tests/grain.js
@paulproteus reported an issue with sharing, and I tried to debug it (and failed). I wrote a failing test that shows off what's wrong.
@dwrensha, can you take a look when you get the chance?
> Add sharing test

- shell/shared/admin.js
Fix #616 
Manually testing this now, but submitting as pull request so I can get Jenkins to verify it.
> ObjectIncluding is part of Match

- install.sh
- installer-tests/full-server-install-on-jessie-with-broken-hostname.t
Close #614 
**Status**: Running tests locally; ETA 5 min or so.
> If hostname -f exits with failure, do not crash

- shell/shared/admin.js
This caused them to never be `ready` and would leave users stuck on a
loading page.
> Subscriptions that failed the auth check were returning exceptions

- docs/vagrant-spk/installation.md
Also clean up formatting by using bash syntax highlighting.
Also remove stray paragraph that was presuably vestigial.
> In docs, link to new Windows installer for vagrant-spk

- shell/shared/admin.js
Most functions named check() throw an exception, rather than returning a
boolean.
> admin.js: rename checkAuthForPublish

- shell/client/shell.scss
- shell/packages/sandstorm-accounts-ui/login_buttons.html
Addresses #586. Ideally this would be something better than title text, and allow having a link to the docs, but this is a decent first step.
> Add an info bubble to email login.

- shell/server/backup.js
> Allow restore-from-backup to use DevApps

- icons/install.svg
- icons/notification.svg
- icons/restore.svg
- icons/upload.svg
> Additional graphics for install, restore, upload, notification

- Makefile
- icons/install.svg
- icons/notification.svg
- icons/restore.svg
- icons/upload.svg
The other SVGs appear to be normalized in this manner, so I'm doing similarly with the new ones.
Also adding them to the Makefile so I can use them in the app list UI later.
> Adjust SVGs - #000000 for all colors, add to Makefile

- shell/client/_account.scss
- shell/packages/sandstorm-accounts-ui/account-settings.html
- shell/packages/sandstorm-accounts-ui/account-settings.js
This also removed the "add identity" button since it never worked and soon the styling will change to not include it anyways.
Should this css be going into _account.scss or not? Especially the `body>.popup.billing-prompt` doesn't quite fit.
> Blackrock payments css

- src/sandstorm/run-bundle.c++
After adding metadata to GitWeb, I was getting the following error:
```
sandstorm/run-bundle.c++:2335: failed: execv(args[0], const_cast<char**>(args.begin())): Argument list too long
```
This patch should fix the problem.
> Pass mongo command over stdin to work around MAX_ARG_STRLEN.

- shell/client/_geometry.scss
- shell/client/_topbar.scss
- shell/client/shell.html
- shell/client/shell.scss
- shell/lib/db-deprecated.js
- shell/packages/sandstorm-ui-applist/applist-common.js
- shell/packages/sandstorm-ui-topbar/topbar.html
- shell/packages/sandstorm-ui-topbar/topbar.js
- shell/server/pre-meteor.js
- shell/shared/demo.js
- shell/shared/grain.js
- shell/shared/shell.js
- src/sandstorm/package.capnp
I'm going to collect commits that address issues with the shell redesign here.
> Continuing shell redesign 

- docs/administering/reverse-proxy.md
- mkdocs.yml
Documentation for an HTTPS reverse-proxy with NGINX.
Figured it may be useful for others.
> Docs: Reverse Proxy

- shell/packages/sandstorm-accounts-ui/login_buttons.html
- shell/packages/sandstorm-accounts-ui/login_buttons.js
Testing done:
* Manually tested with a non-admin dev account: got no admin link.
* Manually tested with an admin dev account: got the admin link.
> Only show admin links list ifAdmin

- shell/client/_account.scss
> Update subscriptions styling

- shell/client/_topbar.scss
Also fixes the "horizontal line through the top of the content" issue.
> Improve styles on mobile

- shell/client/_account.scss
- shell/packages/sandstorm-db/db.js
Also sort plans by price, and make sure computeLabel is capitilized
> Add computeLabel field to Plans collection

- shell/client/_applist.scss
- shell/client/_grainlist.scss
- shell/client/_partials.scss
- shell/client/_topbar.scss
- shell/packages/sandstorm-ui-applist/applist.html
- shell/packages/sandstorm-ui-grainlist/grainlist.html
- shell/packages/sandstorm-ui-topbar/topbar.html
This ensures Internet Explorer can rescale the SVGs.
> Use DIV and background-image instead of IMG

- tests/commands/installApp.js
- tests/tests/grain.js
It seems that somehow the .app-action in the popular-container was interfering with these tests.
> Fix tests by using a more precise CSS selector.

- shell/client/shell.html
- shell/shared/grain.js
The grainSize subscription is now handled by GrainView.
> Delete some obsolete code and clean up some comments.

- shell/client/_account.scss
Also change to always displaying the iframe over the clickable elements,
even on desktop
> Fix stripe iframe display on Internet Explorer

- shell/client/_grainlist.scss
We don't have the pixels for that much text.
> Hide new ownership column in grainlist on mobile

- shell/client/grainview.js
- shell/shared/grain.js
Also, openSession was referencing some non-existent fields like `self._query`.
> Get setPath() to work once again.

- shell/client/_topbar.scss
* Fix issue where horizontal rule did not show when mobile menu expanded
* Adjust topbar padding
* Fix "share" icon placement in mobile menu
> Adjust mobile topbar

- shell/client/_geometry.scss
- shell/client/_topbar.scss
- shell/client/shell.scss
All of the popups probably need to be reworked for consistency and alignment,
but this is a start.
> Align popup contents in some places.

- shell/client/shell.html
- shell/packages/sandstorm-accounts-ui/account-settings.html
This makes it so that clicking the text toggles the checkbox.
> Wrap instances of <input type="checkbox"> in <label>

- shell/packages/sandstorm-accounts-ui/login_buttons.js
> Use a selector for logout that works

- Vagrantfile
This change makes the Vagrantfile detect the host's CPU count and RAM size
using powershell, which is available by default on Win7 and newer.  If
powershell is not available, we'll fall back to the old 1-CPU, 512MB-RAM
behavior.
> Vagrantfile: detect CPUs/RAM on Windows

- shell/packages/sandstorm-db/db.js
- shell/server/installer.js
- shell/shared/install.js
> Perform all installer tasks reactively on the main replica.

- shell/client/shell.html
It used to say `Click "My Files" to create a new file`but now its `Click "New..." to create a new file` after the UI rework.
> Wording after app is installed

- shell/client/_topbar.scss
- shell/client/shell.html
- shell/shared/grain.js
> Change download backup button to a spinner while waiting on server

- shell/client/shell.scss
- shell/packages/sandstorm-ui-applist/applist-client.js
- shell/packages/sandstorm-ui-applist/applist.html
> Show spinner immediately after creating a grain

- install.sh
- installer-tests/full-server-install-with-experimental-https.t
DONE:
* Write tests
DOING NOW:
* Verify that this passes the existing tests
> Add EXPERIMENTAL flag for getting HTTPS certs during install

- Vagrantfile
> Instructions to share /home/vagrant on Windows

- docs/developing/handbook.md
- docs/developing/troubleshooting.md
This changeset includes the commit in #799 and adds one other troubleshooting note to the docs.
> Base href in docs

- docs/developing/handbook.md
https://github.com/audreyt/ethercalc/issues/240#issuecomment-135325954
> Add base href tip as per @paulproteus

- icons/apps.svg
- icons/open-grain.svg
> New menu icons for Apps page and Open or Grains page

- shell/client/grainview.js
- shell/packages/sandstorm-db/db.js
- shell/server/proxy.js
- shell/shared/grain.js
This will allow users' grains to not refresh on a session being removed from the database (eg. when their laptop suspends and resumes after a Session has been removed from the DB).
> Resumable sessions

- docs/developing/raw-packaging-guide.md
> Fix comma <=> period typo

- docs/administering/wildcard.md
> Fix incomplete sentence in wildcard docs

- docs/install.md
Not sure why I didn't think of these things earlier.
> Various tweaks to make the PGP install docs easier to follow.

- docs/developing/path.md
- mkdocs.yml
Also document Host: and X-Forwarded-Proto: while we are it.
> Add docs for X-Sandstorm-Base-Path: header

- docs/analytics.js
> Add Piwik to docs.sandstorm.io

- shell/packages/sandstorm-db/migrations.js
- shell/shared/demo.js
I had overlooked these in https://github.com/sandstorm-io/sandstorm/pull/958
grep informs me that nothing else needs to be updated.
> update remaining uses of sandstormBackend

- shell/packages/sandstorm-accounts-ui/account-settings.js
- shell/packages/sandstorm-accounts-ui/accounts-ui-methods.js
- shell/packages/sandstorm-db/db.js
- shell/server/pre-meteor.js
> Unbreak profile picture upload.

- shell/packages/sandstorm-db/profile.js
I usually bitwise-or my handle with things ;)
> Fix a typo that broke handle autocreation for dev accounts

- shell/packages/sandstorm-autoupdate-apps/autoupdate-apps.js
- shell/packages/sandstorm-db/db.js
- shell/server/pre-meteor.js
- shell/server/proxy.js
- shell/shared/demo.js
- shell/shared/install.js
- shell/shared/testing.js
Fixes some more breakage from #958.
> Fix web publishing and grain upgrades.

- meteor-bundle-main.js
Refs #984 
I _think_ this fix is correct. I'm going to think about it and also test it more now.
> Calculate if to refresh certs based on newest valid cert

- shell/client/shell.html
- shell/packages/sandstorm-accounts-ui/account-settings.html
- shell/packages/sandstorm-accounts-ui/account-settings.js
- shell/packages/sandstorm-ui-applist/applist-client.js
- shell/packages/sandstorm-ui-applist/applist.html
- shell/packages/sandstorm-ui-grainlist/grainlist-client.js
- shell/packages/sandstorm-ui-grainlist/grainlist.html
- shell/shared/admin.js
- shell/shared/shell.js
> Set document.title on more routes

- docs/vagrant-spk/packaging-tutorial-meteor.md
- docs/vagrant-spk/packaging-tutorial.md
- mkdocs.yml
@jparyani and/or @zarvox your feedback very welcome.
I might self-merge and give this to Bill right now for user testing, but I'm also happy to wait ~20 minutes before doing so.
> Add Meteor-specific packaging tutorial

- shell/packages/accounts-email-token/token_server.js
- shell/packages/sandstorm-accounts-ui/accounts-ui-methods.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-permissions/permissions.js
- shell/server/hack-session.js
- shell/server/proxy.js
- shell/shared/grain.js
This addresses some of @zarvox's comments from #983.
> 983 cleanup

- shell/client/_admin.scss
- shell/client/shell.html
- shell/packages/sandstorm-db/db.js
- shell/shared/admin.js
- shell/shared/shell.js
- shell/shared/stats.js
This will send a notification to admins of a Sandstorm server, asking if they wish to opt-in to stats collection.
> Self hoster data optin

- shell/shared/stats.js
There was a bug in the logic before, where the sending of the notification would set the `reportStats` setting to false, and skip all of the first time visitor logic. This also made it so the notification could never be dismissed.
> Fix stats collection prompt not working correctly upon receiving notification

- shell/shared/grain.js
> Fix display of existing API tokens.

- shell/client/shell.html
> shell: link to log tab on server errors

- tests/apps/web-publishing.js
This would've caught the error fixed by
97cb7a28ca71862fd66ebb8b6d81deafae307c87.
> Add test for web publishing

- src/sandstorm/run-bundle.c++
This commit checks if `/var/mongo/mongod.lock` exists and is non-empty, and if so, removes the file, before attempting to start mongo.
This fixes a problem encountered by a couple of people where Sandstorm would fail to start, see #1016.
TESTING DONE:
* I've stopped Sandstorm gracefully, created that `mongod.lock` file, and then started Sandstorm. Before this patch, Sandstorm fails to start; after this patch, Sandstorm starts.
* I will run this build on my server (rose.sandcats.io) with a loop that kills mongo every 2 minutes and use that Sandstorm install a bunch today, to double-check that nothing crazy seems to happen.
> Remove stale mongod.lock file, if present

- docs/developing/web-publishing.md
> Update static publishing docs

- shell/packages/sandstorm-accounts-ui/login_buttons.html
Close #1072
Thanks to @ndarilek.
> Remove unnecessary ARIA role

- shell/server/proxy.js
> Check for null proxy before trying to close

- src/sandstorm/spk.c++
cc @paulproteus 
Addresses sandstorm-io/vagrant-spk#92
> spk: don't generate files with trailing whitespace

- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-ui-applist/applist-client.js
- tests/apps/web-publishing.js
Per @neynah's request.
Also remove a (related) dead function.
> Change fallback nounPhrase from "instance" to "grain"

- shell/client/grainview.js
Fixes #1038.
Fixes sandstorm-io/vagrant-spk#72
> Show dev app icon when opening grain with dev package override

- shell/client/_account.scss
- shell/client/_applist.scss
- shell/client/_partials.scss
- shell/client/_topbar.scss
- shell/client/shell.scss
> Add 'cursor: pointer;' to unstyled-button.

- docs/vagrant-spk/platform-stacks.md
Thanks @zarvox 
Self-merging this 100% docs pull request
> Mention static stack

- shell/shared/admin.js
#1161 drops the "first non-demo user becomes admin" logic. This patch follows the path suggested in #1031 to provide an alternate way for a user to become admin.
> Logged-in users with an admin token get signed up and keep their admin bit

- docs/install.md
Not explained in the "install from source" page
> How to get sources

- docs/developing/http-apis.md
- docs/developing/path.md
- mkdocs.yml
Requesting review from @zarvox and/or @mnutt.
> Document setPath, startSharing, setTitle

- shell/packages/accounts-identity/accounts-identity-client.js
- shell/packages/sandstorm-accounts-ui/account-settings.js
- shell/packages/sandstorm-ui-app-details/app-details-client.js
- shell/packages/sandstorm-ui-app-install/install-client.js
See http://docs.meteor.com/#/full/template_autorun .
> Use Template.autorun() instead of Tracker.autorun() so that the computation gets stopped.

- shell/client/_geometry.scss
- shell/client/_topbar.scss
- shell/client/shell.html
- shell/client/shell.scss
- shell/lib/db-deprecated.js
- shell/packages/sandstorm-accounts-ui/login_buttons.js
- shell/packages/sandstorm-ui-topbar/topbar.html
- shell/packages/sandstorm-ui-topbar/topbar.js
- shell/shared/shell.js
> Implement sidebar shrink/expand

- shell/client/_account.scss
- shell/client/shell.html
- shell/packages/sandstorm-accounts-ui/account-settings.html
- shell/packages/sandstorm-accounts-ui/account-settings.js
- shell/shared/shell.js
Reverts sandstorm-io/sandstorm#1229
Too broken, and unclear if this is really what we want to do.
> Revert "Split /account route into /account/profile and /account/billing."

- shell/client/_account.scss
- shell/packages/sandstorm-accounts-ui/account-settings.html
- shell/packages/sandstorm-accounts-ui/account-settings.js
- shell/packages/sandstorm-db/profile.js
- shell/server/hack-session.js
Now includes email addresses verified by github!
> Update and export SandstormDb.getVerifiedEmails(identity).

- shell/packages/accounts-identity/accounts-identity-server.js
Also tighten the constraint in `createAccountForIdentity()`.
> Prevent demo accounts from being upgraded using an already-linked identity.

- shell/packages/sandstorm-backend/sandstorm-backend.js
I think this improves clarity.
> Add imperative sentence to excessivelyOverQuota message

- shell/client/shell.html
- shell/packages/sandstorm-accounts-ui/accounts-ui-server.js
- shell/packages/sandstorm-accounts-ui/login_buttons.html
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-permissions/permissions.js
- shell/server/proxy.js
- shell/shared/shell.js
Specifically:
- Store referral information on Identities & Accounts, per @kentonv
- Track creation & use of sharing links to record who referred whom
- Create a basic page to see info about the referral program
- Use referral bonus when calculating quota
- Limit max referral bonus
- Use pathFor when creating links, per @zarvox
> Add v1 of referral program code

- shell/client/shell.html
I guess having commented-out HTML is really not helping anyone. We can find a better way to remember to implement these things. I guess it wasn't super reasonable of me to try to get you (Kenton) to merge commented-out HTML.
@kentonv requesting your review/merge.
> Remove nonexistent hypothetical features of referral program

- shell/server/proxy.js
This also sorts the tokens by decreasing value of "owner.user.lastUsed", consistent with how we now sort them in grainview.js and elsewhere.
> Fix title computation for redeemed share tokens.

- shell/packages/sandstorm-backend/sandstorm-backend.js
- shell/packages/sandstorm-db/db.js
- shell/shared/demo.js
Now that we're chasing down any place that this would affect stats, there's no reason not to do this.
> Update lastActive for identity users too.

- shell/.meteor/packages
- shell/.meteor/versions
- shell/client/_topbar.scss
- shell/client/shell.html
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-db/migrations.js
- shell/packages/sandstorm-db/profile.js
- shell/packages/sandstorm-ui-autocomplete-input/autocomplete-client.js
- shell/packages/sandstorm-ui-autocomplete-input/autocomplete-server.js
- shell/packages/sandstorm-ui-autocomplete-input/autocomplete.html
- shell/packages/sandstorm-ui-autocomplete-input/package.js
- shell/server/proxy.js
- shell/shared/grain.js
This changes the sharing dialog box to search contacts, as well as allow
emails to be entered.
Includes a migration to populate the Contacts table from ApiTokens.
> Add initial version of contact autocomplete

- install.sh
> install.sh: Typo/missing word

- src/sandstorm/spk.c++
`spk` should refuse to produce a package that claims compatibility with an API
version of which it is unaware.  It should also refuse to pack an .spk with
maxApiVersion < minApiVersion.
> Check minApiVersion and maxApiVersion validity

- shell/client/shell.html
Thanks to @birdsarah for bringing this to my attention.
> Indicate that action is required, in a notification

- shell/shared/grain.js
Also fail with a reasonable error if the contact input is empty.
> Make sharing form a bit more robust if user never completes contact

- install.sh
- installer-tests/full-server-install-with-domain-reservation-token.t
- Includes a new test for this.
> install.sh: Add support for domain reservation token

- shell/shared/grain.js
- tests/tests/postmessage-api.js
Close #1318
Thanks to @mquandalle for noticing this and reporting the bug.
For `setTitle()` I also wrote a test. Thanks to @zarvox for writing the test suite that I am building upon.
For `setPath()` I did not write a new test.
> Accept an empty string for setTitle() and setPath()

- docs/administering/sandcats.md
Improve detail. Hopefully this helps one confused user.
> Update Sandcats administration docs

- shell/client/_topbar.scss
- shell/client/shell.html
- shell/packages/sandstorm-ui-autocomplete-input/autocomplete-client.js
- shell/shared/grain.js
> Allow moving through completed contacts with up/down

- docs/README.md
@kentonv I'm going to self-merge.
Can I get you to test this out sometime and leave a comment here?
> Document how to deploy the docs

- shell/shared/grain.js
- shell/shared/shell.js
Thanks to @simonv3 for showing up to IRC to ask this question.
Ready for review/merge by @kentonv 
Curious what @zarvox thinks about this, and what @ndarilek thinks of it - specifically Nolan, would this have saved you time when you ran into the same issue before?
Note that this will log a message once per time someone opens a grain within the same browser tab, so they could end up with the message logged N times, once per grain they open in the same browser tab. I think that is OK.
> Tell app authors how to switch IFRAME

- shell/client/shell.html
- shell/packages/sandstorm-ui-app-details/app-details.html
> Remove two uses of "file" where we mean "grain"

- shell/shared/admin.js
> Remove token from admin URL once it's not needed.

- shell/packages/sandstorm-accounts-ui/login_buttons.js
This addresses https://github.com/sandstorm-io/sandstorm/issues/1355
> Display an error message on catching ServiceConfiguation.ConfigError.

- docs/administering/sandcats.md
Tested manually.
Close #1390 
Props to @kpreid for noticing.
> Fix path to sandstorm.log

- shell/client/_topbar.scss
> get the backgrounding test to pass on selenium 2.49

- docs/administering/faq.md
- docs/administering/guide.md
Also mention this from the "administrator's guide".
> Add docs on splash URL

- shell/client/shell.html
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-db/migrations.js
- shell/packages/sandstorm-db/user.js
- shell/shared/shell.js
This only effects servers with Meteor.settings.public.quotaEnabled set
to true (ie. only Oasis).
> Send all users (old and new), a notification about the referral program

- shell/packages/sandstorm-ui-app-details/app-details.html
- shell/packages/sandstorm-ui-app-install/install.html
Close #1403
Thanks @zarvox for noticing.
> Avoid showing "Restore grain backup" on app install page

- installer-tests/fail-on-32-bit-system.t
- installer-tests/fail-on-old-kernel.t
Also hard-code the full "You can report bugs..." string.
> installer-tests: Update order of FAILED vs. details

- shell/packages/sandstorm-ui-app-details/app-details-client.js
Show the 'upgrade grains' button not only when grains with smaller version numbers exist, but also grains of the same version number but different package.
This fixes difficulties @ndarilek described.
> Allow "upgrade" when appVersion is equal.

- shell/client/_account.scss
- shell/packages/accounts-identity/accounts-identity.html
- shell/packages/sandstorm-accounts-ui/login_buttons.html
- shell/packages/sandstorm-accounts-ui/login_buttons.js
- tests/commands/installApp.js
- tests/tests/account.js
- tests/tests/grain.js
This test is designed to prevent a reappearance of the bug fixed in https://github.com/sandstorm-io/sandstorm/commit/6e7887db839749e96b376387a3adf16d979ddd0e.
To make the implementation of the test nice, I also added a text input to the dev login form, so you can log in as any dev user. It looks like the following image:
Note that I use `display: flex`.
Finally, this pull request gets rid of some introjs-related test flakiness, so that the tests pass more reliably on the latest Selenium.
> Add identity-linking test.

- tests/.gitignore
- tests/package.json
- tests/run-local.sh
Also stop using selenium-standalone
> Update selenium to latest version

- docs/administering/sandcats-https.md
- docs/administering/self-signed.md
- docs/administering/ssl.md
- mkdocs.yml
Combines @dwrensha 's #1426 with turning `ssl.md` into a topic guide for easier reading.
> SSL docs changes dwrensha and more

- shell/client/grainview.js
- shell/packages/sandstorm-accounts-ui/account-settings.js
- shell/packages/sandstorm-ui-app-details/app-details-client.js
- shell/packages/sandstorm-ui-app-install/install-client.js
- shell/packages/sandstorm-ui-applist/applist-client.js
- shell/packages/sandstorm-ui-grainlist/grainlist-client.js
- shell/shared/admin.js
- shell/shared/shell.js
- shell/shared/stats.js
- tests/tests/postmessage-api.js
> Use server title in document title.

- shell/packages/sandstorm-db/db.js
The Oasis payments module will be implementing new kinds of bonuses which will be aggregated into this field, such as a bonus if the user signs up for the mailing list, and bonuses from the indiegogo campaign.
Also eliminate a redundant query from referral processing.
> Introduce 'user.planBonus' for aggregating additional quota bonuses.

- docs/administering/reverse-proxy.md
- docs/administering/sample-config/nginx-example.conf
- docs/administering/self-signed.md
- docs/install.md
Also move nginx-example.conf into the docs/ directory.
@kentonv I want your +1 on this pull request to confirm it's OK if I remove `nginx-example.conf` out from the root of the project, and into the `docs/` directory, where I can be its "owner" (in the sense of https://github.com/sandstorm-io/sandstorm/wiki/Pull-Request---Code-Review-Procedure )
> docs: Adjust nginx information

- shell/packages/sandstorm-ui-app-details/app-details-client.js
Variable hoisting can be weird.
> Fix bug where dev mode actions all launched the last action

- shell/server/pre-meteor.js
> Better error messages on missing Host header.

- install.sh
It asked for domain, but if you type the domain (rather than the subdomain)
you get an error.
> install.sh: Clarified (sub)domain recovery

- install.sh
- installer-tests/full-server-install-with-sandcats-https-invalid-domain-first.t
> install.sh: Say we want "example" instead of "example.sandcats.io"

- shell/client/_applist.scss
- shell/packages/sandstorm-ui-applist/applist.html
> Show a simplistic message to help users find apps on the market

- docs/administering.md
- docs/administering/faq.md
- docs/administering/sandcats.md
Thanks @sstephenson for creating & maintaining this service and for making it open source!
Close #1508
> Add docs on xip.io

- shell/.meteor/packages
- shell/.meteor/versions
- shell/client/_partials.scss
- shell/client/_powerbox.scss
- shell/client/_topbar.scss
- shell/client/grainview.js
- shell/client/shell.html
- shell/client/shell.scss
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-permissions/permissions.js
- shell/packages/sandstorm-ui-powerbox/package.js
- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox.html
- shell/packages/sandstorm-ui-topbar/topbar.js
- shell/server/core.js
- shell/server/hack-session.js
- shell/shared/admin.js
- shell/shared/grain.js
- src/sandstorm/grain.capnp
- src/sandstorm/persistentuiview.capnp
- src/sandstorm/sandstorm.ekam-manifest
- src/sandstorm/sealed.capnp
- src/sandstorm/supervisor.capnp
This implements the request and offer sides of the picker powerbox for the SealedUiView interface, which can be used to implement grain sharing.
A test app exercising this functionality can be found at https://alpha-hlngxit86q1mrs2iplnx.sandstorm.io/test-4.spk .  The source lives at https://github.com/zarvox/sandstorm-test-python .
> Picker powerbox: SealedUiView support

- shell/shared/install.js
We appear to not have any tests for uploading `.spk` packages in our test suite!
> Fix install regression related to variable hoisting

- shell/client/_topbar.scss
- shell/client/shell.html
- shell/packages/sandstorm-accounts-ui/login_buttons.html
- shell/packages/sandstorm-ui-topbar/topbar.html
- tests/tests/basic.js
> Add tooltips to more topbar elements

- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox-server.js
My powerbox changes had been waiting in review for a while, and did not obey
the style rules that we later added checks for.
> JSCS: fix style violations introduced by code from pre-JSCS pull request

- shell/client/_account.scss
This only affects Oasis.
It also only creates new CSS, so I believe it is totally safe to merge. *
*. Never believe engineers when they say something is totally safe. And yet I do think this is totally safe!
> Add new CSS for "Get free storage" section on /account

- shell/client/_geometry.scss
- shell/client/_topbar.scss
- shell/packages/sandstorm-ui-topbar/topbar.html
> Fix styling on sidebar shrink button and add :hover css

- shell/lib/db-deprecated.js
> Persist the user's shrink-navbar choice into localStorage

- shell/client/grainview.js
> Wait to open a session until user is logged in

- shell/client/_geometry.scss
- shell/client/_topbar.scss
- shell/packages/sandstorm-ui-topbar/topbar.html
Reverts sandstorm-io/sandstorm#1554
The glyphs look bad on many systems.
> Revert "Fix styling on sidebar shrink button and add :hover css"

- shell/client/shell.html
- shell/server/proxy.js
- shell/shared/grain.js
- tests/tests/grain.js
> Don't present a Request Access button for nonexistent grains.

- icons/arrow.svg
@jparyani for use in sidebar https://github.com/sandstorm-io/sandstorm/issues/1513
> Arrow icon

- src/sandstorm/run-bundle.c++
> Correctly support binding to IPv6 addresses with BIND_IP

- shell/server/proxy.js
Fixes the first two parts of #1569.
Note that this also removes some logic in `getProxyForApiToken()` that was intended to deal with race conditions between the permissions computation and the creation and caching of proxies. As far as I can tell, that logic did not buy us anything; if the API token now longer has access, that will be detected later in the call the `SandstormPermissions.grainPermissions()`.
> Better caching of proxies for ApiSessions.

- shell/client/_geometry.scss
- shell/client/_topbar.scss
- shell/packages/sandstorm-ui-topbar/topbar.html
Use the new arrow icon that @neynah made for the shrink-navbar button. Also add :hover styling.
> Tweak sidebar styling

- shell/server/pre-meteor.js
- src/sandstorm/app-index/app-index.c++
- src/sandstorm/app-index/app-index.capnp
- src/sandstorm/app-index/indexer.c++
- src/sandstorm/app-index/indexer.h
This is actually already live.
> Send notification emails to admins when an app lands in the app index.

- shell/server/pre-meteor.js
> Remove / from BASE_URL for a CORS header

- src/sandstorm/spk.c++
> Detect installHome in `spk` standalone executable

- shell/packages/accounts-identity/accounts-identity-server.js
- tests/tests/account.js
> by default, give newly-linked identities the ability to login

- shell/server/drivers/mail.js
> Make the smtp server also listen on BIND_IP

- src/sandstorm/backend.capnp
This is a totally pointless fix, everyone knows what was meant here. But lysdexia fix is lysdexia fix.
> Fix comment typo

- shell/client/_topbar.scss
- shell/packages/sandstorm-ui-topbar/topbar.html
> Adjust home button to align and collapse with navbar

- shell/packages/sandstorm-ui-app-details/app-details.html
- shell/packages/sandstorm-ui-applist/applist.html
- shell/packages/sandstorm-ui-grainlist/grainlist.html
> Filter file spk and zip inputs to their appropriate file types

- shell/packages/accounts-identity/accounts-identity-client.js
- shell/packages/accounts-identity/accounts-identity-server.js
- shell/packages/sandstorm-accounts-ui/account-settings.js
> Fixes #1526

- docs/administering.md
- docs/administering/for-work.md
- mkdocs.yml
Requesting review & merge from @kentonv . Any feedback is welcome, either here on GitHub, or privately.
> Add Sandstorm for Work documentation

- shell/client/shell.html
> Disable autocomplete for admin settings forms

- src/sandstorm/run-bundle.c++
Fixes #711 via the `access()` method.
> Fail early if we can't access var/sandstorm

- shell/client/admin-client.js
- shell/client/shell.html
- shell/client/styles/_admin.scss
- shell/packages/sandstorm-db/migrations.js
- shell/packages/sandstorm-email/email.js
- shell/server/admin-server.js
> Email port should probably be a Number, not a String

- shell/client/admin-client.js
- shell/client/shell.html
- shell/packages/accounts-ldap/ldap_server.js
- shell/packages/sandstorm-db/db.js
This allows users to specify a raw ldap filter that they want to apply.
> Add ldap filter field

- src/sandstorm/supervisor.c++
Workaround for https://github.com/seccomp/libseccomp/issues/27
> Define syscall numbers before libseccomp has a chance to.

- docs/administering/for-work.md
Thanks to @jparyani for writing the code, and @TC01 for letting us know this was required.
> Add docs on new LDAP fields

- shell/client/grain-client.js
> Make error clearer for contact input

- docs/administering/reverse-proxy.md
Thanks @zarvox 
While at it, clarify that DNS != certificates.
> Fix pluralization error

- shell/client/grain-client.js
- shell/packages/sandstorm-ui-grainview/grainview.js
- tests/tests/sharing.js
Fixes https://github.com/sandstorm-io/sandstorm/issues/1690.
> Fix bug in direct share links. Add test.

- docs/administering/faq.md
- docs/administering/reverse-proxy.md
- docs/administering/sample-config/apache-virtualhost.conf
> Document Apache reverse proxy configuration

- docs/administering/sample-config/apache-virtualhost.conf
> ServerAlias vs. ServerName

- shell/packages/sandstorm-db/migrations.js
> Catch exception in smtpUrl migration.

- shell/client/admin-client.js
- shell/client/shell.html
- shell/client/styles/_admin.scss
> Provide a warning to admins when WebSockets are broken

- docs/developing/handbook.md
Thanks for noticing, @garrison !
> docs: Stop referring to Mailpile

- shell/packages/sandstorm-accounts-ui/login_buttons.js
Fixes a jscs violation introduced in https://github.com/sandstorm-io/sandstorm/commit/fe17f63b4411ea9a7461c5391d375e8799d9257e.
> Get the stylecheck to pass.

- install.sh
- installer-tests/full-server-install-nmap-netcat.t
- installer-tests/full-server-install-on-jessie-with-broken-hostname.t
- installer-tests/full-server-install-on-jessie-with-userns-sysctl.t
- installer-tests/full-server-install-with-sandcats-https-invalid-domain-first.t
- installer-tests/full-server-install-with-sandcats-https.t
- installer-tests/install-without-root.t
- installer-tests/no-root.t
Hopefully this addresses the concern that resulted in #1652
> Clarify that dev install can be used for Sandstorm dev

- shell/client/styles/_powerbox.scss
- shell/client/styles/_topbar.scss
In response to comments on #1726.
> Restore previous Share Access popup width

- .gitignore
Hoping for a speedy review & merge. This is a new generated file, making my `git` state look dirty when it's not dirty.
> Ignore shell/public/ldap.svg

- shell/packages/accounts-ldap/ldap_client.js
- shell/packages/accounts-ldap/ldap_server.js
- shell/packages/accounts-saml/saml_client.js
- shell/packages/sandstorm-accounts-ui/login_buttons.js
- shell/packages/sandstorm-db/profile.js
- shell/packages/sandstorm-db/user.js
See individual commits for details.
> Login improvements

- shell/client/styles/shell.scss
- shell/packages/sandstorm-ui-grainlist/grainlist-client.js
This pull request:
- Fixes  #1573 - guided tour dismissal failure on IE11
- Fixes #1653 - guided tour transparency failure on Firefox
I'm hoping for a speedy review & merge. Props to @zarvox for helping me realize that `Template.instance().data` is like `props`. :)
> Guided tour fixups

- shell/client/admin-client.js
- shell/client/shell.html
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-db/profile.js
"mail" is by convention usually where this field resides (as part of the
inetOrgPerson objectClass). It could theoretically be in a different
field though.
> Add ldap email field

- shell/client/grain-client.js
- shell/client/styles/_account.scss
- shell/client/styles/_powerbox.scss
Three bugs in separate commits.
> Fix IE bugs

- shell/packages/accounts-saml/saml_server.js
- shell/packages/accounts-saml/saml_utils.js
> SAML tweaks

- install.sh
- installer-tests/full-server-install-on-jessie-with-userns-sysctl.t
This is a follow-up pull request to #1747
> install.sh: Fix sandstorm path; add hash -r

- docs/developing/handbook.md
- docs/using/security-practices.md
@kentonv I'm hopeful for your +1 on this. I'll self-merge in about 1 day if you don't comment, but since this is subtle phrasing to get right, I am hoping for your review. Feel free to close this and open a separate pull request, or tell me to wait until we can discuss face-to-face.
> Stop saying alpha in docs

- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
> Disable "Standard Setup" button when a feature key is present

- src/sandstorm/fuse.c++
- src/sandstorm/fuse.h
Implements the suggestions from https://github.com/sandstorm-io/sandstorm/pull/1781.
> Style fixes in new FUSE code.

- shell/client/styles/_admin-email.scss
- shell/client/styles/_admin-identity.scss
- shell/client/styles/_setup-wizard.scss
I need a linter that searches for `flex-begin`.  `flex-begin` is not a thing.
`flex-start` is a thing.
This changeset should produce no visible difference, but will produce valid CSS rules.
> Admin panel SCSS correctness fixes

- src/sandstorm/union-fs.c++
Currently, if my `sourceMap` has some hidden paths and I do `ls -l .` inside a `spk dev` grain, I see results like:
```
ls: cannot access 'hidden': No such file or directory
ls: cannot access 'home': No such file or directory
ls: cannot access 'sys': No such file or directory
total 3500
lrwxrwxrwx  1 65534 65534       7 Dec 14 12:48 bin -> usr/bin
drwxr-xr-x  2 65534 65534    4096 May 28  2014 boot
drwxr-xr-x  2  1000 david     120 Apr 10 09:37 dev
drwxr-xr-x 72 65534 65534    4096 Apr  8 10:31 etc
d?????????  ? ?     ?           ?            ? hidden
d?????????  ? ?     ?           ?            ? home
...
```
The hidden directories correctly return `ENOENT` when they are `stat()`ed, but they still show up in the results of `Directory.read()`.
This patch fixes the problem, which as far as …
> Fix bug where hidden paths actually do show up in the results of Directory.read()

- shell/client/admin/identity-providers.html
- shell/client/admin/identity-providers.js
- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
- shell/client/widgets/widgets-client.js
- shell/client/widgets/widgets.html
No effective code change, just moving lines from one place to another.
> Shuffle some helper components to a more appropriate place based on usage

- shell/client/admin-client.js
- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
- shell/client/shell.html
- shell/client/styles/_topbar.scss
- shell/packages/sandstorm-contacts/contacts-server.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-ui-autocomplete-input/autocomplete-client.js
- shell/server/admin-server.js
This is enabled by default, but can be disabled by an admin if needed.
> Autocomplete contacts inside an org

- shell/client/admin-client.js
- shell/client/admin/admin.html
- shell/client/admin/identity-providers.html
- shell/client/admin/identity-providers.js
- shell/client/setup-wizard/wizard.html
- shell/client/styles/_admin-identity.scss
- shell/client/styles/_partials.scss
> new-admin: IdP settings rework

- shell/packages/sandstorm-accounts-ui/login_buttons.js
- shell/shared/admin.js
@dwrensha can you sign off on this? Also, let me know if you need help setting up SAML for local testing.
> Fix saml login

- docs/guided-tour.md
Update guided tour docs for new wording in WordPress app: https://github.com/dwrensha/wordpress-sandstorm/pull/18
> regenerate -> rebuild

- shell/client/admin-client.js
- shell/client/admin/admin.html
- shell/client/admin/maintenance-message-client.js
- shell/client/admin/maintenance-message.html
- shell/client/styles/_admin-maintenance.scss
- shell/client/styles/_new-admin.scss
- shell/server/admin/admin-alert-server.js
> new-admin: add maintenance message page

- shell/packages/accounts-saml/saml_utils.js
> Add better SAML constraint checking

- shell/client/grain-client.js
- shell/client/shell.html
- tests/tests/sharing.js
Fixes https://github.com/sandstorm-io/sandstorm/issues/1065 and https://github.com/sandstorm-io/sandstorm/issues/1869.
> More sensible text in share-access popup for various corner cases.

- docs/guided-tour.md
- docs/index.md
- docs/using.md
Also added some relevant links to existing text.
> Text tweaks & update guided tour instructions

- shell/server/grain-server.js
The new title is currently only getting denormalized to a single downstream token.
> Add some missing {multi: true} options in grain renaming code.

- docs/developing.md
- docs/index.md
- docs/install.md
Thanks @neynah for pointing out that this is a smart change to make.
> Docs talk about the wiki less

- shell/client/grain-client.js
- shell/client/shell.html
- shell/client/styles/_topbar.scss
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-ui-autocomplete-input/autocomplete.html
- shell/server/drivers/mail.js
- shell/server/grain-server.js
> Prevent demo users from sharing by email. Increment dailySentMailCount when sharing by email.

- shell/client/grain-client.js
As suggested [here](https://github.com/sandstorm-io/sandstorm/pull/1907#issuecomment-214578443).
> In demo mode, make the 'shareable link' tab default.

- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-permissions/package.js
- shell/packages/sandstorm-permissions/permissions-tests.js
- shell/packages/sandstorm-permissions/permissions.js
- shell/packages/sandstorm-ui-grainview/grainview.js
- shell/server/core.js
- shell/server/proxy.js
This is a continuation of https://github.com/sandstorm-io/sandstorm/pull/1620, which accidentally got closed.
I've implemented a selective forward-chaining algorithm that avoids the performance issues of the previous implementation.
> Update permissions computation to account for permissionsHeld membrane requirements.

- shell/server/proxy.js
- src/sandstorm/web-session.capnp
> Whitelist Mercurial headers in web sessions

- meteor-bundle-main.js
- shell/run-dev.sh
- shell/server/drivers/mail.js
Fixes https://github.com/sandstorm-io/sandstorm/issues/1916.
> Fix SMTP listening in run-dev mode.

- shell/client/admin-client.js
- shell/client/admin/admin.html
- shell/client/admin/user-accounts-client.js
- shell/client/admin/user-accounts.html
- shell/client/admin/user-details-client.js
- shell/client/admin/user-details.html
- shell/client/admin/user-invite.html
- shell/client/styles/_admin-users.scss
- shell/client/styles/_colors.scss
- shell/client/styles/_new-admin.scss
- shell/packages/sandstorm-db/db.js
- shell/server/admin-server.js
- shell/server/drivers/mail.js
User list:
Click on any particular user (or the "Manage" link for keyboard users), see details about them:
You cannot modify your own account, as shown above, but you can modify other users:
You can't demote org members to Visitor:
Closes #1822.
> New admin user list and user details pages

- shell/client/admin-client.js
- shell/client/admin/admin.html
- shell/client/admin/feature-key-client.js
- shell/client/admin/feature-key.html
- shell/client/shell.html
- shell/client/styles/_admin-feature-key.scss
- shell/client/styles/_admin.scss
- shell/client/styles/_new-admin.scss
- shell/public/sandstorm-for-work-lanyard.svg
* Lifted (and adjusted width of) sandstorm-for-work-lanyard.svg from
sandstorm-io/sandstorm-website.
* Improved padding and layout of form.
* Refactored templates to maximize reuse.
Closes #1827.
> New admin: Sandstorm for Work

- shell/client/admin/admin.html
- shell/client/admin/organization-client.js
- shell/client/admin/organization.html
- shell/client/setup-wizard/wizard.html
- shell/client/styles/_admin-organization.scss
- shell/client/styles/_colors.scss
- shell/client/styles/_new-admin.scss
- shell/client/styles/_partials.scss
- shell/client/styles/_widgets.scss
Fixes #1828.
No feature key:
With feature key:
Making a change, then clicking the enabled Save button:
> Implement new admin Organization Settings page

- shell/client/admin/user-accounts.html
- shell/client/styles/_admin-users.scss
Addresses comments from @neynah in #1929.
> Adjust new-admin user list search bar and filter styling

- docs/developing/path.md
- shell/client/grain-client.js
- tests/tests/postmessage-api.js
Based on @mitar's work in #1926.  Thanks, Mitar!
Closes #1926, #1850.
> Add `showConnectionGraph` postMessage command

- docs/developing/email-from-apps.md
> Explain that mkdir is required

- install.sh
- installer-tests/Vagrantfile
- installer-tests/full-server-install-on-opensuse.t
Close #1306
Context: This change, with test included, results in install.sh working properly on OpenSuSE where it
not before.
> install.sh: Pass --user-group to useradd

- docs/install.md
- install.sh
Thanks @zarvox for writing this patch and @jparyani for remarking on a clean solution.
> install.sh: Use sysctl.d by default

- shell/client/grain-client.js
- shell/packages/sandstorm-ui-app-details/app-details-client.js
> Give the app-details trash page its own route, '/apps/:appId#trash'.

- shell/packages/sandstorm-accounts-ui/account-settings.html
- shell/packages/sandstorm-accounts-ui/account-settings.js
> disable button while logout-other-sessions request is in flight

- shell/client/shell-client.js
- shell/client/shell.html
> Redirect from root path to setup if no users have been added

- shell/packages/sandstorm-ui-applist/applist.html
> Clarify what is being uploaded by the Upload... button on the apps page

- docs/administering/config-file.md
- docs/administering/for-work.md
- mkdocs.yml
> Add reference docs on config file

- shell/client/admin/email-config-client.js
- shell/client/admin/email-config.html
- shell/client/admin/network-capabilities-client.js
- shell/client/admin/network-capabilities.html
- shell/client/admin/stats-client.js
- shell/client/admin/stats.html
- shell/client/widgets/widgets-client.js
- shell/server/admin/system-status-server.js
Addresses 7/8 issues on #1995.
> New admin bugfixes

- shell/client/admin/user-details-client.js
- shell/client/admin/user-details.html
- shell/client/styles/_admin-users.scss
Also, recommended styling tweaks from @neynah.
Closes #1995.
> Adjust user details page to make current role clearer

- shell/client/setup-wizard/wizard.html
> Center profile-confirm step in setup wizard

- tests/run-local.sh
- tests/run-tests.sh
Also, fetch a handful of packages over HTTPS instead of plain HTTP.
> Check selenium jar shasum after download

- docs/vagrant-spk/installation.md
Thanks @ocdtrekkie for noticing this.
> docs: When installing VirtualBox on Windows, stop implying people should fiddle with %PATH%

- shell/server/proxy.js
> limit the number of in-flight messages during streaming uploads

- docs/vagrant-spk/installation.md
Also make this page easier to skim, I hope.
> vagrant-spk install docs: Mention that Windows users do not need git

- docs/administering/email.md
Also:
- Explain why Gmail won't work
- Remove mention of Mandrill, who dropped their free tier
> docs/admin/email: Say "All you need" less

- shell/client/styles/_install.scss
- shell/packages/sandstorm-ui-app-install/install.html
> Remove appTitle prompt at top of screen

- shell/packages/sandstorm-ui-applist/applist-client.js
> Add hint to /apps about what installing is

- tests/commands/disableGuidedTour.js
> Disable more of the guided tour, for the test suite

- shell/packages/sandstorm-db/db.js
- shell/server/proxy.js
http://docs.meteor.com/api/collections.html#Mongo-Cursor-observe
> fix parameter order of DevPackages changed() observer

- shell/packages/sandstorm-ui-grainview/grainview.js
This should fix resumable sessions.
> When re-establishing a session, only reset the GrainView if the permissions have changed.

- shell/packages/sandstorm-ui-applist/applist-client.js
> fix search bar autofocus on applist page

- shell/packages/sandstorm-ui-applist/applist-client.js
> Only show most-used if >=6 apps installed

- shell/packages/accounts-email-token/token_client.js
- shell/packages/accounts-email-token/token_common.js
- shell/packages/accounts-email-token/token_server.js
- shell/packages/sandstorm-accounts-ui/login_buttons.js
Reverts sandstorm-io/sandstorm#2057
Breaks creation of new email login accounts.
> Revert "accounts-email-token: save/restore URL in email login flow"

- shell/client/styles/_account.scss
- shell/client/styles/_colors.scss
- shell/client/styles/_focus.scss
- shell/client/styles/_partials.scss
- shell/client/styles/_setup-wizard.scss
- shell/packages/sandstorm-accounts-ui/account-settings.html
- shell/packages/sandstorm-accounts-ui/account-settings.js
Reverts sandstorm-io/sandstorm#2140
The "upload new picture" button does not work.
> Revert "Unclutter account view"

- shell/.jscsrc
- shell/server/admin-server.js
- shell/server/pre-meteor.js
I frequently write things like:
if (condition) {
// Nothing to do here because blah blah.
} else {
doStuff();
}
> Fix JSCS issues and also configure JSCS to allow empty blocks that contain a comment.

- shell/packages/sandstorm-ui-applist/applist-client.js
> Don't show install hint when user is not signed up or demo

- shell/client/demo-client.js
- shell/client/shell-client.js
- shell/packages/sandstorm-autoupdate-apps/autoupdate-apps-tests.js
- shell/packages/sandstorm-autoupdate-apps/autoupdate-apps.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-ui-app-details/app-details-client.js
- shell/packages/sandstorm-ui-app-install/install-client.js
- shell/packages/sandstorm-ui-applist/applist-client.js
- shell/server/core.js
- shell/server/install-server.js
- shell/server/installer.js
The `Action.title` field is deprecated, so we shouldn't require that it be present.
See also #2177.
> allow insertion of UserActions that lack a title

- shell/server/proxy.js
When using `spk dev` for local app development, I noticed an occasional error about `stop()` being called on `undefined`. The problem is some code that failed to account for the fact that `added()` can be called before `observe()` returns. (See the [Meteor docs](http://docs.meteor.com/api/collections.html#Mongo-Cursor-observe).) This change eliminates the problem.
> Fix race condition in session resumption.

- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-ui-app-details/app-details-client.js
- shell/packages/sandstorm-ui-grainlist/grainlist-client.js
- shell/server/grain-server.js
> Hide 'shared with me' grains that already show up as 'mine'.

- shell/server/pre-meteor.js
- shell/server/proxy.js
A pretty straightforward change, and I don't think anyone has patches against `proxy.js` or `pre-meteor.js` at the moment
> Validate quote marks

- shell/client/notifications-client.js
- shell/packages/sandstorm-autoupdate-apps/autoupdate-apps.js
- shell/packages/sandstorm-db/db.js
Also tighten up method inputs for updateApps().
> Fix app auto-update, which relied on SandstormDb.addUserActions(), which was recently removed.

- shell/packages/accounts-email-token/token_server.js
Previously, we only returned the `resumePath` to the Accounts.login
codepath; now we also provide it in the return value of the
`linkEmailIdentityToAccount` method.
Fixes #2196.
> Honor resumePath when linking email identity to existing account

- src/sandstorm/run-bundle.c++
> Don't kill Sandstorm if there's an exception while deleting old tmp files.

- shell/server/hack-session.js
Immediately after saving, and before returning the cap to the user, check to see if we actually needed to this new cap. If not, then remove it.
> Deduplicate offered UiView capabilities.

- docs/developing/auth.md
- shell/server/proxy.js
> Fill in userInfo.pictureUrl with identicon if no other picture is available

- shell/packages/sandstorm-ui-app-details/app-details-client.js
#2181 didn't get this quite right.
> Fix bug in grainlist deduplication on app details page.

- docs/administering/install-script.md
- docs/install.md
@zarvox requesting your review before I merge this. I did test these instructions manually, and I'm happy to take any feedback you have. We can discuss in-person if that's easier.
> docs: install.md: Add docs on using Docker, etc.

- docs/administering/for-work.md
> docs: Explain that SAML support exists now

- shell/client/shell-client.js
- shell/packages/sandstorm-ui-grainlist/grainlist-client.js
- shell/packages/sandstorm-ui-grainlist/grainlist.html
- shell/server/backup.js
Fixes #2249
This fixes a possible DOS by the "visitor" class of users.
> Change restoreBackup to request a token up front

- docs/using/security-practices.md
> docs: Mention 95% figure on security-practices page

- install.sh
- installer-tests/full-server-install-with-domain-reservation-token.t
- installer-tests/full-server-install-with-sandcats-https-failure.t
> install.sh: Allow default port to be specified via command line

- installer-tests/full-server-install-with-sandcats-https-failure.t
> installer-tests: Specify port number, so that test passes

- install.sh
> install.sh: Avoid putting :80 in BASE_URL

- docs/administering/config-file.md
Thanks @dwrensha for noticing!
> docs: Correctly state the default MONGO_PORT

- docs/developing/publishing-apps.md
> docs: Fix broken links to install keybase tool

- shell/client/accounts/login-buttons.js
> Display "Loading..." instead of "(incognito)" on first page load.

- docs/install.md
- install.sh
- installer-tests/automatic-dev-install-on-jessie.t
- installer-tests/automatic-dev-install-with-busybox.t
- installer-tests/automatic-dev-install-without-HOME.t
- installer-tests/fail-on-already-installed.t
- installer-tests/full-server-install-nmap-netcat.t
- installer-tests/full-server-install-on-jessie-with-broken-hostname.t
- installer-tests/full-server-install-on-jessie-with-proc-readonly-but-sysctl-already-set.t
- installer-tests/full-server-install-on-jessie-with-userns-sysctl.t
- installer-tests/full-server-install-on-opensuse.t
- installer-tests/full-server-install-say-y.t
- installer-tests/full-server-install-with-domain-reservation-token.t
- installer-tests/full-server-install-with-sandcats-https-failure.t
- installer-tests/full-server-install-with-sandcats-https-invalid-domain-first.t
- installer-tests/full-server-install-with-sandcats-https.t
- installer-tests/full-server-install-with-unwritable-usr-local.t
- installer-tests/install-without-root.t
- installer-tests/interactive-dev-install.t
See the commits for details.
Note that on my testing environment, the test on the precise64 base box fails, but I think my testing environment is weird.
> Numerous install.sh fixes

- installer-tests/fail-on-already-installed.t
I wonder if inconsistent timing of reads from buffers is ruining my day. Who knows.
> installer-tests: Look for a more reliable string

- shell/client/admin-client.js
- shell/client/admin/admin.html
- shell/client/admin/preinstalled-apps-client.js
- shell/client/admin/preinstalled-apps.html
- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
- shell/client/styles/_admin-preinstalled-apps.scss
- shell/client/styles/_new-admin.scss
- shell/client/styles/_setup-wizard.scss
- shell/packages/sandstorm-autoupdate-apps/autoupdate-apps.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-db/migrations.js
- shell/packages/sandstorm-db/user.js
- shell/server/admin-server.js
- shell/server/installer.js
- shell/shared/testing.js
Currently it is only a new route in the admin panel. A subsequent commit
will add it to the setup wizard as well.
> Add preinstalled apps

- docs/developing.md
- docs/developing/powerbox.md
- mkdocs.yml
> Powerbox doc 

- shell/packages/sandstorm-db/migrations.js
- src/sandstorm/backend.c++
- src/sandstorm/backend.capnp
- src/sandstorm/backend.h
- src/sandstorm/supervisor.c++
Also improve the grain size computation slightly.
> Backfill grain sizes

- shell/client/accounts/login-buttons.html
- shell/client/shell-client.js
- shell/client/shell.html
- shell/packages/sandstorm-backend/sandstorm-backend.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-db/migrations.js
- shell/packages/sandstorm-db/user.js
- shell/server/accounts/identity/identity-server.js
- shell/server/core.js
- shell/server/proxy.js
- shell/server/shell-server.js
On a case by case basis, replace Meteor.settings.public.quotaEnabled with either isReferralEnabled or isQuotaEnabled functions.
Fixes #2345
> Replace Meteor.settings.public.quotaEnabled with db functions

- shell/packages/sandstorm-db/db.js
- shell/server/admin-server.js
Also, roll back previous replacements.
> Add feature key field replacement for server

- shell/client/admin/preinstalled-apps.html
- shell/client/styles/_admin-preinstalled-apps.scss
This leads to better behavior under screen readers.
> Change to using a button for toggle-more apps

- shell/packages/sandstorm-db/migrations.js
> Skip preinstalling apps if isTesting==true

- docs/install.md
- install.sh
- src/sandstorm/run-bundle.c++
> Implement `sandstorm uninstall`

- meteor-bundle-main.js
Sandcats servers now get an A from Qualys.
Previously they got an A-, due to lack of forward secrecy. Now that Meteor supports modern Node versions and we've upgraded, FS is supported.
Qualys still dings us for requiring SNI and for not supporting forward secrecy on older browsers that lack ECDH. We could support classic DH, but it requires generating dhparams, which is kind of a pain.
> Fix Sandcats TLS setup on Node 4.

- docs/vagrant-spk/packaging-tutorial.md
I was lucky enough to sit next to @awans yesterday and see him ask me some questions while going through the tutorial. This PR adds information to address his questions.
> docs: Fix issues noticed over the weekend

- docs/administering/for-work.md
@zarvox I humbly request your +1/-1 on this, since the details are subtle.
I do think this is a vast improvement over the earlier text, but I want someone to make sure I'm not saying anything misleading or false.
> docs: Clarify org management features

- docs/administering/faq.md
- docs/administering/sandcats.md
- docs/developing/handbook.md
- docs/vagrant-spk/packaging-tutorial-meteor.md
- docs/vagrant-spk/packaging-tutorial.md
> docs: I => We

- docs/using/top-bar.md
Looks like this page was last updated back when we had the old sharing model.
> update using/top-bar doc page

- shell/client/styles/_topbar.scss
- shell/packages/sandstorm-ui-topbar/topbar.html
> Make the "Sandstorm has been updated - click to reload" an accessible button

- shell/client/styles/_referrals.scss
> Better referral page styles on mobile

- shell/client/demo-client.js
- shell/server/demo-server.js
> appdemo: Use AppIndex to choose app version

- docs/developing/troubleshooting.md
- src/sandstorm/sandstorm-http-bridge.c++
Close #2295
Requesting preliminary review from everyone, and requesting final review/merge/rejection from @kentonv.
> Drop invalid ETag data

- shell/client/styles/_account.scss
Fixes #2121.
Depends on DOM changes in blackrock, so merge simultaneously.
> Fix cut-off FAQ section of billing plan popup and button position

- shell/server/drivers/mail.js
> Don't generate filenames for mail sent through the email driver

- shell/server/backup.js
> Give time for large backup uploads on slow connections.

- shell/client/styleguide.html
- shell/client/styleguide.js
- shell/client/styles/_styleguide.scss
- shell/client/styles/shell.scss
A first pass at some of the things that have been bouncing around in my head.  There is surely more to be written (and a bunch more examples to put on the page), but this at least puts the things that I've tried to express in various code and design reviews into words somewhere.
> Add some content to the styleguide page

- src/sandstorm/sandstorm-http-bridge.c++
Fixes #2440.
Adds some logic so that now, every time that we add a new entry to `identitiesMap`, if there is already a corresponding sturdyref on disk, we kick off a task that tries to restore that sturdyref, and we re-save it upon failure.
> sandstorm-http-bridge: re-save identity caps if they fail to restore

- docs/developing/troubleshooting.md
I'll merge this right now to get it into the docs; post-commit feedback very welcome here.
> docs: Explain how file autodetection works

- docs/administering/faq.md
> docs: Explain that there is no ARM support

- shell/server/startup.js
- src/sandstorm/run-bundle.c++
> Absorb trailing slashes in ROOT_URL

- shell/client/styles/_admin-users.scss
> Don't change color on hovor for admin user-details page

- shell/client/accounts/login-buttons.js
- tests/tests/grain.js
Fixes #2505. Adds a test that fails before the fix and passes after the fix.
> fix the 'stay anonymous' button

- shell/server/account-suspension.js
Thanks to @jadeqwang for noticing.
> Fix typo: "acccount" => account

- shell/server/proxy.js
See individual commits for more info.
> Harden against clickjacking and CSRF vulnerabilities in apps

- shell/client/grain/grainlist-client.js
- shell/client/grain/grainlist.html
> Always show new shares at the top of the grain list.

- shell/packages/sandstorm-db/profile.js
This probably shouldn't be a static method if it needs access to non-static
data...
Fixes #2533
> Fix verified email detection for LDAP

- README.md
@kentonv for your review/merge.
If it's OK with you, let me declare that you merging this PR to `README.md` indicates your approval of my new wording of the GitHub repo description, too.
I already took the liberty of changing the GitHub repo description to:
> Sandstorm is a self-hostable web productivity suite. It's implemented as a security-hardened web app package manager. https://sandstorm.io
I _believe_ it was:
> Personal cloud sandbox
but I'm not totally sure. I should have retained that info, oops. :(
If you don't approve of the new GitHub description,  I'm OK undoing that change and/or wordsmithing it. Or you can wordsmith it yourself, so long as "productivity suite" shows up there :)
Refs #2545
> Indicate that it's a productivity suite

- docs/index.md
> docs: Call it a productivity suite

- shell/client/accounts/account-settings.html
- shell/client/accounts/account-settings.js
- shell/client/styles/_account.scss
- shell/server/account-suspension.js
> Add feedback input to account deletion

- shell/client/demo.html
- shell/client/styles/shell.scss
> demo: Call ourselves a productivity suite

- shell/client/accounts/login-buttons.js
* Remove an unused template helper
* Import the correct `ServiceConfiguration` (only referenced in an exception-handling path)
* switch to ES6 function object shorthand
> login-buttons.js cleanup

- shell/server/proxy.js
https://github.com/sandstorm-io/sandstorm/commit/0084bc458a3c4b516af738ce94705f41fd5de09f introduced a bug where the second argument to `Proxy`'s constructor is the caller of the Meteor method `openSession()`, rather than the owner of the grain. This can lead to a situation where `Backed.getGrain()` gets called with the wrong `ownerId`. (Earlier I had mentioned that I thought this bug might explain some of our resumable-sessions problems, but I am less sure of that now.)
The present patch should make such mistakes more difficult to make. It consolidates the first two parameters of `Proxy.constructor` into a single parameter `grain`, intended to be filled in directly with an entry from `Grains`.
If and when we implement a by-package-ID CSRF whitelist, this change should also make it easy …
> Combine the first two parameters of Proxy's contructor.

- shell/client/admin/identity-providers.html
- shell/client/admin/identity-providers.js
- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
- shell/client/styles/_setup-wizard.scss
These are mostly just the super low-hanging fruit:
* Correct the price in the setup wizard to our sticker price of $10/user/month
* Show completed progress bar on the final page of the setup wizard
* Deemphasize steps other than the current one
* Improve language in step titles and use nouns more consistently
> Setup wizard adjustments from user testing feedback

- shell/imports/server/backend.js
- shell/server/demo-server.js
See individual commit messages.
> Fix bugs around deleteUser()

- shell/client/00-startup.js
CI is currently failing do to this missing semicolon.
> pass the stylecheck

- shell/client/admin/identity-providers.html
- shell/client/admin/identity-providers.js
- shell/imports/server/accounts/ldap.js
- shell/npm-shrinkwrap.json
- shell/package.json
- shell/packages/sandstorm-db/db.js
It requires the user to copy/paste the pem key into the admin config page.
> Allow for ldap self signed certs

- shell/client/grain-client.js
- shell/client/grain.html
- shell/client/styles/_powerbox.scss
- shell/packages/sandstorm-ui-topbar/topbar.js
#2609 was buggy. See individual commits.
> Fix modal popups

- docs/administering/for-work.md
@kentonv requesting your +1/-1 on the accuracy of this text.
I read the code and wrote this text based on how it works now, but I'm concerned that I might have misunderstood an aspect or am taking an implementation detail and turning it into a public promise, and I don't want to give customers any inaccurate info, so I am hopeful you can let me know if you're OK with this text.
> docs: SfW: Explain what the expiry means

- install.sh
- installer-tests/fail-on-already-installed.t
- installer-tests/full-server-install-with-existing-opt-sandstorm.t
Close #2626
Add tests for this case, too.
> install.sh: Permit installing on an empty /opt/sandstorm

- docs/administering/faq.md
Requesting +1 from @zarvox or @kentonv.
For context - I'm mostly copy-pasting from an email @zarvox wrote. I figured that having this information somewhere public is useful, since people ask us about it with some frequency.
> docs: Describe the end of beta for Sandstorm & SfW

- shell/client/styles/_admin-users.scss
list-item-style is not a CSS property
> Fix invalid CSS rule

- shell/client/admin/feature-key-client.js
- shell/client/admin/feature-key.html
- shell/client/styles/_admin.scss
Fixes #2573
@kentonv Note that these links depend on changes to the SfW dashboard app, so if you haven't pushed that yet, please do so before cutting the next Sandstorm.  :)
> Deep-link to Sandstorm-for-Work dashboard purchase routes

- installer-tests/full-server-install-on-jessie-with-mta.t
> installer-tests: Add test for installing with an MTA

- shell/imports/client/grain/grainview.js
- shell/packages/sandstorm-db/db.js
- shell/server/pre-meteor.js
- shell/server/proxy.js
Finish up unfinished stuff from #2566.
> Standalone tweaks

- docs/administering/faq.md
> docs: Fix broken Markdown for a link

- docs/administering/active-directory.md
- docs/analytics.js
- mkdocs.yml
Also:
- Make this page very wide, so that the images can be seen clearly.
- Add commented-out docs for Windows Server Active Directory, whose
text & screenshots I haven't edited yet.
> docs: Add Azure Active Directory docs

- CHANGELOG.md
> Typo fix in changelog

- src/sandstorm/supervisor.c++
This helps detect bugs in apps where they have hard-coded a particular UID or GID.
> "Randomize" sandbox UID and GID in dev mode.

- shell/client/styles/_account.scss
This should be merged in lockstep with https://github.com/sandstorm-io/blackrock/pull/41
> Update styling for pricing prompt

- docs/install.md
Thanks to Mark King for contacting us with a question that inspired this note.
> docs: Offer advice on unattended-upgrades

- mkdocs.yml
Close #2638
Thanks to @neynah for reporting and to @ar-jan for providing information
that makes it easy to see the fix.
> docs: Use correct mkdocs.yml configuration

- docs/administering/faq.md
Thanks to @zarvox for the text.
I'm going to self-merge now, to avoid latency, but post-merge feedback is very welcome.
> docs: Explain strange DNS lookups in admin faq

- docs/administering/faq.md
Thanks @zarvox for readability feedback. Self-merging.
> docs: Slight readability & accuracy improvements

- shell/server/grain-server.js
- shell/shared/grain-shared.js
> enable client-side simulation for grain trash methods

- shell/client/grain-client.js
- shell/client/grain.html
- shell/client/styles/_topbar.scss
> Add loading spinner to see who has access

- shell/shared/grain-shared.js
> Shutdown trashed grains immediately

- shell/client/accounts/login-buttons.html
- shell/client/accounts/login-buttons.js
- shell/client/admin/personalization-client.js
- shell/client/admin/personalization.html
- shell/packages/sandstorm-db/db.js
- shell/server/admin-server.js
- shell/server/admin/personalization-server.js
> Add option to hide "About Sandstorm"

- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
> setup wizard: make visible light background behind "Loading..."

- shell/client/grain/grainlist-client.js
- shell/client/grain/grainlist.html
> Add quota display to the grainlist

- shell/client/styles/_account.scss
- shell/run-dev.sh
There is a corresponding change to the Blackrock payments code.
> Style changes related to Blackrock billing changes for when Oasis leaves beta.

- src/sandstorm/run-bundle.c++
Corrected to change the right menu item.
> fixed the short text for the update console command

- docs/administering/backups.md
> docs: Explain that socket files don't need to be backed up

- shell/server/pre-meteor.js
> Support spaces in paths in static web publishing.

- shell/packages/sandstorm-db/db.js
- shell/server/accounts/accounts-server.js
We want to see if this makes users more likely to "get hooked" and become paying users or refer their friends.
> Add experiment that gives a grain limit of 100 to 10% of new free, including demo users.

- shell/packages/sandstorm-db/db.js
This should make the Jenkins checks pass once again.
> add newline to pass stylecheck

- shell/client/styles/_account.scss
> don't cut off 'go back' button when there are too many identities

- docs/administering/install-troubleshooting.md
- mkdocs.yml
Self-merging because 100% pure docs.
> Add docs page for install troubleshooting

- shell/client/setup-wizard/wizard.html
- shell/client/styles/_setup-wizard.scss
> Rework setup wizard intro page

- docs/install.md
According to https://github.com/sandstorm-io/sandstorm/pull/2644 the docs need to be updated slightly here.
> Update Docs to specify new minimum kernel version

- docs/administering/sample-config/nginx-example.conf
Fixes redirects from HTTP to HTTPS for all subdomains.
> Adds subdomain redirects in nginx-example.conf

- docs/administering/ssl.md
> Update ssl.md, fix broken link

- docs/vagrant-spk/packaging-tutorial.md
I found the former wording quite difficult to understand while reading quickly
> Docs: improve sentence wording

- shell/server/sandcats.js
This is common for people who use sniproxy.
> Fix bug where Sandcats wouldn't update or renew certs if BIND_IP was 127.0.0.1

- roadmap/platform/grains/README.md
I don't know how much you want the roadmap typo-checked, but this one was like... 18 times. It stood out.
> Typo: Subbordinate

- roadmap/platform/accounts/README.md
- roadmap/platform/mobile/README.md
Couple more drive-by typos. I am done reading the roadmap for today so I won't be sending more roadmap typos right now.
> Typos: Sansdtorm and Sandsorm

- docs/extra.css
> Change mobile nav colour to purple

- docs/developing/powerbox.md
@audreyt and @mnutt you may find this interesting!
Once merged, you can read at:
https://docs.sandstorm.io/en/latest/developing/powerbox/
> Add documentation on app-to-app powerbox.

- shell/client/admin/admin-new-client.js
- shell/client/admin/admin.html
> set document.title when visiting admin panel

- src/libseccomp/helper.c
- src/libseccomp/helper.h
Add new symlinks for the files introduced in https://github.com/seccomp/libseccomp/commit/1d055ac3fec5929f47ea6a3148c8f64815cbb220.
> add new libseccomp symlinks

- docs/extra.css
- docs/sandstorm_readthedocs_modified_theme/base.html
"E-mail support" button added to the footer. Fixes: #2517
> Add e-mail support button to docs footer

- docs/administering/faq.md
> Notify the owner of a resource-hogging process

- Vagrantfile
Should be functionally identical.
> Vagrantfile: Use a heredoc to improve readability

- shell/server/identity.js
Fixes #2826.
Follows the existing logic in [contacts-server.js](https://github.com/sandstorm-io/sandstorm/blob/v0.206/shell/server/contacts-server.js#L73-L102).
> include organization members in powerbox contact picker

- docs/vagrant-spk/code-dependencies.md
- docs/vagrant-spk/platform-stacks.md
...which was merged not long ago.
> vagrant-spk docs: mention the golang stack.

- shell/imports/server/header-whitelist.js
- shell/server/drivers/external-ui-view.js
- shell/server/proxy.js
> Honor header whitelist for Powerbox HTTP APIs.

- shell/server/drivers/external-ui-view.js
- src/sandstorm/bridge-proxy.c++
> Support ETag/If-None-Match/304 Not Modified through powerbox HTTP APIs.

- docs/administering/config-file.md
> Add BASE_URL and WILDCARD_HOST to sandstorm.conf docs

- docs/README.md
- docs/administering.md
- docs/administering/faq.md
- docs/administering/offline.md
- mkdocs.yml
This is already live, but if someone wants to proofread, that'd be awesome. :)
https://docs.sandstorm.io/en/latest/administering/offline/
> Document how to run Sandstorm offline.

- CONTRIBUTING.md
...now that this has been dealt with
> Remove out of date mention of profile issue from CONTRIBUTING

- docs/administering/sample-config/apache-virtualhost.conf
Having spent far too much time working on the wrong aspects while trying to get a purchased SSL certificate working, here's what I would have expected this file to look like.  As most people who will see this example are trying to implement an HTTPS installation, I believe it would be useful to have this match the layout of the NGINX example.
> Update apache-virtualhost.conf to include SSL conf

- shell/i18n/en.i18n.json
- shell/i18n/zh-CN.i18n.json
- shell/i18n/zh-TW.i18n.json
> Fix minor translation table problems.

- shell/client/admin/login-providers.html
- shell/client/admin/preinstalled-apps.html
While translating I noticed some strings were showing up wrong or twice, I have removed those from the templates.
> Small ui fixes

- shell/i18n/zh-CN.i18n.json
- shell/i18n/zh-TW.i18n.json
fix github login setup url.
https://github.com/settings/applications/newi -> https://github.com/settings/applications/new
> fix github login setup url in zh-CN and zh-TW

- shell/i18n/fr.i18n.json
Feel free to merge this french translation 
Benoit Renault @Xia0ben, Telec and Thierry Pasquier
> Add French translation to Sandstorm

- shell/client/shell.html
> Fix two template bugs related to i18n in referrals page

- shell/i18n/fi.i18n.json
Fixes to Finnish translation of Sandstorm.
> Fixes to Finnish translation of Sandstorm.

- CHANGELOG.md
- shell/client/admin/user-details.html
- shell/client/styles/_admin-users.scss
- shell/i18n/fr.i18n.json
with this PR could you add the contribution of Benoit Renault to the french translation inside the changelog of v0.224 (2018-01-06)  ? 
Thanks
> correction of the French translation

- shell/i18n/nl.i18n.json
> Remove duplicate line in NL translation

- docs/install.md
> Docs: Add new dependencies for building from source

- shell/client/shell-client.js
> Make en-US uses en too

- shell/client/shell-client.js
I don't know the problem is return or indexOf, but anyway I change the code more similar to the original one. I still can't build up latest sandstorm :/
> Fix language detect fail bug

- docs/vagrant-spk/installation.md
I'm fairly comfortable saying this now that my one outstanding issue is a CNR even for myself.
> Docs: vagrant-spk has been tested on Windows

- docs/guided-tour.md
> Docs: Missing space disrupted formatting

- shell/client/admin/personalization.html
> Typo fix in admin panel i18n

- shell/client/grain-client.js
- shell/client/grain.html
- shell/client/grain/grainlist.html
- shell/client/styles/_transfers.scss
- shell/client/styles/shell.scss
- shell/client/transfers-client.js
- shell/client/transfers.html
- shell/imports/server/backend.js
- shell/packages/sandstorm-db/db.js
- shell/server/backup.js
- shell/server/gateway-router.js
- shell/server/installer.js
- shell/server/transfers-server.js
- src/sandstorm/backend.c++
- src/sandstorm/backup.c++
This makes it easy to mass-transfer grains to another Sandstorm server. A UI lets you choose which grains to transfer, watch the transfer happen, and check and retry any errors.
> Implement Mass Transfers.

- shell/client/transfers.html
> Typo in Mass Transfer page

- make-bundle.sh
See the comment. For reference, the relevant detection logic is here:
https://github.com/lovell/detect-libc/blob/5173db0bc47608f89986d9125c2d868c08d5f429/lib/detect-libc.js#L42
I'm not in love with this solution, but I'm not sure what else to do.
> Fix for part of issue #3171.

- install.sh
> install.sh: Don't ask the user whether to report E_CURL_MISSING

- docs/administering/wildcard.md
Let's not throw Etherpad under the bus for vulnerabilities from five years ago.
> Docs: "Last few months" > "In the past"

- Makefile
- meteor-testapp/capnp/meteor-testapp.capnp
- meteor-testapp/sandstorm-pkgdef.capnp
- meteor-testapp/server/main.js
- src/sandstorm/sandstorm-http-bridge.c++
- tests/commands/uploadMeteorTestApp.js
- tests/tests/account-settings.js
- tests/tests/appHooks.js
Resolves #3027.
I'm still debugging an issue or two, but otherwise this is representative.
> Implement support for AppHooks

- shell/i18n/zh-CN.i18n.json
Still WIP, but most was translated.
Goal:
> Update zh-CN language file

- src/sandstorm/config.c++
- src/sandstorm/config.h
- src/sandstorm/run-bundle.c++
- src/sandstorm/spk.c++
Most of the diff (first commit) is just moving the config parsing into a separate file; the second patch just reads the value from the config and includes it in the message.
> Spk dev: display BASE_URL to the user.

- shell/public/robots.txt
...which just denies everything; nothing on a Sandstorm box is indexable
anyway.
Fixes #2910
> Add a robots.txt

- docs/extra.css
Attempt 2, the first one did the search box on the full page search page, this one should do it for the sidebar: And it is pulled out into extra.css too which is nice.
> Docs: Square up search box

- docs/developing/path.md
- shell/imports/client/grain-client.js
- shell/imports/client/grain/grainview.js
The subscription part mentioned in the docs is not implemented yet. I plan on digging into this a bit more later, but wouldn't mind a pointer as to where a good place to add the subscription would be.
> postMessage API for getting the grain's title.

- install.sh
...if useradd does not exist. See the comment.
Fixes #3272
> install.sh: on busybox systems, use adduser

- shell/client/main.ts
- shell/imports/client/grain-client.js
- shell/imports/sandstorm-ui-powerbox/powerbox-client.js
I figured I'd do this while I was looking at this bit of the code.
> Explicitly import/export SandstormPowerboxRequest

- src/sandstorm/sandstorm-http-bridge.c++
If we're going to inherit from kj::Refcounted, we have to instantiate
with kj::refcount, rather than just creating an unboxed instance of the
class.
@johnbintz reported the crash on the mailing list here:
https://groups.google.com/forum/#!topic/sandstorm-dev/e8vqoF0yi5k
---
I'm attaching a parsed version of the stack trace for posterity
[stacktrace.txt](https://github.com/sandstorm-io/sandstorm/files/4471740/stacktrace.txt)
> Fix a crash bug in sandstorm-http-bridge

- shell/imports/client/admin/login-providers.js
- shell/imports/client/setup-wizard/wizard.js
This reverts commit 9d321089b45ac8c0272da225f0854edcefbe922d.
Fixes #3319
Will need to stare at this a bit to figure out where 'Iron' *should*
come from.
> Revert "Explicit imports for 'Iron'"

- install.sh
This commit was on a branch solely waiting on Asheesh to verify that the fix worked. I am not sure how much testing we need to do prior to merging it, but I figured I'd convert it to a PR so that we can close out what appears to be a fairly trivial issue with an already-written fix.
Fixes #1158
> install.sh: If port 80 is taken, but user wants to bail, let them

- src/sandstorm/powerbox.capnp
`provide()` was rename dto `fulfillRequest()` in commit be73fca88.
> Fix comment

- acme-dns-01-sandcats/index.js
- acme-dns-01-sandcats/package.json
- acme-dns-01-sandcats/test.js
- shell/imports/server/acme.js
- shell/imports/server/sandcats.js
Each server will migrate at a random time between June 10 and June 23.
> Automatically switch Sandcats users to Let's Encrypt over the next few weeks.

- .github/workflows/build.yml
- shell/imports/server/acme.js
Fixes #3375
Note that I haven't actually tested this; we should of course do that before merging. I really wish we had automated tests for the acme stuff...
@Phaen, would you be up for building this branch and testing on your setup?
> ACME: don't request cert for baseHost if covered by wildcard.

- install.sh
- shell/imports/server/acme.js
- shell/imports/server/core.js
- shell/imports/server/gateway-router.js
- shell/imports/server/shell-cli.js
- src/sandstorm/backend.capnp
- src/sandstorm/run-bundle.c++
Currently the CLI doesn't support directly setting certificates but that would be easy for someone to add. I'm out of time this weekend, though.
> Add CLI for configuring ACME and use it in installer script

- shell/i18n/fi.i18n.json
> Update Finnish translation.

- .github/workflows/build.yml
- shell/imports/server/transfers-server.js
> Remove unused variables

- shell/.eslintrc.yml
- shell/npm-shrinkwrap.json
- shell/package.json
- Scan typescript files
- Be a bit more restrictive re: global environment; this could catch
undefined variable errors that the old config would have missed.
> Some improvements to our eslint config

- docs/developing/path.md
> Fix getGrainTitle example

- CONTRIBUTING.md
This strikes me as a good place to link to it.
> Mention the app-requests label in the CONTRIBUTING doc.

- shell/i18n/nl.i18n.json
- Fix typos
- Improve phrasing
- Translate new strings
- Replace the last korrels with grains
> Update Dutch translation

- .github/workflows/build.yml
- shell/imports/blackrock-payments/client/billingPrompt.js
- shell/imports/blackrock-payments/client/billingSettings.js
- shell/imports/blackrock-payments/client/payments-api-client.js
- shell/imports/blackrock-payments/client/payments-client.js
Explicitly import/export updateStripeData, and deal with some unused
variable/parameter warnings.
> Fix some linter warnings

- README.md
Mildly surprised to find a broken link here!
> Fix broken docs link in Readme

- src/sandstorm/config.c++
I think this will probably be around for... a little while yet? So I fixed a typo in it I just noticed.
> Typo in config warning

- src/sandstorm/gateway.c++
- src/sandstorm/gateway.h
- src/sandstorm/util/http.c++
- src/sandstorm/util/http.h
Fixes #3517
---
I'll likely do a cleanup/documentation pass in the next day or two, but this works.
> Opt out of FLoC

- shell/imports/client/admin/certificates-client.js
- shell/imports/client/shell.html
- shell/npm-shrinkwrap.json
- shell/package.json
Fixes #3530 as requested by @riesenrad.
I have not at all tested this, but this PR's changes should be very parallel to #3449, and, unless something is horribly wrong with this package, shouldn't impact anyone who isn't trying to use PowerDNS.
> Add PowerDNS plugin for ACME.js

- shell/run-dev.sh
- src/sandstorm/run-bundle.c++
It's been literally years since this was removed. I don't think we still
need the stub as a reminder, let's delete some code.
> Remove remnants of old shell dev workflow.

- src/sandstorm/web-session-bridge.c++
> CSP: Set worker-src to none

- docs/administering/faq.md
- docs/developing/raw-packaging-guide.md
I also updated the minimum kernel version following 54c50a272
> Doc: Update recommendation of Ubuntu 14.04

- docs/README.md
- docs/generate.sh
- mkdocs.yml
This fixes #3536, except the unrelated https://github.com/sandstorm-io/sandstorm/issues/3536#issuecomment-866981913
> Fix #3536, graphviz on "How it Works" page

- docs/install.md
- tests/README.md
- Add instructions for installing `xvfb`
- Add instructions for installing test dependencies on Fedora
- Mention `tests/README.md` in `docs/install.md`
> Improve docs regarding test suite

- src/sandstorm/run-bundle.c++
- src/sandstorm/util-test.c++
While working on something else, I noticed that the `Pipe` struct from util.h is duplicated in the test suite, so I deleted the one from the test suite to use the one from the library. The second commit also makes use of this helper at a spot in run-bundle where it makes sense. There may be other spots that make sense too, but this was the most straightforward.
> Make use of Pipe::make() helper from utils

- docs/administering/install-troubleshooting.md
We may want to make this more clear in the setup wizard, but this is also a good note for the install troubleshooting section of our docs.
> Docs: Troubleshoot "disallow collab" on install

- docs/developing/debugging.md
Co-Authored-By: spollard <1459574+spollard@users.noreply.github.com>
Supersedes #3653.
> Docs: Minor spelling fix

- shell/imports/client/setup-wizard/wizard.html
This is a place we should direct people to the group.
> Change support@ in setup wizard to dev list link

- docs/developing/http-apis.md
- shell/imports/client/grain-client.js
- shell/public/offer-template.html
Fixes #3646
I did some basic testing of this locally. @ocdtrekkie, want to take it for a spin?
> Support setting the foreground color for offer iframes.

- src/sandstorm/ip.capnp
Caught my eye while I was surfing source files.
> Fix tiny IpNetwork comment typo

- CHANGELOG.md
> Minor changelog typo

- docs/install.md
- shell/i18n/en.i18n.json
> Update docs for golang1.19

- .github/workflows/build.yml
I think we need this to be able to trigger the action manually: https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
> Add ability to run build action manually
