Makefile

If we don't remove this directory, we can hit symbol lookup errors like in #193.

remove shell/.meteor/local on 'make clean'

---

LICENSE

This commit updates the Apache license boilerplate with actual information. The Apache license appendix (designed to be removed before publication) states:
```
APPENDIX: How to apply the Apache License to your work.
To apply the Apache License to your work, attach the following boilerplate notice, with the fields enclosed by brackets "[]" replaced with your own identifying information. (Don't include the brackets!)...
```
Additionally, the copyright year was not included. Copyright notices must reflect the current year. This commit updates the listed year to 2015.
see: http://www.copyright.gov/circs/circ01.pdf for more info

Fix boilerplate text/year in Apache license

---

shell/server/mail.js
src/sandstorm/email.capnp

Fixes #197 
Unfortunately we got the protocol wrong a bit for reply-to, so we now bounce emails that have more than 1 address in the reply-to header.

Fix replyto

---

shell/shared/grain.js

Since [this commit](https://github.com/sandstorm-io/sandstorm/commit/178e174bbc76b51363f73a84bd3057f1f97af464), which changed the element from an input text box to a link, creating a new webkey dumps this error into the browser console:
```
Exception in setTimeout callback: TypeError: undefined is not a function
```

remove broken autoselect code for apiTokenText

---

shell/server/proxy.js
src/sandstorm/sandstorm-http-bridge.c++
src/sandstorm/web-session.capnp

Today I learned that the `Content-Encoding` header is allowed in *requests*. See [RFC 7231](http://tools.ietf.org/html/rfc7231#section-3.1.2.2).
For example, sometimes Git [sets this header to "gzip"](https://github.com/git/git/blob/master/remote-curl.c#L590). This [Apache documentation](http://httpd.apache.org/docs/2.2/mod/mod_deflate.html) hints that WebDAV clients do this too.
Until this is fixed, both GitWeb and GitLab can sometime emit the following error on `git fetch` or `git pull`:
"fatal: protocol error: bad line length character"

add fields for content-encoding header on requests

---

shell/shared/grain.js

Fixes #186.
I added a userId to Sessions query that happens in the reactive data function for a grain. This could go in the publication instead. The pro for that is it might be more secure, the con is it would make it tough if we ever down the road want users to somehow share session database entries.
This only fixes the issue for a user logging in/out. The change would be much more complicated to fix it for the other fields Kenton mentioned. From a security standpoint, they would have to be observed on the server side since unlike a user logging in/out, those fields are not always under the user's control.

Change grain session to be reactive based on user

---

src/sandstorm/sandstorm-http-bridge.c++

With our current `sandstorm-http-bridge`, an app with the following node.js server will fail to respond. (Assume there is another server listening on port 10001.)
```
var http = require('http');
var request = require('request');
http.createServer(function (req, res) {
console.log("got request");
var proxy = request({url: "http://127.0.0.1:10001", method: req.method});
proxy.pipe(res);
}).listen(10000, '127.0.0.1');
```
The problem is that `request().pipe(response)` does not close the response stream once its end is reached, and therefore the http bridge never calls `done()` on the response stream, because we currently wait for EOF.
We should instead use the `on_message_complete()` callback, as in this patch. The EOF case is still covered, because in that case the final call to …

use on_message_complete callback to detect end of HTTP response

---

shell/client/shell.css

The "delete", "show debug log", and other menu buttons don't change color on hover, which makes it hard to be sure that you're actually supposed to be able to click them.
This commit gives them the same background color as the grain title field on hover.

topbar: show light grey background for menu buttons

---

Vagrantfile

Nowadays everything goes through port 6080.
Note that I've never actually used Vagrant, so maybe @paulproteus or someone else with Vagrant experience should approve this change.

remove obsolete port forwarding from vagrant config

---

shell/shared/db.js
shell/shared/install.js
shell/shared/shell.js

Eek -- my change from #257 made it so that dev apps failed to appear at all if they did not have an `appName` in their manifest! This fixes the problem and actually uses the new `appName` field for installed actions.
We may also want to add an `appName` field to the `Grains` collection.

Add appName field to UserActions collection. Unbreak things.

---

shell/client/shell.css
shell/client/shell.html
shell/run-dev.sh
shell/server/proxy.js
shell/shared/db.js
shell/shared/devAccounts.js
src/sandstorm/run-bundle.c++

This uses a new sandstorm.conf setting named ALLOW_DEV_ACCOUNTS. If set to true, there will be a new Meteor login service named DevAccounts, and clicking it will direct you to a page where you can login as your choice of Alice, Bob, or Carol. Alice will always be an admin.
Fixes #150

Add dev accounts

---

shell/server/proxy.js
src/sandstorm/api-session.capnp
src/sandstorm/package.capnp
src/sandstorm/sandstorm-http-bridge.c++
src/sandstorm/sandstorm.ekam-manifest

Now when calling newSession from a proxy that was initiated from an API
connection, we now call it with a type id of ApiSession.
As a transitional measure, we fallback to WebSession if the call asking
for an ApiSession fails. This will eventually be removed once all apps
have updated.
Added apiPath as a variable to BridgeConfig. This will enable ApiSession
functionality as well as limiting what paths an api token can access.
This is blocking on https://github.com/kentonv/node-capnp/pull/9 getting accepted first.

Add ApiSession

---

shell/shared/db.js
shell/shared/install.js
shell/shared/shell.js
src/sandstorm/package.capnp
src/sandstorm/spk.c++

This is for consistency. Elsewhere (e.g. PermissionDef and RoleDef), "title" signifies localized text and "name" signifies something that might be used as a key. Moreover, it appears that @kentonv has already internalized that this field ought to be called "appTitle". (See https://github.com/kentonv/ssjekyll/commit/6b5bb7bcd38bb3a0aaeac56861bab12909adeac1 .)

rename Manifest.appName to Manifest.appTitle

---

README.md

x86_64 and kernel 3.13 requirements were not listed in the readme.

Specify required Linux kernel in Readme file

---

shell/server/drivers/external-ui-view.js
shell/server/hack-session.js
shell/server/proxy.js
src/sandstorm/hack-session.capnp

`getUiViewForToken` is pretty straightforward. I just made `getProxyForApiToken` accessible from proxy.js and called that directly. I also added `getApiEndpoint` because I realized I need a way to tell inside an app when a request is hitting the api server and I should be using `getUiViewForToken`. Should this perhaps be hidden from apps and handled seamlessly by the backend?
`getExternalWebSession` was a little more involved. Mostly it was a reimplementation of parts of sandstorm-http-bridge.c++ in node.js. Do you think we should be passing along cookies, or should they be dropped?

Add getUiViewForToken and getExternalWebSession methods to hack-session

---

src/sandstorm/spk.c++

The variable sawPkgDef was initialized to false, and never set to true when the
pkgdef was loaded successfully.
As a result, specifying --pkg-def would load the user-specified package def, and then ensurePackageDefParsed would additionally attempt to load the default one, which would fail.

spk: make --pkg-def switch work correctly

---

shell/shared/db.js
src/sandstorm/grain.capnp
src/sandstorm/supervisor.c++
src/sandstorm/supervisor.capnp
src/sandstorm/util.capnp

This started as an attempt to add interfaces for background processing -- that is, letting the app request that it not be shut down even if no sessions are open.
This expanded into defining some basic interfaces for notifications. Background processing requires displaying a notification to the user, and I didn't want to write a hack that would change as soon as notifications are truly implemented.
Things got complicated when I realized that the front-end is able to restart independently of any particular grain. This implies that capabilities related to keeping the notification open need to be persistent. (We could perhaps add more hacks that define some new kind of ID, but I'd rather start writing things the way we're supposed to be writing them long-term.)
But thinking about that made me …

Add interface for background processing and expand SturdyRef infrasturcture

---

src/sandstorm/run-bundle.c++

`remove()` with no parameters will cause an error once we upgrade Meteor/Mongo.
http://docs.mongodb.org/manual/reference/method/db.collection.remove/

Mongo 2.6: remove() -> remove({}).

---

shell/shared/grain.js

Fixes #252 
If this hack is unacceptable (and it is a pretty egregious hack), then we may want to do `window.open` on Firefox and just have users deal with the popup blocker.
Also check out https://github.com/jparyani/sandstorm/commit/a989f0013cc0e005c10fac9ae14d45a531e95bf7 if you're curious to see my attempts with an iframe. It did work for Chrome but not for Firefox.

Add a dirty hack for backup downloading on Firefox

---

shell/server/pre-meteor.js

This allows us to make the link back to the server an actual <a> tag.
Fixes #283

Change DNS error messages to be html

---

shell/server/backup.js

Fixes an issue introduced in https://github.com/sandstorm-io/sandstorm/pull/277.

Include symbolic links in backup zip.

---

Makefile

This changeset also makes the color function not silence its own
output -- that is, it removes the @ from the printf -- because otherwise,
invoking $(call color,foo) as part of x || $(call color,foo) would result
in the shell complaining that @printf is not found.

Suggest make update-deps if ekam fails

---

shell/server/proxy.js

[`cursor.observeChanges()`](http://docs.meteor.com/#/full/observe_changes) reports back only the ID field of changed entries. When deleting proxies, we need the `hostId` field as well, so we should use [`cursor.observe()`](http://docs.meteor.com/#/full/observe).
Right now, we are using `observeChanges()` as if it worked like `observe()`. (This is my fault for not reading the documentation carefully enough when I added this code.) The result is a serious memory leak.

Fix bug that caused proxies to never be deleted.

---

shell/run-dev.sh

When executing the xargs version on my machine, the number and length of files exceeded the allowed size and failed. The -exec worked, however.

Use find -exec syntax for chown/chgrp for long names

---

shell/shared/db.js
shell/shared/demo.js
shell/shared/stats.js

This change permits us to export appDemo user stats separately when viewing the JSON stats export.
@jparyani promised me that if I pushed this, he'd make the corresponding change on the Sandstorm internal stats dashboard.
For non-internal people interested in Sandstorm stats, you might like to see how to get JSON stats data from your own Sandstorm install:
* http://local.sandstorm.io:6080/stats (or whatever URL reaches your own Sandstorm)
* Click on the API token at the bottom of that page
* Ta-da, stats!
I have tested this in the following way:
* Create two demo users, each of which use an app
* Create an appDemo user by visiting an appdemo URL and logging in, which also creates an instance of that app
* View the mongo data on the User objects; note that there are 2 'demo' users and 1 …

Export stats on appDemoUsers separately

---

Dockerfile
Makefile

Fixes #321. This will no longer require the user to manually build or
download a Sandstorm distrubition. Going forward, Dockerfile.dev is the
intended way for people that want to build their own Sandstorm docker
image from scratch.

Change Dockerfile to fetch latest Sandstorm binary.

---

shell/.meteor/packages
shell/.meteor/versions
shell/client/shell.html
shell/packages/accounts-email-token/package.js
shell/packages/accounts-email-token/token_client.js
shell/packages/accounts-email-token/token_common.js
shell/packages/accounts-email-token/token_server.js
shell/packages/accounts-email-token/token_templates.html
shell/packages/sandstorm-accounts-packages/accounts.js
shell/packages/sandstorm-accounts-ui/login_buttons.js
shell/packages/sandstorm-accounts-ui/login_buttons_dropdown.html
shell/packages/sandstorm-accounts-ui/login_buttons_dropdown.js
shell/packages/sandstorm-accounts-ui/login_buttons_session.js
shell/server/proxy.js
shell/shared/admin.js

This is an alternate login system, based loosely on accounts-password.
Users input their email, and the server sends a message to that address
containing a token. The user either clicks a link out of that email or
manually copies the token into an input box, and then they are logged
in. This package (accounts-email-token), was intended to be generic
enough to be used outside Sandstorm, and may at some point be moved out
and put onto atmosphere.
On the Sandstorm side, the only things that needed to chage were the
admin page, and the accounts-ui. It's a bit of a mess since we're
building on top of meteor's accounts-ui that has a bunch of custom logic
for accounts-password that I tried to re-use as much as possible.

Add email token login system

---

install.sh

Script usage results:
```
root@sandstorm:/tmp# bash install.sh -c
install.sh: line 297: cc: command not found
WARNING: Couldn't compile user namespace test. We'll assume user namespaces
are enabled.
Where would you like to put Sandstorm? [/opt/sandstorm] 
As a Sandstorm user, you are invited to use a free Internet hostname as a subdomain of sandcats.io.
Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).
Type the word none to skip this step.
What *.sandcats.io subdomain would you like? [] doctaphred
We need your email on file so we can help you recover your domain if you lose access. No spam.
Enter your email address: [] doctaphred@gmail.com
Registering...
Successfully registered!
Congratulations! We have registered your doctaphred.sandcats.io name.
Your credentials …
```

Fix typo in install script.

---

shell/shared/demo.js

This addresses an issue where right now, if you want to Let's Chat, you
end up being offered to "Try Let's >>" because the word "Chat" is eaten
by the appNameFromActionName function.

For appDemo feature, use appTitle if it exists

---

shell/server/proxy.js
src/sandstorm/run-bundle.c++

Fixes https://github.com/sandstorm-io/sandstorm/issues/340.
Bonus: now `spk dev` will only restart grains whose appId matches the app being developed.

Shut down dev app grains from the frontend.

---

shell/shared/grain.js
shell/shared/install.js
shell/shared/shell.js
shell/shared/signup.js
shell/shared/stats.js

According to the [Iron Router docs](https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#using-hooks), the `waitOn` callback is executed in a reactive context. (Note that [`waitOn` gets treated like a hook](https://github.com/iron-meteor/iron-router/blob/86bab2112e44c2e0649006b4ce2f73927e5b0da3/lib/router.js#L351).) According to the [Meteor docs](http://docs.meteor.com/#/full/meteor_subscribe), subscriptions that are created in a reactive context are automatically stopped when the computation is invalidated:
> If you call Meteor.subscribe within a reactive computation, for example using Tracker.autorun, the subscription will automatically be cancelled when the computation is invalidated or stopped; it's not necessary to call stop on subscriptions made from inside autorun. 
By …

Answer: yes, the subscriptions do get stopped when the user browses away.

---

shell/server/proxy.js

Oops! This caused API sessions to always fall back to web sessions.

Fix bug: this -> self.

---

release.sh

With this commit, we will start publishing git tags, which would have made my life a little easier earlier today.

Use git tags to record commit <=> version info

---

src/sandstorm/sandstorm-http-bridge.c++

Fixes #343, allowing git-http-backend to set a nonempty `BridgeConfig.apiPath`.

sandstorm-http-bridge: fill in dummy Host header for API sessions.

---

shell/server/installer.js

This prevents the actual error from getting reported in cases like https://github.com/sandstorm-io/sandstorm/issues/349.

AppInstaller.downloadPath no longer exists.

---

release.sh

This avoids a condition where we do a release but forget to update
the installer.
@ocdtrekkie just ran into this -- the install.sh fix from last week seemingly didn't get pushed to `https://install.sandstorm.io`.
@kentonv if you prefer to handle this a different way, I'm all ears, but it seems to me that we'll be happiest having exactly one release process, rather than one for `install.sh` and another for the rest of Sandstorm.

Release install.sh along with the rest of Sandstorm

---

src/sandstorm/union-fs.c++
src/sandstorm/union-fs.h

This partially addresses https://github.com/sandstorm-io/sandstorm/issues/210.
Ideally, we would not ever dump stack traces for errors caused by bad input from the user. But I think this  fix is good enough for now.

Display the sourcePath value that caused an error. Fix Typo.

---

install.sh
shell/client/shell.html
shell/shared/admin.js
src/sandstorm/run-bundle.c++
src/sandstorm/sandstorm-http-bridge.c++
src/sandstorm/util.c++
src/sandstorm/util.h

This will automatically generate an admin token in the installer and direct users there to configure a login system. Also, added a command `admin-token` to the sandstorm binary to generate said token.

Add token for admin settings page

---

shell/packages/accounts-email-token/token_server.js

The log in email currently has a sentence that gets displayed like this:
> You are receiving this because someone (hopefully you) requested to log in to HOSTNAME with your email address.
This change replaces that "HOSTNAME" with the actual hostname.

Move HOSTNAME outside of quotes.

---

Vagrantfile

At some point, we changed the default BIND_IP to 127.0.0.1,
but with Vagrant, this is a no-go because we need the guest to
listen to port-forwarded requests, which will come in on eth0,
not lo.
Tested with @phildini at the meetup.

Set BIND_IP to 0.0.0.0 for Vagrant, so port forwarding works

---

shell/client/shell.css
shell/client/shell.html
shell/shared/grain.js
tests/tests/grain.js

Fixes https://github.com/sandstorm-io/sandstorm/issues/383. Fills in a default petname "unlabeled sharing link" to make it more clear that you don't need to specify a petname. Allows petnames to be edited after token creation.

Improve the UI for setting and modifying token petnames.

---

shell/shared/admin.js

This prevents your from bricking your Sandstorm install by having no
admin users that are able to login.
Fixes #352

Disallow users from disabling their login service

---

shell/client/shell.html
shell/lib/db.js
shell/server/permissions.js
shell/server/proxy.js
shell/shared/grain.js

This adds a `transitiveShares()` function to permissions.js and uses it in two places:
1. To compute a closer approximation to which sessions need to be killed when permissions change.
2. To implement a new "show transitive shares" button in the share menu. Looks like this:

Compute transitive shares.

---

install.sh

@kentonv This is now ready for review.
Tested manually against the sandcats-dev.sandstorm.io domain via:
`sudo OVERRIDE_SANDCATS_BASE_DOMAIN=sandcats-dev.sandstorm.io OVERRIDE_SANDCATS_API_BASE=https://sandcats-dev-machine.sandstorm.io OVERRIDE_SANDCATS_CURL_PARAMS=-k bash ./install.sh`
Sandcats prod as well as dev have the code needed to use this feature.

Integrate Sandcats domain recovery into installer

---

shell/.meteor/packages
shell/.meteor/versions
shell/packages/accounts-email-token/token_server.js
shell/packages/sandstorm-email/.npm/package/.gitignore
shell/packages/sandstorm-email/.npm/package/README
shell/packages/sandstorm-email/.npm/package/npm-shrinkwrap.json
shell/packages/sandstorm-email/email.js
shell/packages/sandstorm-email/package.js
shell/server/drivers/mail.js
shell/shared/admin.js

I went with adding a sandstorm-email package, that provides a drop in replacement for the `Email` global object, named `SandstormEmail`.

Fixes account-email-token ignoring Settings.smtpUrl

---

shell/client/shell.css
shell/client/shell.html
shell/shared/demo.js
shell/shared/grain.js
shell/shared/shell.js

**Goal**
People seem to use the "appDemo" links we have in the wild, e.g. etherpad.org => "Or try a demo" => https://demo.sandstorm.io/appdemo/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60 , and for those people, I don't think they actually understand they can install Sandstorm then+there and get the app.
**Status**
* This supports linking to `/install/#appName` in the case that you are a demo user, looking at a particular app.
* This defaults to `/install/#demo` if it can't find an `appName` (e.g. if you're in the shell).
* The `/install/` page supports `#appname` as a way to provide extra info. To test that, visit e.g. https://sandstorm.io/install/#EtherCalc
* I had the colors sanity-checked by @neynah.
* This pull request supercedes …

Self install now

---

Makefile
tests/run-local.sh

run-local.sh now spawns an Xvfb and selenium-standalone and cleans up after
itself.  This behavior can be disabled (if you wanted to run a long-lived
selenium server) with the --no-selenium flag.
@jparyani Take a look at this when you have a chance, and adjust the test machine accordingly/show me the appropriate knobs to turn?  Also, should I be calling run-tests.sh as well as run-local.sh in make test?

Add "make test" and extend tests/run-local.sh

---

tests/nightwatch.json
tests/package.json
tests/run-local.sh
tests/run-tests.sh
tests/unittests/cli.js

This uses nightwatch's unit test functionality to run some simple tests to make sure the `sandstorm` command line is working. We should extend this to `spk` and test more complicated scenarios.

Add cli tests

---

Makefile

On some systems GNU make is installed as gmake.  $(MAKE) will pass that
through.

Invoke sub-make with the same make

---

shell/packages/sandstorm-accounts-ui/login_buttons.less
shell/packages/sandstorm-accounts-ui/login_buttons_dropdown.html
shell/packages/sandstorm-accounts-ui/login_buttons_dropdown.js
src/sandstorm/run-bundle.c++

This is gated on `HIDE_TROUBLESHOOTING` in sandstorm.conf
Fixes #414

Add troubleshooting link to login dropdown

---

Makefile

libseccomp moved from Sourceforge to Github.  Just updating the URI for the
clone command would leave existing checkouts in a state where they'll fail to
upgrade, so we make the pulls name the remote to pull from explictly.
Fixes #430.

Makefile: handle updates to deps locations

---

install.sh

As evident in handle_args(), `-c` is not handled.

Removed an obsolete flag from usage.

---

Makefile

For release tarballs:
- increases compressed tarball size by 8 bytes
- reduces compression time from 139.3 to 135.5 seconds
For -fast tarballs:
- increases compressed tarball size by ~400k
- reduces compression time from 9.7 seconds to 2.4 seconds

Compress tarballs with more cores

---

install.sh

This should make it possible to install Sandstorm automatically on Debian
Jessie, which defaults to having unprivileged user namespaces disabled via
sysctl.
Discovered when testing vagrant-spk with the Debian Jessie vagrant boxes.

install.sh: fix unbound variable in userns sysctl prompting

---

src/sandstorm/run-bundle.c++

Meteor 1.1.0.2 uses Mongo 2.6, in which [`addUser()` is depcrecated](http://docs.mongodb.org/v2.6/reference/method/db.addUser/). It looks to be totally gone in [Mongo 3.0](http://docs.mongodb.org/v3.0/reference/method/js-user-management/). The replacement is [`createUser()`](http://docs.mongodb.org/v2.6/reference/method/db.createUser/).

db.addUser -> db.createUser

---

install.sh
src/sandstorm/run-bundle.c++

Currently, the install script makes <install_dir>/var/sandstorm owned by root:root. I might be missing something (cc @paulproteus), but I think this is a mistake; it should have the same ownership and permissions as all of the other directories.
Note that admin tokens live in this directory. After this patch you will be able to do `sandstorm admin-token` without `sudo`.

fix ownership and permissions for var/sandstorm

---

Makefile

If you try `make update` and don't have markdown installed, the build will fail with an error about markdown failing. This is as expected. However, in the current setup, if you try again the build will get farther and then fail with the following error, even if you've successfully installed markdown in the meantime:
```
==== meteor frontend ====
Errors prevented bundling:                    
While building the application:               
client/changelog.html:1: unclosed <template>
```
This patch fixes the problem.

Don't accept a half-formed changelog.

---

shell/shared/grain.js

`dateString` is now a global template helper, since: https://github.com/sandstorm-io/sandstorm/commit/ff63479b0a2b816ff39510d565b84b82c1504ad4

Remove now-unneeded definition of dateString.

---

shell/server/core.js
shell/server/drivers/external-ui-view.js
shell/server/proxy.js
shell/shared/grain.js

This is blocked on https://github.com/kentonv/node-capnp/pull/20
This is needed due to a bug in v8. See
https://code.google.com/p/v8/issues/detail?id=2397

Rename use of error.type to error.kjType

---

Makefile
installer-tests/README.md
installer-tests/Vagrantfile
installer-tests/automatic-dev-install-on-jessie.t
installer-tests/full-server-install-on-jessie-with-userns-sysctl.t
installer-tests/install-without-root.t
installer-tests/prepare-for-tests.sh
installer-tests/run_tests.py

This adjusts the tests in `installer-tests/` so that they:
* Run using `libvirt` and `qemu`, so they can run on Jenkins, and
* Have a `README.md` that explains how the tests work.
I'm running all the tests locally to make sure they all pass this way. If so, I'd like to merge this. For now, still waiting on verification that they all pass.

Installer tests can live in jenkins

---

install.sh
installer-tests/Vagrantfile
installer-tests/fail-on-old-kernel.t
installer-tests/prepare-for-tests.sh

This way, if someone has a Linux distribution that is too old to
run Sandstorm, we give them relevant advice.
Close #478

Check for kernel version before user namespaces

---

shell/lib/db.js
shell/public/offer-template.html
shell/public/tokentemplate.html
shell/server/hack-session.js
shell/server/proxy.js
shell/shared/grain.js

Grains can now make a request to the shell via postMessage() with a template
which can substitute a privileged API token for $API_TOKEN and the API host for
$API_HOST.  The grain will receive a postMessage reply from the shell with a
single-use URL in the shell's origin that will display the rendered template.
The app should iframe this URL in a place in the document inline where it wants
the template to appear.  Apps should *not* persist this URL anywhere.
Implementation detail: the privileged token will expire 5 minutes after
creation, if it is not used in that timeframe.  This helps avoid cluttering the
DB (and UI) with a bunch of tokens that were generated for this templating magic
that the user didn't end up using.

Add token templating

---

src/sandstorm/spk.c++

Too many mmaps breaks on VirtualBox shared folders, where VirtualBox has a
hardcoded 4096-file limit.  Keeping every file mapped while building the
Archive means we eventually get an ENFILE when opening the next file.
While most apps probably don't actually need >4096 files, this limitation makes
life harder for vagrant-spk.
Since most files are small, and most data is in large files, we can get most of
the RAM-saving benefit of mmap()ing files by doing so for files above some
threshold size, and reading the rest greedily into RAM, so we do that.

spk pack: only use mmap for files >=128k in size

---

shell/client/shell.css
shell/client/shell.html
shell/shared/shell.js

For demo users with no grains, point an arrow at "Install apps" and
"New App Instance" if they are looking at an app.
This visually conflicts with the information about the managed hosting
and mailing list signup, so we hide that information until the demo user
has created a grain.
Requesting @kentonv 's review + merge.

Add two nudge arrows for demo users

---

Makefile

Right now, if you edit migrations.js and then do `make update`, your changes won't get applied because the Makefile thinks that nothing has changed. This fixes the problem.

Add shell/lib to the dependencies of the shell-build target.

---

shell/server/proxy.js

This whitelists user agents starting with "GitHub-Hookshot/", per
https://developer.github.com/webhooks/#payloads
Closes #509.

Allow Sandstorm apps to be the target of GitHub webhooks

---

Makefile

This is the smallest possible fix for #524.
Other imaginable fixes include:
* Depending on a dir called `tmp/` which has its own `Makefile` target.
* Adding `tmp/.gitkeep` to the repository so there is always a `tmp/` directory.
I think this is an OK fix. If others have opinions, I'm interested in them, although I'm much more interested in them if the opinions come with their own pull request that supercede this one. (But if people think I should adjust this one, OK.)
Also perhaps @jparyani we should be `git clean -d -x -f -f`-ing from the tests to catch problems like this?

Ensure tmp/ exists before generating changelog in it

---

shell/lib/db.js
shell/server/proxy.js

This will allow us to answer questions like "Does Alice have permissions X on grain Y?" without needing to wake up grain Y.
@jparyani and I stumbled upon the need for this nearly simultaneously today.

Cache viewInfo in a new field in Grains.

---

shell/server/pre-meteor.js
shell/server/proxy.js
src/sandstorm/backend.c++
src/sandstorm/backend.h
src/sandstorm/supervisor.c++
src/sandstorm/supervisor.capnp
src/sandstorm/supervisor.h
src/sandstorm/util.c++
src/sandstorm/util.h

I've added a hacky method to the Supervisor interface, so that the supervisor can directly serve these files. I also modified the supervisor to delay starting up the app until it receives a getMainView() or restore() call, which requires the app to be running. This allows WWW files to be served without actually starting the app. The overhead of running the supervisor is comparatively small, and is acceptable for the time being until we replace all of this with a driver.
I believe this eliminates the last way that the front-end was reaching directly into grain storage.
This change will make web publishing work correctly on Oasis.
All code in this change will go away as soon as we have web publishing drivers. There are many improvements that could be made otherwise, e.g. caching and range …

Implement web publishing by RPC rather than filesystem access.

---

shell/server/proxy.js
src/sandstorm/api-session.capnp
src/sandstorm/sandstorm-http-bridge.c++

While in most cases, we want to avoid exposing a client's IP address to
sandboxed apps, having the option of sharing it is acutely valuable for
analytics apps like Piwik, which benefit substantially from having external IP
addresses for geolocation.
If an authenticated client sends the API endpoint a header:
X-Sandstorm-Passthrough: address
then we will pass the client's observed IP address as a parameter in the
ApiSession, and sandstorm-http-bridge will pass that to the app's backend as
an X-Real-IP header.
Additionally, if the request to the API endpoint is made from an RFC1918
address, we will substitute the value of an X-Real-IP header, if present, for
the client's address.  This should make things work out-of-the-box for most
simple SSL termination setups, while preventing spoofing …

Add opt-in passthrough of remote address to ApiSession as X-Real-IP

---

shell/lib/db.js
shell/server/hack-session.js
shell/shared/grain.js

This puts `roleAssignment` into its own field. Additionally, it validates `roleAssignment` on the client side, resulting in a better error message if the match fails.
(Unfortunately there's a related issue where Firefox does not report the full exception information when a `Meteor.Error` is thrown from within the event listener callback. (Chrome does just fine.) I think that problem should be dealt with in a separate pull request.)
I couldn't think of a good way to precisely express an exclusive union in a Meteor [pattern](http://docs.meteor.com/#/full/matchpatterns).
Something like the following would work, but it starts to get really verbose:
```
roleAssignmentPattern = Match.OneOf([
{none : null,
addPermissions: Match.Optional([Boolean]),
removePermissions: Match.Optional([Boolean])}, …
```

Clean up offer template argument validation.

---

shell/client/shell.html
shell/shared/grain.js

This implements the change discussed in https://github.com/sandstorm-io/sandstorm/pull/443.

Default role for share-with-app tokens is now 'allAccess'.

---

shell/client/shell.html
shell/lib/db.js
shell/lib/server/migrations.js
shell/server/permissions.js
shell/server/proxy.js
shell/shared/grain.js
shell/shared/shell.js
src/sandstorm/supervisor.capnp

We're also going to need to update a bunch of code for this to work (particularly in permissions.js). I'm submitting this as a request for comments about the big picture.
The migration translates each RoleAssignment into a direct edge from the attenuated UiView to the user. They essentially become "shares by identity". In contrast, new ApiTokens created by redeeming webkeys will always have the `parentToken` field set.
I think we could go even farther and merge Grains into ApiTokens. That would entail adding a new "raw UiView" provider in addition to the existing "attenuated UiView" provider.

Merge RoleAssignments into ApiTokens.

---

shell/shared/shell.js

This affects a purely-cosmetic stacktrace that arises when visiting
https://demo.sandstorm.io/ -- the admin alert wants to show information
about when this user expires, but there is no user yet, so it would
crash with:
```
Exception in template helper: TypeError: Cannot read property expires of null
```
in `formatAccountExpiresIn()`.
It's "purely cosmetic" in that it didn't affect functionality.
Regardless, this fixes that.

Stop crashing when Meteor.user() is null

---

shell/client/shell.css
shell/client/shell.html
shell/lib/db.js
shell/lib/server/migrations.js
shell/server/backup.js
shell/server/proxy.js
shell/shared/admin.js
shell/shared/grain.js
shell/shared/install.js
shell/shared/shell.js
shell/shared/signup.js
src/sandstorm/backend.capnp

The basic idea here is:
- Admin assigns storage quota to users e.g. at invite time.
- The back-end can determine how much space the user's grains are currently using. (Only on Blackrock, though; regular Sandstorm doesn't have any efficient way to do this.)
- We'll use this to display to the user how much space they are using.
- When the user goes over their quota, we'll stop letting them create new grains.
- When the user goes over 120% of their quota, we'll stop letting them start their existing grains.
@jparyani can you review this?

Implement storage quotas.

---

src/sandstorm/grain.capnp
src/sandstorm/ip.capnp
src/sandstorm/package.capnp

Namely that the responding app is rendered embedded inside the powerbox and can display an additional UI there to choose a capability or even mint a new capability.
Thoughts? @zarvox @jparyani @dwrensha

Update powerbox query and related interfaces to match current thinking

---

shell/server/permissions.js

Now when you revoke a token, users downstream from it will no longer show up in your 'see who has access' view.

Fix bug in `downstreamTokens()`.

---

shell/client/shell.css
shell/client/shell.html
shell/shared/shell.js

This is ridiculously hacky since there's no good way to do this fully in
CSS.
Ideally, we would measure everything in the topbar's width and subtract
that from the window width to figure out how large the admin alert can
be. For now, we just pick some reasonable estimates.

Hide the admin alert if it's too large for the screen size

---

shell/server/pre-meteor.js

This lead to some unreasonably long cache times on static publishing URLs.

Cache-Control headers use seconds, not milliseconds

---

shell/shared/grain.js

This is relevant for Piwik, where you're trying to create a token that is not
bound to a user, but is intended for public consumption.

Offer templates can set forSharing: true to dissociate identity

---

shell/client/shell.html
shell/server/core.js
shell/server/permissions.js
shell/server/proxy.js
shell/shared/grain.js

The biggest change here is that now when you open a child token UiView anonymously, the permissions are correctly computed. I ended up pushing a lot of shared logic in the `collectEdges()` function, which I think makes things nicer and opens the door to further simplifications later. (Eventually I think we'll want to call `collectEdges()` only once per grain-startup request; right now we call it once under `mayOpenGrain()` and once under `grainPermissions()`.)

Fix various things pertaining to sharing.

---

shell/packages/sandstorm-email/email.js

Currently I see this error if I run the tests without email configured:
```
Error sending e-mail: ReferenceError: Exception is not defined
at Object.SandstormEmail.rawSend (packages/sandstorm-email/email.js:178:1)
at app/server/drivers/mail.js:276:20
at app/server/proxy.js:64:17
at app/server/proxy.js:56:3
at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

Exception -> Error

---

shell/client/shell.html
shell/shared/admin.js
shell/shared/shell.js

This fixes #578
Before we were using trickery with extending RouteControllers, which should have worked, but for some reason is causing problems in Chrome.

Refactor admin tabs to use `Router.current().route.getName()`

---

README.md

On Debian stable, clang-3.4 does not provide /usr/bin/clang, only
/usr/bin/clang-3.4.  The "clang" package (which provides /usr/bin/clang) pulls
in clang-3.5, which is even better.
On Ubuntu 14.04 LTS, the "clang" package provides clang-3.4 as /usr/bin/clang,
which is acceptable.

README specifies just clang, rather than (outdated) clang-3.4

---

src/sandstorm/package.capnp

The goal here is that the app market should not need authors to fill in any form; they just upload an spk.
Note that I plan to extend Cap'n Proto with an `embed` keyword, which is like `import` except that it turns the raw contents of the specified file into `Text` or `Data`. Thus things like image files and license text would not actually be specified inside `sandstorm-pkgdef.capnp` but would be embedded from separate files. When the manifest is compiled to binary, those separate files are pulled into it, forming one big Cap'n Proto blob.

Extend spk manifest format with market metadata.

---

shell/shared/grain.js

This allows the offer template text to mention the token and the host multiple times.

offer templates: globally replace $API_TOKEN and $API_HOST

---

src/sandstorm/run-bundle.c++

Without this, `make update` and `sandstorm restart` take a long time to succeed.

Enable SO_REUSEADDR on the Meteor socket

---

shell/packages/sandstorm-email/email.js

This was causing problems if a % symbol was in the decoded URL.
Fixes #635.

Stop double decoding smtp URLs.

---

src/sandstorm/run-bundle.c++

Today, if you do a default development install, SERVER_USER gets configured to a new user "sandstorm". If a non-root user gets added to the "sandstorm" group, they should be allowed to do `sandstorm admin-token` without sudo. Currently, the command succeeds, but it leaves an adminToken file that causes an error when the frontend tries to open it; the user ends up seeing the admin page stuck on "loading...".
This patch fixes that case and preserves the current functionality for the other cases we care about.

Always fchown the admin token to the sandstorm group.

---

shell/shared/grain.js

Fixes #605.
The problem was that a user who was in the process of logging in would always immediately request an anonymous session, because `Meteor.userId()` would initially be unset.

Make sure not to try opening a share link while logging in.

---

shell/client/_topbar.scss
shell/client/shell.scss
shell/packages/sandstorm-ui-topbar/topbar.html
shell/packages/sandstorm-ui-topbar/topbar.js

This will create a popup in the center of the screen that extends a
caret into the topbar. There will be no icon in the topbar associated
with these items.

Add `onlyPopup` parameter to sandstormTopbar

---

Makefile
shell/server/pre-meteor.js
src/sandstorm/app-index/app-index.c++
src/sandstorm/app-index/app-index.capnp
src/sandstorm/app-index/category-table.c++
src/sandstorm/app-index/category-table.capnp
src/sandstorm/app-index/category-table.ekam-rule
src/sandstorm/app-index/indexer.c++
src/sandstorm/app-index/indexer.h
src/sandstorm/app-index/review.html
src/sandstorm/app-index/submit.capnp
src/sandstorm/package.capnp
src/sandstorm/spk.c++
src/sandstorm/spk.h
src/sandstorm/util.c++
src/sandstorm/util.h

The app index is itself a Sandstorm app. It presents an API through which apps can be submitted (with the new `spk publish` being the client to this API) and presents a review interface to the admin. Once apps are approved, they are published via web publishing such that the app market client can download and display the index, and Sandstorm servers can install packages from the index.
Currently `spk publish` only works with a webkey pointing to an app index instance, but once we have a standard one up we'll embed the webkey directly into the spk source code.
This code is generally not done and is kind of messy at present, but it basically works.

WIP app index with `spk publish` command.

---

shell/packages/sandstorm-accounts-ui/accounts-ui-methods.js
shell/packages/sandstorm-db/user.js

This occurs when a GitHub user attempts to sign in to Sandstorm where
they have no name configured in GitHub, just a username (aka handle).
Close #675

Permit null as name

---

shell/.meteor/packages
shell/.meteor/versions
shell/client/_grainlist.scss
shell/client/shell.html
shell/client/shell.scss
shell/lib/db-deprecated.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-ui-applist/applist.js
shell/packages/sandstorm-ui-grainlist/grainlist.html
shell/packages/sandstorm-ui-grainlist/grainlist.js
shell/packages/sandstorm-ui-grainlist/package.js
shell/shared/grain.js

Like the "new grain" UI, this is exposed at a route, but not linked by default.  The path to try out is `/grain`.
Depends on #688 for the crazy server-side reactive publish, icon helpers, and other fun helpers.

Add new "open grain" UI

---

shell/client/_topbar.scss

[The change here](https://github.com/sandstorm-io/sandstorm/commit/51347e50f49b93c1d67a7d29c3c645a93aa9f322#diff-f41c8458d337dd4e150b2ed41c120dc1R687) allows the following to happen:
This patch fixes it.

Prevent the role select element from getting too big.

---

shell/packages/sandstorm-accounts-ui/account-settings.html

This prevents confusion when it's embedded in a form. Without this,
pressing enter on any input in the form will trigger a click event on
this button.

Add type="button" to profile upload button

---

shell/shared/shell.js

I don't see it occur much on high-latency connections, but on a local
Sandstorm, I constantly get redirected away from /account because of
this problem.

Fix possible timing issue with accounts page

---

shell/client/_topbar.scss

We need to account for the 1 pixel border that will result in a 42px
offset

Fixes topbar popups being slightly off-center from their icon

---

shell/shared/grain.js

Using `onBeforeAction()` here somehow breaks multigrain. This is a quick fix while I investigate the cause.

onBeforeAction() -> onRun() in the /grain route, for now

---

shell/shared/grain.js

This logic has moved to GrainView._isIdentityAlreadyRevealedToOwner().

Delete some unused code. 

---

shell/client/grainview.js

One case where this is important is when the server kills sessions on a permissions change. Clients should immediately attempt to reestablish sessions.

Attempt to reopen sessions after they have been removed.

---

shell/client/grainview.js

This was causing the incognito interstitial to appear in some cases where an error message ought to have appeared.

Fix typo in error handling.

---

shell/client/shell.html
shell/client/shell.scss
shell/packages/sandstorm-ui-topbar/topbar.js

...so that errors, loading spinners, and interstitials only get shown when their corresponding grain is selected.
Also, display "unknown grain" in the navbar for /shared/ links that are still on the incognito interstitial and thus have no title yet.

Add a grain container div above the grain frame... 

---

shell/client/grainview.js
shell/client/shell.html
shell/shared/grain.js

1. Fixes the Share button for old-sharing-model (i.e. public) grains.
2. Fixes grain-title-setting for shared grains, and adds a prompt that better explains what's happening.
3. Gets rid of the `Grains.allow()` rule, in favor of Meteor methods `privatizeGrain()` and `updateGrainTitle()`
4. Shows the correct title for public grains opened by non-owners.
5. Deletes some obsolete `showMenu` stuff.

Fix grain title issues for shared grains and public grains.

---

shell/client/_colors.scss
shell/client/shell.scss

This should fix @kentonv's complaint about "white past the bottom of the grainlist/applist"

Make main-content have a default foreground and background color

---

shell/client/_topbar.scss

Currently, the open tab is incorrectly rendered like this is the desktop view:
and like this in the mobile view:
This patch fixes both views to look like this:

Fix style on tabs in the share popup.

---

shell/client/_topbar.scss

This commit removes "color: black;" from hamburger-menu-item.
Only a few items remain black, such as one's username, since other
items seem to have extra styling that overrides this rule.
But black text on a (nearly) black background doesn't make much sense
anyway. So this commit simply removes that style rule.

Remove color rule from %hamburger-menu-item

---

shell/client/_topbar.scss
shell/client/shell.html
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js
shell/packages/sandstorm-ui-topbar/topbar.html
shell/packages/sandstorm-ui-topbar/topbar.js
shell/shared/shell.js

Goal:
Status:
* Ready for review.

Changes for non-logged-in users

---

shell/client/_topbar.scss

This patchset is @neynah requested and @neynah approved!
The idea is that without this change, it looks like "Open..." and "New..." are missing an icon.

Open and New now align with the start of the icon, rather than the start of the grain title

---

shell/client/shell.scss

Some apps like Acronymy don't set a background, so it's nice if we make it the
default browser background color.

Make iframes have white backgrounds

---

shell/client/_account.scss
shell/client/shell.html
shell/client/shell.scss

Currently, if you still need to confirm your profile but you visit a grain or a shared link, the grainview gets rendered below the profile prompt (scroll down and you'll see it!) and then gets destroyed once the profile prompt is dismissed. The problem is that grainviews attach themselves to the first `.main-content` element they see, and the profile prompt was also using `.main-content`. This somewhat hacky fix works around the problem. With this change, we render the grain *behind* the profile prompt, where it is not visible. I've verified that even when grains are very tall (e.g. a MediaWiki with lots of content on the front page) they don't peek out from behind the profile prompt. (I don't fully understand why not, but hey, it works!)

Don't use the main-content class for first signup, as grainview special-cases it.

---

shell/client/_account.scss
shell/packages/sandstorm-accounts-ui/account-settings.html

In Firefox, this currently looks like:
After this patch, it looks like:
I've also verified that it looks good in Chrome and Safari.

Fix @-sign in 'handle' field of account-settings page.

---

shell/client/grainview.js
shell/client/shell.html
shell/shared/grain.js

This forwards the query and fragment to the grain iframe.

Include the query and fragment directly in the path.

---

shell/packages/sandstorm-ui-topbar/topbar.js
shell/shared/grain.js

... otherwise, when we close or delete or forget a grain, the newly-focused grain doesn't get its path set properly.

Use GrainView.route() when going to an already open GrainView.

---

shell/client/_grainlog.scss

Currently, a horizontal scrollbar can appear *above* the bottom of the window:
This fixes the problem by giving the div a fixed height.

grain log contents: max-height -> height

---

shell/client/grainview.js
shell/server/pre-meteor.js
shell/server/proxy.js
shell/shared/grain.js

This change refactors proxy.js such that `Proxy` objects are constructed lazily on first request rather than proactively.
This will make it easier to run multiple front-ends, since it's not necessary to specifically hit the one that has the Proxy object you're looking for. It would generally be nice if all requests for the same session arrive at the same front-end instance (to avoid creating multiple WebSessions for the same grain host), but this is not strictly necessary.
@dwrensha, please review. Note that I have attempted to organize my commits into bite-sized chunks. :)

Construct proxies lazily on request

---

shell/packages/accounts-email-token/package.js
shell/packages/accounts-email-token/token_server.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/migrations.js
shell/server/backup.js
shell/server/drivers/mail.js
shell/server/permissions.js
shell/server/proxy.js
shell/shared/demo.js
shell/shared/stats.js

Most uses of Meteor.setInterval were registering "cleanup" events, e.g. removing expired tokens. For a multi-replica system, we probably want these events to fire more often, because more data is being generated. So we stagger them according to replica number.
A couple uses of setInterval were non-cleanup, e.g. stat collection and daily mail limit enforcement. These need to be limited to running only on the first replica.
This change also fixes the mail rate limiter code to store limits in Mongo rather than in-memory, since the latter won't work when there are multiple replicas.
@jparyani, please review.

Make periodic server-side actions replica-safe.

---

shell/client/grainview.js

Steps to reproduce:
* Open about 5 Etherpad grains in different browser tabs
Expected behavior:
* I can tell them apart.
Actual behavior:
* They all start with "Etherpad" and that's all I see.
This change:
* Make the grainTitle first, giving me more control over the title in my tab bar.
(BTW I think @ocdtrekkie would like this pull request.)
Testing done:
* Ran `./run-dev.sh` on my laptop and confirmed that the title uses the the grain title first.

Change tab title to always put grainTitle first, if possible

---

shell/client/shell.html
shell/packages/sandstorm-ui-topbar/topbar.html
shell/shared/grain.js

This should fix a regression in the new UI where grain were not renameable by keyboard users because you couldn't keyboard-focus the <span> you'd need to click to change the grain title.
I also added a title to the sidebar buttons to make it clearer that 1) they are close buttons, and 2) which grain they will close.
Big thanks to @ndarilek for the bug report.

Make title keyboard-focusable and give close buttons a title

---

shell/packages/sandstorm-ui-grainlist/grainlist-client.js

Some users were concerned that they could no longer filter their grains by app.
While the search and filter logic might not be optimal when filtering with
multiple search keys, this restores the majority of that functionality.

Grainlist: also allow filtering by app title

---

shell/packages/sandstorm-accounts-ui/login_buttons.js

A suggested change from @neynah per user studies. 
Now you won't see "403 Unauthorized" in grain frames, and instead you'll see
the expected login UI.

When user logs out, clear open grain list and redirect to root page

---

docs/developing/publishing-apps.md
docs/developing/raw-packaging-guide.md
mkdocs.yml

I am not sure where to place this, so far this is just the basics, and it's not linked to other pages yet. I've combined details from the Github wiki and the package.capnp file to create this, and it's possibly worded in a friendlier manner? Licenses should be broken out into a separate page, almost certainly. This still links to the Etherpad file as well as package.capnp as it is not as exhaustive, nor does it currently show formatting for the manifest. (I highly recommend spk init creates manifests with metadata fields ready to go. (See also: #787)

Move the app submission instructions into docs

---

shell/packages/sandstorm-ui-applist/applist-client.js

Template instances have a function `autorun` that does not return the computation, but passes it as an arg to the inner function.

Fix a bug when highlighting an app in the app list

---

docs/developing/raw-packaging-guide.md

A lot of links led to the Github wiki, which then redirected you back to the docs. Also, remove "Install Vagrant" option for raw packaging, because those users should be using vagrant-spk, and we introduce people to that first, including directing people to it at the top of this page.

Update links on Raw Packaging Guide, remove outdated Vagrant info

---

shell/client/grainview.js

Never show the interstitial for /grain/ routes.

---

shell/packages/sandstorm-permissions/permissions.js
shell/server/proxy.js

Also, get offer templates to work again. For some reason, Meteor is now translating
`undefined` into `null` for `rawParentToken`.

Update a previously-overlooked usage of mayOpenGrain().

---

shell/packages/sandstorm-permissions/permissions.js
tests/tests/grain.js

This fixes some more fallout from #874.

Argh, apparently the transitiveShares() method was broken too.

---

shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-ui-applist/applist-client.js
shell/packages/sandstorm-ui-applist/applist-server.js

Fixes #846.
I took the liberty of cleaning up the methods I'd introduced in db.js to be
less Mongo-specific and to do matching and sorting in client code, rather than
using minimongo's limited capabilities for this (especially given the
complicated backwards-compatibility logic for appTitle and friends).

Sort apps in the app list case-insensitively

---

install.sh

Luckily this only ever caused people to see fun messages printed out and a slightly slower installer, it didn't cause them to actually _get_ broken HTTPS.

Do not default to fetching HTTPS certificates

---

shell/client/_about.scss
shell/client/_account.scss

These are falling back to the default font-weight: normal - might as well
remove them if we're not using Source Sans Pro Light.

We don't provide a font-weight: 300, so don't use it

---

shell/client/_topbar.scss
shell/client/shell.html
shell/packages/sandstorm-accounts-ui/login_buttons.html

* Users generally interpret "Share" to mean "Share on social media",
especially with the icon we provided.  We mean to communicate something else:
that this is how you grant access to this grain.
* "Save this link" has no information scent for signing in.  Revert to "Sign in".

Fix some low-hanging usability fruit

---

.gitignore
Makefile
install.sh
release.sh

This change arranges to sign all releases with a particular PGP key. The installer script, upon downloading a release bundle, will verify its signature.
I (and maybe other Sandstorm employees) will also sign statements (using our personal PGP keys) that the release-signing key is trustworthy. We will then extend the installation instructions with a "secure install" option that includes instructions for verifying our PGP keys, following the web of trust to the release-signing key, and then verifying the installer script using that key.
This change does *not* address verifying auto-udpates. That will happen separately, and will probably employ libsodium/ed25519 rather than PGP.
This change was written while not entirely sober. Needs careful review.

Verify installs using PGP.

---

release.sh
src/sandstorm/run-bundle.c++
src/sandstorm/update-tool.c++
src/sandstorm/update-tool.capnp
src/sodium/crypto_sign_ed25519

Updates are signed using ed25519 via libsodium. We don't use gpg for updates because it would be an extra dependency and it's hard to use correctly. (OTOH we have to use gpg for install verification since we need to bootstrap from tools people have; see pull request #901.)
The strategy is as follows:
- We maintain a list of signing keys, which for now has only one element.
- The public keys in this list are compiled directly into the Sandstorm binary.
- Private keys are kept in a keyring file.
- Every time we want to "rotate" the key, we actually add a new key to the list, and use it to sign future updates.
- Each update is shipped with a signature file containing signatures using *every* key in the list.
- Sandstorm, when updating, checks the signature file for a signature using the …

Cryptographically verify updates to Sandstorm proper.

---

docs/administering/ssl.md
install.sh
meteor-bundle-main.js
shell/packages/sandstorm-db/db.js
shell/run-dev.sh
shell/server/pre-meteor.js
src/sandstorm/run-bundle.c++

Changes:
* Adjust run-bundle to listen on multiple ports and pass their sockets over.
* Adjust meteor-bundle-main.js to optionally rebind http.createServer() to
return a HTTPS server.
* Adjust pre-meteor.js to handle secondary HTTP services.
* Adjust default ROOT_URL to be https:// if HTTPS is enabled.
* Adjust run-bundle & install.sh to fix permissions problems in https dir.
* Adjust install.sh to create the HTTPS keys with permissions that are readable by Sandstorm.
* Serve static publishing on the first HTTPS port as well as the first HTTP port, even for custom user domain names.
* Adjust run-dev.sh to do something reasonable when multiple ports are defined.

Support serving HTTPS if configured to do so and listening on multiple ports

---

docs/administering/sandcats.md

This looks like a typo... "run Sandstorm without the Sandstorm service"

Typo "Sandstorm" -> "Sandcats"

---

docs/developing/publishing-apps.md

Pulls a bit more info from the original package.capnp documentation to provide more guidance in docs.

Expand categories section of the publishing guide

---

meteor-bundle-main.js
shell/.meteor/packages
shell/.meteor/versions
shell/packages/meteor-node-forge/import.js
shell/packages/meteor-node-forge/package.js
shell/server/sandcats.js

I believe this is ready to merge. It achieves the following:
* When we have either 0 valid certificates, or 1 valid certificate that expires 3 or fewer days from now, then we get a new cert.
Implementation details:
* In the face of multiple certificates being valid, pick one in a reasonable way.
* It outright denies access to all non-SNI clients by giving them an invalid cert. (@jparyani you might find that amusing.)
* It only calls `.listen()` on the HTTPS socket (fd 3) if a key is available.
Out of scope for this pull request (to be handled tomorrow):
* Deal with clock skew.

Refresh cert as needed

---

shell/server/sandcats.js

This is one piece of the puzzle for actually getting wildcard certs
from GlobalSign.
The other piece of the puzzle is a `sandcats.io`-side code change that
changes how we request wildcards via the GlobalSign SOAP API. That code
is already tested & deployed.

Use *.hostname as commonName in CSR

---

installer-tests/install-without-root.t

The `installer-tests` now run cleanly for me on my laptop.

Fix more bad installer-tests strings

---

install.sh
installer-tests/full-server-install-on-jessie-with-broken-hostname.t
installer-tests/full-server-install-on-jessie-with-userns-sysctl.t
installer-tests/full-server-install-with-sandcats-https.t

We were checking if port 80 is available, but never actually using it.
This fixes that.

Actually bind to port 80

---

shell/.meteor/versions
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/package.js
shell/packages/sandstorm-db/profile.js
shell/packages/sandstorm-ui-applist/package.js

After #958, we are no longer actually using the jparker:crypto-sha256 package. Note also that if we just want a function to return a hex-encoded SHA256 in the browser, then the meteor sha package (see https://www.meteor.com/utilities and https://atmospherejs.com/meteor/sha) might be a better choice. (We're already using it in our accounts-email-token package.)
This change also updates some documentation to specify that some hashes in our database are base64-encoded.

Remove unused jparker:crypto-sha256 dependencies.

---

docs/developing/publishing-apps.md

Micro-benchmark results on my personal key.
```
$ gpg --export --export-options export-minimal '97225E589D6B9E01533C485EEC4B033C70096AD1' | wc -c
8118
```
```
$ gpg --export '97225E589D6B9E01533C485EEC4B033C70096AD1' | wc -c
78782
```
Realistically this only affects people (like me) who have a lot of signatures
on their key. But I think it's smart to document it the export-minimal way
to help those who do.

Use export-minimal to get smallest GPG keyring

---

shell/packages/sandstorm-db/db.js
shell/server/installer.js

We maintain a cache of this information on the Sandstorm server. We force a cache update when a new package is installed by the same author. All fetches are server-to-server and do not identify the user who triggered the fetch (and the cache is shared between users).
@zarvox, care to review?

Add code to fetch Keybase profile information.

---

src/sandstorm/run-bundle.c++

Fix ownership and permissions /var/sandstorm/socket to allow reinstalling.

---

shell/lib/db-deprecated.js
shell/packages/sandstorm-backend/sandstorm-backend.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-ui-applist/applist-client.js
shell/packages/sandstorm-ui-applist/applist-server.js
shell/packages/sandstorm-ui-applist/package.js
shell/packages/sandstorm-ui-grainlist/grainlist-client.js
shell/server/backup.js
shell/server/proxy.js
shell/shared/demo.js
shell/shared/grain.js
shell/shared/shell.js
shell/shared/stats.js
src/sandstorm/run-bundle.c++
tests/apps/powerbox.js
tests/apps/roundcube.js
tests/tests/grain.js

We have a decent amount of logic dealing with backwards-compatibility with app
titles and actions, and guessing values for new manifest fields based on older
ones.  This commit attempts to centralize that logic as some methods on the data
model in the sandstorm-db package.
This commit also add an appId field to devApps, to make accessing them more
like accessing Packages.  This makes dealing with packages that may be dev
packages or installed packages a bit simpler.

Move fallback logic about packages to SandstormDb static methods

---

src/sandstorm/spk.c++

Historically, MongoDB users should be admonished to use
NiscuDB. However, since the creation of meteor-spk, Meteor
apps use NiscuDB (or Mongo 3) which wastes less space
per grain. And since Mongo 3 is going to be increasingly
common, this warning mostly affects people who do not need
to read it.

Remove mongod warning from spk.c++

---

shell/packages/sandstorm-db/profile.js

Makes it convenient to retrieve all emails associated with a user.

Add SandstormDb.getUserEmails().

---

shell/packages/sandstorm-accounts-ui/login_buttons.js

Currently, if you log in with an email identity from the "loginButtonsDialog" (as opposed to the "loginButtonsPopup", which is rooted on the topbar), the client hits an exception after the login succeeds.
The change here sidesteps the issue in the same way that [`loginResultCallback()`](https://github.com/sandstorm-io/sandstorm/blob/747cd5783a59a570a8195781fe43145eb00dd781/shell/packages/sandstorm-accounts-ui/login_buttons.js#L124) already sidesteps the issue for a related case.
I consider this a temporary hack, as it's really only an accident that `topbar == null` in these cases. I'm going to have to deal with the more general case in my merge-accounts branch, which will be reusing the login buttons in a different context.

Don't call `topbar.closePopup()` when `topbar` is null.

---

shell/packages/sandstorm-db/db.js

This fixes a regression where, on logout, the javascript console would sometimes display a match failure exception.  The cause was a `check(userId, String)` that I had added to `userApiTokens()` in https://github.com/sandstorm-io/sandstorm/commit/9bd302dbce3ec8bd185c461602c5d61d5d6fc646. The fix proposed here is to adjust the check to allow null values, so that an empty cursor will be returned in that case.

Adjust some SandstormDb methods to not throw exceptions on null input.

---

install.sh

Here's how it appears to users:
```
vagrant@localhost:~$ sudo CURL_USER_AGENT=testing OVERRIDE_SANDCATS_BASE_DOMAIN=sandcats-dev.sandstorm.io OVERRIDE_SANDCATS_API_BASE=https://sandcats-dev-machine.sandstorm.io OVERRIDE_SANDCATS_CURL_PARAMS=-k bash /vagrant/install.sh
Sandstorm makes it easy to run web apps on your own server. You can have:
1. A full server with automatic setup (press enter to accept this default)
2. A development server, for writing apps.
How are you going to use this Sandstorm install? [1] 
We're going to:
* Install Sandstorm in /opt/sandstorm
* Automatically keep Sandstorm up-to-date
* Configure auto-renewing HTTPS if you use a subdomain of sandcats.io
* Create a service user (sandstorm) that owns Sandstorm's files
* Configure Sandstorm to start on System boot (with …
```

Mention Sandcats terms of service & privacy policy

---

shell/packages/sandstorm-backend/sandstorm-backend.js

Before this, devPackages would never be able to call continueGrain

Fix bug with continueGrain + devPackages

---

make-bundle.sh
src/sandstorm/run-bundle.c++

This way, when e.g. `resolv.conf` changes, we won't be using an out-of-date copy.
Fixes #895

run-bundle: bind /etc to /etc.host RO and symlink interesting files

---

tests/nightwatch.json
tests/package.json

@jparyani I would love it if we integrated screenshots with Jenkins, so when tests fail, we can see what the page looked like for the failed assertion.  Any thoughts on:
* if upgrading nightwatch is risky or not
* how might we organize/clean out the screenshots folder?
* how might we make Jenkins capture these things as build artifacts?

Upgrade nightwatch and capture screenshots on test/assertion failure

---

shell/server/sandcats.js

This avoids a crash where, if the server IP address changed, we would
crash rather than actually update the IP address.
Tested by maurer.

Only log certificateSigningRequest if there is one

---

shell/public/offer-template.html

If I'm understanding it correctly, it looks like `expires` has been sent as `exires` such that `data.expires < Date.now()` never matches and expired keys never get removed from sessionStorage.

Typo in offer template data

---

shell/server/proxy.js

This makes it so that incoming requests to a former session (identified by the "sandstorm-sid" cookie) which no longer has a Session object in the DB will block requests for up to 15s waiting for the client to recreate a Session.

Make resumable sessions a bit more robust

---

docs/administering/sandcats.md

This PR comprises one grammar fix, one typo fix, one formatting fix and one added explicit link; details below.
"...which Sandstorm (and the install script) manage for users" - subject and predicate should agree in the absence of the parenthetical; here, they do not. See [The Chicago Manual of Style](http://www.chicagomanualofstyle.org/qanda/data/faq/topics/Usage/faq0180.html) for more details.
"...and places it in places it in" - typo.
"To manually recover..." - use spacing consistent with previous subsection.
Add mailto link for the lazy.

Copyediting of "Sandcats dynamic DNS"

---

install.sh

This fixes what I believe is the one remaining flakiness of installer-tests.

Allow up to 60 seconds (not 20) for /getcertificate response

---

shell/packages/sandstorm-db/user.js

The first dev user was erroneously becoming an admin.

Update the first-user-admin-promotion code to account for the new schema

---

src/sandstorm/supervisor.c++

Include netinet/in.h before sys/capability.h.

---

shell/packages/sandstorm-ui-app-details/app-details-client.js
shell/packages/sandstorm-ui-grainlist/grainlist-client.js
shell/packages/sandstorm-ui-grainlist/grainlist.html
shell/shared/grain.js

* Make rows in the app-details page clickable anywhere in the row, not just on the link
* Fix dangling link pointing to `/grain/new`
* Redirect `/grain/new` to `/apps`
* Remove a `console.log`

App details cleanups

---

shell/packages/sandstorm-ui-applist/applist.html

They're most interesting in the main listing, and we're going to scroll to make sure that one's visible anyway, so calling attention to exactly one thing is preferable.
Fixes #1095.

Don't highlight newly-installed apps in the Most Used row

---

docs/developing/email-from-apps.md
docs/developing/web-publishing.md

These ../ links used to work when the docs were based on the
GitHub wiki for sandstorm-io/sandstorm, but seeing as they are
no longer there, we use absolute URLs.
Verified this was all of them by doing:
$ git grep '[.][.].*capnp'

Adjust links to capnp files to go to the right place

---

shell/shared/grain.js

Before, comma seperated lists would have subtlely different behavior.
Fixes #1086

Allow invite emails to be space or comma deliminated

---

make-bundle.sh
src/sandstorm/run-bundle.c++

We now also bind in `/run` from the host as `/run.host` to deal with recent Ubuntu releases, where `/etc/resolv.conf` is a symlink to `/run/resolvconf/resolv.conf`.
To keep names coherant, `etc.list` is renamed to `host.list` and now allows paths under both `/etc` and `/run`.
`/run/resolvconf` is added to `host.list`.
Fixes #895.
Fixes #1047.

Second attempt at making DNS work when `resolv.conf` is updated

---

src/sodium/crypto_generichash.h

This fixes the build failure seen in the Jenkins test for #1110.

Add symlink for crypto_generichash.h.

---

shell/packages/sandstorm-ui-applist/applist-client.js

A refactoring caused app search to look at the wrong object when doing matching
for filter-search on (appTitle, shortDescription, nounPhrase).
In other news, I miss static typechecking, which would have easily caught my
mistake.
Fixes #1111.

Fix regression in app search

---

shell/server/proxy.js

Partially fixes #1103. Currently, the client can wait up to 60s to send
a keepAlive. We probably want the Session to be properly reactive so
that the client never has to wait to re-open a session.

Up the timeout for waiting for sessions to re-open

---

docs/developing/web-publishing.md

I was seeing the following error, when it failed and I reran manually:
```
vagrant@localhost:/tmp/capnproto/c++$ autoreconf -i
Makefile.am:189: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:189:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:189:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:189:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:189:   its definition is in aclocal's search path.
Makefile.am:187: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:187:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:187:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:187:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:187:   its definition is …
```

Update Web Publishing helper docs to install libtool dependency

---

docs/developing/handbook.md

This also means that we link to http://www.w3.org/TR/capability-urls/
in a way that is consistent with current Sandstorm.

Update handbook to explain sharing links

---

.gitignore
Makefile
icons/Gruntfile.js
icons/package.json
shell/client/_topbar.scss
shell/client/shell.scss

I've replaced the notification bell icon as an example of how this should be used.
There's some small stylistic things that I'm open to changing.
1. The icon classes are prefixed by default with `icon_` (eg. `icon_notification`). By convention, I think we have been using `-` instead of `_` in CSS.
2. I'm using a mixin for `webfont-icon`. This is a little inefficient, but I'm not sure how to cleanly do this with an extend instead.

Replace svg icons with an autogenerated webfont

---

shell/packages/sandstorm-ui-topbar/topbar.js
shell/shared/grain.js

@jacksingleton noted at the recent meetup that it's nice to have a button in
the app to start the sharing flow, rather than showing a screenshot with
instructions for users that might become out-of-date.
This adds a postMessage handler the current grain can call that simply shows
the sharing popup.

Allow apps to request that the "Share Access" menu be shown via postMessage

---

Makefile

#1102 made the build depend on installed versions of npm and node. This patch eliminates those new dependencies, using the bundled Meteor versions of those binaries.

Use Meteor's npm and node for webfont generation.

---

shell/.meteor/packages
shell/.meteor/versions
shell/client/_app-details.scss
shell/client/_applist.scss
shell/client/_install.scss
shell/client/shell.html
shell/client/shell.scss
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-ui-app-details/app-details-client.js
shell/packages/sandstorm-ui-app-details/app-details.html
shell/packages/sandstorm-ui-app-install/install-client.js
shell/packages/sandstorm-ui-app-install/install-server.js
shell/packages/sandstorm-ui-app-install/install.html
shell/packages/sandstorm-ui-app-install/package.js
shell/packages/sandstorm-ui-applist/applist-client.js
shell/packages/sandstorm-ui-applist/applist.html
shell/server/installer.js
shell/shared/grain.js
shell/shared/install.js
tests/commands/installApp.js
tests/tests/grain.js
tests/utils.js

Adapted the app details components to allow for reuse in the install flow.
If "safe", installing an app proceeds directly to the app page after successful
download and installation.  If not known safe, users are prompted with the details
of the app before confirming installation.
Fixes #15 (as of this writing, the oldest open bug!)
Fixes #1043
Fixes #1135 as part of the refactor
Closes #873

Install flow shows app details

---

shell/server/proxy.js

This will result in us sending a 401 to the apps when they try to connect
without providing credentials.
@mnutt do you think this change will allow the owncloud mobile apps to work with Davros on Sandstorm, or will additional changes be needed?

Whitelist the owncloud mobile client apps for HTTP Basic auth.

---

src/sandstorm/spk.c++

Leave the switch in, to preserve compatibility with callers, but it has no noticeable effect.

spk: enable --details by default for `verify`

---

shell/packages/accounts-identity/accounts-identity-server.js

I missed this when I was making some adjustments to the schema in my branch.

The .profile field indicates that a user is an identity.

---

shell/server/proxy.js

The "overwrite" header seems to be somewhat optional, defaulting to "t", so we should make sure the proxy doesn't break if it doesn't get sent on a `MOVE` or `COPY` action.

Protect against missing Overwrite header in WebDAV MOVE or COPY

---

docs/developing/publishing-apps.md

This is probably not the best way to explain it, but it's short, and it works. Most people are using SVGs, so I don't want to devote a large amount of page space to it, so long as this is a single-page document.

Docs: Add example for using PNGs as app icons.

---

shell/packages/sandstorm-identicons/helpers.js

This makes subsequent renders of the app list faster, and speeds up
renders of the grain list (since it's common to have multiple of the
same grain that uses an identicon).
This also avoids duplicating the identicon strings for every usage,
which can save on heap size.

Cache and reuse identicons in JS

---

shell/server/pre-meteor.js
src/sandstorm/app-index/app-index.c++
src/sandstorm/app-index/indexer.c++
src/sandstorm/app-index/indexer.h

This includes all non-published, non-embargoed packages. We will soon setup a mirror of the Sandstorm App Market that points to this.

Change the app-index to produce index-unpublished.json

---

install.sh

In theory our gpg commands shouldn't affect or be affected by GPGHOME, but one user reported that gpg failed out on their machine because the default GPG homedir didn't already exist.

Installer: Use throw-away GPGHOME

---

docs/using/how-it-works.md
mkdocs.yml

This adds a new section to "How It Works" with graphical overviews of communication between a web client and both native and legacy HTTP Sandstorm apps. The graphs are generated by graphviz.
This depends on the markdown-inline-graphviz plugin. To install graphviz and the plugin (Debian example):
```
sudo apt-get install graphviz
pip install markdown-inline-graphviz
```

Docs: HTTP Communication Overview

---

shell/client/_account.scss
shell/packages/accounts-identity/accounts-identity-client.js
shell/packages/accounts-identity/accounts-identity-server.js
shell/packages/accounts-identity/accounts-identity.html
shell/packages/accounts-identity/package.js
shell/packages/sandstorm-accounts-ui/account-settings.html
shell/packages/sandstorm-db/profile.js

This big change here is the addition of the fully reactive `LoginIdentitiesOfLinkedAccounts` pseudocollection. This allows for some simplifications in the login interstitial. The new pseudocollection also gets used for a new widget on the profile editor page; now if an identity is linked to other accounts, you can click a button to expand a list of login identities for those accounts, which looks like this (and needs some design work):

add pseudocollection for tracking other accounts that an identity is linked to

---

LICENSE
Makefile
localedata-C
make-bundle.sh

Before this patch, to obtain a sane locale, we would copy in locales from the
host system, then set `LANG=C.UTF-8` in `run-bundle.c++`.  This had two issues:
* Build hosts that aren't running Debian don't have a C.UTF-8 locale, so the
generated bundle wouldn't run unless you'd manually defined one on the host
* This included *all locales* from the host system, including the whole
locale-archive, which (if you have additional locales installed) could add
~100MB to the package.
With this patch, we move to standardize what locale data we ship:
`make-bundle.sh` will generate a locale similar to Debian's C.UTF-8 locale for
inclusion in the bundle.  This locale, like Debian's, is non-conforming to the
SUS, but is significantly more useful in a variety of ways that are more
important for real …

Add a C.UTF-8 locale descriptor, and generate a locale in make-bundle.sh

---

shell/client/_account.scss
shell/client/_topbar.scss
shell/client/grainview.js
shell/client/shell.html
shell/packages/accounts-identity/accounts-identity-client.js
shell/packages/accounts-identity/accounts-identity-server.js
shell/packages/accounts-identity/package.js
shell/packages/sandstorm-accounts-ui/account-settings.html
shell/packages/sandstorm-accounts-ui/account-settings.js
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js
shell/packages/sandstorm-accounts-ui/package.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/profile.js
shell/packages/sandstorm-db/user.js
shell/packages/sandstorm-permissions/permissions-tests.js
shell/packages/sandstorm-permissions/permissions.js
shell/server/backup.js
shell/shared/admin.js
shell/shared/grain.js
shell/shared/shell.js
tests/tests/grain.js

This rebases and adds one commit (https://github.com/sandstorm-io/sandstorm/commit/7ef09579d34335d239f48473072a54ae0e623f62) to #1199, moving the identity switcher into the account buttons dropdown menu. I'll rebase away the duplicated commits if #1199 ends up getting merged first.
The new commit also gets rid of the `SandstormDb.getUserIdentities()` function, replacing it with `SandstormDb.getUserIdentityIds()`, which doesn't need to make a database query.

move identity switcher into account buttons dropdown

---

src/sandstorm/supervisor.c++

On IRC, mortehu noted that `expectSizeTask` is unused. When it gets dropped, the `expectSize()` request could (and probably does) get cancelled.
This patch ensures that the request goes through and ignores any errors, as recommended by the documentation in [util.capnp](https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/util.capnp).
Note: that documentation may have been written before `Exception.Type.Unimplemented` existed. A more complete solution might be to only ignore errors if they are of type `Unimplemented`. Indeed, there is some code to that effect in blackrock.

Ensure that expectSize() request gets sent.

---

docs/administering/faq.md

the link to "Sandcats dynamic DNS" was broken. Replaced it with `sandcats.md`

Fix broken link in docs/administering/faq.md

---

shell/packages/sandstorm-ui-topbar/topbar.js

#1213 introduced the `AccountButtonsPopup` topbar item. Its data context contains an `isAdmin` field that sometimes is briefly false before becoming true --- I'm guessing that its value depends on some subscription. Currently, that means that the account buttons sometimes fail to show the "admin" button to admin users, because the data context does not get updated. This patch fixes the problem.

Q. Does the template get recreated? A. No.

---

shell/client/_account.scss
shell/packages/accounts-email-token/package.js
shell/packages/accounts-email-token/token_common.js
shell/packages/accounts-identity/accounts-identity-client.js
shell/packages/accounts-identity/accounts-identity.html
shell/packages/sandstorm-accounts-ui/account-settings.html
shell/packages/sandstorm-accounts-ui/account-settings.js
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js

1. Add warning messages for 'unlink identity' buttons.
2. Switch to using a checkbox for toggling login.
3. Disable various actions that could get the user into trouble.
4. Display a message on success or failure.
5. Use 'make primary' buttons for selecting a verified email.

Lots of cleanup for the account profile UI

---

shell/client/_account.scss
shell/client/shell.html
shell/packages/sandstorm-accounts-ui/account-settings.html
shell/packages/sandstorm-accounts-ui/account-settings.js
shell/shared/shell.js

This adds a "Profile" and a "Billing" tab to the /account page when payments are enabled. The design follows the pattern of the tabs in our /admin page.

Split /account route into /account/profile and /account/billing.

---

shell/client/_topbar.scss
shell/client/shell.html
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js
shell/packages/sandstorm-ui-topbar/topbar.html
shell/packages/sandstorm-ui-topbar/topbar.js

We were already planning to do this, but also a Twitter conversation with @hintjens today made it really clear to me that we have a problem here: people don't realize that the demo is time-bound, and don't see the countdown timer in the upper-right. This change makes it much bigger and eye-catching on the sidebar, with a "create account" button that opens the login menu.
@hintjens also gave feedback that:
* If we had asked him to register upfront before doing anything, he probably would have refused.
* Once he created some data he wanted it to be permanent, and to that end he would have registered if prompted.
* The demo / non-demo dichotomy is confusing and unexpected.
So far I haven't thought of a way to satisfy all three constraints: We can't let people create permanent data without …

Make demo timer much more obvious.

---

shell/packages/accounts-email-token/token_common.js
shell/packages/accounts-email-token/token_server.js
shell/packages/accounts-identity/accounts-identity-client.js
shell/packages/accounts-identity/accounts-identity-server.js
shell/packages/sandstorm-accounts-ui/account-settings.html
shell/packages/sandstorm-accounts-ui/account-settings.js

This patch prevents an account from linking an identity that is already a login identity for another account.  When the account attempts (and fails) to perform such a link, an explanatory error message will be shown in the usual place on the /account page.
This patch also makes sure that demo identities are nonlogin and cannot be upgraded to login.

Tighter constraints on which identities may be linked or set to login.

---

.gitignore
Makefile
shell/client/_account.scss

This makes the icons the same shade of gray that they are in @neynah's mock-ups.
before:
after:

Make identity provider icons darker and a bit larger, for readability.

---

shell/client/_account.scss
shell/packages/sandstorm-accounts-ui/account-settings.html

Add some padding in the title bars, better alignment for verified email buttons, and a horizontal rule between the profile fields and the identity management buttons. Looks like:

style tweaks

---

shell/client/grainview.js

GrainView's `reset()` did not clear all the fields it needed to clear,
so other derived data were incorrect.  This includes having bad values
for the iframe's src in transitional states.

Fix setPath/identity switcher interaction

---

meteor-bundle-main.js

This fixes a bug that logs this message:
```
Will switch certs, probably to /var/sandcats/https/{{hostname}}/{{filename}}, at time Invalid Date via real-time SNI re-keying system.
```
which has the side-effect that real-time SNI re-keying didn't work.
Details:
- I was adding `undefined` to an integer and getting `NaN`, then
- Adding `NaN` to another number and getting `NaN`.
- As a result, I had an unused helper value, `twentyMinutesInMilliseconds`.
- Eventually I converted some of these things to `new Date()`s and got an `Invalid Date`.
Testing done:
- Added this patch to `rose.sandcats.io` (my self-install), then
- Manually fiddled with time on my self-install to Sat Dec 5, then
- Caused it to log this message: `Will switch certs, probably to …

sandcats https: Do date arithmetic on the right operands

---

shell/packages/sandstorm-db/db.js

It might make sense to have this field on identities too, but we would first need to update the stats code in several places.

Update Users.lastActive documentation to match current reality: only accounts have this field.

---

shell/client/shell.html
shell/packages/sandstorm-accounts-ui/account-settings.html
shell/packages/sandstorm-accounts-ui/account-settings.js
shell/packages/sandstorm-accounts-ui/login_buttons.js

This fixes a bug that sometimes created blank grain views when a user linked an email identity.

Use linkEmailIdentityToAccount() Meteor method in all cases when linking an email identity.

---

shell/client/_account.scss
shell/client/grainview.js
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js

We auto-open the login popup with options for "sign in" (goes to the normal login button list) and "stay anonymous" (closes the popup).
Currently looks like screenshot below. I suspect @neynah can come up with something better, but I think this is good enough to push now.

Suggest sign-in when opening a sharing link anonymously.

---

shell/shared/demo.js
shell/shared/grain.js

Also, don't show a blank screen if a token's grain has been deleted.
Currently, it's possible for the shared links of demo users to lead to blank pages.  For example: https://twitter.com/hintjens/status/672118319961513984
This patch doubly fixes the problem:
1. Shared links whose grains have been deleted now display "invalid token" rather than a blank screen.
2. Shared links to demo grains are now actually cleaned up when the demo user is deleted.

Clean up more data from demo users when they expire. 

---

shell/client/shell.html
shell/client/shell.scss

Problem: [this selector](https://github.com/sandstorm-io/sandstorm/blob/09c03628b27e86957b41a7dfc483a0e891da9d96/shell/shared/grain.js#L1419) matches the `main-content` element.
Solution: use a different class, as we did with `first-sign-in-main-content`.

Fix bug where an expired demo user could see a grain just by refreshing the page.

---

shell/shared/admin.js

The behavior in which the first setting change succeeds but subsequent changes fail is not intuitive to users. The intent of the admin token is to give the user time-limited access to the admin interface -- but not to limit it to only one change.
In the past, the problem was masked by the fact that the first setting change was usually to enable a login service. The user would then log in and, by virtue of being first user, get promoted to admin, so never use an admin token again.
However, the "first user becomes admin" thing has changed. Now, the user must exchange the admin token to receive permanent admin rights. With the token being good for only one change, this means that two admin tokens are required while setting up a server: one to enable login, and another to actually become …

Don't clear the admin token after setting just one setting.

---

shell/shared/shell.js

@jadeqwang reported a bug with the following steps to reproduce:
- Have a paid plan, and
- Go to /referrals on Oasis, and
- See text about how you could earn up to 2GB of storage, when that text really should be telling you that you can earn up to 30GB of storage
I took a shortcut here in the template helper, which was not to wrap it in `function()`, but perhaps that was wrong. So this commit fixes that. I say "perhaps that was wrong" because it seems to work fine both ways for me on localhost. But maybe if I don't make it a function, it doesn't get reactively re-run, but I can't trigger the reactivity on localhost because latency is too low.
@jparyani I had emailed you about this before; everything I know is here, so maybe if we discuss, let's discuss here.
Note that I _can_ reproduce …

Use normal syntax for template helper

---

shell/packages/accounts-identity/accounts-identity-client.js

Addresses #1263 by avoiding ever explicitly setting the current identity ID for demo users. When such users link a non-demo identity, that identity will become the current identity as a result of the default identity precedence order in `Accounts.getCurrentIdentityId()`.
Also, removes a call to `Meteor.loginWithIdentity(result)` that's unneeded, due to reactivity.

Don't set the current identityId for demo users.

---

shell/packages/accounts-email-token/token_server.js
shell/packages/accounts-identity/accounts-identity-server.js
shell/packages/accounts-identity/package.js
shell/packages/sandstorm-backend/sandstorm-backend.js
shell/packages/sandstorm-db/db.js

This prevents the error seen in #1255.
Note that we now need to explicitly check that we aren't linking an identity that's already linked to the current account --- otherwise, a fresh account that tries to re-link its only identity gets pushed back to the login interstitial with no helpful error reported.

Automatically delete unused accounts when doing so would free up an identity that a user wants to link.

---

shell/packages/accounts-identity/accounts-identity-server.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/user.js
shell/shared/demo.js

Currently appdemo users are being counted as plain demo users because the `appDemoId` field only gets written to identities, not accounts. This patch propagates `appDemoId` to accounts and drops the unneeded `isAppDemoUser` field.

Fix appdemo stats collection.

---

shell/client/_account.scss
shell/client/shell.html
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/user.js
shell/shared/shell.js

This lets the user know that billing is a thing. The user can of course choose "free", but perhaps some will want to choose a plan immediately, and others will want to keep in mind that they have options.
The strategy is similar to the profile confirmation page, in that the plan selector overrides other routes. However, there is an exception: if the user is trying to view a shared grain (not one they own), then we do not interrupt them, since this would be weird for people who are only here to interact with their friend's grains.
There is a risk that this change will scare some users away too early. We should consider running a controlled experiment.
Note how the prompt does not show any plan as "current", even though the free plan is technically current.
This PR is the Sandstorm side of …

On initial signup, if billing is enabled, show a billing plan selector.

---

shell/packages/sandstorm-permissions/permissions.js
shell/server/proxy.js

Grains that have been shared since #1161 have broken app icons. This patch fixes the problem and deletes some now-unused code.
It would not be too difficult to also write a migration that fixes up any tokens that have been created in the mean time.
Related question: I seem to remember that we had some discussions at one point where we decided that the recipients of shares should not get to see the appId of grains that are shared with them. Do we still think that would be desirable?

DenormalizedGrainMetadata has an 'icon' field, not an 'appIcon' field.

---

tests/tests/postmessage-api.js
tests/utils.js

The test app now renders a template that includes the token and host as JSON,
for easier use in the tests.

Add postMessage API tests

---

src/sandstorm/app-index/app-index.c++
src/sandstorm/app-index/app-index.capnp
src/sandstorm/app-index/indexer.c++
src/sandstorm/app-index/indexer.h

1. Fix a bug introduced by the "experimental" index change: Detailed metadata from non-approved version of packages was taking precedence over approved packages of the same app. Details for experimental packages are now placed under `/experimental` rather than `/apps`.
2. Reject app updates that fail to bump `appVersion`.
I've actually already updated the master index with these changes because we were displaying bogus metadata on app details pages.

App index improvements

---

Makefile

A CI system using this can not be affected when upstreams make non-fast-forward
pushes to branches that we rely on.
Closes #1261.

Add a clobber-deps command to the Makefile for CI usage

---

shell/client/_account.scss

Stop intrinsic name from overflowing in identity cards

---

shell/shared/devAccounts.js
tests/commands/loginDevAccount.js
tests/tests/backup-restore.js
tests/tests/basic.js
tests/tests/grain.js

Attempt to remove the need for arbitrary `pause()` invocations.  Ideally, we
should wait for things to reach a desired state, with a timeout for that
happening, so we don't sit idly for the rest of the timeout period.
This change makes login cleanly async, which should save a couple seconds on
each test that performs login.

Test code cleanup

---

shell/packages/sandstorm-db/migrations.js
shell/packages/sandstorm-permissions/permissions.js
shell/server/proxy.js

This deletes the ill-formed tokens discussed in https://github.com/sandstorm-io/sandstorm/pull/1179#issuecomment-162548946, fixes the tokens described in #1285, and adds the `identityId` field in some tokens where it had been accidentally omitted previously. It also simplifies some conditional login in proxy.js; the deleted branch should have had `proxy.apiToken = tokenInfo`.

Add a migration to clean up some ill-formed entries in ApiTokens.

---

Makefile

This appears in the Makefile and how it invokes `stodgy-tester`.

Fix trivial typo: hyphen vs underscore

---

Makefile

Going to self-merge because this is 100% installer-tests related.

Set TERM= for installer-tests, so it prints colorized output in Jenkins

---

Makefile

Going to self-merge because it's 100% related to installer-tests.

Makefile: Get output from installer-tests a little faster

---

Makefile

Going to self-merge since this is 100% installer-tests.

Extend timeout for jessie VM apt-get slowness

---

docs/administering/backups.md

Self-merging because this is 100% docs

Typo fix: backup => back up, for verb form

---

src/sodium/crypto_core
src/sodium/crypto_core_hsalsa20.h
src/sodium/crypto_core_salsa20.h
src/sodium/crypto_core_salsa2012.h
src/sodium/crypto_core_salsa208.h
src/sodium/crypto_sign
src/sodium/crypto_sign.c
src/sodium/crypto_sign_ed25519

This makes the directory structure more faithful to the original repository, so that [this include](https://github.com/jedisct1/libsodium/blob/f9d982480ba68895dd90f29cf072bc3e533f09de/src/libsodium/crypto_sign/ed25519/ref10/open.c#L10) has a chance of working.

twiddle with some symlinks to get libsodium to build

---

shell/packages/sandstorm-ui-topbar/topbar.html

Removed the title attribute on the app icon, since you can't actually trigger a
hover on the app icon because the link stacks above it.
Fixes #1325.

Add tooltip with grain title to links in navbar

---

shell/shared/admin.js

Currently if any non-admin visits /admin/settings they will see an error like "Error invoking Method 'signUpAsAdmin': Match failed [400]".

Only attempt to sign up as admin if there actually is a token.

---

shell/packages/sandstorm-ui-autocomplete-input/autocomplete-client.js

It turns out we only need to monitor `mousedown` events. `click` events
don't trigger correctly for these elements on desktop anyways.

Fix mobile double completing contacts on click

---

shell/packages/sandstorm-ui-app-details/app-details-client.js
shell/packages/sandstorm-ui-app-details/app-details.html
shell/shared/grain.js

This is almost certainly due to the fact that meteor's reconnect timer can exceed 60s (it caps at 5 minutes). Add a check in the keepAlive interval and manually call Meteor.reconnect if needed.

Fix sessions sometimes not refreshing within 60s

---

shell/client/_account.scss
shell/client/shell.html
shell/packages/accounts-email-token/token_common.js
shell/packages/accounts-email-token/token_server.js
shell/packages/sandstorm-accounts-oauth/oauth_common.js
shell/packages/sandstorm-accounts-packages/accounts.js
shell/packages/sandstorm-accounts-packages/package.js
shell/packages/sandstorm-accounts-ui/account-settings.html
shell/packages/sandstorm-accounts-ui/accounts_ui.js
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js
shell/packages/sandstorm-accounts-ui/package.js
shell/shared/admin.js
shell/shared/devAccounts.js

Notes:
We were previously calling `Accounts.oauth.registerService()` on every service. The only thing that got us was the ability use `Accounts.oauth.serviceNames()` as a convenient way to enumerate the enabled services. `Accounts.identityServices` now gives us a better way to enumerate them.
`Meteor.loginWithDevAccounts` was only needed previously so that clicking on the devAccounts login button would redirect to the devAccounts page.
I deleted some code that existed to close the topbar popup on login. It's no longer needed because the login menu is now different from the account menu; logging in destroys the former, triggering an `onDestroyed()` callback that clears the topbar-expanded state.

Modularize login buttons registration and rendering.

---

shell/client/_admin.scss
shell/client/shell.html
shell/packages/accounts-email-token/token_server.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/migrations.js
shell/shared/admin.js

For now this is only used on login emails, but I also plan to use it for invoice emails in Blackrock.
Note that I intentionally did NOT apply this to sharing emails because we plan to make those be "from" the sharing user soon.

Add configurable server title and return address for notification emails

---

shell/packages/sandstorm-db/profile.js

Some of our code assumes that `intrinsicName` exists for all identities:
https://github.com/sandstorm-io/sandstorm/blob/097ee0da80dcd1ec76823b38396a03365a04a079/shell/packages/sandstorm-ui-autocomplete-input/autocomplete-client.js#L55
https://github.com/sandstorm-io/sandstorm/blob/097ee0da80dcd1ec76823b38396a03365a04a079/shell/shared/grain.js#L275
Currently we don't fill in `intrinsicName` for demo identities, mostly I couldn't think of what it would make sense to put there.
With this patch, we fill in `intrinsicName` with the date that the demo started.
An account profile that has a linked demo identity will look like this now:

Give demo users an intrinsicName of the form 'demo on 2016-01-14'.

---

shell/server/proxy.js

Looks like this broke in one of the big ES6 changes: https://github.com/sandstorm-io/sandstorm/commit/eed6e5a2dab392f59d610a9ec8f3669e38a4be72 (which GitHub apparently can't render in-browser)

Fix references to WebSocketReceiver.queue.

---

shell/client/_topbar.scss

Fixes #1299 
I'm not sure this is actually any clearer than  using a table, since I'd never heard of "block formatting contexts" before doing this. I'm also not sure if there's some easier way to do this with display: flex. Feel free to suggest alternatives.

Makes contact input sized more flexibly

---

shell/client/_admin.scss
shell/client/shell.html
shell/packages/sandstorm-db/db.js
shell/server/startup.js
shell/shared/admin.js

Disables oauth services on BASE_URL change, but does not delete the config. Displays red boxes in the admin area, explaining why the services were disabled.
Looks like this:

Implement the plan described in #1374

---

shell/client/_account.scss
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js

I noticed that it was difficult to navigate to dev login using just the keyboard, probably because the dev login element in the login buttons list is a form, not a button. This makes it easier.

Make dev login element a button when not expanded.

---

shell/packages/sandstorm-accounts-ui/login_buttons.js

Fixes some fallout from https://github.com/sandstorm-io/sandstorm/commit/1887ba24dcf79d9e07dd75143d97b1c1748c9b65.
Currently, I see errors like `TypeError: Cannot read property 'focus' of null` when I expand the login menu.

Fix autofocus in login dropdown and account dropdown.

---

install.sh
installer-tests/fail-on-32-bit-system.t

NOTE that this changes the "fail" function to have two arguments.
Also:
- installer-tests: Adjust failure string to be more lenient.
- Capitalize the first word in a sentence.
- Include half-written code for sending errors to an Oasis grain, if
users opt in. This is disabled by default at the moment.
- Avoid race condition in permissions for sandcats logs by creating
the file with touch and then setting its permissions.

install.sh: Create error codes for install.sh failures

---

shell/client/grainview.js
shell/client/shell.html
shell/client/shell.scss
shell/shared/grain.js

This allows us to display a helpful error message if the intended recipient is not logged in when they click the link:

use /shared/ links in share-by-identity emails

---

shell/packages/sandstorm-db/db.js

@phildini reported being unable to link an identity from a unused account on Oasis. The problem was that the account had received the referrals announcement notification, so Sandstorm did not consider it to be unused.
This patch changes the logic so that Sandstorm would still have considered that account to be unused. Deleting an account that has some notifications but nothing else should not be dangerous.

Ignore notifications in SandstormDb.deleteUnusedAccount().

---

shell/client/_account.scss
shell/client/shell.scss
shell/packages/accounts-identity/accounts-identity.html

https://github.com/sandstorm-io/sandstorm/commit/c62deea2485d5012bc98f965b6ba784bb34186e5 included some changes to make the `.main-content` div more stable. Unfortunately, those changes imply that now the `.main-content` div gets rendered on top of the identity login interstitial and the demo expired interstitial. This means that attempts to log in with non-login identities get stuck at what looks like a blank screen, and demos seem to continue past their 60 minutes.
Here we fix the problem by ensuring that the interstitials get rendered on top.

Fix invisible identity-login-interstitial and demo-expired-interstitial.

---

docs/administering/faq.md
shell/.meteor/packages
shell/.meteor/versions
shell/packages/npm-request/.npm/package/.gitignore
shell/packages/npm-request/.npm/package/README
shell/packages/npm-request/.npm/package/npm-shrinkwrap.json
shell/packages/npm-request/package.js
shell/packages/npm-request/server.js
shell/server/installer.js
src/sandstorm/run-bundle.c++

This adjusts `installer.js` to use the `request` API, rather than the node
HTTP/HTTPS API. It also adjusts `run-bundle.c++` to pass this variable through,
and adjusts the docs to explain how to use this feature.
Refs #693
Does not fully close #693 yet because a few other places need a similar update.

Add support for using a HTTP proxy for outbound connections (just for app install for now)

---

shell/packages/sandstorm-ui-applist/applist-client.js

They are the most likely app for a developer to be interested in launching, so sort dev apps before non-dev apps.

Sort dev apps at the top of the app list

---

tests/apps/roundcube.js

Roundcube appears to discard an early click on the settings button.  The click
changes the button's appearance, but does not actually lead to the settings
pane being shown, which makes the rest of the test fail.
Adding a short pause to allow the initial pageload to complete seems to make this
better.

Add a pause to roundcube test to increase reliability

---

docs/administering/self-signed.md
docs/administering/ssl.md
mkdocs.yml

It's confusing that our current "HTTPS & SSL" documentation page only talks about Sandcats, and even talks about self-signing certificates for use with Sandcats --- something that very few users will want to do now that we are offering free certificates. In paricular, [thegq on IRC](http://logbot.g0v.tw/channel/sandstorm/2016-01-25), who wanted to set up non-sandcats HTTPS, seemed to be confused by these docs.
This pull request attempts to make things less confusing. It keeps the self-signing docs because they still might still be useful to someone, but it makes them somewhat less prominent.

Link to reverse proxy docs from ssl.md. Push self-signing instructions into their own page.

---

docs/vagrant-spk/packaging-tutorial.md

... to reflect that vagrant-spk works. You may want to add more details, but I'd figured I'd update it to at least indicate that it can work on Windows.

Changed line about Windows support

---

src/sandstorm/backend.c++
src/sandstorm/sandstorm-http-bridge.c++
src/sandstorm/supervisor.c++

We make use of the new `kj::Promise.ignoreResult()` where possible.
We still need some additional type hints for clang to figure out the return
type of the functions where we have side-effects, but don't return anything.
Closes #1132
Closes #936

Fix compilation against clang-3.7+

---

shell/client/grainview.js
shell/shared/stats.js

When ApiTokens migrated from using `userId` to using `identityId`, we appear to
have missed a couple of places we used the old value.
As usual, this could have been caught by a typechecker and a strongly-typed
interface.
Fixes #1449.

Fix vestigial references to userId that should be identityId

---

tests/commands/disableGuidedTour.js
tests/commands/installApp.js
tests/tests/backup-restore.js
tests/tests/grain.js
tests/tests/postmessage-api.js

Extract `disableGuidedTour` into a helper command, since we want to use it in a
couple places.  Use `installApp` in more places.

tests: deal with more guided tour failure possibilities

---

shell/server/proxy.js
src/sandstorm/sandstorm-http-bridge.c++
src/sandstorm/web-session.capnp

From sandstorm's perspective, PATCH and PUT are functionally equivalent. PATCH RFC: https://tools.ietf.org/html/rfc5789
Addresses https://github.com/sandstorm-io/sandstorm/issues/1218.

add PATCH http method support

---

shell/client/grainview.js

Currently, if you open a grain and then close it from the navbar, its GrainView can linger on due to a still-alive `_sessionObserver` observer. That observer actually gets triggered every three minutes when `gcSessions()` happens. At that point, the GrainView calls `openSession()`, causing the session to be renewed and the grain's `lastUsed` time to be updated. The confusing result: the "Last Activity" column in the grain list continues to update for grains that have been closed!

Make sure to stop all subscriptions and observers when a grainview is destroyed.

---

shell/shared/shell.js

Currently the referral notification's "dismiss" button has hovertext "Stops the background app", which is the default for such buttons.
This patch changes the default to "Dismiss this notification". To help do this, we push to the client the `ongoing` field. That field contains an ApiToken with owner `{frontend: null}`. It would be nice if we did not need to share this token with the client, because we really only care whether it's present or not. However, I don't think it's that big of a deal, since only the frontend can do anything with the token.

Fix hovertext for referral notification.

---

shell/.meteor/packages
shell/.meteor/versions
shell/client/shell.html
shell/client/shell.scss
shell/packages/sandstorm-contacts/contacts-client.js
shell/packages/sandstorm-contacts/contacts-server.js
shell/packages/sandstorm-contacts/package.js
shell/packages/sandstorm-ui-autocomplete-input/autocomplete-client.js
shell/shared/grain.js

Baby steps towards a more fully-featured Who Has Access view.
This change adds a revoke button for each time the current user appears in the "added by" column. It looks like:
Clicking the button revokes the share. If the share went through a sharing link, a confirmation dialog is displayed that explains who else might also be affected by the revocation.

Allow revocation of direct shares in the Who Has Access view.

---

src/sandstorm/run-bundle.c++
tests/unittests/cli.js

The `sandstorm reset-oauth` command was useful back when we had no admin settings page and when changing the `BASE_URL` didn't not automatically clear the oauth config. Nowadays, however, I think its existence is a net negative.
@mrdomino reported invoking the command, expecting it to log out all currently logged-in users, but instead getting into a state with broken config and then not noticing until a rather long time later that nobody could log in. Had he visited the admin/settings page instead of invoking `sandstorm reset-oauth`, this confusion would likely have been averted. (Note that our admin/settings page has both "reconfigure" and "log out all users of this provider" options.) The situation was made worse by the fact that `db.meteor_accounts_loginServiceConfiguration.remove({})` …

Remove the `sandstorm reset-oauth` command.

---

docs/administering/faq.md

#1478 removes the command, so let's just stop mentioning it.
The admin UI will step the user through any further steps they need.
Thanks to @mrdomino for using this command which we realized was sort of useless so we deleted it, and to @dwrensha and @kentonv for deleting it.

Remove remaining reset-oauth mention in docs

---

shell/server/proxy.js

The third argument of `globalBackend.updateLastActive(grainId, this.userId, session.identityId)` ends up undefined, which causes the 'last active' time to not get updated.
I believe this bug was introduced in the accounts/identities split. It became more exposed after #1448 got merged.

Fix bug with the 'last active' time of 'shared with me' grains.

---

shell/client/grainview.js
shell/client/shell.html
shell/shared/grain.js

Fixes #1474.
Presents the Share Access button to everyone, including signed-out users. For incognito users, the popup looks like:
For signed-out users, it looks like:

Share Access popup for incognito grainviews.

---

src/sandstorm/supervisor.c++

[323 is the correct value for x86_64](https://github.com/torvalds/linux/blob/cb4c4e8091e86e08cb2d48e7ae6bf454245c36cb/arch/x86/entry/syscalls/syscall_64.tbl#L332).

Define userfaultfd syscall number if it is not already defined.

---

shell/client/_admin.scss
shell/client/shell.html
shell/packages/sandstorm-db/db.js
shell/server/pre-meteor.js
shell/shared/admin.js

This is some fairly minimal changes for showing information to the admin about a misconfigured `WILDCARD_HOST`.
Screenshot of what admin looks like when this warning is visible:
Review request from:
- @neynah and/or @zarvox - please sanity-check my proposed text
Review & merge requested from:
- @kentonv
Note for Kenton: This adds a new subdomain pattern, `selftest*`.
Note that this _only_ affects `/admin/*` routes. That means that people can still get a forever-spinning grain spinner.
From my perspective, @jadeqwang and I want to limit how much time I spend on this particular bit of self-testing, so I'd like to declare making the `grain-frame` provide warning text as out-of-scope for this pull request. IMHO the most important thing is that people see this when they are doing initial …

On admin screen, detect misconfigured WILDCARD_HOST & show warning

---

docs/extra.css
docs/sandstorm_readthedocs_modified_theme/README.md
docs/sandstorm_readthedocs_modified_theme/base.html
docs/sandstorm_readthedocs_modified_theme/js/theme.js
mkdocs.yml

This commit:
- Forks base.html from the mkdocs readthedocs theme.
- Copies in the Javascript unmodified, since I was having problems with the JS
not executing locally otherwise.
- Adds a README.md to this directory.
- Uses extra_css.
- Adjusts mkdocs.yml to point at the customizations.
- Uses flexbox to add a "sandstorm.io" link so people can get to
the sandstorm.io home.
- Adjusts mkdocs.yml to rename this project to just "Docs" rather tha
"Sandstorm" or "Sandstorm Docs" so that the navigation link in the top
is clearer.
- Tells mkdocs to ignore the env/ directory, which contains a
virtualenv.
Close #1405

docs: Fork theme; add separate sandstorm.io link to nav

---

shell/server/proxy.js
src/sandstorm/sandstorm-http-bridge.c++
src/sandstorm/web-session.capnp

Fixes #1437
Closes #1491
Note that https://github.com/kentonv/node-capnp/commit/10e269d298189236881d038413950b0302610e9a is also needed for `*` to work correctly (for both `If-Match` and `If-None-Match`).

Support If-None-Match: *.

---

shell/client/_about.scss
shell/client/_account.scss
shell/client/_grainlist.scss
shell/client/shell.scss

This changeset switches to border-box box-sizing for everything by default.  This is widely considered best practice: http://www.paulirish.com/2012/box-sizing-border-box-ftw/
I did my best to audit our codebase for places where box-sizing would affect layout -- namely, elements with both a `width` or `max-width` and a `margin` or `border`.  To discover sites where layout would be affected, I manually added the rules in the last commit in Chrome to a tab open to oasis.sandstorm.io (to ensure that I discovered issues that only exist when e.g. payments are enabled), and toggled the rule on the `<html>` tag.  Where things changed appearance, I adjusted element sizes.
While there may be some subtle changes in layout that I have missed, I believe they should be generally inconsequential.
Things …

Use `box-sizing: border-box;` everywhere

---

docs/administering/backups.md
docs/install.md
mkdocs.yml

People sometimes want to know how to uninstall Sandstorm. There isn't a script, but there is now a complete guide.
I also took the liberty of improving the backups docs at the same time.
I also took the liberty of explaining what the install script actually does. I think this would have addressed @glyph's questions when he asked me things on IRC. I'll go check with him after pushing this.

Add install & uninstall docs

---

shell/.jscsrc

We have a bunch of places that are over 100 characters, and I don't think they
are particularly harmful to readability.  I'd welcome over-time reworking
toward a 100-character line limit, but I don't think we need to be religious
about line lengths in general.
This rule was added to the airbnb preset recently, which is why my previous
changesets did not deal with this warning.

JSCS: don't warn about line length

---

docs/administering/faq.md
shell/client/shell.html

Rationale: axx on #sandstorm had working wildcard DNS, but non-working wildcard
HTTPS. This change adjusts the error message info and updates the FAQ item to
mention wildcard HTTPS.
Thanks to @axelsimon for showing me the issue!

Mention certificates in wildcard hosts warning

---

docs/administering/faq.md
src/sandstorm/run-bundle.c++

Having a better log message could have helped @sanderant debug this without assistance, I believe.
We found ~350MB triggered the error case, but 500MB free resulted in success.
Requesting review/merge from @kentonv

Tell people mongod failure could be due to low disk free

---

src/sandstorm/feature-key.capnp

A feature key unlocks "Sandstorm for Work" features. Most commercial software would use the term "license key" or "license file". However, a sandstorm feature key does not correspond to a license. The license is Apache 2.0, and everyone receives the license even if they don't have a feature key.

Initial definition of feature keys.

---

shell/client/_powerbox.scss
shell/packages/sandstorm-ui-powerbox/package.js
shell/packages/sandstorm-ui-powerbox/powerbox-client.js
shell/packages/sandstorm-ui-powerbox/powerbox-server.js
shell/packages/sandstorm-ui-powerbox/powerbox.html
shell/shared/grain.js
src/sandstorm/ip.capnp

Adds support for requesting `IpNetwork` and `IpInterface` capabilities.
https://alpha-hlngxit86q1mrs2iplnx.sandstorm.io/test-5.spk is capable of requesting and (minimally) testing both IpNetwork and IpInterface.
The IpNetwork test will make an HTTP request to http://zarvox.org/ and return the page contents.  You can see this (and indeed, the page content) in the network tab of the Chrome Dev Tools.
The IpInterface test will listen on port 8888, and write "Hello world!\n" to the first client that connects, then close the connection and provide an empty 200 response to the HTTP request that triggered it.  node will continue listening on port 8888 until the grain is stopped or deleted; I think this may be a bug in pycapnp: https://github.com/jparyani/pycapnp/issues/90

Powerbox IP capabilities

---

docs/vagrant-spk/customizing.md

This hopefully minimizes confusion when people modify `setup.sh` but don't realize they need to re-run `provision` or `destroy && up`.

Emphasize how to manually re-run setup.sh

---

shell/client/_account.scss
shell/client/grainview.js
shell/client/shell.html
shell/client/shell.scss
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-email/email.js
shell/packages/sandstorm-ui-autocomplete-input/autocomplete-client.js
shell/shared/grain.js

When a user visits a grain they are unauthorized to access, displays a button that requests access from the grain owner. The button looks like this:
After the button is clicked, the grain owner gets an email that looks like this:
The "Open Sharing Menu" button is a link to `/share/:grainId/:identityId`, which redirects to the grain with the sharing menu popped up and prepopulated with the requester's identity.
The `replyTo` field in the email is the address of the access-requester.

Request Access button

---

src/sandstorm/app-index/app-index.c++
src/sandstorm/app-index/indexer.c++
src/sandstorm/app-index/indexer.h
src/sandstorm/appid-replacements-test.c++
src/sandstorm/appid-replacements-test.capnp
src/sandstorm/appid-replacements.c++
src/sandstorm/appid-replacements.capnp
src/sandstorm/appid-replacements.h
src/sandstorm/id-to-text-test.c++
src/sandstorm/id-to-text.c++
src/sandstorm/id-to-text.h
src/sandstorm/spk.c++
src/sandstorm/spk.h

This allows developers to recover from a lost or stolen app ID. The idea is that we compile directly into Sandstorm a mapping of lost keys and new keys that are replacing them. Apps signed with the new key will be treated by Sandstorm and all tools as if they are signed with the old key. Old keys can also optionally be revoked while specifying an exact list of known-good packages that had been signed with said keys. If the old key was merely lost but not believed to have leaked (e.g. all copies were destroyed), then revocation is not necessary.
@JamborJan in particular needs this for Paperwork.
This change is cleanly split into two commits which I recommend reading separately.
Also: Yay unit tests.

Implement app ID replacement table.

---

LICENSE
Makefile
shell/.meteor/packages
shell/.meteor/versions
shell/client/_account.scss
shell/client/shell.html
shell/lib/db-deprecated.js
shell/packages/accounts-email-token/token_server.js
shell/packages/accounts-ldap/LICENSE
shell/packages/accounts-ldap/README.md
shell/packages/accounts-ldap/ldap_client.js
shell/packages/accounts-ldap/ldap_server.js
shell/packages/accounts-ldap/package.js
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/profile.js
shell/packages/sandstorm-db/user.js
shell/run-dev.sh
shell/shared/admin.js

This is in a rough state, but it seems to be working (tested extensively with OpenLDAP, see https://help.ubuntu.com/lts/serverguide/openldap-server.html#openldap-server-populate for how to setup a local server).
In order to enable this functionality, a Meteor settings variable named `isFeatureKeyValid` must be true. This is set in `run-dev.sh` for testing purposes.

Add ldap login support

---

Vagrantfile

Rationale:
- Close #263 for now because the build works on Debian, at least in theory
- Fewer things for us to support, since we already use this base box in vagrant-spk.
- Document how to install dependencies, allowing me to close #544 (by also
overriding SERVER_USER)
- While we're at it, link to some docs.

Switch the default Vagrantfile to Debian

---

shell/packages/sandstorm-backend/sandstorm-backend.js
shell/server/drivers/mail.js
shell/server/proxy.js

Fixes #1550.
The `runningGrains` table allows us to avoid calling `Backend.startGrain()` in many cases. Because we currently call `waitPromise()` when we call `Backend.startGrain()`, that means that we avoid a round trip in those cases. However, the table is problematic in that can lead to separate `Proxy` objects holding the same reference to a supervisor. When one of those proxies closes, it calls `supervisor.close()`, invalidating the reference for everybody. Moreover, as far as I can tell, we don't actually need to wait for `startGrain()` to finish, and there's no harm in calling `startGrain()` on grains that are already started.
Narrower fixes to #1550 are possible, but this looks to me like a good opportunity to get rid of some cruft.

Remove the SandstormBackend.runningGrains table.

---

shell/client/shell.html
shell/shared/grain.js
shell/shared/shell.js
tests/commands/getDevName.js
tests/tests/grain.js

Fixes #1581 and adds an integration test for it.
Destroying all grainviews on login used to be problematic in the case of linking an email identity, but after the identity-provider refactor of last month, I don't think it's an issue.

Destroy all existing GrainViews on login.

---

shell/packages/sandstorm-accounts-ui/account-settings.js
shell/packages/sandstorm-db/profile.js
shell/server/hack-session.js
shell/shared/grain.js

Indicate which email is primary in the results of SandstormDb.getVerifiedEmails().

---

shell/client/_app-details.scss
shell/client/_topbar.scss
shell/client/shell.html
shell/packages/sandstorm-ui-app-details/app-details.html

I went ahead and switched over to font icons since we need to do this anyway and they display consistently in IE (amazingly).
This also fixes some minor mobile styling regressions caused by the box-sizing change.
@jparyani I found that the webfont-icon mixin wasn't very reusable. Initially I tried to add parameters to customize but then I realized I was customizing everything so there was no point. We may want to remove this.
Fixes #1560

Fix a bunch of icons on IE, mostly in the sharing UI.

---

src/sandstorm/appid-replacements.capnp

As the original key was destroyed a new key is used.

new app key for Paperwork app

---

shell/server/hack-session.js
shell/shared/grain.js
shell/shared/shell.js
tests/tests/grain.js

This fixes a bug in #1590 where users would see blank pages after a `sandstorm restart`.
This also fixes a few places in #1585 where I forgot to project out the `email` field.

Subscribe to "requestingAccess" immediately on displaying the Request Access page.

---

shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-permissions/permissions.js
shell/server/core.js
shell/server/proxy.js
shell/shared/demo.js
shell/shared/grain.js
shell/shared/testing.js
src/sandstorm/sandstorm-http-bridge.c++
src/sandstorm/web-session.capnp
tests/tests/apihost.js

This supports both:
* Setting the `DAV` header to return for unauthenticated OPTIONS requests.
* Defining small static resources which can be `GET`ed unauthenticated, e.g. `/status.php`.
Example app code: https://github.com/kentonv/apihost-testapp/blob/master/client/index.html
Also in this PR, I extended web-session.capnp to pass through DAV extension identifiers in OPTIONS requests.
I would like to get this out in this weekend's build so that we can fix up Radicale next week. If @zarvox can't review in time, I'll probably just merge as-is.
@mnutt @synchrone

Support adding unauthenticated options headers and resources to API hosts

---

shell/shared/grain.js

Currently, if a user receives access to a grain through a sharing link, that link gets revoked, and then the user tries to visit the grain from their grain list, the client goes into an infinite retry loop.
This fixes the problem.

Ignore child tokens in 'requestingAccess' publish.

---

docs/administering/sandcats-https.md

* Fix broken brackets for [CanIUse SNI availability link](http://caniuse.com/#feat=sni)
* Correct ```teminator``` -> ```terminator```

Fix typos in Sandcats.io HTTPS technical docs

---

shell/client/styleguide.html
shell/client/styleguide.js

cc @neynah Feel free to add arbitrary HTML to `shell/client/styleguide.html` to demonstrate whatever widgets you find appropriate. :)
If you have a Sandstorm development environment up and running, you'll be able to see this page at http://local.sandstorm.io:6080/styleguide ; if not, happy to help you set one up tomorrow/whenever.

Add trivial route and template for styleguide

---

docs/developing/http-apis.md
shell/shared/grain.js

This adds the ability to use `$GRAIN_SLUG` in an offer template to generate a useful representation of the name of the grain.
My use case for this is Owncloud Client authentication. While Sandstorm ignores the username field of basic auth, Owncloud Client displays it when listing remote servers, so setting it to the name of the grain is the only real way to distinguish remote servers in Owncloud Client.
Unfortunately not anything can go in the `username` part of a URL, so it sanitizes things like `Michael's Grain` down to `michaels-grain`.

offerTemplate $GRAIN_SLUG replacement

---

shell/packages/sandstorm-db/db.js

Happily, the old code coincidentally did the right thing at runtime, but this is the more reliably correct thing to do.

Whoops, shouldn't use globalDb from inside db.js

---

src/sandstorm/package.capnp

Zlib/libpng is a free software non-copyleft license which some
projects use. https://opensource.org/licenses/Zlib

Zlib added to the allowed opensource licences list

---

shell/client/_topbar.scss

The popup frame should be `position: relative`, so that children (like the close
button) will be placed relative to that frame.

Fix position of popup close button on mobile

---

shell/packages/sandstorm-db/db.js
shell/run-dev.sh
shell/server/admin.js
shell/server/feature-key.js
src/sandstorm/feature-key-tool.c++
src/sandstorm/feature-key.capnp
src/sandstorm/update-tool.c++

Also:
- Removed isFeatureKeyValid Meteor setting. Instead, feature keys with "isForTesting = true" will work only when the server is running in testing mode (another Meteor setting). I will generate such testing certificates for everyone to use.
- Fixed key reassembly in feature-key.js to be little-endian.

Create command-line tool for generating feature keys.

---

Makefile
shell/client/admin-client.js
shell/client/shell-client.js
shell/client/shell.html
shell/client/styles/_admin.scss
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-db/db.js
shell/server/admin-server.js

- Group the organizational management (auto-upgrade) settings together rather than putting them next to each provider, because this is an important concept and needs some explanation. New users won't understand the concept of "auto-upgrade" and could easily miss the checkbox otherwise.
- Move LDAP settings into their own section because cramming them between basic login providers created an unnatural split.
- Make auto-upgrade actually work. It din't work previously because the feature key was not subscribed except in admin routes.
- Add a button to delete the feature key, mainly for testing purposes.

Tweak Sandstorm for Work

---

docs/administering/guide.md
docs/developing/publishing-apps.md
docs/vagrant-spk/customizing.md
docs/vagrant-spk/packaging-tutorial-meteor.md
docs/vagrant-spk/packaging-tutorial.md
docs/vagrant-spk/platform-stacks.md

Adjusts docs to recommend the canonical commands as amended by sandstorm-io/vagrant-spk#145

docs: use `vagrant-spk vm *` for up, halt, ssh, destroy

---

shell/client/grain-client.js
shell/client/grainview.js
shell/client/shell-client.js
shell/lib/db-deprecated.js

We store the list of open grains in localStorage at shutdown and restore it at startup. We also clear the saved list at startup so that if you open a second window it doesn't open the same grains again. Additionally, we do *not* store anything when closing a window that only has one grain open (or none), as probably in this case the user is relying on browser tabs rather than our sidebar tabs and restoring the last-opened grain would be surprising.
(Also fixed a random exception I've been seeing and fixes #1578.)

Restore last-opened grains on load.

---

shell/client/admin-client.js
shell/client/shell.html
shell/packages/accounts-ldap/ldap_server.js
shell/packages/sandstorm-db/db.js

Split ldap settings into two branches. It's now more clear that you either need to specify an explicit Dn, or provide a base DN to search on. Also added the ability to specify the username field when searching.

Tweak ldap settings

---

install.sh

We use the "type" value when calculating how many people attempted to do a
Sandstorm install. We had to stop using "install" because vagrant-spk happens
to use &type=install during situations that we do not want to categorize as an
attempt by a human to install Sandstorm.

install.sh: Switch to type=install_v2

---

src/sandstorm/api-session.capnp
src/sandstorm/email.capnp
src/sandstorm/util.capnp
src/sandstorm/web-publishing.capnp

Note that while the outgoing-HTTP and email drivers may be implemented as pseudo-drivers, I think that the web publishing driver may have no such luck, as it needs to store significant amounts of data and we will want to charge that against the user's quota. Plus we don't have a great place to store the data if not in a grain.
@zarvox @jparyani

Add / extend Cap'n Proto interfaces for key drivers.

---

docs/install.md

See https://github.com/sandstorm-io/sandstorm/commit/f9e5db8a488502bcf10a7d0b5cba7bcab75c6307.

Update docs to reflect the fact the we no longer depend on ImageMagick.

---

shell/.meteor/packages
shell/.meteor/versions
shell/client/grain-client.js
shell/client/shell-client.js
shell/lib/db-deprecated.js
shell/packages/accounts-identity/accounts-identity-client.js
shell/packages/accounts-identity/package.js
shell/packages/sandstorm-ui-grainview/grainview-list.js
shell/packages/sandstorm-ui-grainview/grainview.js
shell/packages/sandstorm-ui-grainview/package.js
shell/packages/sandstorm-ui-topbar/topbar.js
tests/tests/grain.js
tests/tests/restore-open-grains.js

This defines a new class `GrainViewList` for the value held by `globalGrains`. The list is automatically cleared whenever `Meteor.userId()` is detected to have changed. When an oauth identity is linked, the grain restoration logic is postponed until the linking is complete, so that the automatic clearing does not destroy any open grains.
Fixes #1625. (@kentonv: I don't fully understand your comment about membranes there. I think it suffices to remove the grain iframe from the DOM, because that should cause any javascript associated with the grain to stop executing.)

GrainViewList

---

tests/tests/account.js

A logged-in user has a "current identity" for each open grain, as well as one for the Sandstorm shell in general. Currently we make sure that after a demo user upgrades, their shell current identity is equal to their non-demo identity.
We do not switch the identity on any other grains. User testing has suggested that it would maybe be less confusing if we did switch those identities, including for any open grain views. However, I'm not entirely convinced that's the correct behavior, as there may be some apps that present a completely different view for different identities, so automatically switching identities for them could make it seem like data has been lost. In any case, switching the identities would not be a completely trivial change. If we decide that's the way to go, we should …

Check that immediately after demo upgrade, the current identity is the non-demo identity.

---

shell/client/grain-client.js

Fixes https://github.com/sandstorm-io/sandstorm/issues/679. Note that when you link a new identity, you are not required to fill in profile information for it, so `profile.name` being empty needs to be handled. Note also that the `ContactsProfiles` pseudocollection already fills in the defaults in the non-self case.

Make sure to fill in profile defaults for the 'added by' column.

---

shell/server/pre-meteor.js

This change (in my opinion) clarifies the issues and available next-steps for someone who is:
- Accessing Sandstorm at the wrong URL, by accident
- Attempting to view their static publishing site without ever setting up DNS TXT records
- Attempting to view their static publishing site while DNS TXT records are slowly propagating and haven't arrived at this server yet
Credit goes to @zarvox, as I recall, for mentioning recently that this error message could be improved, although I honestly forget exactly when he mentioned that. Maybe he remembers.
Screenshot:

Clarify the "Wrong URL" error message page

---

shell/server/admin-server.js

In the client/server split, I missed that a server Meteor method relied upon
one of the client-side route definitions.
Considering that we shouldn't ever change that route definition, since it would
break already-sent signup invites, we can manually construct the appropriate
path on the server.

Fix email invites

---

shell/.jscsrc
shell/client/grain-client.js
shell/packages/sandstorm-ui-powerbox/package.js
shell/packages/sandstorm-ui-powerbox/powerbox-client.js
shell/packages/sandstorm-ui-powerbox/powerbox-server.js
shell/packages/sandstorm-ui-powerbox/powerbox.html
shell/server/core.js

PowerboxDescriptors are now provided in base64url-serialized-packed Cap'n Proto format, not JSON. For example, a UiView can be requested as "EAZQAQEAABEBF1EEAQH_5-Jn6pjXtNsAAAA".
This will be necessary going forward because PowerboxDescriptor.Tag.value is an AnyPointer, the schema of which Sandstorm may not even know. The query-matching algorithm is designed to operate on Cap'n Proto binary format without the need for a schema, but without a schema it is not possible to convert to/from JSON.
I expect most apps won't need to customize their queries very much, so can probably get away with using hard-coded queries copied from documentation. Copying a whole query string seems not much worse than copying a type ID. I also imagine adding an spk sub-command for generating query strings.

Refactor Picker Powerbox so that query matching happens on the server side.

---

docs/developing/auth.md
shell/client/grain-client.js
shell/packages/sandstorm-backend/sandstorm-backend.js
shell/packages/sandstorm-db/db.js
shell/server/hack-session.js
shell/server/proxy.js
src/sandstorm/grain.capnp
src/sandstorm/sandstorm-http-bridge.c++

In the future, a grain tab may in fact be displaying multiple grains at once, and thus multiple sessions. This can happen when the Picker Powerbox is displaying an embedded picker, or when a grain embeds other grains (e.g. the "Tabbify" proposal). It may also be useful for a single grain to recognize server-side when multiple sequential back-end sessions actually come from the same tab, as occurs e.g. when the user suspends their laptop and then comes back later without refreshing their browser.
In some cases it may be helpful if these grains can recognize that they live in the same tab. Hence we generate a `tabId` which is passed to `newSession()` and uniquely identifies the tab.
The current motivating use case is one where the Powerbox is being used in an authentication interaction: The …

Implement `tabId` to correlate sessions in a grain tab.

---

docs/administering/reverse-proxy.md
docs/administering/wildcard.md

These docs changes adjust a few things:
- Mention how `HTTPS_PORT` relates to other things in the reverse proxy docs.
- Adjust `wildcard.md` to tell people how to set up wildcard DNS, rather than just that we're so cool to use it.
- Adjust reverse proxy docs to clarify that HTTPS behind a reverse proxy is optional.

Mention https port in reverse proxy docs

---

docs/developing/troubleshooting.md

Fixes a typo.
Before
> If possible, configure the app to use a base URL of '', literally the empty string. Then it will send HTTP redirects without specifying a base URL. If that isn't possible, Sandstorm apps should look at the
> 
> Sandstorm apps should look at the Host: header for a base URL if they need one.
After
> If possible, configure the app to use a base URL of '', literally the empty string. Then it will send HTTP redirects without specifying a base URL. If that isn't possible, Sandstorm apps should look at the `Host:` header for a base URL.
Also made the word-wrapping in this file consistent; let me know if you'd rather I not touch this, and I'll put it back.

Fix typo in troubleshooting guide

---

shell/client/grain-client.js
shell/client/shell.html
shell/server/grain-server.js
tests/tests/grain.js
tests/tests/sharing.js

Also, skip the identity chooser for already-redeemed tokens.
Fixes #1693.

Don't show request access button for /shared/ links.

---

shell/packages/sandstorm-permissions/permissions.js
shell/packages/sandstorm-ui-powerbox/powerbox-client.js
shell/server/core.js
shell/server/drivers/ip.js
shell/server/hack-session.js
src/sandstorm/ip.capnp
src/sandstorm/supervisor.capnp

Nothing exploitable (at least with today's non-powerbox-using apps).
- SandstormPermissions.createNewApiToken()'s check()s lazily used Match.ObjectIncluding() to match LocalizedString, possibly allowing garbage through (ignored garbage, but this is being stored).
- SandstormPermissions.createNewApiToken() did not support all ApiTokenOwner types, so could't safely be used to implement save().
- SandstormCoreImpl.restore() added a membrane reqirement that the token was valid, only to have save() (makeChildTokenInternal()) attempt to filter it out of the requirements later. It seems more natural to say that this requirement is implicit, so doesn't need to be in the list.
- SandstormCoreImpl.restore() was not enforcing that the token was owned by the calling grain.
- …

Fix lots of bugs in SturdyRef handling.

---

shell/server/grain-server.js
tests/tests/grain.js

Don't show identity chooser interstitial if the opener is the grain owner or the token creator.

---

docs/developing/publishing-apps.md

This partially fixes #1564. @paulproteus is going to re-host the image.

Added icon preview graphic to docs

---

shell/client/styles/_account.scss
shell/client/styles/_topbar.scss
shell/packages/sandstorm-ui-topbar/topbar.html
shell/packages/sandstorm-ui-topbar/topbar.js

We rely on `position: static` on mobile to ignore the `left: $41px` or `right:
0px` inline styles which we compute to place the popup near its controlling
element for desktop.
Since we benefit from using `position: relative` for the contents of the frame,
split this into two nested divs:
`div.frame-container` is responsible for the placement and size of the popup as
well as border and drop-shadow.
`div.frame` is responsible for including all of the interesting content of that
popup, which can be `position: relative` to allow for absolutely-positioned
items within the frame.
Fixes #1725.

Fix mobile popup positioning

---

shell/client/styles/_account.scss
shell/client/styles/_powerbox.scss
shell/client/styles/_topbar.scss

This also fixes a bug in the powerbox popup where at small screen heights
content would overflow the .frame-container by using `max-height: inherit`.
This also fixes an issue where I wrote `flex-begin` rather than `flex-start` in
four places.  It would be nice if we had a CSS/SCSS linter.

Fix up more popup styling

---

shell/client/admin-client.js
shell/packages/accounts-ldap/ldap_server.js

This forces all users to setup a search DN with LDAP. The reasoning is that very soon, we'll be syncing LDAP directories for other purposes, so the ability to only set an explicit bind DN without searching would be problematic. We're reasonably confident that no current beta feature key testers are using in this wild, but if so, this will break them (since there's no reasonable automated migration we can perform for them).
This also involved completely removing the explicit DN binding code path in `ldap_server.js`.

Remove the option for setting an explicit DN with LDAP

---

install.sh
installer-tests/full-server-install-with-unwritable-usr-local.t

Close #1660
Note that this prints an ugly warning when this occurs. If we want smarter handling, someone can file a new bug. I think this addresses @ndarilek's need that `install.sh` should succeed on CoreOS.

Make install succeed when /usr/local/bin is unwritable

---

shell/client/admin-client.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/migrations.js
shell/server/admin-server.js

Reduces client-server/DB roundtrips when checking org membership and makes for more straightforward settings code.  The setup wizard uses this merged settings layout.
@jparyani I'd appreciate a sanity check on this.

Consolidate organization membership settings

---

shell/client/grain-client.js
shell/client/shell.html
shell/client/styles/_topbar.scss
shell/packages/sandstorm-db/db.js
shell/server/grain-server.js

This uses `SandstormDb.getReturnAddress()` for the envelope sender and something like "Alice \<alice@example.com\>" for the inner "from" field. It also fills the subject line with "grain title - Invitation to collaborate".
I tested this out with some display names containing non-ASCII characters and it seems to work; at least, when gmail received the messaged the headers were properly encoded as per [RFC 2047](https://tools.ietf.org/html/rfc2047).
One snag is that SimpleSmtp (or something that it depends on) does not like to see certain characters such as "<" in the display name, and encoding or escaping them does not seem to help. (Whereas according to my reading of [RFC 2822](https://tools.ietf.org/html/rfc2822), "<" ought to be allowed.) So I drop such characters.

In grain-invite emails, fill in the "from" field with a more appropriate value.

---

installer-tests/full-server-install-on-jessie-with-userns-sysctl.t

This will hopefully make installer-tests be green.

Remove assertion that Sandstorm shows up on $PATH

---

src/sodium/crypto_core_hchacha20.h
src/sodium/crypto_pwhash_argon2i.h
src/sodium/private

This should fix the build once https://github.com/jedisct1/libsodium/commit/3927cad829156038a6baa9821d041b76b2f8f0f8 gets pushed to the libsodium stable branch.

Get libsodium to build with the new include/sodium/private directory.

---

shell/packages/sandstorm-db/db.js

I don't think this would actually break under any actual circumstances (the
migration guarantees all the things being null-guarded all exist), but it's
clearly not what was intended.

Fix a copy-o.

---

install.sh
installer-tests/Vagrantfile
installer-tests/automatic-dev-install-on-jessie.t
installer-tests/install-without-root.t
installer-tests/interactive-dev-install.t

While we're at it:
- Stop sending people to the admin token flow in the case of dev accounts being on. (EDIT: Somehow my change to do this caused syntax errors in bash on jessie, but not on unstable? Skipping for now.) (RE-EDIT: I forgot a `fi` for bash to close the `if`. Fixed.)
- Stop asking `-u` users if they want option (1) or (2) when only (2) will work. (Send them straight into option 2.)

install.sh: fix issue 1777

---

.gitignore
Makefile
icons/ldap.svg
shell/client/styles/_account.scss

Turns out that `ldap.svg` currently has some invisible cruft in it that causes it to render poorly in the webfont. So part of my change here is to delete that cruft.

Add webfont icon to LDAP and SAML identity cards and switch to webfont for other providers.

---

shell/server/grain-server.js

This is [`$sandstorm-purple-color`](https://github.com/sandstorm-io/sandstorm/blob/0ba3e06c246217c81f46a641e8e1a9c4561d49ba/shell/client/styles/_colors.scss#L4).
Looks like:

Switch the button in sharing emails from blue to purple.

---

src/sandstorm/supervisor.c++

Note that this does not remove the underlying code. I can do that if we
really want, but for what it is worth, the warning causes much more heartache
than the unused code.

Remove ip_tables red herring warning

---

shell/client/shell-client.js

I'm tired of seeing this every time the page refreshes and I care about what's
being logged but instead see mostly this giant note with yellow background and
larger type than console.log() and links that are large click targets that make
it harder to focus the JS console input.
Disable the note from the JS console:
localStorage.setItem("muteDevNote", true)

Allow muting the app dev message with a particular key in localStorage

---

tests/tests/grain.js

Lately we've been seeing a bunch of failures like https://build.sandstorm.io/job/Sandstorm/1099/. My current hypothesis is that [our `unload` listener](https://github.com/sandstorm-io/sandstorm/blob/480bf3fde24796c169d4b196da6b5f0deab51660/shell/packages/sandstorm-ui-grainview/grainview-list.js#L35-L67) somehow interacts poorly with our grain loading logic, particularly in the case when a share link is being redeemed. It would be good to actually track down the root cause, but in the meantime let's make our tests less flaky.

Attempt to make the 'grain identity chooser interstitial' test more robust.

---

shell/public/offer-template.html

There appears to be a Selection edge case in Firefox that inserts spurious
newlines into the value copied onto the clipboard if you attempt to select
everything contained by a `<pre>` within a `<div>` if the `<div>` contains newlines,
but the `<pre>` does not.
Removing the contained newlines makes Firefox do the right thing.
Fixes #1795.

Offer templates should avoid extra newlines on the clipboard in Firefox

---

tests/run-local.sh

Firefox 45.0.1 causes errors [like this](https://bsr44jl5i2yrk3lgqhmd.oasis.sandstorm.io/debug.txt) when I run `make test`. Updating Selenium makes the problem go away.

Update Selenium to version 2.53.0.

---

src/sandstorm/backend.c++
src/sandstorm/supervisor.c++
src/sandstorm/supervisor.capnp
src/sandstorm/supervisor.h
src/sandstorm/util.c++
src/sandstorm/util.h

This is important if the front-end has independently shut down and started up again; any existing capability will be disconnected.
As part of this, I had to refactor the CapabilityRedirector stuff a bit. Previously, were actually creating two levels of redirectors, one of which was never being redirected.
While I was there, I also made CapabilityRedirector directly detect disconnects in case the caller can't (as is the case after keepAlive()).
(This problem has been causing the feature key vendor to fail a lot.)

Send a new SandstormCore capability on Supervisor.keepAlive().

---

shell/client/admin-client.js
shell/client/shell.html

Due to a hilarious dual-purposing, the default empty string value is
considered by the backend to mean "please delete the current feature key".
We have a button for that, with an appropriate warning.  We should not let you
accidentally remove your feature key in this manner.
Fixes #1766.

Feature key form: don't allow submitting an empty feature key text

---

install.sh

Note that without this fix, new dev installs are broken. Thanks to @Daemoen
for showing up on IRC and sharing the problem.

install.sh: if adminToken does not exist, do not try to chown it

---

install.sh

There is no reason to expect that non-root installs want a dev server. In fact, dev servers mostly don't work with non-root installs (although I'd prefer not to default to live either because I often use this flow for testing).

Don't default to dev server when using install.sh -u.

---

install.sh

Reverts sandstorm-io/sandstorm#1800
I'm stupid. See discussion on #1800.

Undo: Don't default to dev server when using install.sh -u.

---

tests/commands/assertReceiveEmail.js
tests/commands/sendEmail.js

The SMTP server in `assertReceiveEmail` currently has the default connection timeout of 60 seconds. This implies that if you just run the roundcube tests, you end up waiting for a minute after the tests are complete until they actually shut down. 10 seconds, as specified by the `timeout` option in this pull request, is more reasonable. (As far as I could determine, there is no easy way to immediately close the connection.)
The `req.accept()` call makes sure that the client knows that the message was accepted. Without it, Sandstorm throws a "DeliveryError: Message delivery failed" exception that gets logged in `sandstorm.log`.
The `pool.close()` calls in `sendEmail` shut down the client right away. (Currently this connection stays open until a timeout, as in the server.)
These changes …

Mail integration tests: faster and cleaner closing of simplesmtp stub client and server.

---

make-bundle.sh

If the system's `node --version` is not 0.10, then the built Sandstorm bundle will crash with errors like 
```
Error: `/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`
```
This fixes the problem. See also https://github.com/sandstorm-io/meteor-spk/pull/16.

Make sure that the fibers package targets the correct v8 version.

---

shell/server/grain-server.js

Alice owns a grain. Alice shares the grain to Bob through the identity `alice@example.com`. Alice unlinks her `alice@example.com` identity. Bob no longer has access, as expected. What's not expected is that when Bob visits the grain URL, he now sees an infinite redirect loop. The problem is that the `accountId` on Bob's token still points to Alice, the grain owner, so it looks kind of like Bob should have access, and therefore the client retries again and again. The solution proposed here is to base the decision to retry on more reliable data: the `identityId` field.

Request access button: prevent redirect loop when grain owner has unlinked the sharer identity.

---

shell/client/admin/identity-providers.html
shell/client/admin/identity-providers.js
shell/client/styles/_admin-identity.scss

We need to be able to keep this up to date in our releases,
since Google changes their workflow more frequently than
Meteor manages to update their setup instructions.
This change includes the copy updates from @ocdtrekkie aka Jacob Weisz from
https://github.com/meteor/meteor/pull/6757
This change strips the trailing slash from the Javascript origin in the Google
instructions, since Google's form complains if you include a path in that
scheme/host/port.
Fixes #1756, #1188, #953.

IdP settings: vendor in and improve Google/GitHub OAuth instructions

---

shell/client/grain-client.js
shell/client/shell.html
shell/client/styles/_account.scss
shell/client/styles/shell.scss
shell/packages/accounts-identity/accounts-identity-client.js
shell/packages/accounts-identity/accounts-identity-server.js
shell/packages/accounts-identity/accounts-identity.html
shell/packages/sandstorm-accounts-packages/accounts.js
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-accounts-ui/login_buttons.js
shell/packages/sandstorm-db/profile.js
shell/packages/sandstorm-ui-grainview/grainview.js
shell/server/grain-server.js
shell/shared/admin.js
shell/shared/dev-accounts.js
tests/tests/sharing.js

Alice shares to Bob by identity. Bob clicks the link in the email, but is either not signed in or is signed in to a different account. In this situation, we currently display an identity card for the shared-to identity and we indicate that Bob needs to sign is as that identity in order to access the grain. With the changes in this pull request, that identity card becomes a button. If Bob clicks on it, he initiates sign-in as that identity.
For example, for a github identity, the identity card button looks like this:
and one click is sufficient to sign in. For an email identity, the sign-in sequence looks like:
Fixes #1624.
This also fixes a few other things that I noticed were broken, such as linking of LDAP or SAML identities, and email notifications for share-by-identity to LDAP or SAML …

Clickable identity cards in share-by-wrong-identity.

---

shell/client/styles/_about.scss
shell/client/styles/_account.scss
shell/client/styles/_admin.scss
shell/client/styles/_app-details.scss
shell/client/styles/_applist.scss
shell/client/styles/_grainlist.scss
shell/client/styles/_partials.scss
shell/client/styles/_powerbox.scss
shell/client/styles/_referrals.scss
shell/client/styles/_topbar.scss

We declare `box-sizing: border-box` [at the top level](https://github.com/sandstorm-io/sandstorm/blob/v0.158/shell/client/styles/shell.scss#L30-L52) and we don't use `box-sizing: content-box` anywhere, so all of the other instances of `box-sizing: border-box` can be removed.

Remove superfluous instances of 'box-sizing: border-box'.

---

shell/client/admin-client.js

@zarvox and @dwrensha and @paulproteus have all experienced false-positives
on this self-test. Four seconds might be long enough.

Use a longer WILDCARD_HOST self-test delay

---

shell/packages/sandstorm-backend/sandstorm-backend.js
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/migrations.js
shell/packages/sandstorm-permissions/permissions.js
shell/packages/sandstorm-ui-grainlist/grainlist-client.js
shell/packages/sandstorm-ui-grainview/grainview.js
shell/packages/sandstorm-ui-powerbox/powerbox-client.js
shell/server/hack-session.js
shell/server/proxy.js
shell/server/stats-server.js
src/sandstorm/supervisor.capnp

The addition of `lastUsed` to `user` in `ApiTokenOwner` caused the field to propagate to `createNewChildToken()` where the presence of its default-value caused a shape check to fail.
`lastUsed` is useful in contexts other than `ApiTokenOwner`, is not actually needed as a part of any of the protocols that use `ApiTokenOwner`, and is better off removed from the `.capnp` and added as a top-level field on `ApiTokens`.
Usually, removing a field from a `.capnp` would be **strictly forbidden**, but the commit message of dfc260cea1c7a24cbefb95aa0b87c8d7bf6f9347 explains why this is actually okay in this particular case.

Fix powerbox offer of UiView

---

docs/developing.md
docs/extra.css

Update developer portal icons and change sidebar header colour

---

shell/client/grain-client.js
shell/client/shell.html
shell/client/styles/_topbar.scss
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-db/migrations.js
shell/packages/sandstorm-ui-grainlist/grainlist-client.js
shell/packages/sandstorm-ui-grainlist/grainlist.html
shell/packages/sandstorm-ui-grainview/grainview.js
shell/server/grain-server.js
src/sandstorm/supervisor.capnp

Historically, when a grain is shared, the title would be copied and become the receiver's "petname" for the grain, displayed whenever the receiver opens the grain. If the owner renamed the grain post-sharing, the receiver would never see the rename, only their petname. If the receiver renamed the grain, it would change their petname. This was generally confusing to people.
However, the alternative of "always show the owner's title" is also problematic since:
- If the title changes in the recipient's grain list, they may be confused as to how this new grain that they don't remember got here.
- If the owner's title is poorly-chosen or similar to other grains in the receiver's grain list, the receiver may want to retitle the grain for themselves (hence the petname behavior).
This change …

Improve grain renaming behavior. Fixes #1087

---

shell/packages/sandstorm-backend/sandstorm-backend.js
shell/packages/sandstorm-permissions/permissions.js
shell/packages/sandstorm-ui-grainlist/grainlist-client.js
shell/server/grain-server.js

We should actually write `upstreamTitle` when initially creating tokens.
A user can have multiple incoming tokens for a single grain. The `lastUsed` update in sandstorm-backend.js needs `{ multi: true }`, or else it just picks a single token nondeterministically.
The token used in the grainlist should be the oldest, not the most recently used. It would be weird if merely receiving a new share caused the title to change.
When the user updates the title on an incoming token, all incoming tokens for that grain should get renamed, for the sake of robustness.

Fix various corner cases with grain renaming.

---

meteor-bundle-main.js
shell/server/drivers/mail.js
shell/server/pre-meteor.js
src/sandstorm/run-bundle.c++

Close: #1386 
Testing done so far:
Testing still to do:
Notes to reviewers:
- I believe all this code works, so feel free to give me review feedback on the code right now, so I can get it merged faster.

Bind to SMTP_LISTEN_PORT in C++-land (now ready for review/merge)

---

Makefile

Fixes #1922.
Meteor's bundled npm script now does
```
#!/usr/bin/env node
```
whereas it previously did
```
`dirname "$0"`/node "$0" "$@"
```
therefore we should set the PATH so that the correct node binary is found.

Avoid using system node when installing webfont packages.

---

shell/packages/sandstorm-permissions/permissions.js
shell/packages/sandstorm-ui-powerbox/powerbox-client.js

Reintroduces some changes in `createNewApiToken()` from https://github.com/sandstorm-io/sandstorm/commit/9f5b98324b7c78b7e9e5004435c2cc02897977ec that accidentally got rebased away in https://github.com/sandstorm-io/sandstorm/pull/1767.
Fixes some references to an undefined `cardData` variable. These were introduced in https://github.com/sandstorm-io/sandstorm/pull/1675.

Fix uiview offer

---

shell/server/drivers/mail.js

Just some things I noticed while reading through the code.
Not tested.

Small e-mail fixes

---

shell/client/shell-client.js

Currently, the upload error is only set when actions complete. So if you upload an invalid zip, and then try uploading a valid one, you see `Upload failed: Invalid backup file. [500]` instead of the usual progress message, even through the upload is taking place.

Clear upload error before starting a new upload.

---

shell/run-dev.sh

Currently, the `meteor run` call in `run-dev.sh` binds to all interfaces. This has repeatedly annoyed me when I've launched a vangrant-spk VM and later discovered that it has failed to set up port forwarding because `run-dev.sh` was already using `127.0.0.1:6080`. (In my local setup, I have a Sandstorm server bound to `127.0.0.2:6080`.) The problem is solved if `run-dev.sh` only listens on IP address configured in sandstorm.conf, as in this patch.

only listen on BIND_IP in run-dev.sh

---

shell/client/admin-client.js
shell/client/admin/admin.html
shell/client/admin/personalization-client.js
shell/client/admin/personalization.html
shell/client/styles/_admin-personalization.scss
shell/client/styles/_new-admin.scss
shell/imports/server/auth.js
shell/server/admin-server.js
shell/server/admin/admin-alert-server.js
shell/server/admin/personalization-server.js

Includes a small backend refactor to extract a couple of previously-magic-global functions to be explicitly imported.
Adds a new home for a few one-off settings that were neglected in the new-admin redesign, but arguably fit together under a "server customization + personalization + whitelabeling" header.
Closes #1960.

New admin personalization

---

shell/client/admin/user-invite-client.js
shell/client/admin/user-invite.html
shell/client/styles/_admin-users.scss
shell/client/widgets/widgets-client.js
shell/server/admin/admin-user-invite.js

Improvements to previous iteration that I couldn't not make:
* Creating a link does not close the page
* Creating a link autofocuses the link text for easy copy/paste
* Email invite is disabled if email is not configured, and nudges
admins to configure email
* Email invite has slightly better placeholders/details text.
* Styles match our standard forms.
References #1938.

New Admin: User invite

---

shell/client/admin/system-status-client.js
shell/client/admin/system-status.html
shell/client/grain-client.js
shell/client/shell-client.js
shell/client/styles/_admin-status.scss
shell/imports/client/build-info.js
shell/imports/client/download-file.js
shell/server/admin/system-status-server.js
shell/server/install-server.js

This marks the start of me attempting to use ES6 modules to deduplicate code,
as described in http://guide.meteor.com/structure.html#example-app-structure
Expect future work to attempt to avoid duplicating functions in various modules,
and to see existing mostly-UI packages to move out of Meteor packages and
into ES6 modules.
One nice affordance I managed to get to work is that the log starts out scrolled to the **end** of the file, and will continue to follow the end as logs stream in if scrolled to the bottom, but will preserve the scroll position if you scroll up (so new input doesn't prevent you from seeing older input if you want).  I intend to replicate this behavior for the "Show Debug Log" pane some time, as the most recent logs are almost always the most interesting to see, and …

New Admin: System Status page

---

shell/client/grain-client.js
shell/client/shell.html
shell/client/styles/_app-details.scss
shell/client/styles/_grainlist.scss
shell/client/styles/_partials.scss
shell/client/styles/shell.scss
shell/packages/sandstorm-db/db.js
shell/packages/sandstorm-permissions/permissions.js
shell/packages/sandstorm-ui-app-details/app-details-client.js
shell/packages/sandstorm-ui-app-details/app-details.html
shell/packages/sandstorm-ui-app-install/install.html
shell/packages/sandstorm-ui-grainlist/grainlist-client.js
shell/packages/sandstorm-ui-grainlist/grainlist.html
shell/packages/sandstorm-ui-grainlist/package.js
shell/packages/sandstorm-ui-grainview/grainview.js
shell/server/grain-server.js
shell/server/proxy.js
tests/tests/trash.js

This implements most of #1915.
The grain list looks like: 
When you click "View Trash", you get:
The "Delete permanently" button updates its text depending on what's selected. If only "shared with me grains" are selected, it says "Forget permanently". If both kinds of grains are selected, it says "Delete/forget permanently".
The app details page gets a similar update:
If you search for something in the main list and matches only exist in the trash list, you get a pointer like this: 
If you try to open a grain that is in your trash, you get an error page like this:
If you try to open a grain that is not owned by you and is in its owner's trash, you get an error page like this: 
This also updates the permissions computation so that when a grain gets trashed or deleted, any sessions that …

Implement trash bin and bulk grain action buttons.

---

install.sh

Close #631 
I chose to make this message both technically clear ("Could not detect the script's filename") because when someone triggers it, it might cue them to realize that the reason they triggered it is that they chose a strange filename.
I chose to provide a specific command to run at the end so that people who are seeing it, but don't know why, can get past it too.

install.sh: Explain why we failed to re-exec ourselves

---

shell/client/admin/admin.html
shell/client/admin/stats-client.js
shell/client/admin/stats.html
shell/client/admin/user-invite-client.js
shell/client/admin/user-invite.html
shell/client/styles/_admin-stats.scss
shell/client/styles/_colors.scss
shell/client/styles/_new-admin.scss
shell/client/styles/_partials.scss
shell/client/styles/_widgets.scss
shell/client/widgets/widgets-client.js
shell/client/widgets/widgets.html

`reportStats` unset:
Click "Send anonymous stats":
You can disable reporting if you change your mind:
Tables have the same content as ever, but now also lightly highlight the row you're hovering over, to aid readability of wide rows:
Closes #1826.

New admin stats

---

shell/run-dev.sh

https://github.com/sandstorm-io/sandstorm/pull/1958 did not completely solve my problem. When trying to run `run-dev.sh` just now, I kept getting the error "Please shut down your Sandstorm front-end", even though the frontend was most definitely already shut down. The problem was that I had a vagrant-spk VM running on localhost:6080, and run-dev.sh uses `localhost` to check if a frontend is running.

localhost -> BIND_IP in run-dev.sh

---

shell/client/grain-client.js
shell/client/shell-client.js
shell/client/shell.html
shell/packages/accounts-identity/accounts-identity-client.js
shell/packages/sandstorm-accounts-ui/login_buttons.js
shell/packages/sandstorm-ui-grainview/grainview-list.js
shell/packages/sandstorm-ui-grainview/grainview.js
tests/tests/grain.js
tests/tests/trash.js

After this change, `Accounts.getCurrentIdentityId()` and `Accounts.setCurrentIdentityId()` do not deal with the grainview list at all. If you care about the active identity on a grainview, you need to call `globalGrains.getActive().identityId()`.
Closes https://github.com/sandstorm-io/sandstorm/issues/1291.

Eliminate some out-of-scope usages of globalGrains.

---

docs/developing/http-apis.md
shell/server/proxy.js

It turns out that sending an Authorization header is techincally not
allowed for cross origin websockets. To work around this, we will allow
websockets to provide the token as part of the path.

Add an authentication method for API websockets

---

shell/client/shell-client.js
shell/packages/sandstorm-ui-grainlist/grainlist-client.js

The "root" route is supposed to redirect to `/grain` on login if the user has any grains at all. Currently, the redirect logic can fail in a few ways: it can check for the existence of grains during the half-logged in state, and it can end up rendering the grainlist template with the "root" data context (?!). This patch fixes the former problem by waiting until the user is actually logged in as an account user. The latter problem is still mysterious to me, but my use of a `subscriptions` hook here seems to make it go away. By checking that `data.grains` exists before iterating over it, I ensure that even if the problem does come up again, it won't create a blank screen as it currently does.

Fix exception on login and make sure to redirect to the correct place.

---

shell/client/admin/admin.html
shell/client/admin/network-capabilities-client.js
shell/client/admin/network-capabilities.html
shell/client/styles/_admin-network-capabilities.scss
shell/client/styles/_new-admin.scss
shell/client/styles/_widgets.scss
shell/server/admin-server.js
shell/server/admin/network-capabilities-server.js

I'm not super thrilled with the fact that:
1. There's no way to sanely assign width to the grain title vs. grain owner boxes, short of just making both fixed width.  (Note that the `.identity-card` is already a fixed width box.)
2. We only show grain owner if it's different from who granted the capability.  The two people I've shown this design to were both confused by this behavior.
But I think this is still better than what existed before (provides more context about the capability, offers search/filtering), and we're likely to make more changes in the future that will obsolete this design, so I think we can roll with this.
Closes #1823.

New Admin: Network Capabilities

---

shell/client/admin/user-accounts-client.js
shell/client/admin/user-accounts.html
shell/client/admin/user-details-client.js
shell/client/admin/user-details.html

...where accounts reference missing identities.
On at least alpha.sandstorm.io and zero (@kentonv's dev instance), there are
user accounts in Mongo's users collection with a loginIdentities field that
references an identity account for which there is no document in the
collection.
Theoretically this is supposed to be impossible, since we only ever delete
identities that are demo identities, and at least alpha has never enabled demo
accounts.  In practice, these DBs exist, and we'd do well to handle their
(surprising) contents a little more defensively.

Admin panel users page: deal with corrupted DBs

---

shell/client/grain-client.js
shell/packages/accounts-identity/accounts-identity-client.js
shell/packages/sandstorm-ui-grainview/grainview-list.js
shell/packages/sandstorm-ui-grainview/grainview.js
tests/tests/grain.js

Fixes #1984. The problem was that, during login, we would attempt to open a session during the half-logged in state. This would result in two separate redirects from `/shared/:tokenId` to `/grain/:grainId`, the second of which would remove the grainview added by the first, due to [this logic](https://github.com/sandstorm-io/sandstorm/blob/d54130627e0c18fb33604dffbe65b5618d22ed31/shell/packages/sandstorm-ui-grainview/grainview.js#L514).
This also fixes a problem where we were sometimes attaching multiple Blaze views for the same grain at the same time. (You could see this behavior by doing `Meteor.logout()` while visiting a grain.) The fix here is somewhat crude: in `GrainView.reset()`, before attaching a new Blaze view, we verify that the current `GrainView` is in fact in grainview list. …

Fix a few bugs pertaining to grainviews and login/logout.

---

shell/client/admin/user-details-client.js
shell/client/styles/_admin-users.scss

Fix a couple of bugs @kentonv pointed out during testing:
* reuse the LDAP icon for SAML logins
* avoid showing unverified email addresses if the identity has a matching verified email.

New admin users bugfixes

---

docs/vagrant-spk/packaging-tutorial.md

- When linking to the sample app, indicate that the link is to an online view,
rather than the files on your own computer.
- When talking about platform stacks, consistently call them platform stacks.
Refs #1953

Further clarity improvements in tutorial

---

shell/server/admin-server.js

Fixes a bug where if a user unlinked an identity while you had the admin user details page open, a subscription would not close cleanly.
I checked the rest of the codebase for instances of `] = undefined;` and this was happily the only one.

Delete keys from objects, rather than assigning "undefined"

---

shell/server/sandcats.js

This makes us do the same thing as install.sh (which delegates to openssl(1)) , and also
makes us stop triggering warnings from GlobalSign, who for some reason is shocked to see
an asterisk character in a PRINTABLESTRING.

sandcats https: Use UTF8STRING in certificate signing request

---

shell/client/admin-client.js
shell/client/admin/admin-new-client.js
shell/client/admin/admin.html
shell/client/admin/app-sources.html
shell/client/admin/email-config.html
shell/client/admin/feature-key.html
shell/client/admin/identity-providers.html
shell/client/admin/maintenance-message.html
shell/client/admin/network-capabilities.html
shell/client/admin/organization.html
shell/client/admin/personalization.html
shell/client/admin/stats.html
shell/client/admin/system-status.html
shell/client/admin/user-accounts.html
shell/client/admin/user-details.html
shell/client/admin/user-invite.html
shell/client/shell.html
shell/client/styles/_about.scss
shell/client/styles/_admin-status.scss
shell/client/styles/_colors.scss
shell/client/styles/_new-admin.scss
shell/client/styles/_partials.scss
shell/client/styles/shell.scss
shell/packages/sandstorm-accounts-ui/account-settings.html
shell/packages/sandstorm-accounts-ui/login_buttons.html
shell/packages/sandstorm-ui-app-details/app-details.html
shell/packages/sandstorm-ui-applist/applist.html
shell/packages/sandstorm-ui-grainlist/grainlist.html

* Adds a root admin panel page
* Divides admin panel pages into Configuration (server settings) and Management (day-to-day operational task support).
* Moves to breadcrumb-based hierarchical navigation for individual admin pages (which works very nicely for e.g. `Admin / Users / Invite`)
* Corrects a good deal of inconsistent capitalization in the product.  The standard we (attempt to) follow is to capitalize the first letter of a heading, label, or button, but no other words, unless they are proper nouns.  For example, "Sandstorm for Work" and "Sandstorm" are always capitalized as written here.
* I don't think "Trash" and "Main list" qualify as proper nouns.
* App market is not a proper noun when we write it on our blog, so I assumed it needn't be here either.
* I didn't bother fixing …

New admin reorganization

---

shell/client/admin-client.js
shell/client/setup-wizard/wizard.html
shell/packages/sandstorm-accounts-ui/login_buttons.html
tests/apps/ip-networking.js
tests/commands/installApp.js

This change replaces the old admin UI with the new admin UI (which previously lived at `/admin-new`), and places the old admin UI at `/admin-old`.  We intend to remove the latter after some settling period to make sure users aren't missing essential functionality that was available in the old UI.
This also replaces the old powerbox IpNetwork and IpInterface tests with new ones that use the appropriate powerbox descriptors.
Merging this change marks the completion of the admin panel project.  I'm pretty excited about how much more well-organized, consistent, and altogether *usable* things feel.  And it's quite pretty!  A huge thanks to @neynah, @kentonv, and @paulproteus for voluminous discussion and feedback, both on the admin panel and the setup wizard.
I want to tag @ndarilek here - …

New admin panel

---

tests/apps/ip-networking.js

While the test is succeeding for me locally, it seems to be failing on
build.sandstorm.io.  My best guess is that there's too much load on the build
machine.

Bump timeout in IpNetwork test

---

shell/client/admin/system-status-client.js
shell/client/grain-client.js
shell/client/shell.html
shell/client/styles/_grainlog.scss

The previous grainlog behavior attempted to tail the log, but failed to do so
reliably for various reasons:
* not dealing with fractional pixels or "almost at the bottom" scroll states
* recomputing whether the scroll position was at the bottom *after* the additional
content had been added (causing the window to never scroll to the bottom on
content change)
* didn't pay attention to resize events, which can knock the view off the "bottom"
of the log
Reusing the design from the new admin system log page, we fix all of these issues
and make the log window actually reliably tail the log when scrolled to the bottom,
while leaving the scroll position untouched if you scroll elsewhere.

Grainlog smarter autoscroll

---

tests/apps/ip-networking.js

v0.0.8 of the test app had a bug where I used `elem.innerText` (nonstandard)
when I should have used `elem.textContent` (standard).
This broke in CI, which runs iceweasel 38, which did not have support for `elem.innerText`.  (Support was added somewhere between firefox 38 and firefox 46, which is the version available in Fedora, which worked fine.)

Fix IpNetwork/IpInterface tests

---

docs/developing/http-apis.md

Close #2013
Also rework the rest of the http-apis.md document to be clearer, hopefully.

docs: Explain why we don't need user-agent whitelist anymore

---

src/libseccomp/arch-parisc-syscalls.c
src/libseccomp/arch-parisc.c
src/libseccomp/arch-parisc.h
src/libseccomp/arch-parisc64.c

The changes in https://github.com/seccomp/libseccomp/commit/c86e1f565537b28b73ebd63f0239b4a446925534 are causing our integration tests to fail. This should fix things.

Add symlinks for new libseccomp files.

---

docs/administering/faq.md
docs/administering/self-signed.md
docs/administering/wildcard.md
shell/client/admin-client.js
shell/client/admin/admin.html

Also:
- Make the WILDCARD_HOST self-test log things to the JS console.
- Explain more clearly in the docs that wildcard HTTPS is needed.
- In the docs, remark that you _might_ see this message in the admin
area; this way, we do not promise you would see it in the admin area,
which is good since there's no way to actively trigger the self-test.
- Close #1987 (by improving error logging to the JS console, and linking
to the docs from the JS console, and indicating in the docs how to fix
a variety of different things the user might see in the JS console.)

Add websockets warning to new-admin

---

docs/administering/install-script.md
install.sh
installer-tests/automatic-dev-install-on-jessie.t
installer-tests/fail-on-32-bit-system.t
installer-tests/fail-on-old-kernel.t
installer-tests/full-server-install-nmap-netcat.t
installer-tests/full-server-install-on-jessie-with-broken-hostname.t
installer-tests/full-server-install-on-jessie-with-userns-sysctl.t
installer-tests/full-server-install-on-opensuse.t
installer-tests/full-server-install-with-domain-reservation-token.t
installer-tests/full-server-install-with-sandcats-https-invalid-domain-first.t
installer-tests/full-server-install-with-sandcats-https.t
installer-tests/full-server-install-with-unwritable-usr-local.t
installer-tests/install-without-root.t
installer-tests/interactive-dev-install.t
installer-tests/no-root.t
installer-tests/prepare-for-tests.sh

Details:
- Stop using curl args from the future, e.g. use data-ascii
- Text change: Clarify that failure is failure.
- Logic change: When asking if the user wants to report failures to us, insist
on prompting them.
- IMPORTANT CHANGE: Pass ENVVARS when running script from current working
directory. The lack of this was prevent the CURL_USER_AGENT environment
variable from being passed into the script when it re-exec'd itself as
root, if and only if the script decided it was being run from a local
filename. However, this presumably does affect the test suite.
- While at it, adjust prepare-for-tests.sh to request a few more dependencies.
- Adjust existing installer-tests to not report errors, for simplicity.
- Adjust install.sh reference docs to remark on REPORT=no.

install.sh: Make error reporting enabled by default

---

install.sh
installer-tests/full-server-install-say-y.t

- Rationale: We discovered in user-testing that a person typed "y" rather than
pressing enter (or typing "1"). This resulted in install.sh choosing mode 2,
which is development mode, which resulted in a server bound to localhost.
- This commit also adds a test to verify the behavior.
Close #2036

install.sh: Verify that numeric inputs are numeric

---

docs/administering/for-work.md
docs/administering/guide.md
shell/client/admin/user-details.html

Fixes #2040.
Query: Should some note be here about Demo users? People trying Oasis may wonder why there is no "Demo" user level, or they may wonder how they can configure their server to grant that behavior.

Change names of user levels in docs

---

shell/client/admin-client.js
shell/client/admin/feature-key-client.js
shell/client/admin/feature-key.html
shell/client/admin/organization-client.js
shell/client/setup-wizard/wizard.js
shell/client/styles/_admin.scss
shell/packages/sandstorm-db/db.js
src/sandstorm/feature-key.capnp

This patch series sits atop #2044 since it moves some feature key related templates around.
We add an optional Bool field `isFreeKey` to feature keys.
Feature keys which do not have isFreeKey=true but do have isTrial=true will automatically convert to free keys with 15 (is this the right number?) seats after the expiry date.
The UI has been updated so that a free key (or converted expired trial key) looks like the following:
The colored tags are replaced with one that reads "Free", and the row about expiry date is removed.

Free feature keys

---

shell/packages/sandstorm-permissions/permissions-tests.js
shell/packages/sandstorm-permissions/permissions.js

Fixes a bug found by @zarvox when trying out the new powerbox flow: https://github.com/zarvox/sandstorm-test-python/pull/4#issuecomment-223857013. Adds a testcase that fails before the fix and succeeds afterwards.
`activateRelevantTokens()` is supposed to return `true` if any new activations may have made more progress possible. Currently it incorrectly returns false in the case where there are no new relevant tokens, but there are some new "grain owner edges".

Fix bug in permissions computation.

---

shell/client/admin/stats.html

Very minor content organization change - puts "View as JSON" under the "Statistics" heading, which I think makes slightly more sense in terms of content hierarchy.

Reshuffle hierarchy on stats

---

docs/developing/troubleshooting.md

I noticed a warning from mkdocs so I thought I'd fix it.

Finish moving enter-grain docs to debugging/

---

shell/client/admin/identity-providers.html
shell/client/admin/identity-providers.js
shell/packages/accounts-saml/saml_server.js
shell/packages/accounts-saml/saml_utils.js
shell/packages/sandstorm-db/db.js

We add a sentence to the SAML configuration which mentions what the Service URL is.
We make Entity ID a required, configurable field, with a default value of the hostname (which was the previous implicit behavior).
I verified that the configured Entity ID is indeed passed in the SAMLRequest passed to the provider entry point correctly, but I have not actually configured a SAML server and tested this end-to-end.  But SAML is a pretty strongly-specified protocol, and I appear to be making only a very small change here.

SAML: make Entity ID configurable; show Service URL
