- shell/client/admin/identity-providers.html
Should be more clear with the updated UI. Google added an extra step in there. I also decided I liked the verb "click" better than my original choice, "press".
> Update Google Client ID instructions

- shell/server/pre-meteor.js
- shell/server/proxy.js
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/supervisor.c++
This was causing several processes to allocate excessive memory as a result of any large download:
- sandstorm-http-bridge
- the backend coordinator
- the front-end
This change also reduces the total number of write() calls performed which improves performance. Previously, a write() RPC was occurring for every "chunk" in the HTTP chunking sense.
Unfortunately, an app update is required. But, only a few apps do large downloads.
Fixes #1982
Fixes #1054
> Fix large downloads from apps buffering in memory.

- docs/administering/email.md
- docs/administering/faq.md
- docs/administering/for-work.md
- docs/administering/guide.md
- docs/administering/reverse-proxy.md
- docs/administering/sandcats-https.md
A bunch of updates to the docs to bring them in line with the names of things in the new admin UI.
Open question: do we want to use "identity providers" or "login providers"?  I observe that the product uses "identity providers" throughout (and that tends to be the term we use internally), but the docs say "login providers".
> Admin docs: update based on new admin UI

- tests/apps/ip-networking.js
- tests/apps/powerbox.js
- tests/commands/assertReceiveEmail.js
- tests/run-local.sh
Dismissing the offer prompts is something we should be doing explicitly anyway.
We should end the browser session at the end of the IP networking testsuite to avoid leaking a browser window when running tests.
> Dismiss offers and end after IP networking tests

- shell/server/proxy.js
We might as well use the already-opened supervisor capability that `openSessionInternal()` returns. (Looks like I just forgot to do this in https://github.com/sandstorm-io/sandstorm/commit/0084bc458a3c4b516af738ce94705f41fd5de09f)
> use already-opened supervisor capabiliy when constructing proxy

- shell/client/styles/_app-details.scss
Before, on narrow window:
After, on narrow window:
@neynah requesting your +1; after that, review/merge by Kenton.
> Add word wrap to PGP key fingerprint

- shell/client/admin-client.js
- shell/client/admin/feature-key.html
- shell/client/styles/_admin-feature-key.scss
Fixes #2089.
Makes "Upload new feature key..." show a modal with the form, rather than
modifying the page in-place.
Makes "Delete feature key" show a modal with two buttons, one to confirm, and
one to reject.
Tested in both the setup wizard and in the admin panel.
Click "Upload new feature key...":
Or click "Delete feature key":
> Feature key update/delete forms: prefer modals to other weirdness

- shell/packages/sandstorm-ui-grainlist/grainlist-client.js
Before this diff:
After this diff:
> Grains hints: be reasonable on mobile

- docs/install.md
- icons/Gruntfile.js
- Also add this to `install.md`
- This fixes the "Where did the circle go?" problem in #2102
> Use FontForge to convert SVGs to TTF

- docs/install.md
- icons/Gruntfile.js
This reverts commit c9f0899ed0004152442b8084046ea6f957a65361.
Rationale:
- It introduces an issue where the down-arrow is in a weird place,
among other bad icon issues. See https://github.com/sandstorm-io/sandstorm/pull/2110
for one example.
- It means the question mark will have no circular outline. I personally
believe this should not be a show-stopper for the user onboarding changes
being improved.
> Revert "Use FontForge to convert SVGs to TTF"

- shell/packages/sandstorm-ui-app-details/app-details.html
- shell/packages/sandstorm-ui-grainlist/grainlist-client.js
- shell/packages/sandstorm-ui-grainlist/grainlist.html
- tests/tests/account.js
After:
This addresses feedback from @kentonv that it's preferable to always show the table headers on the app details page, even if the user has 0 grains with that app, while staying consistent with @neynah 's request that on the overall grains list page, there is no table header.
It also adds code documentation for an existing but undocumented parameter of the grain list template.
> Always show table headers on app details page

- shell/server/proxy.js
- src/sandstorm/supervisor.c++
We limit an app to having 8MiB of outgoing calls in-flight at once. This prevents even apps that have not yet received last week's sandstorm-http-bridge update from inundating the front-end with queued writes. (However, apps with old sandstorm-http-bridge will still have the problem that the writes queue up inside sandstorm-http-bridge. Consuming RAM there is still bad, but should do less damage at least on Oasis.)
Note that we now no longer want the front-end to start prematurely closing out write()s when it detects a lack of flow control from the app, because that would prevent the connection-level flow control logic from doing its job.
This depends on a recent Cap'n Proto commit: https://github.com/sandstorm-io/capnproto/commit/538a767e04f11b8135fc086314c0250724cac148
> Use new Cap'n-Proto-connection-level flow control in supervisor.

- shell/client/admin/user-invite.html
Close #2076
I changed the proposed text here so that it:
- Avoids the word "just".
- Avoids all-caps "NOT".
- Avoids the word "magic", preferring a phrase specific to what kind of magic.
> Add explanatory text to /admin/users/invite

- shell/client/demo-client.js
- shell/client/grain-client.js
- shell/client/styles/_geometry.scss
- shell/client/styles/introjs-customizations.scss
- shell/packages/sandstorm-ui-applist/applist-client.js
Close #2049
Implementation notes:
- We only show this to appdemo users and to users who see
the hint about installing apps. Therefore, the test suite
should be unaffected.
- We check the viewport width, and if it is less than 900px
(aka "$mobile" for Sandstorm) then we don't show this note.
> Add guided-tour hint explaining how to share access

- install.sh
Rationale:
- By running this assertion first, we cause the side-effect that FD#3 is
ready.
- This happens to be important because since I enabled error reporting
by default, and since the error reporting code assumes that FD#3 is
ready, a horrifying infinite loop occurs instead.
- Since the installer-test suite runs with REPORT=no, it does not catch
this error, but it is true that the "precise64" base box can be used
to reproduce the error.
Close #2081
> Test that we are on a terminal first

- install.sh
Context: assert_on_terminal needs to know if USE_DEFAULTS is set.
> install.sh: Handle args before asserting on a terminal

- shell/client/admin/email-config-client.js
- shell/server/admin-server.js
This provides more useful error messages when an exception is thrown while
attempting to send a test email.  Specific cases tested:
* hostname doesn't resolve
* hostname resolves but server isn't listening on that port
* server is listening but rejects your credentials
Fixes #2091.
> email config: propagate information about errors users might hit

- src/sandstorm/sandstorm-http-bridge.c++
It's been a long time since we've called this thing the "legacy bridge". So it's weird that it still calls itself that.
> LegacyBridgeMain -> SandstormHttpBridgeMain

- shell/server/proxy.js
- src/sandstorm/sandstorm-http-bridge.c++
Due to an odd cyclic reference between proxy.js and sandstorm-http-bridge, various objects were not being cleaned up after a streaming download. The recent refactoring of sandstorm-http-bridge to support flow control made things worse: now sandstorm-http-bridge is leaking sockets, too, which eventually causes it to hit the FD limit. The underlying problem, though, was the pre-existing leak.
This change fixes both ends. The proxy.js-side fix solves the problem in the case of completed streams (probably 99.99% of cases). The sandstorm-http-bridge fix solves the problem in error cases.
See individual commits for more info.
@mnutt FYI
> Fix resource leaks in proxy.js and http-bridge

- shell/client/admin/network-capabilities-client.js
If you grant a grain a capability and then delete the grain, the ApiToken is
still lying around in the collection.
The Network Capabilities UI previously assumed this would not happen; now it
ignores such tokens.
Refs: #2117.
> admin caps: ignore caps for grains that don't exist

- shell/client/styles/_account.scss
- shell/client/styles/_colors.scss
- shell/client/styles/_focus.scss
- shell/client/styles/_partials.scss
- shell/client/styles/_setup-wizard.scss
- shell/packages/sandstorm-accounts-ui/account-settings.html
- shell/packages/sandstorm-accounts-ui/account-settings.js
* Same total width as previous layout.
* Profile picture is no longer a separate column.
* The remaining content has more horizontal space.
* The form uses our standard form layout styles.
* Icons were removed, as suggested by @neynah.
* Page subheadings no longer have a distracting white background.
* Copy about handles was made more terse.
Longer-term, I think the account settings page should probably get split out
into multiple pages - we've already got a number of things that deserve a place
in the hierarchy:
* identities
* email addresses
* referral program
* billing
And I expect we'll wind up adding 2FA and notifications and maybe even OAuth
tokens some day.  So, we should plan to organize content and find a good way
to navigate between all these "my account" data.
Revised accounts …
> Unclutter account view

- shell/server/pre-meteor.js
- shell/server/proxy.js
This turned 404 errors into 500's. It may also have broken redirects to add a trailing '/' when the specified file is a directory.
The root of the problem is that I wrote some really terrible code in pre-meteor.js which made assumptions about ResponseStream that would not be obvious to someone changing ResponseStream, and sure enough a later change to ResponseStream broke it. So, now I did the right thing and added a method to ResponseStream for this specific case so that it's obvious that this is a requirement.
> Fix regression in static web publishing.

- shell/client/setup-wizard/wizard.js
- shell/client/styles/_account.scss
- shell/client/styles/_colors.scss
- shell/client/styles/_focus.scss
- shell/client/styles/_partials.scss
- shell/client/styles/_setup-wizard.scss
- shell/packages/sandstorm-accounts-ui/account-settings.html
- shell/packages/sandstorm-accounts-ui/account-settings.js
- tests/tests/account.js
In #2140 I changed a class name in a final refactoring, but this broke the event handler, which captured click events based on that class name.
I took a closer look at the upload code, and it had a number of other weird issues that I decided to fix while I was poking at that area of the codebase.
We now:
* use the focusing success/error boxes, so the message can't get lost below the fold
* avoid `window.alert()` entirely
* avoid leaking event listeners which would cause us to upload the same file multiple times if you canceled the file picker, then opened it again (which would produce multiple `alert()`s if it was too large...)
* can see upload success/failure messages from the confirm-your-profile page (and the equivalent page in the setup wizard).
> Unclutter account view, v2

- tests/commands/disableGuidedTour.js
- tests/tests/grain.js
- tests/tests/trash.js
These were causing issues for me locally, because the guided tour backdrop
prevents click events from reaching anything else on the page.
> tests: disable more of the new guided tour stuff

- shell/npm-shrinkwrap.json
- shell/package.json
When we added the heapdump dependency via NPM, we also needed to update the
shrinkwrap to specify precisely which version.
Updating the shrinkwrap was nontrivial because npm3 has a bug.  In particular,
npm3 (which we got upgraded to by the recent Meteor upgrade to 1.3.3) appears
to have a bug in resolving dependencies from git that specify a branch name
rather than a SHA1: https://github.com/npm/npm/issues/10502 .  To work around
this, we specify our intro.js dependency via the current sha1.  (We should probably
try to get back on an upstream intro.js release.)
We'd probably benefit from a lint/pre-commit hook that checks that commits that
modify `package.json` also modify `npm-shrinkwrap.json`.
Refs #2153.
> Update npm shrinkwrap

- shell/server/pre-meteor.js
This fixes the longstanding "Meteor app refresh loop" issue.
Meteor's sockjs inserts itself as the first request listener on the Meteor HTTP
handler object.  Normally, this is fine, and keeps DDP requests from
accidentally getting routed to the application handlers.  This is problematic
for programs that happen to implement a proxy, and which need to proxy requests
that use the same paths and overall protocol as Meteor does internally.
As a result of the sockjs middleware being first in the chain, XHRs to an
Meteor app's sockjs endpoint would wind up getting answered by Sandstorm's
instance of sockjs and communicating over DDP to Sandstorm itself.  So any app
that fell back to long-polling would speak DDP to Sandstorm, rather than to the
intended app's backend.
Meteor hashes all the code …
> Route/proxy non-main-host requests before sockjs's handler swallows them

- shell/client/shell-client.js
- shell/lib/db-deprecated.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-db/package.js
- shell/packages/sandstorm-identicons/helpers.js
- shell/packages/sandstorm-identicons/identicon.js
- shell/packages/sandstorm-identicons/package.js
- shell/packages/sandstorm-permissions/permissions.js
- shell/packages/sandstorm-ui-app-details/app-details-client.js
- shell/packages/sandstorm-ui-grainlist/grainlist-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox-server.js
- shell/server/core.js
- shell/server/demo-server.js
- shell/server/grain-server.js
- shell/server/hack-session.js
- shell/server/pre-meteor.js
- shell/server/proxy.js
- src/sandstorm/grain.capnp
- src/sandstorm/package.capnp
- src/sandstorm/powerbox.capnp
- src/sandstorm/sandstorm.ekam-manifest
- src/sandstorm/supervisor.c++
- src/sandstorm/supervisor.capnp
- src/sandstorm/web-session.capnp
- tests/apps/ip-networking.js
- tests/apps/powerbox.js
This pulls together the work from #2016 and #2019.
The ip-networking integration tests are working after applying https://github.com/zarvox/sandstorm-test-python/pull/4.
I have not yet updated the other powerbox integration tests, which are based on https://github.com/jparyani/sandstorm-test-app. So this will not pass Jenkins.
I've split out a new file powerbox.capnp. Doing so isn't strictly necessary for this change, but if we want to do that eventually, now seems like an opportune time.
I've not yet addressed all of the comments in #2019, but I wanted to get this pull request up for discussion.
> claimRequest() and other powerbox-related updates

- shell/packages/accounts-saml/saml_utils.js
This fixes bugs we were seeing with utf8 and other encodings
> Correctly detect the encoding of SAML XML responses

- shell/packages/sandstorm-permissions/permissions.js
- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox-server.js
- shell/server/core.js
- shell/server/hack-session.js
- src/sandstorm/grain.capnp
- src/sandstorm/supervisor.c++
- src/sandstorm/supervisor.capnp
- tests/apps/ip-networking.js
- tests/apps/powerbox.js
Shortly after #2027 was merged, @kentonv noticed that it probably makes more sense for `claimRequest()` to go on `SessionContext` rather than `SandstormApi`.
This makes it so that you can only claim a request token that was created with your current session.
> Move claimRequest() to SessionContext.

- shell/client/admin/user-accounts-client.js
- shell/client/admin/user-accounts.html
- shell/client/styles/_admin-users.scss
The ability to sort by last active is an important affordance for allowing
admins to audit which accounts are active.
Blaze's "eventually rendered" semantics make the page look downright goofy
immediately after you click on the "Created" or "Last Active" header -- those
two columns repaint with the new data immediately, whereas the "Account" column
doesn't update until a future frame.  This seems to be unavoidable given
Blaze's design - unlike React, there doesn't appear to be a `key={_id}` prop
you can pass in explicitly to help the UI layer deal better with reorderings.
At least, I'm not finding a solution for this in the docs.
> admin user accounts list: allow sorting

- shell/client/styles/_account.scss
- shell/packages/accounts-identity/accounts-identity-client.js
- shell/packages/accounts-identity/accounts-identity.html
This refactor makes explicit all of the states that the UI can be in.  We also
handle any Meteor method call failures, displaying the error message in the UI.
This will allow us to add UI to explain why login with identity fails when a user limit is reached, and provides a reasonable place for us to prompt for two-factor auth in the more distant future.
In the non-login-identity view, we:
* split the identity list out by account with a faint horizontal rule
* retain only one "unlink" button per account, since unlinking is an action
taken on the account, rather than on the identity pictured
* avoid using window.confirm() in favor of an in-app modal dialog
* visibly handle success/failure of any of the Meteor method calls with
the focusing success/error boxes
Additional stylistic changes …
> Refactor accounts-identity UI

- src/sandstorm/spk.c++
The `title` field [is deprecated](https://github.com/sandstorm-io/sandstorm/blob/v0.170/src/sandstorm/package.capnp#L147-L153).
See also #1885.
> update spk init template to use Action.nounPhrase rather than Action.title

- shell/server/core.js
Some apps, such as Hacker CMS, do not implement `getViewInfo()`, so we can't assume that `Grains.cachedViewInfo` gets filled in. (The filling-in happens [here](https://github.com/sandstorm-io/sandstorm/blob/5b15b6d203edde6fe005ebec32df0ffd95dcb786/shell/server/proxy.js#L1385-L1392).) As a result, currently the collections app fails to retrieve an icon and title for Hacker CMS grains. This patch fixes the problem.
> account for the fact that grain.cachedViewInfo might not exist

- shell/client/desktop-notifications-client.js
- shell/client/desktop-notifications.html
- shell/client/shell.html
- shell/imports/server/desktop-notifications.js
- shell/packages/sandstorm-db/db.js
- shell/server/desktop-notifications-server.js
Tabs coordinate over localStorage to make desktop notifications spawn
from the most useful tab to handle them - one of the ones that already
has that grain open, or if none do, whichever one gets there first.
> Add desktop notifications, triggerable from the server

- shell/packages/sandstorm-permissions/permissions.js
#2174 introduced a `ApiTokenOwner.user.seenAllActivity` field. Its absence in the input-checking of `SandstormPermissions.createNewApiToken()` is causing `UiView` offers to fail, rendering the Collections app useless.
> Get UiView offers to work again.

- shell/packages/sandstorm-db/db.js
The `SandstormDb.upgradeGrains()` method only exists on the server. The `isSimulation` check is left over from when this code used to be directly part of a Meteor method: https://github.com/sandstorm-io/sandstorm/commit/21598d55e68cc29cac0a73006797a9a7ab61ae05
> Remove vestigial 'isSimulation' check.

- shell/server/core.js
Currently, `SandstormApi.drop()` fails on any token that is does not represent either a wakelock notification or a notification handle. Moreover, in the wakelock case we never actually remove the token from the database, even when the grain is deleted!
The patch makes `dropInternal()` succeed by default. Some types of token require special handling on drop. For everything else, we can just remove the token from the database.
> Get SandstormApi.drop() to succeed on non-notification sturdyrefs.

- install.sh
- installer-tests/full-server-install-on-jessie-with-proc-readonly-but-sysctl-already-set.t
- installer-tests/full-server-install-on-jessie-with-proc-readonly.t
- Run the unprivileged userns test program always, to find out if unprivileged
userns works properly; if so, skip warnings related to read-only /proc/sys.
- If the sysctl for Debian unprivileged userns is already set to 1, then
skip warnings.
- Add tests for these.
- Also rearrange the warning to Docker users about the sysctl for easier
readability.
> install.sh: Fixes related to running within Docker

- shell/packages/sandstorm-ui-grainview/grainview.js
By the time we have the grainId in the offered UiView, we can open the grain
immediately.  We don't need to wait for the dismiss RPC roundtrip to complete
to open the grain, and we're unlikely to do anything in particular if the
dismiss call produces an error.
> Open offered UiView immediately and dismiss the offer asynchronously

- shell/packages/sandstorm-accounts-packages/package.js
A package was using "const" without declaring api.use("ecmascript")
in its package.js.  This resulted in it not getting passed through
the transpilation pipeline, and having its contents placed in the
bundle directly.
IE10 does not support the "const" keyword, and parse errors when it
sees this code, and stops attempting to parse JS.
> Fix loading anything at all under IE10

- shell/imports/server/frontend-ref.js
- shell/imports/server/persistent.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-db/migrations.js
- shell/packages/sandstorm-ui-powerbox/package.js
- shell/packages/sandstorm-ui-powerbox/powerbox-server.js
- shell/server/00-startup.js
- shell/server/admin-server.js
- shell/server/core.js
- shell/server/drivers/ip.js
- shell/server/drivers/mail.js
- shell/server/hack-session.js
- shell/server/identity.js
- shell/server/proxy.js
- tests/apps/powerbox.js
A few things going on here:
* Creating a registry for FrontendRef types, so that it's easy to add new ones in a self-contained way.
* Getting rid of the ugly `persistentMethods` hack and instead having capability classes inherit from a common PersistentImpl class.
* Simplifying all the different code paths around save(). These turned out to have way more interlocking branches than were really needed. Note that save() no longer delegates to SandstormPermissions.createNewApiToken() -- it seemed that most of the complication of that function doesn't actually apply to the child token case anyhow. It may also be possible to simplify that function now that it's not used for this code ptah.
* Moving messy code into clean imports. @zarvox will like this.
Note that there is some unfinished work …
> Refactor sturdyref handling code

- shell/server/proxy.js
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/web-session.capnp
This resolves #2160 pretty much as hinted in the issue comments:
* add new field `eTag` to the WebSession::noContent
* copypaste eTag from-http-to-rpc in sandstorm-http-bridge.c++
* copypaste eTag from-rpc-to-http-response in proxy.js
With this commit, my currently unpublished TiddlyWiki5 package started to work. TiddlyWiki5 is the only way I tested this change, in addition to building and updating my `vagrant-spk` vm to it.
I also tested by mistake using a package created by older sandstorm version with the sandstorm of this version. In that case, there were no obvious problems, but because of the old `sandstorm-http-bridge` version, the `proxy.js` always saw `noContent.eTag` as `undefined`. I believe this is to be expected feature of capnproto backwards compatibility and confirms that I …
> add ETag header support for NO_CONTENT responses

- shell/client/admin/personalization-client.js
Fixes #2229. 
This follows the pattern used for other settings such as [`appMarketUrl`](https://github.com/sandstorm-io/sandstorm/blob/cc2b028e607715f3f2e9119438326a9b73e525ce/shell/client/admin/app-sources-client.js#L6).
> empty string fallback for termsUrl and privacyUrl

- docs/administering/self-signed.md
- shell/client/grain.html
- tests/apps/backgrounding.js
- tests/apps/collections.js
- tests/apps/ip-networking.js
- tests/apps/powerbox.js
- tests/apps/roundcube.js
- tests/apps/web-publishing.js
- tests/commands/grainFrame.js
- tests/commands/newGrain.js
- tests/tests/apihost.js
- tests/tests/appdemo.js
- tests/tests/autoupdate.js
- tests/tests/backup-restore.js
- tests/tests/grain.js
- tests/tests/postmessage-api.js
- tests/tests/restore-open-grains.js
- tests/tests/sharing.js
- tests/tests/trash.js
Fixes #2225. Adds `newGrain()` and `grainFrame()` testing commands. Decouples `loginDevAccount()` from `installApp()`, because sometimes it's useful to install an app on an existing account.
> Add test for Collections app.

- shell/client/styles/_topbar.scss
Using 0 rather than CSS default ("auto") allows introjs to highlight elements in the topbar.
Interestingly, at runtime, Chrome reports the z-index of the topbar element as "0" before
this change; Firefox reports it as "auto." By setting it to 0 explicitly, we cause Firefox
and Chrome to have the same behavior when queried by introjs about the top bar's z-index.
Close #2163
> Give top bar a z-index of 0

- docs/administering/sandcats.md
> docs: Explain why you should back up HTTPS certs during a server move

- shell/client/admin/user-details-client.js
- shell/client/admin/user-details.html
I miscapitalized nonloginIdentities, which resulted in the admin UI never
showing non-login identities in the list of identities for an account.
> admin user details: show non-login identities

- shell/client/grain-client.js
- shell/client/grain.html
- shell/client/styles/_topbar.scss
- src/sandstorm/package.capnp
This allows the Collections app to alert the user that backup/restore do not work as might be expected. 
After this change, a topbar popup always appears when you download a backup. If the app does not specify a warning, it goes straight to the "in progress" state, where there is a new "cancel" button.
> Add backup warning for Collections app grains.

- shell/client/shell-client.js
Pull #2250 introduced a regression when it changed the HTTP response code from
204 to 200 and the frontend wasn't particularly resilient.
> Fix app upload

- shell/client/accounts/login-buttons.html
- shell/client/accounts/login-buttons.js
- shell/client/admin/feature-key.html
- shell/client/admin/personalization-client.js
- shell/client/admin/personalization.html
- shell/client/shell-client.js
- shell/client/shell.html
- shell/client/styles/_account.scss
- shell/client/styles/_admin-personalization.scss
- shell/client/styles/_topbar.scss
- shell/packages/sandstorm-db/db.js
- shell/server/admin-server.js
- shell/server/admin/personalization-server.js
- shell/server/pre-meteor.js
New options for Sandstorm for Work users:
* Custom logo on sign-in dialog
* Custom text on LDAP/SAML sign-in buttons.
* Hide troubleshooting button.
* Hide "send feedback" button.
* Use server title in top left.
Example with all features enabled:
I added the configuration options to the Personalization page.  It's possible we'll want to rename that page, now that it's got some not-very-personal features.
I also added this paragraph to help you find the features you're looking for at the bottom of the Sandstorm for Work settings page, if you have a valid key:
Closes #2241.
> Add basic whitelabeling

- installer-tests/full-server-install-on-jessie-with-proc-readonly-but-sysctl-already-set.t
- installer-tests/full-server-install-on-jessie-with-proc-readonly.t
- installer-tests/full-server-install-say-y.t
- installer-tests/full-server-install-with-domain-reservation-token.t
- installer-tests/full-server-install-with-sandcats-https-invalid-domain-first.t
- installer-tests/full-server-install-with-sandcats-https.t
- installer-tests/prepare-for-tests.sh
They're failing, so keeping them running isn't doing anyone any good.
> installer-tests: disable https tests for now

- shell/server/proxy.js
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/util-test.c++
- src/sandstorm/util.c++
- src/sandstorm/util.h
- src/sandstorm/web-session.capnp
This is mostly @sprin's https://github.com/sandstorm-io/sandstorm/pull/1202 with some additional changes:
* While @sprin was working on the change, @zombiezen independently added header prefix whitelisting using a trailing '*' to indicate that the whitelist entry is a prefix. @sprin reconciled this with his changes by instead creating a separate list for prefixes. I feel, though, that having one list with wildcards is easier to read and understand, so I went back to this model. (This involved removing a couple of @sprin's commits that weren't relevant, and then adding some code of my own.)
* I prematurely optimized the header matching by introducing a `HeaderWhitelist` class in both C++ and Javascript which sort of "precompiles" the whitelist for efficiency. This probably wasn't necessary …
> Response header whitelist and X-Sandstorm-App- prefix

- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox-server.js
- shell/packages/sandstorm-ui-powerbox/powerbox.html
- shell/server/drivers/ip.js
- shell/server/drivers/mail.js
- shell/server/hack-session.js
PowerboxOptions returned from the server may now contain the name of the appropriate client-side template to use to display the powerbox card and even to display a second-step dialog when relevant.
Handling of UiView requests has been refactored to fit into this new model.
> Make powerbox client code pluggable.

- docs/administering.md
In the /administering/ page of the docs, we (before this PR) emphasize the https://sandstorm.io/install page. But the https://sandstorm.io/install page's main point is to lead people to https://docs.sandstorm.io/en/latest/install/ in my opinion. So I now emphasize https://docs.sandstorm.io/en/latest/install/ .
> docs: Clarify install landing area

- install.sh
Testing done:
- Actually try doing an install and make sure starts properly.
Before this change:
- `2016-07-25T22:17:17.346+0000 warning: Failed to connect to 127.0.0.1:81, reason: errno:111 Connection refused`
After this change:
- Sandstorm works.
> install.sh: Try hard to use >1024 port numbers for Mongo

- src/sandstorm/hack-session.capnp
`HackSessionContextImpl` no longer implements these methods.
> Label some HackSession methods as obsolete.

- shell/client/accounts/account-settings.js
Currently, if I visit account-settings and then refresh the page, my debug console display a bunch of errors like: `Exception in template helper: TypeError: Cannot read property 'privateIntrinsicName' of undefined`. This patch prevents those errors.
> Prevent error that could happen on reloading account-settings page.

- shell/packages/sandstorm-ui-powerbox/powerbox.html
If these quotes are not present, then our data-url svgs fail to render. Other similar usages of `background-image` in our code also use single quotes, e.g. https://github.com/sandstorm-io/sandstorm/blob/7ead9c71c9bbd2932df6b1ba31f3397d96a571bf/shell/client/grain/grainlist.html#L150
> Add single-quote marks to get identicons to work in powerbox cards.

- shell/client/grain-client.js
- shell/client/grain.html
- shell/client/shell-client.js
- shell/client/styles/_topbar.scss
- shell/imports/client/grain/grainview.js
- shell/imports/server/persistent.js
- shell/packages/sandstorm-permissions/permissions-tests.js
- shell/packages/sandstorm-permissions/permissions.js
- shell/packages/sandstorm-ui-topbar/topbar.html
- shell/server/00-startup.js
- shell/server/core.js
- shell/server/hack-session.js
- shell/server/proxy.js
- src/sandstorm/supervisor.capnp
- tests/apps/collections.js
The two big changes here are:
1. `MembraneRequirement.permissionsHeld.identityId` is now part of a union, the other variant being `MembraneRequirement.permissionsHeld.tokenId`.
2. `ApiTokenOwner` has a new variant `clientPowerboxOffer` whose purpose is to allow `SessionContext.offer()` to push a webkey to the client without ever actually writing the webkey to the database (as we currently do in the copy/paste powerbox). In principle, we should be able to avoid the need for this owner variant (probably by using a pseudo-collection), but that seems at least somewhat tricky, and we already have machinery in place for doing it the way proposed here.
Fixes #2190.
This does *not* dedupe webkeys offered to anonymous users, as had been suggested in #2190. Deduping seems less important in this …
> Allow anonymous users to be offered capabilities.

- Makefile
- shell/run-dev.sh
Meteor has long since fixed their node-gyp path bug, and the code in the
Makefile can't possibly be right because `$HOME/.meteor/tools` doesn't exist
anymore.
> Remove PYTHONPATH override that worked around a Meteor bug

- docs/vagrant-spk/packaging-tutorial-meteor.md
- docs/vagrant-spk/packaging-tutorial.md
@paulproteus docs-only change
Fixes sandstorm-io/vagrant-spk#183
> Fix packaging tutorial where we replaced actions.title with nounPhrase

- shell/client/styles/_topbar.scss
Fixes the background-color regression in the share menu buttons.
I grepped (but not very hard) for other instances of the same element having
both an `@include` and an `@extend`, and this seemed to be the only instance.
> Avoid mixing @include and @extends on the same properties

- shell/client/styles/_topbar.scss
Actually, we can just @extend %button-base like all the other things that use %button-primary.
> Share button style fixes, attempt 2

- shell/imports/server/email.js
We can come up with a cleaner fix later.
> Temporarily restore SandstormEmail to global scope to fix Blackrock invoices.

- docs/developing/powerbox.md
Adding these docs because the blog post https://github.com/sandstorm-io/sandstorm-website/pull/212 want to link to them.
> add some docs about developing an app using the powerbox

- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
Currently, when you type any text into the search field, all of the results disappear.
> get searching in powerbox requests to work

- shell/client/shell-client.js
Longer-term, we should probably make uploading not be an application-modal
action, perhaps by displaying the upload progress in the notification area.
Fixes #2354.
> use replaceState when navigating away from `/upload` or `/uploadBackup`

- LICENSE
- shell/client/shell.html
... and it appears that we've been linking to the wrong package on npm all along.  We used `es6-promise` (singular), not `es6-promises` (plural).
> Remove some now-obsolete mentions of 'es6-promise'.

- hack/.gitignore
- make-bundle.sh
sandstorm-84 and earlier shipped mongo 2.4, which creates its auth schema in a
different way than mongo 2.6 and above.  While mongo 2.6 is able to read said
schema, mongo 3.2 is not.
To avoid breaking servers that were originally installed with mongo 2.4, we
can't jump to mongo 3.2 just yet.  Mongo 2.6 is still fine, and Meteor remains
backwards-compatible with Mongo 2.6, so we can continue shipping this for a while.
This change makes make-bundle.sh cache a copy of sandstorm-171 (the latest
release as of this writing) and copy its mongo/mongod into the new bundle,
rather than pulling those binaries from the current Meteor dev bundle.
Additional notes on mongo upgrades:
* https://jira.mongodb.org/browse/SERVER-22004
* https://docs.mongodb.com/manual/release-notes/2.6-upgrade-authorization/ …
> Pin bundled mongo to 2.6 to avoid in-place upgrade woes

- shell/client/notifications-client.js
Complements #2342, which did the same for the referral program button.
> Don't navigate when dismissing a grain notification

- shell/client/grain/grainlist-client.js
- shell/client/grain/grainlist.html
- shell/client/styles/_grainlist.scss
- shell/imports/client/grain/grainview.js
- shell/packages/sandstorm-backend/sandstorm-backend.js
- shell/packages/sandstorm-db/db.js
- shell/server/backup.js
- shell/server/core.js
- shell/server/grain-server.js
- shell/server/proxy.js
- shell/server/shell-server.js
- src/sandstorm/supervisor.c++
- src/sandstorm/supervisor.capnp
After this change:
* Storage quota can be enforced on single-machine Sandstorm. (However, the UI needs to be detangled from the Oasis payments code -- @jparyani is working on that.)
* The size of each grain is shown in the grain list. (However, preexisting grains won't show a size until they are next opened.)
> Save inotify-derived grain sizes to database

- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
This allows powerbox plugins to dismiss the dialog entirely, marking the request as canceled by the user.
> Add cancelRequest() for powerbox plugins to call

- shell/client/styles/_powerbox.scss
- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox.html
This should make `failRequest()` more useful, since error messages can go somewhere other than just the console.
> Show errors in powerbox request dialog

- shell/client/setup-wizard/wizard.html
A template was missing a callback hook.
Fixes #2340.
> setup wizard email step: make self-test dialog "Close" button work

- src/sandstorm/supervisor.c++
```
In file included from /ekam-provider/canonical/sandstorm/supervisor.c++:17:
In file included from /ekam-provider/canonical/sandstorm/supervisor.h:21:
In file included from /ekam-provider/canonical/sandstorm/util.h:31:
In file included from /ekam-provider/c++header/kj/async.h:675:
/ekam-provider/c++header/kj/async-inl.h:319:12: error: no matching function for call to 'from'
return PtmfHelper::from<ReturnType, Decay<Func>, ParamTypes...>(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ekam-provider/c++header/kj/async-inl.h:358:45: note: in instantiation of function template specialization 'kj::_::GetFunctorStartAddress<capnp::
Response<sandstorm::SandstormCore::ReportGrainSizeResults> &&>::apply<(lambda at /ekam-provider/canonical/sandstorm/supervisor.c++:415:30) &>' …
```
> Get new supervisor code to typecheck in (buggy) clang v3.8.

- shell/client/desktop-notifications-client.js
I had tested with a browser that had cached the permission grant, and incognito windows blanket-deny desktop notifications entirely, and I mistakenly thought that creating the first `new Notification()` would trigger the browser to prompt you to show notifications.  Oops.
This change requests permissions to show notifications the first time Sandstorm would want to show a desktop notification.  This obviously isn't perfect, but this at least avoids the problem of "user is asked for permission when they don't have the context to understand why that permission is being asked for" and makes notifications available to users that would clearly benefit from them.  I am very strongly against dropping a permission request on users first thing when they e.g. log in or refresh their browser window. …
> Call Notification.requestPermission() to make notifications work

- docs/developing/web-publishing.md
- docs/vagrant-spk/customizing.md
In some places, we used to write:
```bash
cd .sandstorm
vagrant provision
cd ..
```
But this is no longer needed due to https://github.com/sandstorm-io/vagrant-spk/pull/145
by @zarvox. Therefore, we say this instead:
```bash
vagrant-spk vm provision
```
> docs: Use vagrant-spk vm provision

- shell/imports/server/email.js
- tests/commands/assertReceiveEmail.js
This is restoring the behavior that existed before #2362.  Several users have
reported that the most recent upgrade has broken mail delivery on their systems
due to attempting to perform STARTTLS, then aborting when the cert provided by
the mailserver didn't validate.  This appears to be a fairly common configuration.
Node 0.10 did not validate certs at all before now, so I'm disabling cert
validation to undo the breakage.  Longer-term, we should add UI for admins to
specify one of the following behaviors:
* "none" use STARTTLS if available, but don't validate the cert
* "starttls" require STARTTLS, and validate the certificate
* "smtps" connect on port 465 and validate the cert
> Don't check that mail server certs are signed by any CA in particular

- docs/developing/auth.md
- docs/developing/handbook.md
- docs/developing/path.md
- docs/developing/powerbox.md
Closes #489.
Also includes a few other minor updates. Principle when including github links: if linking to a specific line number, then use `/blob/v0.latest/whatever#line`, because line numbers are likely to change. If linking to a file, then use `/blob/master/whatever`.
> docs about permissions and roles

- shell/client/desktop-notifications-client.js
- shell/client/notifications-client.js
- shell/imports/client/grain/grainview.js
- shell/imports/client/model-helpers.js
- shell/server/notifications-server.js
The `.title` field canonically lives on `ApiTokenOwner`, not on
`.denormalizedGrainMetadata.title`.  Ditto `.upstreamTitle`.
While debugging this with @jparyani, we discovered that sometimes you can wind up with a stub object in your `Grains` collection with only the fields `_id` and `title`, even if you don't own that grain.  This causes the grain lookup logic to get confused and think that you own the grain, which breaks my expectations.
> Fix grain title in desktop notifications on shared grains (sometimes?)

- shell/imports/server/accounts/picture.js
- shell/imports/server/migrations.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-db/migrations.js
- shell/packages/sandstorm-db/package.js
- shell/server/00-startup.js
- shell/server/accounts/accounts-server.js
This changeset extracts migrations out of sandstorm-db and into a separate file.
I also extracted some accounts-related network-touching code that previously lived in `sandstorm-db` because it needed to be executed during migrations.
`migrateToLatest` now receives two arguments, an instance of `SandstormDb` and an instance of `SandstormBackend`.  It no longer reaches into global state.
This is one of several steps involved in my ongoing effort to clean up initialization order.
> Relocate migrations

- shell/client/accounts/login-buttons.html
- shell/client/accounts/login-buttons.js
Fixes a regression of #2275. (The `profilePictureUrl()` helper omits a necessary check.)
> Make sure incognito icon does not display when we're still waiting for data.

- docs/developing/auth.md
Addresses some of @paulproteus's comments in #2401.
> Docs: Link to non-http-bridge examples. Put less-jargony paragraphs first.

- shell/server/drivers/mail.js
nodemailer accepts message objects in precisely the format the capnp
struct expects, so we no longer need to stringify addresses, and it's
better that we present them in a well-typed format than as a string.
Code deleted is code tested!
Fixes #2409.
> Fix email driver behavior when .name present in EmailAddress struct

- shell/client/apps/app-details-client.js
- shell/client/apps/app-details.html
- shell/client/grain/grainlist-client.js
- shell/client/grain/grainlist.html
- shell/client/styles/_grainlist.scss
Now that we let you see per-grain size everywhere, it makes sense to also
allow sorting the grain list by size, in addition to the default sort order
of "last activity".  And we might as well let you sort by title too, if you want.
> Allow sorting grain list by last used, title, and size

- shell/client/styles/_applist.scss
Previously, a sliver of the second row of most-used was visible.
I also added two pixels to the height of the cards because on Firefox I was seeing the bottom of the app short descriptions getting cut off.
Fixes #2427
> Adjust size of most-used apps row on mobile.

- tests/run-local.sh
Often there are interesting logs or grain logs or other grain state that might
be interesting to look at in a post-mortem analysis, but the script immediately
wipes everything out, preventing further analysis.
This change preserves the `tests/tmp-sandstorm` folder if the testsuite doesn't
pass.
> tests/run-local.sh: preserve sandstorm data dir on testsuite failure

- shell/client/accounts/account-settings.html
- shell/client/accounts/identity/identity-client.js
- shell/client/accounts/identity/identity.html
- shell/client/accounts/login-buttons.html
- shell/client/accounts/login-buttons.js
- shell/client/admin/feature-key.html
- shell/client/admin/identity-providers.html
- shell/client/admin/organization.html
- shell/client/admin/system-status.html
- shell/client/admin/user-details.html
- shell/client/admin/user-invite.html
- shell/client/apps/app-details.html
- shell/client/apps/applist.html
- shell/client/demo.html
- shell/client/grain-client.js
- shell/client/grain.html
- shell/client/grain/contact-autocomplete.html
- shell/client/notifications-client.js
- shell/client/setup-wizard/wizard.html
- shell/client/shell.html
- shell/client/styles/_account.scss
- shell/client/styles/_applist.scss
- shell/client/styles/_colors.scss
- shell/packages/sandstorm-ui-powerbox/powerbox.html
- shell/packages/sandstorm-ui-topbar/topbar.html
* Fix bug where identity cards weren't looking up the current identity correctly
* Give identity cards some margin so they don't look weird when stacked
* Audit the codebase for use of `{{> someTemplate }}` and convert to either `{{> someTemplate . }}` (explicitly passing on data context) or `{{> someTemplate ""}}` (passing on an empty data context).
* Add a couple typechecks on the args to the login/account button templates
> Account buttons cleanup

- shell/client/styles/_grainlist.scss
Font metrics/rendering are different on Windows, which causes the arrow in the
last activity column to wrap on Windows.
This change takes 10 pixels from the Size column (which is nowhere close to needing all the space) and gives it to the last used column.
> Grainlist: make space for the ▴ on Windows

- shell/client/styles/_partials.scss
> Pad search bar by 4px so the cursor doesn't blend into the border

- shell/imports/server/backend.js
- shell/server/core.js
- shell/server/hack-session.js
- shell/server/proxy.js
With this change, `shell/server/core.js` no longer refers to `globalDb`.
We still refer to some other globals, which I'll find ways to inject in separate PRs:
* injecting a db with which to access `ApiTokens` in `unwrapFrontendCap` will require a coordinated change in Blackrock
* `globalBackend` is still used.  There's a weird circular dependency between `SandstormCoreImpl` and `SandstormBackend` - you can't construct a `SandstormBackend` without first having a `SandstormCoreFactory`, which produces a `SandstormCoreImpl`, which makes calls on the `SandstormBackend`.
This can maybe be resolved by adding a `setSandstormBackend()` method on `SandstormCoreFactory`, and then having SandstormCoreFactory inject that `SandstormBackend` into any `SandstormCore` it constructs.
* …
> Inject db into SandstormCore and associated functions

- shell/client/admin/email-config-client.js
- shell/client/admin/email-config.html
- shell/client/styles/_admin-email.scss
- shell/server/admin-server.js
Some users can't trust email providers and would like to be able to disable
email after they've previously configured it.  This adds a reset button to do
just that.
Fixes #2446.
> Email config: allow de-configuring email

- src/sandstorm/supervisor.c++
Currently if you call `SandstormApi.save()` and forget to set `cap`, you get this error: 
```
Failed: remote exception: Called null capability.
```
which is not super helpful. This patch changes the error to:
```
Failed: remote exception: expected args.hasCap(); Cannot save a null capability.
```
> Better error message when calling SandstormApi.save() with cap = null.

- shell/imports/server/static-asset.js
- shell/server/core.js
- shell/server/identity.js
- src/sandstorm/grain.capnp
- src/sandstorm/identity.capnp
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/util.capnp
This allows grains to retrieve up-to-date profile information on their users, even for users who have not visited the grain in a long time, and even for users who have never visited the grain at all (as may happen if the grain powerbox-requests an identity).
After this change, a grain can have a very simple user database consisting of a map from identity ID to Identity sturdyref, where `SandstormApi.restore()` and `Identity.getProfile()` are called whenever a particular user's profile is needed.
I have tested this change on a branch of the Collections app that implements an "added-by" column.
> Implement Identity.getProfile().

- shell/client/grain-client.js
- shell/public/offer-template.html
This allows you to make the whole offer template into a link. At the
moment, the only thing you can specify is a scheme, and the rest is
autogenerated for you.
This needs some input on what we're actually going to do about filtering dangerous schemes. Either add a whitelist or only allow them to start with "sandstorm-" (or automatically prefix it ourselves).
> Add link parameter to offer template

- src/sandstorm/sandstorm-http-bridge.c++
This is intended to help:
- App authors who are mistaken about which port number their app was
supposed to bind to, e.g. an app author a few months ago.
- App authors who forgot to ever actually listen on the port, e.g. an app
author who showed up to IRC today.
> Log a message if grain is slow to start

- shell/server/proxy.js
@zenhack observed Sandstorm returning a consfusing 500 error due to this problem.
> HTTP APIs: gracefully handle case when user-agent header is missing

- docs/developing/http-apis.md
- shell/server/proxy.js
The code updated to use `.sandstorm-token` in [this commit](https://github.com/sandstorm-io/sandstorm/pull/1949/commits/ac3e9b3b92c6d4f40f69fbc33b1745e8e122c31a), but several mentions in the documentation did not get updated.
> update some mentions of .sandstorm-api-token to .sandstorm-token

- shell/server/proxy.js
* Fix typo of ```ownder``` → ```owner``` for the grain-owner-suspended error
*As this is a very small change, I've skipped the usual breakdown and risk analysis*
> Fix typo in grain-owner-suspended error

- shell/server/core.js
Currently, if you back up and restore a grain that uses a self-repairing identity database as in #2441, and the original grain has not been completely deleted, the restored grain ends up with identities accumulating in its trash directory, because `drop()` fails. This patch fixes the problem.
> Dropping a token you don't own should not be an error.

- shell/packages/sandstorm-db/db.js
- shell/server/account-suspension.js
This isn't quite ready to merge as it needs better text (and perhaps an html version?).
I would like comments on if you think it's appropriate to inject an email object similar to quoteManager into SandstormDb.
> Send an email to admins/users on account deletion

- shell/server/00-startup.js
Each fiber created adds an entry to `v8::Isolate::ThreadDataTable`. Unfortunatley, items are
never deleted from this table. So if we create and delete a lot of fibers, then we leak memory.
Worse yet, the table is represented as a linked list, and v8 performs a linear scan of this
linked list every time we switch fibers. We've seen cases where Sandstorm was spending 65% of
its CPU time just scanning this list! The v8 people say this is "working as intended".
The fibers package has implemented a work-around by maintaining a fiber pool. Fibers are not
deleted; they are returned to the pool. Unfortunately the pool has a default size of 120. So
if we pass 120 simultaneous fibers, we start leaking and slowing down. It's very easy to hit
this number with a few dozen users present.
Up until it …
> Make the fiber pool size infinite(ish)!

- shell/packages/sandstorm-db/db.js
The [`defineMutationMethods` option](http://docs.meteor.com/api/collections.html#Mongo-Collection) was introduced in https://github.com/meteor/meteor/commit/2ddf14575a8b45a2899e6e6c5760fc0b8f6b6828 . Since all of our client-initiated database writes go through Meteor methods, we can take advantage of it.
> defineMutationMethods: Meteor.isClient for all Mongo collections

- make-bundle.sh
This allows `perf(1)` and friends to provide a better profiling experience.
The bundle size difference is fairly small (about 8MB uncompressed, <1MB compressed) and
there is basically no runtime overhead because the sections won't get faulted
into memory until something tries to make use of them.
> Don't strip binaries in the Sandstorm bundle

- docs/administering/faq.md
* Fix typo of ```loginp providers``` to ```login providers``` for the FAQ entry
on changing Sandstorm's domain name
*As this is a very small change, I've skipped the usual breakdown and risk analysis*
> Fix typo in docs Admin → FAQ → change domain name

- shell/imports/server/backend.js
- shell/packages/sandstorm-db/db.js
- shell/server/proxy.js
- src/sandstorm/backend.c++
- src/sandstorm/backend.capnp
- src/sandstorm/backend.h
- src/sandstorm/run-bundle.c++
- src/sandstorm/spk.c++
This allows dev-mode apps to opt-in to getting a procfs. I've verified that it does indeed allow Rust programs to generate human-readable stack traces (see #371).
Since `--proc` already exists as a supervisor flag, most of the changes here are to propagate the flag from `spk dev` to the supervisor. This involves writing a "1\n" or a "0\n" to a socket, adding a field to `DevPackages`, and adding an argument to `Backend.startGrain()`.
> Implement `spk dev --proc`.

- shell/client/accounts/account-settings.html
- shell/client/accounts/account-settings.js
- shell/client/shell.html
- shell/client/styles/_account.scss
- shell/client/styles/_focus.scss
- shell/client/styles/_geometry.scss
I tried to avoid significantly changing the existing design on desktop, but it
probably wouldn't hurt to make it fluid within a given set of widths rather
than strictly fixed-width.  Perhaps we can do that when we move profiles
off identities and onto accounts, which simplifies the profile editor?
Longer term, we probably want to make more things use the 600px breakpoint
rather than the current 900px one, but I don't have time to audit the entire
codebase for designs that only work at fixed widths right now.
Fixes #2122.
> Accounts page rework for mobile

- shell/client/apps/app-details-client.js
- shell/client/apps/applist-client.js
- shell/client/grain/grainlist-client.js
- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-ui-powerbox/powerbox-server.js
We've noticed that the observer [here](https://github.com/sandstorm-io/sandstorm/blob/990debe376cf545931853664834e880c5e665aeb/shell/packages/sandstorm-db/db.js#L2662-L2677) can spawn a large number of fibers when a user moves a bunch of grains into their trash. It seems that the problem has to do with the observed cursor's query, which includes `{ trashed: { $exists: false } }`. In addition to to the performance problem, there is a bug. We actually want the query to simply be `Grains.find({userId: this.userId})`.
This patch makes it easier to ask for what you want in `db.userGrains()` and `db.currentUserGrains()`. In particular, if you want *all* of the grains, including the trashed ones, you don't provide any additional arguments. So this fixes the problem case described above. It also …
> Make `db.userGrains()` and `db.currentUserGrains()` more flexible.

- shell/client/admin/stats-client.js
- shell/client/admin/stats.html
- shell/packages/sandstorm-db/db.js
- shell/server/stats-server.js
The hard coded date assumes we update our terms/privacy policy for the
feature key vendor by tomorrow.
Also add their customer ID to the stats object
> Opt Sandstorm for Work trial users into stats reporting

- shell/client/grain-client.js
- shell/client/grain.html
- shell/client/styles/_topbar.scss
Fixes #2290 by adding a "Grains" section to the "who has access" view.
> Show grain-owned tokens in "who has access" view.

- docs/administering/for-work.md
- shell/client/admin/feature-key-client.js
- shell/client/admin/feature-key.html
- shell/client/styles/_partials.scss
- shell/server/admin-server.js
Any admin will be able to click on the button and arrive at the key's info in the feature key vendor, where they can do things like convert a trial key to permanent, specify payment source, purchase more users, change contact info, etc.
Currently the button looks like this:
@neynah, @zarvox: Any opinions on the button style and label? Maybe this should be promoted to the primary button, or otherwise colored differently?
> Add button to feature key page linking to key vendor.

- shell/server/account-suspension.js
The idea here is that deleting accounts is one of the few really dangerous things an admin can do, so if an admin account is hijacked and the hijacker starts deleting accounts, the admin should be notified.
> Email all admins when an admin deletes an account, including the one who did it.

- shell/client/styles/_account.scss
@zarvox I'm assuming this change was a mistake but if it's intentional let's discuss next week. Changing this back doesn't appear to affect the new mobile style.
> Make sections of 'Billing' appear side-by-side again, when space permits.

- shell/client/apps/app-details-client.js
- shell/client/grain/grainlist-client.js
Since #2489, if you upload an spk upgrade to one of your apps and then you visit the app details page, the javascript console shows:
```
Exception in template helper: Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
at exports.check (http://sandstorm-radon.dwrensha.ws:6080/packages/check.js?hash=bf95dee84c2be9008274d2385c637659760b9057:67:15)
at SandstormDb.userGrains (http://sandstorm-radon.dwrensha.ws:6080/packages/sandstorm-db.js?hash=48eb3dbed6e1c8a3a60977905c2450e43f34e280:1271:7)
at SandstormDb.currentUserGrains (http://sandstorm-radon.dwrensha.ws:6080/packages/sandstorm-db.js?hash=48eb3dbed6e1c8a3a60977905c2450e43f34e280:1290:19)
at appGrains (http://sandstorm-radon.dwrensha.ws:6080/app/app.js?hash=034f1a98e827442e998904d5a63a2826dae0f18f:13195:22) …
```
> Make sure to send a well-formed options object to currentUserGrains().

- shell/client/grain/grainlist-client.js
- shell/client/grain/grainlist.html
Currently, if you have no grains in your trash, if you visit your trash and then click "View main list", your browser console will show an exception:
```
typeError: Cannot set property 'checked' of null
```
and the "select grain" check boxes will be broken until you reload the page.
This patch fixes the problem by simplifying the logic that updates the state of the "select all" checkbox.
> Minor bugfix for 'select all grains' checkbox.

- shell/client/shell-client.js
- shell/client/shell.html
It doesn't render correctly (too dependent on DOM hierarchy) and appears to be
completely unused to boot.  (If you think it is used somewhere and we should resurrect it, please close this PR.)
> Remove `/account/usage` route

- shell/client/shell-client.js
Without this, you get some nasty flashes of partial content on the page if you refresh `/account`
> Accounts page: wait for subscriptions

- shell/client/styles/_topbar.scss
For some reason, a "1px transparent" border doesn't seem to be treated
the same as a "1px solid transparent" border.  Also, we should be specifying
`background-size` and `background-repeat`.
Observed behavior before this patch:
But things were fine on hover:
> Fix the size of the close button in recent Chrome releases

- shell/packages/sandstorm-db/db.js
- shell/server/00-startup.js
* use function shorthand so you get named functions in stacktraces
* remove references to `globalDb` from db.js
* use this.collections.* with all collections (except Meteor.users)
> Assorted db.js cleanups

- shell/packages/sandstorm-permissions/permissions.js
- src/sandstorm/grain.capnp
For apps that use the client powerbox request flow, a common way to get a token to the server is to make a POST to a path like `/token/<TOKEN>`. This works currently because the token can only contain alphanumeric characters plus '-' and '_'. Let's promise to our app developers that it will continue to work in the future.
> Assert that tokens returned from client powerbox requests are URL-safe.

- shell/client/grain-client.js
- tests/tests/trash.js
Fixes a bug where sometimes the trash button does not show up in the topbar. The problem is that we are checking whether the user has the grain in the trash while what we should really be checking is whether the user has any *non-trashed* references to the grain.
Also adds a test that fails before and passes after the fix.
> Don't hide topbar trash button when user has some tokens in trash and some not.

- shell/client/admin/feature-key-client.js
- shell/client/admin/feature-key.html
- shell/client/notifications-client.js
- shell/client/notifications.html
- shell/client/styles/_admin.scss
- shell/client/styles/_topbar.scss
- shell/packages/sandstorm-db/db.js
- shell/server/00-startup.js
- shell/server/admin-server.js
- shell/server/feature-key.js
- shell/server/notifications-server.js
- shell/server/stats-server.js
The commits are arranged in bite-sized chunks for your reviewing pleasure.
Overview:
* Once a feature key is installed, it will be automatically renewed.
* To avoid accidents, we no longer allow installing a feature key that is expired, since this would trigger immediate renewal, which could be a costly mistake for the user.
* However, if the user tries to install an expired key, we will go check if a newer version of the same key is available, e.g. because it had been renewed already, and the user just happened to use the wrong version. If so, we'll go ahead and use the new version. This will not trigger a renewal.
* If renewal fails, we will record the error.
* We display it on the feature key config page, in a red box.
* The box has a "retry" button to immediately retry renewal.
* We …
> Implement feature key auto-renewal

- src/sandstorm/web-session.capnp
Phabricator's CSRF tokens for AJAX requests are passed in this manner, and
there are a couple other headers they use like `X-Phabricator-Via` that it'd be
better to not remove from requests.
cc @liamzdenek
> Add X-Phabricator-* to the HTTP header whitelist

- shell/client/setup-wizard/wizard.js
- shell/imports/server/migrations.js
Fortunately?, the check which prevents users from clicking "Next" on this
page was also not checking for collections, so it all worked out without
anyone complaining.
> Fix collections app not being preinstalled by the wizard

- shell/client/apps/applist.html
Now that we've moved the two buttons up above the horizontal rule, they should
no longer be confused as being related to search results.
Fixes #2038.
> Don't hide "Upload app" button while searching on app list page

- shell/client/apps/applist-client.js
- shell/client/grain/grainlist-client.js
If available, use [String.prototype.localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) when sorting app titles or grain titles.  (It's [not available in some versions of Safari](http://caniuse.com/#feat=internationalization), so we retain the fallback logic of comparing lowercased strings directly.)
Fixes #2529.
> Locale aware grain and app sorting

- shell/client/accounts/account-settings.html
Fixes a typo introduced in https://github.com/sandstorm-io/sandstorm/commit/87de090c061608167336dfa7bb5a89bfb2df8369 that causes the account profile page to always display "they" as the chosen pronoun.
> fix pronoun selector on account settings page

- shell/server/accounts/accounts-server.js
"pronoun" is the correct field to be using here: https://github.com/sandstorm-io/sandstorm/blob/v0.185/shell/packages/sandstorm-db/db.js#L86
I don't think we ever actually fill in this field when creating a new user (usually it gets filled in lazily, with a default being inferred from the service-specific identity data), so I don't think there would be any point in writing a migration to clean up database entries that have a `profile.pronouns` field.
> fix new user validation to include 'pronoun' instead of 'pronouns' 

- shell/packages/sandstorm-db/db.js
The bug was introduced in https://github.com/sandstorm-io/sandstorm/commit/d4f96cea87024305daa6f3ebcb50e1c69ddfe07d.
> fix broken 'this' reference in `removeApiTokens()`

- src/sandstorm/run-bundle.c++
Currently, there is a few-second window during updates when the user might experience connection errors.
We can close this window by opening our listen sockets higher-up in run-bundle and actually passing them on to the successor version on updates. Thus, the listen sockets never close, they just temporarily pause accepting connections.
> Zero-downtime self-hosted updates.

- docs/developing/raw-ruby-on-rails.md
- src/sandstorm/web-session.capnp
jQuery provides the X-Requested-With header that is required by
a number of applications, including Trac.
> Add X-Requested-With to the HTTP header whitelist

- shell/client/demo.html
The intended meaning was: "Making it easy to run apps on your own server is the only way to make open source web apps viable."
However, it was easy to interpret: "Sandstorm is the only way to make open source web apps viable."
I couldn't think of an easy way to clarify, so I removed the word "only" to sound less Trumpian.
> Soften our claim about being the "only" way to make open source web apps viable.

- shell/imports/server/migrations.js
- shell/server/identity.js
- shell/server/proxy.js
Our current `makeIdentity()` function ignores its `requirements` parameter. Therefore `Identity` capabilities passed to grains have no membrane requirements, and hence #2414.
This patch migrates existing saved identity capabilities to add the appropriate membrane requirement. It also removes the buggy `makeIdentity()` function in favor of `FrontendRefRegistry.create()`, which additionally validates the requirement. (A potential downside here is that this triggers another permissions computation. I don't think we've seen performance problems related to permissions computations yet, so maybe this isn't worth worrying about.)
This patch helps with https://github.com/sandstorm-io/sandstorm/issues/2414, but is not a complete fix; it does not kill any live identity capabilities and hence still …
> add membrane requirements to identities

- shell/imports/server/frontend-ref.js
- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox-server.js
- shell/packages/sandstorm-ui-powerbox/powerbox.html
- shell/server/core.js
- shell/server/drivers/ip.js
- shell/server/drivers/mail.js
- shell/server/identity.js
- shell/server/notifications-server.js
- src/sandstorm/grain.capnp
- src/sandstorm/identity.capnp
- src/sandstorm/supervisor.c++
- src/sandstorm/supervisor.capnp
- tests/apps/ip-networking.js
- tests/tests/powerbox-contacts.js
Allows a user to introduce one of their contacts to a grain, giving the grain access to the contact's profile information while simultaneously granting the contact access to the grain.
I've updated the sandstorm-test-python app to test out this functionality. I also have a Wekan branch that uses it.
Looks like:
Future work is to figure out some nice way to include the identity-provider icon and the intrinsic name on these powerbox cards.
> Implement powerbox requests for identities.

- shell/packages/sandstorm-ui-topbar/topbar.js
This was sometimes (non-deterministically) causing a blank page when the demo expired (rather than showing the login form).
> Work around template rendering timing issue causing duplicate topbar registrations.

- shell/packages/sandstorm-db/db.js
When an app update is discovered through an app index refresh, if the newer version of the app was already installed (for example, because someone had gone to the app market and installed it manually before the index update landed), then the preinstall package ID was never updated. This means the old version continued to be preinstalled and also broke appdemos of the particular app.
> Fix that the preinstalled app package IDs could become outdated.

- shell/server/backup.js
This follows RFC 6266, which all browsers have supported for a while now.
Fixes #2597
> Correctly serve utf8 filenames for backups

- shell/packages/sandstorm-db/profile.js
This isn't called from the Sandstorm codebase, but is called by the code which receives mailing list subscribe/unsubscribe events from Mailchimp and updates bonuses accordingly. Probably, a few people who unsubscribed are still receiving the bonus. Oh well.
Also fixed it to handle LDAP correctly, even though this code is not currently used on any server that uses LDAP.
> Fix findIdentitiesByEmail()

- shell/server/identity.js
@jparyani noticed that the new powerbox contact picker sometimes fails on Oasis. The problem is that it's possible for an entry in the `Contacts` table to have an `identityId` for an identity that no longer exists (maybe because it was a demo identity), and we don't account for that possibility.
I think that after https://github.com/sandstorm-io/sandstorm/pull/2587 we now do clean up newly-dead contacts when identities get deleted, but that doesn't do anything to clean up the existing dead contacts in the database.
> don't try to make powerbox cards for identities that don't exist

- shell/client/admin-client.js
- shell/client/admin/admin.html
- shell/client/admin/system-status-client.js
- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
- shell/server/admin/system-status-server.js
This:
* Allows access to `/admin/status` with only a setup token (not logged in).
* Adds a button to the setup wizard footer to open the log.
* Improves some adjacent code.
This is important because often debugging login problems requires looking at the system log. #2603 in particular adds more debug logging around SAML and adds a link to `/admin/status` to the SAML error page; this isn't helpful if the user has to be logged in to view the log.
> Make system log accessible during setup wizard

- shell/imports/server/accounts/saml-utils.js
- shell/server/accounts/saml/saml-server.js
- When we don't understand the assertion, dump the whole XML to the system log.
- Link directly to the system log from SAML error message.
> Make SAML errors easier to debug.

- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/sandstorm-http-bridge.capnp
This allows Wekan to send notifications to a user who has been added to a grain but has not yet opened the grain.
> Add SandstormHttpBridge.saveIdentity() method.

- Makefile
- make-bundle.sh
v8's performance in the face of many fibers is currently quite poor because
they use a linked list for all thread control block lookups.  We've observed
frontends on Oasis sitting with 65% CPU usage just navigating that linked
list.  See #2484 for screenshots.
Switching to a real data structure (a hash map) improves this situation
drastically.  @jparyani's test app [1] spends 46% of CPU time in
Isolate::FindOrAllocatePerThreadDataForThisThread when run with the default
meteor-bundled node.  That function doesn't even register in the perf report
when run against a node compiled with the hashmap patch.
I'm not thrilled about building node and carrying this patch, so if we can get
a proper fix upstream, that would be preferable.
[1] - https://github.com/jparyani/meteor-fiber-repro
Profiles …
> Build and ship a patched node in the Sandstorm bundle

- shell/packages/sandstorm-db/db.js
Users find this confusing.
A better solution would be to automatically delete trashed grains as needed when the user is running up against quota limits, but that would be trickier to implement, and as a result we haven't done it. In the meantime, this stopgap is much better than nothing.
Technically a user could abuse this by swapping grains in and out of their trash, but whatever.
> Don't count trashed grains against grain quota.

- src/sandstorm/spk.c++
Fixes #2582.
The case where `target` remains uninitialized is apparently already handled: https://github.com/sandstorm-io/sandstorm/blob/v0.187/src/sandstorm/spk.c%2B%2B#L1110-L1113
> fix segfault in spk pack

- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
Jade reported that she struggled to find her recently-created item to attach
when doing a powerbox query, and that the grains seemed unordered.
While we do sort the grains by last used time, it seems that grains shared with
you that you never opened sit at the top of the list, whereas you probably want
them to show up in the grain list by their creation timestamp, as we do in the
grain list.
cc @jadeqwang
> UiView powerbox: sort unopened apiTokens by created if no lastUsed

- shell/client/admin/email-config-client.js
- shell/client/admin/identity-providers.js
This should help make setup more reliable in the face of users accidentally
copying whitespace into their config snippets.  In particular, Google's
copy-pasteable OAuth config includes leading and trailing whitespace in
Firefox, which makes it very easy for users to think they've done the right
thing, and to fail to login because of a whitespace.
Since we don't message these errors well, users often wind up stuck.  So let's
just fix the errors from the get-go.
Strips leading and trailing whitespace from:
* Google OAuth settings UI
* GitHub OAuth settings UI
* LDAP settings UI
* SAML settings UI
* Email settings UI
Fixes #1861.
> Trim whitespace from identity provider and email config fields

- shell/server/accounts/saml/saml-server.js
It's probably typical for users to include these when pasting.
> Automatically remove '---BEGIN CERTIFICATE---', etc. from SAML certs.

- make-bundle.sh
Creating or removing children of a directory causes the directory's mtime to change.  The node-building code previously rm'd `deps/node/out` and replaced it with a newly-built one.  This caused make to think that we had updated `deps/node`, which would force an ekam run and everything else that follows in the build process, when really a rebuild on unchanged source should be a noop.
@dwrensha This should make repeated `make update` calls fast, as they used to be.
> Avoid make thinking that deps/node has been modified

- tests/apps/ip-networking.js
The `IpInterface` tests have been flaky since their incept due to a race
condition between the testsuite attempting to connect to the port the test
grain requests to `listenTcp` on and the grain actually getting the frontend to
bind/listen that port.
The changes to the test app in [1] make a visible-on-the-page change when the
server acknowledges having completed binding the port, so we can now wait for
that before calling `assertTcpConnection()`, which in turn should prevent this
race condition from causing spurious test failures on Jenkins.
[1] https://github.com/sandstorm-io/sandstorm-test-python/pull/7
> Make IpInterface test reliable

- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
- shell/client/styles/_setup-wizard.scss
The link at the bottom of the page is now turned into a button that shows the log inline on the page.
Closes #1956
> Make it possible to view the system log inline in the setup wizard

- shell/server/hack-session.js
It turns out `pathname` defaults to "/".
> Fix bug in getUiViewForEndpoint handling webkeys

- src/sandstorm/sandstorm-http-bridge.c++
`Sandstorm.getSavedIdentity()` returns a pipelined identity capability. If the `restore()` call fails, the error is reported when the app tries to use the returned pipelined identity capability. Currently, the same error is also unconditionally reported by sandstorm-http-bridge; an app that calls `whenResolved()` on the returned cap and attempts to gracefully deal with the error still ends up with the error logged by sandstorm-http-bridge. That could be confusing for someone trying to debug an app.
> sandstorm-http-bridge: don't double-report errors upon restoring identities

- shell/client/accounts/email-token/token-client.js
- shell/client/accounts/email-token/token-templates.html
- shell/client/accounts/login-buttons.js
- shell/client/styles/_powerbox.scss
- shell/imports/client/accounts/email-token/token-login-helpers.js
- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox.html
- shell/server/accounts/email-token/token-server.js
- shell/server/accounts/identity/identity-server.js
- shell/server/drivers/mail.js
- src/sandstorm/email.capnp
If the verifier is configured to accept emails from the "email" identity provider, displays a powerbox option like this:
Clicking the "Add a new email..." button leads to a prompt:
If you enter an email that's already verified, then this is the last step, and the button automatically updates to reflect that fact:
Otherwise, you need to get the token from your email:
If you enter the wrong token, you get an error:
I opted to write these templates from scratch because our existing email login templates are kind of a mess.
By adding a `searchTerms` field, this also makes it so the powerbox search bar actually works in email requests.
> Implement "add a new email" in verifiedEmail powerbox picker.

- installer-tests/full-server-install-on-jessie-with-mta.t
This allows slower machines (like Jenkins) to be able to complete this test.
> installer-tests: Start Postfix separate from install

- shell/client/setup-wizard/wizard.js
While #2612 added trimming in the admin panel, some forms are duplicated in the
setup wizard, and a user hit the issue in the email hostname form there.
> Trim inputs in setup wizard too

- shell/client/accounts/login-buttons.html
Placing errors below the thing the user is interacting with is bad because:
* the errors can wind up completely off-screen if they appear below the fold
* users are less likely to associate the error message with the action they
just took if it is in a section that they haven't read/interacted with on the
page.
It is better to place errors at the top of the context to which they apply
than to place them below the context to which they apply.
Ideally, we'd place errors associated with a particular login mechanism just
above *that login mechanism's login section* but I don't think we currently
track those separately and this seems like a strict improvement.
> Move info/error messages in the login dialog to the top of the form

- shell/client/admin/identity-providers.html
- shell/client/styles/_admin-identity.scss
I also noticed that the styles for this form could be DRYed up, which fixed a
problem where the `<input type="password">` was not `display: block;`
> Mask LDAP bind password in the dialog

- src/sandstorm/backend.c++
- src/sandstorm/backend.h
- src/sandstorm/backup.c++
- src/sandstorm/backup.h
- src/sandstorm/run-bundle.c++
- src/sandstorm/spk.c++
- src/sandstorm/spk.h
- src/sandstorm/supervisor.c++
- src/sandstorm/supervisor.h
- src/sandstorm/util.c++
- src/sandstorm/util.h
This turned out significantly less horrible than imagined.
Until now our assumption had been that supporting non-userns systems would require turning the supervisor into a setuid binary. Setuid binaries are scary. Also, the supervisor isn't actually a separate binary from other Sandstorm components these days, which would be a pain to undo.
But I came up with a trick that avoids the need for setuid binaries: Instead, root privileges are handed down from the bundle runner through the "backend" process to the supervisor. The backend process runs with _effective_ UID non-root, but still has a _real_ UID of root, which allows it to run the supervisor as root. No setuid binaries.
This does mean that an RCE vulnerability in the backend process would be able to do more damage, since it could …
> Support RHEL 7, CentOS 7, and Arch by not using userns when unavailable

- shell/client/admin/feature-key-client.js
- shell/client/admin/feature-key.html
- shell/client/styles/_admin.scss
In user testing, it took a user longer than I expected to realize what was they
were supposed to do next after obtaining a trial key.  In an ideal world, they
wouldn't need to take any particular action, but for now we can make this have
a bit more consistency/familiarity by mimicking the stylization and format of
the feature key in the Sandstorm for Work dashboard.
The goal here is to show an example of what a feature key looks like, so when
the user obtains one they'll more quickly connect that they're supposed to
paste it into the box.
If the user attempts to use the placeholder feature key, we will give them a
gentle admonishment.
> Feature key upload form: show example feature key

- shell/client/accounts/login-buttons.html
Reverts sandstorm-io/sandstorm#2651
This change makes e-mail login confusing. Reverting for now until we can figure out how to make it better. See discussion on original PR.
> Revert "Move info/error messages in the login dialog to the top of the form"

- shell/client/accounts/login-buttons.html
- shell/client/accounts/login-buttons.js
- shell/client/grain-client.js
- shell/client/grain.html
- shell/client/setup-wizard/wizard.html
- shell/client/shell.html
- shell/client/styles/_widgets.scss
- shell/imports/client/grain/grainview.js
The previous sign-in overlay did not behave well in the presence of scrolling.
Now, we show a modal overlay rather than painting over the app at the same
time.
This change also makes the sign-in dialog's label optionally explicit, which means
we can say "Create account" in the setup wizard for the first user, or "Sign in" if you're
trying to promote an existing user to admin.
> Rework sign-in overlay postMessage API

- installer-tests/prepare-for-tests.sh
This commit can go away once 1.2.1 is released.
> installer-tests: Get vagrant-mutate from git

- Makefile
- shell/client/shell-client.js
- shell/client/shell.html
- shell/client/styles/_applist.scss
- shell/client/styles/_topbar.scss
- shell/packages/sandstorm-ui-topbar/topbar.html
Some rejiggering was needed to keep styles from cascading where we don't want
them to cascade.  We could probably stand to avoid styling tags without a class
in all but the last item in the selector in the future.
Fixes #2658
We don't handle the case where there's too much content on mobile, but that's not new.
> Restyle demo sidebar

- shell/imports/server/email.js
Apparently nodemailer's defaults will supply "localhost" for the hostname
if none is provided.  This hilariously results in email getting sent via
localhost if you have explicitly deconfigured email.
This change makes the email pool factory throw if you provide an empty hostname.
> Don't accidentally send email via localhost if hostname unset

- shell/client/accounts/login-buttons.js
- shell/client/dev-accounts-client.js
Without this, login methods that do not redirect (thus refreshing the page)
leave the login overlay visible even after login has succeeded.
With this patchset, each of the non-redirect login methods (dev accounts, email
token form submission, and LDAP login) close any leftover login overlays when
login succeeds.
I had to add a continuation argument to `loginDevAccount`.
> Close any login overlays on login

- shell/client/grain-client.js
- shell/client/shell-client.js
Standalone grains lack the topbar, but you should still be able to log out from them, especially if your account has e.g. credit cards on file or something of the sort.
With this change, apps can support this workflow by requesting that Sandstorm log the user out via postMessage.
To avoid allowing grains to DoS users through this postMessage, we restrict its use to standalone grains.
> Allow logout via postmessage on standalone grains

- shell/client/admin/admin-new-client.js
- shell/client/admin/admin.html
1. Feature key is super technical.  Subscription is better.
2. Change the subtext when you already have SfW enabled.
Fixes #2576
No feature key:
With feature key:
> Adjust copy in admin root page re: Sandstorm for Work

- shell/client/grain/grainlist-client.js
- shell/client/grain/grainlist.html
Since most users will have preinstalled apps, the "install an app to create a
grain" text is a little odd.
Fixes #2575
No apps installed:
Apps installed:
> grainlist: make app install hint more specific

- shell/server/proxy.js
This fixes a bug in powerbox offer + standalone domains
> Pass user/identity ID to sessions for standalone domains

- install.sh
Depends on #2644.
We've decided to delay releasing the installer changes until we've been able to test the privileged (non-userns) sandbox mode more thoroughly, because once we update the installer, users of Debian and Ubuntu will probably start using the privileged sandbox by default.
> installer: Don't require userns. Accept kernel 3.10.

- shell/imports/server/backend.js
- shell/packages/sandstorm-permissions/permissions.js
- shell/packages/sandstorm-ui-powerbox/powerbox-server.js
- shell/server/hack-session.js
- src/sandstorm/supervisor.capnp
Claiming the request was failing if the identity didn't have direct access to the grain, because a MembraneRequirement was being added requiring that the identity have such access. Instead, we should add a token requirement.
> Fix powerbox requests for standalone domains.

- shell/client/styles/_partials.scss
The existing white-on-pure-red is somewhat low-contrast.  The saturation of the
red is also very eye-catching and attention-grabbing, when most danger
buttons are not a part of the UI that we wish to draw attention to.
This change deemphasizes danger buttons, but preserves a darker red background on
hover and keeps the text red to indicate that the action is destructive to e.g.
mobile users that won't see hover states.
Fixes #2702
> Make danger buttons not so loud

- shell/client/styles/_widgets.scss
It turns out that justify-content doesn't do anything meaningful for us
here on chrome/firefox, but has a weird interaction on IE11.
Fixes #2709
> Fixes centering of overlay signin on IE11

- src/sandstorm/backup.c++
- src/sandstorm/run-bundle.c++
- src/sandstorm/supervisor.c++
Currenly, for servers running with no root privileges, each update crashes the server. Starting the server back up again works fine.
The problem was introduced in the change introducing the privileged sandbox. On non-root installs, Sandstorm's outer container needs to use a user namespace. Within that user namespace, the UID was being mapped to zero. This caused a newly-added assert in supervisor.c++ to fail. Rather than roll back the assert, I decided to change the UID mapping to non-zero, *completely ignoring* the comment *right above* the code that explained why it really does need to be zero. :(
This change goes back to mapping as UID zero and removes the asserts instead.
Note that UID zero inside the user namespace is not actually root on the system. Also, we explicitly drop …
> Fix updates for non-root installs.

- shell/shared/grain-shared.js
This causes the client to now correctly handle the session closing.
> When trashing grain, only delete the session server-side

- src/sandstorm/supervisor.c++
The inconsistency originated in https://github.com/sandstorm-io/sandstorm/commit/ce3d0fd8560f62666a97140426d82a04ce0b6fa4.
> update comment about supervisor SIGALRM to be consistent with code

- src/sandstorm/appid-replacements.capnp
Adds a new key held by me. Does not revoke the one held by @mquandalle.
> add replacement app ID for wekan

- shell/packages/sandstorm-ui-topbar/topbar.html
This is the simplest possible change that I can think of that results in us knowing if the recent changes to the demo sidebar result in increased traffic to `/get`.
> Add metadata so we know when /get visits come from demo

- shell/server/proxy.js
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/web-session.capnp
This fixes #2691 where a client could get an encoding
that it did not expect since the HTTP bridge always
added gzip encoding.
> Add Accept-Encoding header to Web Session

- shell/server/00-startup.js
I suspect we are leaking capabilities somewhere.
Depends on: https://github.com/kentonv/node-capnp/commit/74958750f1c10a36d626ddca51539936687100c3
> For debug purposes on Blackrock, dump counts of local capability object types every minute.

- shell/server/proxy.js
We already have logic that periodically culls the proxy objects being used by API sessions. This patch adds a call to `proxy.supervisor.keepAlive()` for each proxy that we decide not to clean up. It also accounts for requests and responses that are streaming.
This handles the most urgent pieces of #2462 and #2218.
> Keep grains alive if they have recent API session activity.

- shell/server/pre-meteor.js
Otherwise index.html does not get added to paths ending in '/', leading to other weird behavior.
Fixes #2745
> Remove query string before adding index.html.

- shell/client/admin/identity-providers.html
- shell/client/admin/identity-providers.js
- shell/client/setup-wizard/wizard.html
- shell/client/setup-wizard/wizard.js
- shell/client/styles/_admin-identity.scss
Changing BASE_URL can deconfigure Google and GitHub login, which can leave
the server in a situation where you can't log in, but you're directed to
sign in to create an admin account.  We should prompt you to reconfigure login.
Also, in the transition to the new admin UI, we stopped help text when the BASE_URL was changed.  This changeset adds a note and additional instructions when you go to reconfigure Google or GitHub login after a BASE_URL change.
Fixes #2030.
> Setup wizard base url changes

- docs/administering/sample-config/nginx-example.conf
1. Passes the remote address in the header so that sandstorm can use the remote address in apps like Piwik (fixes https://github.com/zarvox/piwik/issues/10 )
2. Changes server_name so that sandstorm api access url will be recognized.
> nginx configuration tweaks for geolocation

- shell/packages/sandstorm-db/db.js
Currently, the object returned here can have `grainInfo.icon = undefined`. When this gets written to Mongo, that `undefined` (somewhat surprisingly) morphs into a `null`, which can lead to bugs like #2633.
It's cleaner to not the `icon` field at all if there is nothing to put there.
> don't bother setting grainInfo.icon if there is no icon

- shell/client/apps/applist-client.js
- shell/server/install-server.js
This change allows invited and demo users who are at or above their quota
limits to navigate to the app market and install apps from the app market where
previously we would have blocked the installation.
User testing reveals that demo users who hit the quota interstitial when
attempting to install a new app immediately attempt to uninstall apps to
free up quota.  This has a couple of downsides:
* The user's immediate reaction is usually to attempt to uninstall apps, which
the user hopes will free up quota, but which doesn't actually free quota
because app storage on Sandstorm doesn't work like storage on mobile phones.
* There's no other way for users to navigate from the Sandstorm UI to the app
market, so they get stuck unable to look back at the app market, which is sad
Especially on …
> Disable quota enforcement in app installation flow

- src/sandstorm/grain.capnp
In order to work around https://github.com/dwrensha/capnpc-rust/issues/30, I'm copy/pasting `AppPersistent` into an app-specific schema file. It would be nice if the canonical declaration of `AppPersistent` specified its type ID, so that it would be easier to verify that my copy matches up.
The ID added in this pull request was obtained from `capnp compile -ocapnp`.
> explicitly annotate AppPersistent's type ID

- src/sandstorm/backup.c++
- tests/tests/backup-restore.js
Currently, the backup-restore test triggers the error:
```
sandstorm/backup.c++:126: failed: expected uid != 0
stack: 0x519863 0x494975
capnp/rpc.c++:142: info: returning failure over rpc; exception = sandstorm/util.c++:959: failed: expected exitCode == 0; child process failed; name = backup; exitCode = 1
stack: 0x5a2ccc 0x4a7a92 0x425140
Exception while invoking method 'backupGrain' Error: remote exception: expected exitCode == 0; child process failed; name = backup; exitCode = 1
at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
at waitPromise (imports/server/async-helpers.js:39:35)
at [object Object].backupGrain (server/backup.js:66:5)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
at packages/ddp-server/livedata_server.js:711:19 …
```
> fix backup-restore test failure

- shell/server/hack-session.js
There are a few old versions of the Collections app and the Rocket.Chat app that depend on this not being an error, but any grains using those versions ought to be updated by now.
> throw an error if a UiView offer provides no title

- shell/imports/server/accounts/ldap.js
Fixes #2778 
It turns out that we weren't querying for the `mail` field in LDAP correctly. This is now corrected, and I can confirm it displays correctly in the grains list when it is working.
> Fix ldap quota not querying correctly

- tests/README.md
As of https://github.com/sandstorm-io/sandstorm/commit/c19c93a8cb271d9c07fb28141ce5db75bc479789 we no longer use the selenium-standalone package.
> update README explanation about manually running Selenium

- shell/server/drivers/external-ui-view.js
The `path` parameter to `WebSession`'s methods should never include the leading `'/'`. (See [this](https://github.com/sandstorm-io/sandstorm/blob/v0.196/src/sandstorm/web-session.capnp#L98-L99) and [this](https://github.com/sandstorm-io/sandstorm/blob/v0.196/shell/server/proxy.js#L1863).)
In contrast, the `path` argument in a call to node's [`http.request()`](https://nodejs.org/api/http.html#http_http_request_options_callback) should have a leading `'/'`. So  this pull request adds it.
I noticed this problem when I tried making a hacky HTTP pseudodriver by copying this code.
> prepend '/' to paths in ExternalWebSessionImpl

- shell/server/installer.js
Before this change, if a user on the server manually installed the package before the autoupdate downloaded the package, and then the user deleted all their references to the package, the package would be deleted.
I don't think this actually fixes #2772, but it could be what @zarvox ran into.
> Fix up the logic for garbage collecting autoupdate apps

- shell/server/proxy.js
Fixes #2809.
Note that we are already calling `encodeURI()` in [the other place we set the Location header](https://github.com/sandstorm-io/sandstorm/blob/v0.198/shell/server/proxy.js#L1603).
> properly encode Location header in redirect responses

- shell/imports/server/auth.js
- shell/server/accounts/email-token/token-server.js
This seems particularly needed for e-mail tokens since e-mail can suffer from slow queues.
Fixes #2775.
@ndarilek
> Increase 15-minute token timeouts to 1 hour.

- shell/server/admin-server.js
- src/sandstorm/run-bundle.c++
- src/sandstorm/supervisor.c++
- src/sandstorm/util.c++
- src/sandstorm/util.h
Have been wanting to do this a long time but continuously procrastinated...
As written this will save 512k-1MB of grain logs at a time and 1MB-2MB of main log. These numbers could well be adjusted if desired.
Fixes #2636.
> Rotate logs -- both sandstorm.log and grain logs.

- find-meteor-dev-bundle.sh
This script seems to need to communicate with Meteor servers, taking an annoyingly long time, and for some reason ends up running 2-3 times per make. Cache the output so it's fast.
> Cache output of find-meteor-dev-bundle.sh.

- src/sandstorm/sandstorm-http-bridge.c++
Fixes #2779.
The only places where we need to `connect()` to the app are in methods of `WebSessionImpl`, so it suffices to return promise capabilities from `UiViewImpl::newSession()` that resolve once we've successfully made the initial connection.
cc @zenhack
> [http-bridge] Asynchronously wait for app to accept connections

- shell/imports/server/accounts/saml-utils.js
Apparently, this clause actually prevents Sandstorm from working with ADFS installations that use non-password mechanisms like Kerberos.
I do not know why SAML lets the client specify the authentication mechanism, nor do I know why our code specified password authentication here (seems to have been inherited from the old meteor-accounts-saml code).
I've tested this change against: SimpleSamlPhp, Windows Server ADFS, Azure AD.
@abliss This is the change you wanted, right?
> SAML login: Don't require password authentication.

- shell/imports/client/grain/grainview.js
> On grain share, don't assume Meteor.user() is valid

- src/sandstorm/api-session.capnp
- src/sandstorm/bridge-proxy.c++
- src/sandstorm/bridge-proxy.capnp
- src/sandstorm/bridge-proxy.h
- src/sandstorm/grain.capnp
- src/sandstorm/package.capnp
- src/sandstorm/sandstorm-http-bridge-internal.capnp
- src/sandstorm/sandstorm-http-bridge-request.html
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/util.c++
- src/sandstorm/util.h
Commits 3acb128 through c970f29 implement the ability to *export* HTTP APIs from an http-bridge app. In the bridge config, the user may define a list of APIs the grain supports. (Currently these are singleton declarations -- the grain cannot implement multiple sub-objects. For most apps, this is probably fine, because grains themselves are usually the appropriate unit of export.)
Commits cd92c08 through 73bd11d implement the ability to *import* HTTP APIs in an http-bridge app. http-bridge is extended to export an HTTP proxy on localhost:15239. The `HTTP_PROXY` and `http_proxy` environment variables are set appropriately. A special route, `http://http-bridge/session/<session-id>/claim`, wraps the `SessionContext.claimRequest()` method, converting a request token obtained via a …
> Extend http-bridge to support app-to-app powerbox HTTP APIs

- shell/server/sandcats.js
Fixes sandstorm-io/sandcats#153.
I'm not quite sure if this actually works, as I can't actually get a local dev environment set up (and even if I could I'm not particularly sure how to test Sandcats-related stuff since it calls out to the network service). However, it does pass JSHint, so at least it's not totally busted.
Question: does Sandcats determine the IP to set the DNS record to from the IP used to send the POST request? Or is it embedded in the HTTP body? AFAICT it's the former, but I could be wrong as I don't fully understand everything this code does yet.
Also, I fixed a whitespace issue as a bonus.
> Handle Sandstorm being bound on secondary addresses in Sandcats

- shell/client/admin/network-capabilities-client.js
- shell/client/admin/network-capabilities.html
- shell/imports/server/migrations.js
- shell/packages/sandstorm-ui-powerbox/powerbox-client.js
- shell/packages/sandstorm-ui-powerbox/powerbox.html
- shell/server/drivers/ip.js
- src/sandstorm/ip.capnp
This is an implementation of @kentonv's [suggestion](https://github.com/sandstorm-io/sandstorm/pull/2774#issuecomment-263086336) from #2774.
This changes the database representation of `IpNetwork` sturdyrefs and includes a migration to convert existing sturdyrefs of the form `ipNetwork: true` into `ipNetwork: {encryption: {none: null}}`.
Adds a "TLS-encrypted outbound network access" table to the "Network capabilities" section of the admin panel. Also in the "Network capabilities" section, fixes some bugs, most of which were introduced when we switched to using the `claimRequest()` flow. `cap.owner.grain.introducerIdentity` is now obsolete!
> Add option for IpNetwork to be layered on top of TLS.

- docs/vagrant-spk/installation.md
The `git://` protocol is unencrypted and not recommended for use on the public internet.
> Specify HTTPS URL for `git clone` example

- docs/administering/ssl.md
Linked to an article + script I wrote providing a way to use HTTPS sandcats.io with your normal reverse proxy.
> Update ssl.md, added a cleaner way to share the 443 port without sniproxy

- make-bundle.sh
This file will be broken if installed because of the `embed` line. It appears that some tools or scripts or something try to parse all the capnp files in the directory even if not needed, for some reason.
> Don't include sandstorm-http-bridge-internal.capnp in installed capnp files.

- shell/packages/sandstorm-db/db.js
For example, in the gov.tw instance we need to allow all .gov.tw users using `/\.gov\.tw$/` in this field.
If this makes sense, we can change the description of `Users with an email address at this domain will be members of this server's organization.` to mention the regex syntax.
> Support comma-delimited emailDomain suffixes, optionally with leading "*."

- shell/client/grain-client.js
- shell/client/shell-client.js
- shell/server/backup.js
- shell/server/install-server.js
When a separate DDP host is specified, it should be used for all "dynamic" interaction, where the main host is used only for static content (e.g. static HTML, Javascript, CSS, images).
See also: https://sandstorm.io/news/2017-02-28-cloudbleed
> Upload/download backups on DDP host rather than main host.

- shell/client/styles/_admin-users.scss
Currently, the rows in the Admin/Users table are clickable, but the cursor does not reflect that fact.
> add 'cursor: pointer;' to the clickable rows in the users table

- shell/imports/server/accounts/saml-utils.js
When I  trying to logged in with Azure AD,  an error occurred with message `SAML profile did not contain an email address`  and I could not log in.
As far as I can see, this issue is caused by the field name of SAML response about email is different between Azure AD accounts and Microsoft accounts. (ref., https://onlinehelp.tableau.com/current/online/en-us/saml_config_azure_ad.htm)
This patch is fix of this issue.
> Fix SAML login for Azure active directory accounts

- docs/install.md
heapdump, a dependency of the meteor shell, wants a python binary. My stock Ubuntu 16.04.1 image on vultr.com doesn't come with one.
> Mention Python dep in install.md

- shell/server/shell-server.js
Fixes #2578.
Our `connect-src` already includes `*`. According to [this document](https://webkit.org/blog/6830/a-refined-content-security-policy/), last year WebKit changed the meaning of the `*` in a backwards-incompatible way, such that now it only matches the scheme of the current page. So we still need to add a `ws` and/or `wss` scheme.
See also: https://github.com/meteor/meteor/issues/7772#issuecomment-265600327
> add 'connect-src wss: ws' so that Safari can use a websocket on the main host

- shell/client/shell-client.js
- shell/client/shell.html
- shell/packages/sandstorm-db/db.js
- shell/server/accounts/accounts-server.js
This experiment caused 50% of Oasis users to see the billing plan chooser immediately upon logging in for the first time (with the option to choose the free plan), while the other 50% would default to a free account and only see the plan chooser once they had hit their quota limits.
Conclusion: Showing the billing prompt at account creation did not significantly affect any behavior that we attempted to measure. See: https://oasis.sandstorm.io/shared/LLFTfbhqQUHnTJ0_cKCn1yWk9Dcl-uP1pk0DfuJlJf9
However:
- The prompt was probably annoying.
- The prompt was responsible for numerous bugs over the time the experiment was active, in which the prompt would appear in inappropriate contexts.
Therefore, we will no longer show the billing prompt at account creation.
> Delete billing-prompt-on-account-creation experiment.

- src/sandstorm/run-bundle.c++
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/union-fs.c++
`realpath()` and `signal()` return a pointer, but `KJ_SYSCALL()` expects a function that returns an integer.
> fix errors reported by clang++ 4.0

- shell/imports/server/backend.js
When a grain provides a capability through a `SessionContext`, that capability will have a `permissionsHeld` `MembraneRequirement` attached to it that automatically revokes the capability when the grain gets trashed.
When a grain provides a capability directly through the `SandstormApi`, (e.g. a `Runnable` in https://github.com/sandstorm-io/sandstorm/pull/2922), no such requirement is added, and currently there is nothing stopping the capability from being restored even after the grain is trashed.
This pull request fixes that problem.
(Additionally, it might make sense to add a new kind of `MembraneRequirement` to handle this kind of situation. We can discuss such a change in a separate issue/pull request if it is desired.)
> don't start grains that are trashed

- shell/server/drivers/external-ui-view.js
- src/sandstorm/bridge-proxy.c++
- src/sandstorm/web-session.capnp
Previously, error responses were replacing the response body with the error status name, e.g. "Not Found". For HTTP APIs, error bodies are often important.
Since HTTP APIs often want to return non-HTML error bodies, I extended web-session.capnp to be able to represent these.
However, I have not updated sandstorm-http-bridge or proxy.js to understand this protocol for now. I would like to rewrite sandstorm-http-bridge in terms of kj-http at some point, which would be a good time to update it.
This also fixes a bug: The content-type header on 200-OK responses wasn't being set correctly (it was clobbering the Content-Language header instead).
> Correctly pass through error bodies for Powerbox HTTP requests

- src/sandstorm/supervisor.c++
A while back I'd been just playing around with these things, and I derived the same set of arguments by reading the docs -- so when I was poking through this code and saw the AFAICT comment, I knew that couldn't be right. I've changed the comment to point to the relevant docs, and supply a quick summary.
> Add man page references re: mount propagation type

- shell/server/proxy.js
I was futzing around with typescript, decided to run it on sandstorm to see what it caught without any annotations -- this is what I got.
Note that I'm not really clear on the purpose of that code, so for all I know this may represent a real bug, but it also may.
> Remove dead code

- shell/client/accounts/account-settings.html
- shell/client/accounts/account-settings.js
- shell/client/notifications-client.js
- shell/client/notifications.html
- shell/client/styles/_account.scss
- shell/imports/server/migrations.js
- shell/packages/sandstorm-db/.npm/package/npm-shrinkwrap.json
- shell/packages/sandstorm-db/db.js
- shell/server/notifications-server.js
See explanation here: https://github.com/sandstorm-io/sandstorm-website/pull/289
We send a bell notification to all users who have multiple identities where the display names of those identities are not all the same. We also show a warning on the accounts page for these users.
We specifically look for users with varying names on the assumption that if all the names are the same, then the user really only has one identity anyway, and the coming changes will be a strict improvement for them. I didn't feel it was necessary to compare profile pictures, handles, or preferred pronouns because if the display name is the same, it seems unlikely that the profiles vary significantly in these other factors.
> Send a notification warning affected users that identities are changing.

- src/sandstorm/spk.h
Without this I get the following error:
```
compile: sandstorm/spk.c++
In file included from /ekam-provider/canonical/sandstorm/spk.c++:19:
/ekam-provider/canonical/sandstorm/spk.h:37:51: error: unknown type name 'uid_t'; did you mean 'pid_t'?
kj::Maybe<uid_t> sandboxUid = nullptr);
^~~~~
pid_t
/usr/include/fcntl.h:69:17: note: 'pid_t' declared here
typedef __pid_t pid_t;
^
1 error generated.
```
I assume this is dev-environment dependent in some way, since I can't
imagine it's just not building for anyone...
> spk.h: #include <sys/types.h>

- shell/i18n/nl.i18n.json
I have translated everything except for the style guide.
When saving your preferences the confirmation still shows up as 'Saved changes', but I don not know enough web development to fix that.
Also some text boxes are a little too small for the words, this is noticeable for instance in the user settings.
> Dutch translation

- shell/i18n/fi.i18n.json
Added Finnish translation to Sandstorm.
> Add Finnish translation to Sandstorm

- docs/vagrant-spk/customizing.md
As per sandstorm-io/vagrant-spk#211. Also MkDocs isn't making these repo URLs into links, so I'm trying to force that.
> Docs: Update PHP version in example

- docs/vagrant-spk/platform-stacks.md
This reminds me that the Node stacks are probably really old. But descriptions of all the stacks should really be here.
> Docs: Updated vagrant-spk platform stacks page with new stacks

- docs/install.md
These are all of the packages I needed to install for
a successful build of Sandstorm as of early March, 2018.
> Updated install docs for Fedora 27 packages

- docs/vagrant-spk/packaging-tutorial-meteor.md
Fixes #2866. As of https://github.com/sandstorm-io/vagrant-spk/pull/231 being merged and included in a release it is safe to remove this warning.
> Docs: Remove outdated compatibility note

- shell/client/apps/app-details-client.js
I haven't tested this, but it's fairly simple code. I believe all my parenthesis are correct.
I am baffled why this doesn't use `startsWith` like the app market in https://github.com/sandstorm-io/sandstorm-app-market/pull/134
> Support GitLab and Bitbucket with Bug Report link

- docs/developing/publishing-apps.md
**IMPORTANT: This change depends on a pending vagrant-spk PR, hold for merge and release.**
This drastically simplifies using these commands from vagrant-spk.
https://github.com/sandstorm-io/vagrant-spk/issues/236 adds vagrant-spk listkeys support. vagrant-spk keygen was already supported.
> Docs: Update vagrant-spk key-handling

- shell/packages/sandstorm-db/db.js
- shell/packages/sandstorm-permissions/permissions.js
- shell/server/backup.js
- shell/server/grain-server.js
- shell/server/install-server.js
- shell/server/shell-server.js
- shell/shared/grain-shared.js
- src/sandstorm/grain.capnp
Two years ago, I [refactored the way identities work](https://sandstorm.io/news/2017-05-08-refactoring-identities).
Prior to that refactor, the "identity ID" that apps received identifying each user was exactly the ID of the credential they used to open the grain. These IDs were consistent across servers; e.g. if you used Google login on multiple Sandstorm servers using the same Google account, then you'd have the same identity ID in every app. (The identity ID was derived from taking a hash of the Google account ID.)
This had some problems:
* In theory, it meant that users could be tracked across grains and apps could know who a user is in advance (by having a database of known identities). This could be a privacy threat.
* With the identity refactor, users no longer chose a specific …
> Remember user identities through "forget grain" and backup/restore

- shell/server/drivers/external-ui-view.js
I don't understand why this was previously restricted to the /users
path on the GitHub api; this ought to match for the entire API.
> external-ui-view: Don't restrict GitHub to /users

- src/sandstorm/package.capnp
- src/sandstorm/sandstorm-http-bridge-internal.capnp
- src/sandstorm/sandstorm-http-bridge.capnp
This introduces additions to capnproto interfaces to allow
sandstorm-http-bridge to delegate MainView.restore/drop and
UiView.getViewInfo to the app, while still handling HTTP
translation.
Would like opinions on the design.
//cc @kentonv, @ocdtrekkie
> Spec out a solution to #3027

- docs/developing/raw-packaging-guide.md
There is no wrench icon. I assume there used to be. This updates the one reference to "wrench" in the docs.
> Docs: Update "wrench icon" with "console icon"

- Makefile
Fixes #3171.
Someone just asked on the mailing list about this happening on Fedora.
It would be nice to better understand what's going on, but this clearly
affects most newer systems, let's fix the build already.
> Add -DKJ_STD_COMPAT to C(XX)FLAGS.

- tests/README.md
- tests/run-local.sh
Per the new section in the README, I've found this useful for debugging.
> Test suite: add an option for displaying the browser window.

- .github/workflows/doc-prod.yml
- docs/README.md
- docs/generate.sh
This PR, built atop my previous one, makes it possible to deploy the docs with a github push.
It extends the `generate.sh` script to fetch its dependencies and setup from scratch when given the `-s` option.
I created two "Workflow" files, one for staging and one for prod. The URL to the gitweb-pages grain, including its username and password, can be stored in Github Secrets. I was thinking that the flow could be to merge master to the doc-staging branch, wait for the action to complete, inspect the staging grain, and then merge master to the doc-prod branch. 
I tested this by pushing to my own repo and letting it deploy to my own staging grain.
Future work: use the github cache action to make it faster (setting up from scratch takes about 30sec). 
Example deployment log: …
> Doc action

- docs/developing/web-publishing.md
Running `vagrant-spk vm provision` after following instructions here https://docs.sandstorm.io/en/latest/developing/web-publishing/#a-helper-program-you-can-include-to-enable-publishing-request-a-publicid failed saying git wasn't installed.
This would install git.
> VM requires git - standard setup.sh doesn't install it

- install.sh
Ensures that resolv.conf is present on Sandstorm server startup.
I have tested this on my own self-hosted server running on Debian Stretch.
Fixes #3099
> Depend on network-online.service instead of network.service

- shell/i18n/sync-langs.py
With these changes, the script runs under Python >=2.7. With the sunsetting of Python 2, this seems like a good idea.
> Adapt sync-langs.py for Python 3

- docs/vagrant-spk/platform-stacks.md
We do tell people to use GitHub master by default, so we should update this in Docs immediately.
> Update vagrant-spk stack list to reflect master

- docs/vagrant-spk/packaging-tutorial.md
This could be a little clearer what it is for, and it doesn't cost much space to give a quick example or two. Someone packaging an app was unsure if they should set this to "showcase" as per the tutorial, or leave it as "instance" like it is by default.
> Clarify what one might use for a nounPhrase

- docs/developing/debugging.md
- docs/vagrant-spk/packaging-tutorial-meteor.md
- docs/vagrant-spk/packaging-tutorial.md
- docs/vagrant-spk/platform-stacks.md
This changes all the vagrant-spk tutorials to specify using port 6090 instead of port 6080, which should be true for new packages made after the merge of https://github.com/sandstorm-io/vagrant-spk/pull/260
I also drive-by-deleted a line about the minimum version of vagrant-spk required to use enter-grain, because that was four years ago and the Docs reflect the current state of vagrant-spk anyways, which is very much different than four years ago.
> Docs: Change vagrant-spk port to 6090

- Vagrantfile
See https://github.com/sandstorm-io/vagrant-spk/pull/241 for the same fix on vagrant-spk, see https://github.com/sandstorm-io/vagrant-spk/pull/240 for details on how the existing command responds (listing half the RAM twice instead of providing a single valid amount of RAM).
> Fix Vagrantfile's Windows RAM calculation

- shell/i18n/en.i18n.json
This typo was introduced with i18n. Since it's a short string, my guess is someone hand-typed it instead of copy-pasting.
> Fix typo in about page

- .github/workflows/build.yml
Currently the test fails, so we don't fail the job for that (to reduce noisy
emails). Instead we upload the test log for inspection.
My next plan is to try to disable the failing tests, then switch the job to fail for any failing test, then fix and re-enable the tests one by one. It'd be nice if someone could browse through the test log and let me know if there are any tests that shouldn't be disabled (e.g. because the failure appears to be an issue with the runner, not with the test).
> Add a Github action to automatically build and test

- tests/apps/schedule.js
Otherwise the next test starts navigating in the grain log window, and
ends up confused. Fixes #3226.
> Schedule tests: close the grain window when we're done.

- docs/developing/powerbox.md
- src/sandstorm/sandstorm-http-bridge-internal.capnp
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/sandstorm-http-bridge.capnp
Starting with just spec'ing out the solution I described in #3197 precisely; I've done the capnproto parts of this, and will push subsequent commits that update other relevant parts of the docs. Once that's in place and folks are happy with the API, I'll start implementing. I'll probably wait until #3221 is merged and rebase on top of that to avoid potential conflicts.
> Allow apps using the bridge to respond to powerbox requests & offers

- .github/workflows/build.yml
As noted in reviews of #3208 it could be dangerous to install a build 9999, and the default behavior (build 0) is assumed to be a dev build. It's probably not super necessary to upload every single built Sandstorm test for every commit and PR either, but it's just commented out in case we want to restore it.
Side note: I haven't tested this, but creating a PR should test it?
> Actions: Don't upload every build, BUILD 0

- docs/administering/active-directory.md
- docs/administering/faq.md
- docs/administering/for-work.md
- docs/administering/guide.md
- docs/administering/reverse-proxy.md
- docs/developing.md
- docs/developing/handbook.md
- docs/developing/publishing-apps.md
- docs/install.md
- docs/vagrant-spk/packaging-tutorial-meteor.md
Kenton stated that community@ is not monitored and is full of spam. And that we should probably not have calls to email support@ everywhere either, especially since people emailing Kenton solely may not get a response as quickly as people who reach out to the community.
In a couple instances, I put in a link that should invite someone to open a GitHub issue. In others, I dropped it entirely as it may not be a focus for us to collect certain requests, and we have enough places users can find a route to contact the community for help. Many of these email references were in old pages migrated from the wiki or the like.
I also fixed one typo, deleted a "changelog" for a file as the changelog is GitHub, and removed the claim Keybase is invite-only.
> Docs: Remove calls to email

- docs/developing.md
Since Asheesh is not here to help promote your app, Nena is not here to design your app icons, and Oasis is not here to provide free service to app developers, we should remove all of that. I think eventually community-sponsored initiatives can be added in here, but let's clean this out for now.
> Docs: Remove offers of services we don't offer

- shell/imports/sandstorm-ui-powerbox/powerbox-server.js
Per the (now-deleted) comment, this previously wasn't this simple
because powerbox-server.js was inside of a meteor package, but @zarvox
did a recent refactoring that changed that, so we can just delete the
duplicate and import now.
> powerbox-server: dedup code from async-helpers.

- shell/imports/client/grain.html
Apparently blaze grew this feature some time in the past couple years.
Much more readable this way. I'm sure there are other places in the code
base we should do this, but I was staring at this template and having a
hard time following it...
> grain.html: use blaze's else-if support.

- docs/sandstorm_readthedocs_modified_theme/css/theme_extra.css
Sandstorm.io and the App Market have a very angular look, as does the Sandstorm UI itself. A 4px border-radius is common on sandstorm.io buttons, and I think it makes Docs a bit more fitting with the overall branding.
> Docs: Square off search box

- shell/imports/client/accounts/login-buttons.html
We should have people open GitHub issues with problems/suggestions/feedback rather than emailing Kenton. As it was, I found this link irritating before (#775), because unexpected mailtos often launch unintended email clients in the days most people use webmail.
I chose to not use /new here like I did for Docs, because if you aren't logged into GitHub, that'll present a login screen. I think that's okay for my Docs PR, where the link text says "open an issue on GitHub", and hence, people clicking GitHub will expect to login. But for "Send feedback", sending them to the issues page is the cleanest solution.
docs.microsoft.com literally now just opens GitHub issues for any "feedback" on documentation pages, so this is a totally unheard of pattern, and the community can respond often faster …
> Have "send feedback" link to GitHub issues

- src/sandstorm/backend.capnp
The gateway is no longer optional, so per the comment, this can be
removed.
> Remove obsolete `socketPath` constant in backend.capnp

- src/sandstorm/fuse.c++
Fixes #3219.
Technically all that is needed to fix that issue is to return ENOSYS for
FUSE_POLL, but this also future-proofs us for further changes to the
fuse protocol.
> Fuse: list write operations explicitly, default to ENOSYS.

- .github/workflows/build.yml
- Makefile
- shell/.eslintrc.yml
- shell/.meteor/versions
- shell/imports/client/accounts/login-buttons.js
- shell/imports/client/contacts.js
- shell/imports/client/grain/grainview-list.js
- shell/imports/client/grain/grainview.js
- shell/imports/server/sandcats.js
- shell/npm-shrinkwrap.json
- shell/package.json
These issues were caught by eslint and fixed:
- In a couple places were were setting global variables without
explicitly declaring them. We now actually declare variables for
these. One such case was of the form 'Foo = class Foo {', and is
now just 'class Foo {', since the assignment was redundant anyway.
- A few files that used said globals did not explicitly import them; now
they do.
- In once place we were using what is apparently deprecated syntax
for octal literals. We now use the current 0oXXX syntax.
> Add basic eslint config, fix some issues.

- .github/workflows/build.yml
- Makefile
- shell/.eslintrc.yml
- shell/.meteor/versions
- shell/client/main.ts
- shell/imports/blackrock-payments/client/billingPrompt.js
- shell/imports/blackrock-payments/client/billingSettings.js
- shell/imports/blackrock-payments/server/payments-api-server.js
- shell/imports/client/accounts/login-buttons.js
- shell/imports/client/contacts.js
- shell/imports/client/grain/grainview-list.js
- shell/imports/client/grain/grainview.js
- shell/imports/sandstorm-autoupdate-apps/autoupdate-apps-tests.js
- shell/imports/sandstorm-db/scheduled-jobs-db.js
- shell/imports/sandstorm-permissions/permissions-tests.js
- shell/imports/sandstorm-permissions/permissions.js
- shell/imports/server/dev-accounts-server.js
- shell/imports/server/sandcats.js
- shell/npm-shrinkwrap.json
- shell/package.json
- shell/tsconfig.json
Apparently the meteor typescript package doesn't actually *check* the typescript source, it just translates `.ts` files to `.js` so the build works (grumble). This adds a tsconfig.json, runs tsc as part of CI, and fixes some things that cropped up.
Note that this is built on top of #3274, so the first commit is from that. I didn't want to do two parallel prs because they would conflict, since the lint target invokes both. That PR should be merged first.
> Actually start *checking* the typescript code

- tests/package.json
The tests that use this are broken anyway (#3188) and fixing them
probably means moving to a different testing framework. Meanwhile,
spacejam pulls in phantomjs, which is unmaintained and seems to be
broken on node 12, so this breaks the whole CI system.
Hopefully fixes #3277
> Remove spacejam dependency from tests/

- shell/i18n/en.i18n.json
- shell/imports/client/admin/network-capabilities.html
Fixes #2039
@kentonv mentioned on that issue that the page is likely to cover other types of capabilities at some point. I am of the opinion that it makes sense to wait until that actually happens to update the explanation; otherwise I think it will just seem overly abstract (especially without other examples).
This will need translation (cc @xet7, who else?). (It would be nice if we had a team for translators so when submitting prs that change UI text we could just cc @sandstorm-io/translators or something).
> admin panel: add an explanation for network capabilities.

- src/sandstorm/control-socket.capnp
Per #3218.
Nothing is implemented yet, this specifies the protocol via a schema.
> Spec out a capnp version of the devmode protocol.

- Makefile
- src/sandstorm/supervisor.c++
- src/sandstorm/test-app/test-app.c++
- src/sandstorm/test-app/test-app.html
- tests/tests/system-api.js
...To get shm_open() and friends working.
Fixes #3196.
Note that the tests are currently *not* passing on my machine -- for some reason `shm_open` is returning `ENOSYS`. Based on the links @abliss posted at:
https://github.com/sandstorm-io/sandstorm/issues/3196#issuecomment-580909238
and the fact that there are two alternate implementations of `shm_open`, depending on build flags:
https://sourceware.org/git/?p=glibc.git;a=blob;f=rt/shm_open.c;h=b4623d3cdaf5a26e4fd795a866c12aa1b29eaa9a;hb=HEAD
...one possible explanation is that my system's glibc is built without support for this. So I'd be curious as to whether the tests pass for others. Grepping through the postgres source suggests it has some fallbacks if shm_open is not available, so another possibility is that the errors @orblivion …
> Mount a tmpfs at /dev/shm in the sandbox.

- .github/workflows/build.yml
- shell/.eslintrc.yml
- shell/imports/blackrock-payments/server/payments-server.js
- shell/imports/client/00-startup.js
- shell/imports/client/accounts/account-settings.js
- shell/imports/client/admin-client.js
- shell/imports/client/admin/login-providers.js
- shell/imports/client/admin/personalization-client.js
- shell/imports/client/setup-wizard/wizard.js
- shell/imports/client/shell-client.js
- shell/imports/sandstorm-autoupdate-apps/autoupdate-apps-tests.js
- shell/imports/sandstorm-autoupdate-apps/autoupdate-apps.js
- shell/imports/sandstorm-ui-topbar/topbar.js
- shell/imports/server/00-startup.js
- shell/imports/server/backup.js
- shell/imports/server/core.js
- shell/imports/server/drivers/external-ui-view.js
- shell/imports/server/drivers/mail.js
- shell/imports/server/gateway-router.js
- shell/imports/server/hack-session.js
- shell/imports/server/scheduled-job.js
- shell/imports/server/stats-server.js
- shell/imports/server/transfers-server.js
- shell/imports/shared/testing.js
- tests/apps/schedule.js
This gets rid of about 70 of them. I also set the warning to `"warn"` in the config, so it won't fail CI but we can still see the output.
> Fix more `no-undef` eslint warnings.

- docs/install.md
Per comments in the Makefile and the GitHub action, we actually need to
install specifically meteor 1.8.2, to work around a problem with font
generation (ick). The installing from source docs were never updated
when the workaround became necessary however; this patch does that.
See also #3303, where someone tripped on this getting set up to hack on
things.
> Fix bitrot in install docs.

- docs/administering/for-work.md
The default searchUsername populated by Sandstorm is `uid`, which is not populated in Active Directory. I figured we should add an implementation note here on what setting(s) someone should consider when trying to use LDAP with Active Directory. I believe both choices presented in this PR are potentially valid choices depending on the environment.
> Docs: Provide advice for AD-over-LDAP config

- find-meteor-dev-bundle.sh
When this script fails (e.g. because the requested meteor version is not installed), it writes an empty cache file. Later, that empty value would be reported as success, and so the makefile would blithely continue on with an empty path.
> find-meteor-dev-bundle: don't use empty cache

- acme-dns-01-sandcats/index.js
- acme-dns-01-sandcats/package.json
- acme-dns-01-sandcats/test.js
@kentonv, the magic seems to be to put `"type": "module"` in package.json, but I had to actually pop it open and try it to figure it out, so I figured I'd just send a pr rather than make you replicate it.
...it would be nice if it were possible for other people to run these tests somehow.
> Use es6 modules in the Sandcats ACME.js plugin.

- tests/commands/installApp.js
When navigating to /apps, it's possible that the introjs overlay will make the
.app-list element not "visible" (because the overlay is blocking the entirety
of the page).
It's also possible that we'll win that race, but then once we navigate to the
grain list page, we'll lose a race against a different introjs overlay.
Additionally, the introjs overlay does not appear to get reactively removed
when we mark that it's no longer needed in the Session.  So we need to catch
things early.
Making the call to `disableGuidedTour()` *before* navigating to any of the
pages that feature introjs helpers should help ensure that they never render
and never cause test failures.
It's possible we should rethink how we manage introjs and testing -- perhaps we
should disable the overlays earlier for testing …
> Fix flakiness from race condition in installApp test helper

- shell/.eslintrc.yml
- shell/imports/server/accounts/ldap.js
- shell/imports/server/accounts/saml-utils.js
- shell/imports/server/shell-server.js
This should fix the errors described in the commit message for 932214aa0604fce54ff061d1555262242269047c; presumably hasOwnProperty.call is making use of `this` somehow.
> Fix LDAP hasOwnProperty breakage.

- src/sandstorm/app-index/indexer.c++
- src/sandstorm/backend.c++
- src/sandstorm/backend.h
- src/sandstorm/backup.h
- src/sandstorm/gateway.c++
- src/sandstorm/gateway.h
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/smtp-proxy.c++
- src/sandstorm/spk.c++
- src/sandstorm/supervisor.c++
- src/sandstorm/supervisor.h
- src/sandstorm/util.h
- src/sandstorm/web-session-bridge.c++
I was working on something else and got tired of ekam cutting off compiler output before the actual error, so I decided to fix a big pile of warnings. Most of these are either unused lambda captures or non-final classes with no virtual dtor. There is only one (in the second commit) that should have any functional impact; it removes an unnecessary copy caught by the compiler.
There are still a few warnings left regarding use of a couple deprecated functions and one about getaddrinfo in statically linked executables. Fixing those is less mechanical though, and this makes the output a lot less noisy.
> Clean up a bunch of c++ compiler warnings.

- tests/commands/installApp.js
Reverts sandstorm-io/sandstorm#3294
This seems to have created more test failures.
> Revert "Fix flakiness from race condition in installApp test helper"

- docs/administering/sample-config/nginx-example.conf
Prioritize newer recommendations and mention older ones if the platform uses older nginx+openssl.
Changes:
- Security:
- Disable `ssl_session_tickets`
- [`ssl_dhparam`](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_dhparam) to support EDH ciphers.
- `ssl_ciphers` always use GCM mode for AES
- Increase `Strict-Transport-Security` expiry to 2 years (from 1 year).
- Retain `ssl_session_timeout 5m`; Mozilla [recommends](https://github.com/mozilla/server-side-tls/issues/198) 1d for performance and comes with security tradeoff.
- Performance:
- Enable http/2
- Enable `ssl_session_cache`
- Misc:
- Remove [redundant](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl) `ssl on`
- Disable `ssl_prefer_server_ciphers`. Not exactly security related, but it's more of respecting …
> docs(nginx-example): update ssl config

- docs/administering/sample-config/apache-virtualhost.conf
Prioritize newer recommendations and mention older ones when applicable.
Changes:
- Security:
- Disable `SSLSessionTickets`
- Mention dhparam in `SSLCertificateFile` to support EDH ciphers.
- `SSLCipherSuite` always use GCM mode for AES
- Increase `Strict-Transport-Security` expiry to 2 years (from 1 year)
- Performance:
- Enable http/2
- Misc:
- Comment out obsolete `SSLCertificateChainFile`
- Disable `SSLHonorCipherOrder`. Not exactly security related, but it's more of respecting browser's choice, e.g. Chrome prefers `CHACHA20-POLY1305`
- OCSP stapling is mentioned but not enabled by default as it requires intermediate cert, which is not always present.
Ref: https://httpd.apache.org/docs/2.4/mod/mod_ssl.html
Related PR: https://github.com/sandstorm-io/sandstorm/pull/3158
> docs(apache-example): update ssl config

- docs/administering/faq.md
A lot more docs need to be adjusted for this release, but we might as well get this out of the way. This supersedes #3135.
> Docs: Quick fix for FAQ entry about Let's Encrypt

- shell/imports/client/admin/login-providers.js
- shell/imports/client/setup-wizard/wizard.js
The previous attempt erroneously tried to import this from `iron:router`, which is the wrong package. Tested this manually and it works. Would be nice to automate some of this (though once we actually get the linter going we should get errors about non-existent imports in the future...)
> Add explicit imports for iron:core.

- shell/imports/db-deprecated.js
- shell/imports/sandstorm-db/profile.js
This should fix #3322, but I don't have an actual LDAP setup to test with.
Help testing would be appreciated.
This was caused by the recent refactoring -- we added an explicit import
for `Settings`, but no explicit *export*.
This is actually the only remaining use of the variable, so instead of
simply revert the broken refactor, I just switched it over to using
`globalDb.collection.settings` (which is used all over the place), and
removed the `Settings` alias entirely.
> Fix broken use of Settings.

- shell/imports/sandstorm-db/db.js
This had been previously blocked on the fact that sandstorm-db was a
meteor package, and thus couldn't call into the server import.
> Remove redundant implementation of waitPromise.

- acme-dns-01-sandcats/index.js
- acme-dns-01-sandcats/package.json
- acme-dns-01-sandcats/test.js
This apparently didn't land on master, because @kentonv merged #3299 into master before merging #3302 into the `lets-encrypt-sandcats` feature branch. So, new pr for the same patch.
> Use es6 modules in the Sandcats ACME.js plugin (again).

- shell/i18n/en.i18n.json
- shell/i18n/fi.i18n.json
- shell/i18n/fr.i18n.json
- shell/i18n/nl.i18n.json
- shell/i18n/zh-CN.i18n.json
- shell/i18n/zh-TW.i18n.json
- shell/imports/client/shell.html
Fixes #2051 
Absolutely no testing has been done. But it's a language file only change. Basically, the label "Home" is solely displayed on the log in screen, where it does nothing and serves no informative purpose. I don't really see a good reason to invent a more complicated solution here.
Current:
Expected result (via Firefox dev console hacking):
I'm a little surprised the little divider also seems to go away (CSS is a mysterious beast), but I think it looks pretty clean that way.
> Remove "Home" label from login page

- docs/administering/sniproxy.md
- docs/administering/ssl.md
- mkdocs.yml
Okay, so, I rebased #1588 (and cleaned up the merge conflict with ssl.md) and then applied Asheesh's review notes. I have not adjusted the formatting of `sniproxy` where appropriate yet, nor added this doc to the sidebar, both of which I will do before merging this. I also may do a bit more review of my own, I haven't given it a clean read-through yet. I also removed the diagram because the link is dead.
@pjamar if there is any chance you still have that diagram somewhere, I would love to see it! <3
> Docs: Add sniproxy guide to share TLS port

- docs/administering/config-file.md
I believe this is accurate? We didn't change the installer, so I felt it was correct to leave the behavior specified regarding Sandcats and install behavior.
> Update HTTPS_PORT in sandstorm.conf docs

- docs/administering/config-file.md
HIDE_TROUBLESHOOTING is redundant with the far more expanded whitelisting options in the admin panel. We should mark this deprecated so new servers don't decide to use this over the database setting. I am going to open an issue to discuss the retirement of this setting further.
I also moved a "Used rarely" option up so that all the Deprecated options are at the bottom of the page.
> Mark HIDE_TROUBLESHOOTING deprecated, reordering

- .github/workflows/build.yml
- shell/.eslintrc.yml
- shell/imports/sandstorm-ui-powerbox/powerbox-server.js
- shell/imports/server/accounts/accounts-server.js
- shell/imports/server/accounts/saml-utils.js
- shell/imports/server/acme.js
- shell/imports/server/backend.js
- shell/imports/server/backup.js
- shell/imports/server/demo-server.js
- shell/imports/server/dev-accounts-server.js
- shell/imports/server/drivers/external-ui-view.js
- shell/imports/server/drivers/ip.js
- shell/imports/server/drivers/mail.js
- shell/imports/server/grain-server.js
- shell/imports/server/hack-session.js
- shell/imports/server/installer.js
- shell/imports/server/notifications-server.js
- shell/imports/server/pre-meteor.js
- shell/imports/server/scheduled-job.js
- shell/imports/server/static-asset.js
- shell/imports/server/stats-server.js
- shell/imports/shared/grain-shared.js
- shell/public/pwa-service-worker.js
This fixes a bunch of `no-unused-var` warnings, and also sets CI up to fail if the number of warnings goes *up*, which lets us actually make use of this while there are still hundreds of warnings to churn through.
> Be a bit stricter with eslint, fix a number of unused variable warnings.

- shell/imports/sandstorm-db/profile.js
- shell/imports/sandstorm-identicons/helpers.js
- shell/imports/sandstorm-identicons/identicon-server.js
- shell/imports/sandstorm-identicons/identicon.ts
Just identicon.js for now, the rest will come in future commits.
This was mostly just a matter of adding annotations in the right places,
but I also had to rename a local variable s (to `sat`), because it was
being re-assigned to a value of a different type (number to number[]).
There should be no functional impact.
The identicon module is interesting mostly because it is the only
dependency of sandstorm-db/db.js. The db stuff will require more
refactoring to get to a place where typescript will be happy with it,
but it will also have much bigger payoffs.
> Port some of the identicon stuff over to typescript.

- shell/imports/sandstorm-db/db.js
This patch:
- makes `SandstormDb` a class, rather than just a prototype function.
- moves many method definitions from the call to `extend` to the class.
The comments had the latter as a TODO (though there are still some I haven't gotten). This is also a step towards making it easier to convert this module to typescript.
> Some cleanup in db.js

- .github/workflows/build.yml
- shell/imports/server/migrations.js
Eslint caught this (with an unused-variable warning); apparently this
has been defined for a long time but never actually set to *run*.
> Actually run the removeFeatureKeys migration.

- tests/commands/uploadMeteorTestApp.js
This appears to fix `tests/account-settings`.
Looks like `appHooks` passing in https://github.com/sandstorm-io/sandstorm/runs/715515605 was a transient success, and it's back to failing.
> Make uploadMeteorTestApp.js navigate to a canonical URL

- .github/workflows/build.yml
- shell/.eslintrc.yml
- shell/imports/server/migrations.js
A migration is just a function that takes a SandstormDb and a backend,
but the majority of these functions don't actually use the backend.
This patch updates our eslint config to allow silencing an unused
argument warning by prefixing the argument with an underscore, then uses
this throughout migrations.js. This way we can start cutting down on
the noise.
> Silence a bunch of unused-argument warnings

- .github/workflows/build.yml
- shell/imports/server/transfers-server.js
As-written the function is called with nothing bound to `this`, so this
would probably just throw an exception. But clearly the intent was to
use the parameter.
Caught this via an unused variable warning.
> Fix bug re: mass transfers resulting in tokens not being deleted.

- docs/administering/ssl.md
So here's my first attempt at this. I basically give people a shunt over to sandcats-https.md right away if they are using Sandcats, then explain the other ways Sandstorm can configure HTTPS directly. I shoved reverse-proxy and self-signed tutorials out to an "Additional options" header, since that's now less ideal. I also tweaked the sniproxy bullet to let people know it's not just for Sandcats.io users here.
Paging @zenhack for opinions.
> First pass at modernizing ssl.md

- shell/client/styles/_topbar.scss
When there are many grains open on desktop or just a few grains open on Firefox on Android, the user needs to be able to scroll the navbar menu down to see them. These changes should allow that without breaking anything else. It was a little difficult to trace all the curly brackets for scss, but here are the intended changes:
@media (max-width: 900px) {
body > .topbar {
overflow: hidden; /\* REMOVE THIS \*/
overflow: scroll; /\* ADD THIS \*/
}
}
@media (min-width: 901px) {
body > .topbar > .navbar {
overflow: scroll; /\* ADD THIS \*/
}
}
> Allow scrolling the navbar

- shell/client/styles/_about.scss
This is totally not tested, but this seems like the right place to do what I did in CSS.
Before, you can only see one *very short* changelog entry. In this case, you don't even see all of the updates on that given day! Even a slightly longer changelog might require scrolling.
After, you see a healthy portion of the recent changelog, and at least on my 1080p screen with Firefox, you still can see there is another section below with the core developers and all. Usually you'll get three or so changelog entries in view at a time.
This was suggested in #2722 as one possible improvement to the page.
> Larger changelog box on about

- .github/workflows/build.yml
- shell/imports/server/hack-session.js
- shell/imports/server/notifications-server.js
- shell/imports/server/transfers-server.js
Gets rid of a few more warnings. Most of these are just prefixing a `_` in some places where the behavior is fine, but the last commit also strips out an ineffectual .then(...).
> Quiet some unused parameter warnings.

- docs/administering/ssl.md
The original script to extract Sandcats certificates no longer works,
per Sandstorm issue #3370.  This is an attempt at a new script that
appears to work properly.
The new script could also be copied to a repository owned by the
Sandstorm project or one of the committers, and it's trivial shell
commands so I'm happy to relicense it upon request.
> Updated cron script for extracting certificates

- shell/imports/server/drivers/ip.js
- src/sandstorm/app-index/app-index.c++
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/supervisor.c++
- src/sandstorm/util.c++
- src/sandstorm/util.capnp
- src/sandstorm/web-session-bridge.c++
- src/sandstorm/web-session.capnp
...to take advantage of the new flow-control stuff in capnp 0.8
This also requires some mechanical changes to the C++ uses of these,
but it's mostly just a matter of dropping some calls to ignoreResult()
and the like.
Closes #3373
> Add `-> stream` to a couple capnp methods.

- docs/administering/install-script.md
- install.sh
Noticed this while reading the discussion in #3379.
> Fix a typo in the install script and docs

- docs/administering/install-script.md
- install.sh
I read this in the Docs, and I was briefly like "I sure hope we don't download the bundle using HTTP". Which, of course, we don't. It was a quote from text in the installer script, so I fixed it in both places.
> Clarify installer downloads over HTTPS

- src/sandstorm/gateway.c++
The main thing this does is re-order some of the information. From the
questions we get it seems like 99% of the time when a user sees this
page it's because they visited the wrong domain when trying to go to
Sandstorm's main interface, but the old error message de-emphasizes this
possibility, and we've seen a lot of confusion from users.
This patch puts the most likely possibility front-and-center, so users
who don't read the full wall of text still see it. Static publishing
is a less common cause of this error, so move that further down.
This also structures the page a bit more clearly, with each possible
source of errors being under a large heading indicating "If you were
tring to do X," to make finding information generally easier.
> Improve the "unknown host" error page.

- install.sh
No longer true just for Sandcats.io.
> Remove stray HTTPS = sandcats.io in installer text

- src/sandstorm/backend.c++
- src/sandstorm/backend.h
- src/sandstorm/cgroup2.c++
- src/sandstorm/cgroup2.h
- src/sandstorm/run-bundle.c++
- src/sandstorm/supervisor.c++
This patch adds rudimentary support for cgroups (v2). Currently, we create a cgroup `grains` under the main sandstorm cgroup, and then put each grain in a cgroup within that.
Right now this doesn't really achieve anything useful, as we're not setting any policy on the cgroups, but this will enable future changes including:
- Making sandstorm robust to DoS attacks by grains; right now it's entirely possible to bog down a sandstorm box using e.g. a fork bomb inside a grain, but using cgroups we can place appropriate limits to prevent this kind of thing.
- Atomically pausing grains when taking backups, which would solve #3186.
Since in some cases (notably if we're not running as root) we may not be able to gain the ability to manage cgroups, this gracefully degrades to the status quo if we …
> Put grains in cgroups.

- src/sandstorm/app-index/app-index.capnp
- src/sandstorm/app-index/review.html
Fixes #3392
This is _completely untested_ but it appears to be a standard built-in of JavaScript, so I'm not _expecting_ it to cause a problem. In my dev console, URI encoding the SVG data fixed display. As SVGs currently do not display at all, I can't imagine this change being _worse_.
> Fix SVGs in App Index review interface

- shell/imports/server/drivers/external-ui-view.js
This was the source of https://github.com/zenhack/ttrss-sandstorm/issues/14;
Sandstorm was sending an accept header with the value `*/*; 1`, but the
correct syntax is `*/*; q=1`, and Discourse is apparently stricter than
most web servers on this point.
> Fix incorrect formatting of qValue in accept header.

- shell/imports/sandstorm-db/db.js
- shell/imports/server/hack-session.js
- src/sandstorm/hack-session.capnp
Per the comments in db.js, it is still possible to re-enable this for
now, through an un-documented database setting that users will have to
ask us about to learn of. In the comments for #3192 we'd planned on
making this an option in sandstorm.conf, but this is a bit easier to
implement and given that we're intentionally avoiding documenting this,
requiring people who need it to pop open `sandstorm mongo` seems fine.
When we finally remove this, we'll want to add a database migration that
deletes the setting.
---
It's up for discussion *when* we merge this; we could have it land in the next release if folks thing that's reasonable (that gives folks a few weeks to get the ttrss update). I could be talked into putting it off for another release if others think that's too soon.
We should …
> Disable HTTP access through hack-session.

- src/sandstorm/config.c++
- src/sandstorm/config.h
- src/sandstorm/gateway.c++
- src/sandstorm/gateway.h
- src/sandstorm/run-bundle.c++
- src/sandstorm/web-session-bridge.c++
- src/sandstorm/web-session-bridge.h
This blocks grains from loading external resources, with the exception
of images and media (per the comment, there are legitimate uses for
these that we want to allow; eventually we'll want the user to
specifically approve these).
---
While the pr itself is complete, before this lands we need to go through and find apps that this breaks, and maybe fix/update them. So far I've lightly tested:
- Davros
- uWiki
- Etherpad
- Ethercalc
- Draw.io
- Rocket.Chat
- Contact Otter
- ttrss
Of these, the following problems arose:
The others shook out some bugs in the policy but trigger no violations with the current iteration. We should go through other apps to see what else breaks.
> Content security policy for grains.

- src/sandstorm/config.h
We'll roll this out a bit more cautiously: ship it off by default, ask
people to test, once we stop getting bug reports then we can flip it
back on.
> Flip the default for ALLOW_LEGACY_RELAXED_CSP to true.

- docs/administering/sandcats-https.md
- docs/administering/sandcats.md
Use of the Sandcats certificate service was [removed in Sandstorm v0.269](https://github.com/sandstorm-io/sandstorm/commit/93d80ac4bf2ca721f239fb58395a32970f92e953).
> Update docs: Remove mention of Sandcats HTTPS certificate service

- shell/imports/client/grain.html
Oasis doesn't exist anymore, so if this message ever triggers it will just be confusing.
> Remove an obsolete reference to oasis.

- src/sandstorm/web-session.capnp
This adds headers mentioned in the discussion on #457 to the
additionalHeaders whitelist. We could add more if people want to audit
additional frameworks, but this is a start.
> Add comment CSRF headers to whitelist.

- shell/imports/client/apps/applist.html
- shell/imports/client/grain/grainlist.html
- shell/imports/client/shell-client.js
Both of these events have come to pass; we don't need the notification
code for them any more.
> Remove obsolete messges re: oasis.

- src/sandstorm/cgroup2.c++
- src/sandstorm/cgroup2.h
Apparently this functionality is configurable independently from
the rest of cgroups2, so we can't rely on it necessarily being
there.
Fixes #3457
---
@ocdtrekkie, @orblivion, can you guys test this on your own systems to make sure it fixes the problem? Once CI completes there should be a build you can download, or you can build from source.
> cgroups: don't fail to back up if cgroup.freeze doesn't exist.

- docs/install.md
@troyjfarrell pointed out on the mailing list that this is used by
`make-bundle.sh`, but not mentioned in the docs.
`gcc` is also missing as a dependency, but probably we should solve that
one by changing the script to use the same C compiler as the rest of the
build.
> Install docs: add strace to the dependency list.

- src/sandstorm/supervisor.c++
- src/sandstorm/util-test.c++
- src/sandstorm/util.c++
- src/sandstorm/util.h
N.B. I originally sent this to security@sandstorm.io out of an abundance of caution, but as @kentonv points out it's very unlikely any real apps are affected in a way that matters, and there are some deisgn questions regarding the solution, so per his request I'm opening a normal PR so we can discuss publicly.
---
Previously, getWwwFileHack() would unconditionally follow symbolic
links.  An attacker able to place symlinks in a grains /var/www could
abuse this to perform a path traversal attack, allowing regular files
visible to the supervisor but outside of the static publishing directory
to be accessed via static publishing.
This is limited to the grain's mutable storage, since the supervisor
self-sandboxes, but notably it does include the parent directory of the
sandbox, which is not …
> Fix a path traversal vulnerability involving static publishing.

- src/sandstorm/sandstorm-http-bridge.c++
In the vm created by vagrant-spk, sandstorm-http-bridge currently fails
to build, apparently because the implementation of insertSession() ends
up selecting the (deleted) copy constructor for SessionRecord. This
doesn't seem to be the case on my usual dev system, where this was
building just fine.
Perhaps the difference lies in the version of the C++ stdlib (the
compilers should be the same), but why these are different is stretching
the limits of my C++ knowledge.
...but using the copy constructor here is actually fine, since
SessionRecord doesn't own any of its data anyway. So I guess we can just
allow this.
The build failure was reported on the mailing list by @troyjfarrell,
here:
https://groups.google.com/forum/#!topic/sandstorm-dev/ARrmLkmWJcw
> Fix a build error affecting some systems.

- Makefile
- make-bundle.sh
@troyjfarrell pointed out that the build currently relies on gcc,
even though we build with clang, because of this statement in
make-bundle.sh. This patch changes it to use whatever compiler
is used for the rest of the build, avoiding the dependency on a
system gcc.
> make-bundle.sh: use the same compiler as the rest of the build.

- .github/workflows/build.yml
- shell/imports/sandstorm-db/db.js
- shell/imports/server/drivers/external-ui-view.js
- shell/imports/server/hack-session.js
- shell/imports/server/migrations.js
This has been disabled for a few months and nobody's complained, so I think we can safely remove this.
This patch removes:
- The implementations of the obsolete methods on `HackSession` itself (they now just throw exceptions)
- Support code used to check whether to enable the functionality
- Also includes a database migration to remove the setting.
- Some code paths that were only used via `HackSession`, and are not relevant when the powerbox is used to obtain HTTP access.
> Finish removing legacy HTTP access via HackSession

- shell/.meteor/packages
- shell/.meteor/versions
This will give us accurate stack traces in the browser, and generally
make debugging client-side code easier.
Note that there is a pr to merge this functionality into meteor core:
https://github.com/meteor/meteor/pull/10341
...but which is stalled on some things Sandstorm doesn't actually care
about (notably, many developers don't actually want to expose the source
to end-users, they want the source maps uploaded to a CI or something,
but Sandstorm is FOSS so we absolutely _do_ want users to have the
source).
The PR has been open for a couple years though. If/when that lands we
can switch over to using meteor core's support.
> Generate JavaScript source maps.

- src/sandstorm/sandstorm-http-bridge.c++
I tried updating the capnproto submodule and found that
sandstorm-http-bridge doesn't build against master; this patch fixes the
build errors.
The particular errors we were seeing were:
```
/ekam-provider/canonical/sandstorm/sandstorm-http-bridge.c++:767:15:
error: non-const reference cannot
bind to bit-field 'status_code'
KJ_ASSERT(status_code >= 100, (int)status_code);
^~~~~~~~~~~
```
And:
```
In file included from /ekam-provider/canonical/sandstorm/sandstorm-http-bridge.c++:24:
/ekam-provider/c++header/kj/debug.h:655:19: error: comparison between pointer and integer ('const char
*' and 'long')
DEFINE_OPERATOR(!=);
~~~~~~~~~~~~~~~~^~~
/ekam-provider/c++header/kj/debug.h:651:25: note: expanded from macro 'DEFINE_OPERATOR'
bool result = value OP other; \
~~~~~ ^  ~~~~~ …
```
> sandstorm-http-bridge: Fix some build errors against capnp master.

- src/sandstorm/supervisor.c++
- src/sandstorm/util-test.c++
- src/sandstorm/util.c++
- src/sandstorm/util.h
There are two problems:
1. Davros apparently makes /var/www itself a symlink to another
directory
2. We need to call Path::parse() on the path. Apparently I didn't test
this thoroughly enough after changing raiiOpenAtIfExistsContained
to take a kj::Path rather than a string.
We fix (1) by allowing /var/www itself to be a symlink, and then only
enforcing that symlinks within that directory do not point outside of
it.
Fixes #3472
---
@ocdtrekkie sent me a backup of his davros grain, and I've confirmed that this fixes that case. I have not tested the issue affecting docs.sandstorm.io, but from the error message I'm fairly confident that this is the issue.
I will probably send a follow pr making sure we have test coverage for all this, but this should at least fix the issue.
> Fix some regressions re: the recent static publishng symlink fix.

- tests/nightwatch.json
Use the old wire protocol with ChromeDriver (set w3c to false).  This fixes some Chrome (mis)behaviors, including failing to switch browser windows.  Tested with Chromium 80 on Debian 10.
> Fix tests/grain.js tests using Chromium 80 and Debian 10

- docs/developing/path.md
- shell/imports/client/grain-client.js
- shell/imports/client/grain/grainview.js
- tests/tests/postmessage-api.js
This commit allows apps to provide a path and hash when using the postMessage
startSharing API.
This commit uses the ``URL`` [browser API](https://caniuse.com/url), so we'll need a polyfill if we're supporting browsers that don't support this.
Implements #3428.
> Add pathname and hash support for shared URLs

- src/sandstorm/supervisor.c++
Add post-2017 system calls to the seccomp filter.
Per the comment above, it would be better to just block all calls above
a certain syscall number, but in the immediate term let's just add these
explicitly (I have some WIP on a proper blacklist on another branch).
> Add post-2017 system calls to the seccomp filter.

- docs/using/security-practices.md
I found the Beta Notice very out of date, as we are technically not "in beta", nor does the HTTP hole still exist. The Powerbox exists, so I removed that note, and I updated the CSP confinement note to specify that it's implemented.
> Docs: Update security practices for April 2021

- shell/imports/server/scheduled-job.js
I spotted this when it threw an exception while I was doing other
development. So, this fixes a bug where the intended logic was to stop
re-trying after some number of consecutive disconnects, but because of
the typo, tasks would stay in the "retry queue" forever, unless they
were eventually successful.
Not a super serious bug, since retries don't happen rapidly anyway,
but...
> Fix a typo in a variable name.

- .github/workflows/build.yml
So, currently our tests failed because Selenium flipped out, didn't actually run tests... and then why they failed was that there were no screenshots to upload. Interestingly, this means with our current test script... tests should fail when we have no test failures (and hence no screenshots).
If we upgrade to upload-artifact@v2, it generates a warning when there are no screenshots, rather than an error. I believe this is the correct way to go, though we should do better ensuring when Selenium fails, tests also fail at that step.
> Update upload-artifact to v2

- CONTRIBUTING.md
- docs/administering/install-troubleshooting.md
- docs/developing.md
- docs/developing/troubleshooting.md
- docs/sandstorm_readthedocs_modified_theme/footer.html
This is a Docs PR, but I'll hold it for Kenton because it should be simultaneously merged with it's partner, sandstorm-io/sandstorm-website#334
> Update IRC channel in docs

- docs/developing/http-apis.md
This updates the documentation following the change in 4edb2aeb1788542a78d1a3f85884848c45c09d0c (#3038).
> Update doc link to allowed non-web-browser User-Agent strings

- SECURITY.md
Someone asked us how to submit security issues with Sandstorm on IRC. I tried to look on my own to verify that the disclosure address was/is still security@sandstorm.io and could not quickly find it. Common GitHub practice is a SECURITY.md file, in this format, generated from the GitHub Security tab for this repo.
90 day disclosure is pretty standard, and as a community project, I think we should ask for at least that, but given Sandstorm's automatic update model, I feel it's safe to disclose a couple days after we release a fix. So hopefully I got the policy about where it should be there.
We probably should also add a https://securitytxt.org/ to the website.
> Add a SECURITY.md file

- tests/utils.js
Fixes #3550, I think. (Well, it won't fix that tests are failing left and right, but it might give us screenshots again.)
> Artifacts from failing tests get valid filenames

- src/sandstorm/web-session.capnp
Adds some additional ownCloud/NextCloud client headers relating to https://github.com/mnutt/davros/issues/114.
The new headers:
* `oc-checksum` - a hash (typically `SHA1`) of the entire file. After all chunks have been uploaded, davros should be checking this to ensure that it uploaded correctly, otherwise we may end up saving a corrupted file. [this header has been around for a while, I should have been doing this all along]
* `oc-chunk-offset` - part of a new chunking scheme. Right now the legacy chunking scheme relies on all chunks being the same size in order to calculate the offset (number * chunkSize); this header would allow the client to vary the chunk size based on timing/bandwidth.
* `oc-lazyops` - I'm unlikely to implement this soon, but it would be a way for the client to …
> Add more owncloud/nextcloud client headers

- docs/install.md
- `flex` and `bison` are required for the build.
- `locales` is required under Debian/Ubuntu; otherwise the build fails because `/usr/share/i18n/charmaps` is missing.
- bullseye is now the latest Debian stable release.  The source build fails on stretch because `SECCOMP_FILTER_FLAG_LOG` is undeclared, unless (presumably) the kernel headers were to be upgraded.  (See also 2021-09-06 discussion on IRC.)  The `contrib-` is no longer necessary because the `vboxsf` kernel module is in `debian/bullseye64`.
> Update documentation on installing from source

- docs/install.md
`zlib-static` worked, and I verified once again that everything I added to the install list is actually required for the build.
> Update build instructions for Fedora (closes #3565)

- .gitignore
- tests/nightwatch.json
We haven't atually used phantomjs in a long time, but apparently we
never actually removed these bits.
---
I noticed this while otherwise fussing around with our test suite.
> Remove remaining references to phantomjs

- Makefile
Caught this while debugging the new test failures. We delete
meteor-testapp.spk, so we should delete this one too.
> make ci-clean: delete test-app.spk

- shell/i18n/en.i18n.json
I couldn't help but notice and fix this after testing the install script repeatedly.
> Fix typo on login providers page

- .github/workflows/doc-ci.yml
- docs/README.md
- docs/generate.sh
- docs/requirements.txt
This at least outputs an artifact we can download, which gets us one step closer to Ian's wish at https://github.com/sandstorm-io/sandstorm/pull/3573#issuecomment-938296567.
I've tested this with [act](https://github.com/nektos/act) using the command
```
act -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest -W .github/workflows/doc-ci.yml
```
(I had to remove any broken symlinks in the source directory before it would work, but that's an act problem, not a sandstorm one.)
The act environment doesn't perfectly match the GitHub Actions environment, so there's no guaranteeing this will work, but it should be pretty close...
> Add a workflow for previewing doc changes

- docs/install.md
`git-blame` points to 6b0ad2716 (first mention) and e055782e1 (second mention).  I guess, as of the second commit, it was missing from the `dnf` and `apt-get` commands but not the overall list.  Easy enough to fix.
> install.md: remove duplicate mention of strace

- Makefile
- icons/Gruntfile.js
- icons/package.json
This switches to the maintained `grunt-webfonts` and sets options to fix the font generation by normalizing the icon sizes.
The font is not exactly the same as can be seen here:
Compared to the original font:
The problem is that the SVGs are not the same size and while the old version of `grunt-webfont` would normalize the sizes automatically. In the last versions of the package you had to specify explicitly that you wanted the icons normalized and the algorithm for doing that seems to have changed slightly.
If we want to preserve the font as it was we need to normalize the SVGs manually in an editor.
> Fix the icon font generation

- Vagrantfile
The first commit is to avoid a warning when provisioning the machine.
The second commit adds an upper bound of 3 GB of RAM to the Vagrant VM.  The rationale is that systems have more and more RAM these days, and using 1/4 of the system RAM seems quite overkill in many cases.  2 GB might also be a reasonable upper bound, I chose 3 GB to be on the generous end.  With this patch, a user can tweak either the desired fraction of RAM, the lower bound, or the upper bound, each by adjusting a single number.  I somewhat doubt that 512 MB is enough these days to provision a Sandstorm VM, but if the user really only has 2 GB of system RAM, it is probably worth trying and letting them deal with the consequences...
> More Vagrantfile improvements

- src/sandstorm/backup.c++
- src/sandstorm/sandbox.c++
- src/sandstorm/sandbox.h
- src/sandstorm/supervisor.c++
...between the supervisor and the backup code. We should ideally pull
most of what's common out into a shared module, but I was looking at
this while debugging #3584, and it seemed like a good start.
> Factor out some common sandbox setup code

- .github/workflows/build.yml
- docs/install.md
This should be unnecessary now that #3576 has been merged.
This should also fix the build error we've been seeing in CI.
> Stop installing a very old version of meteor

- .github/workflows/build.yml
- docs/install.md
Recently, the clang update script [was changed](https://chromium.googlesource.com/chromium/src/tools/clang.git/+/5c0e867150ea239d3f0f0316370e71672c77b91a) to require python3, specifically.
I discovered this change when attempting to build Sandstorm using a [Dockerfile](https://gist.github.com/garrison/f025090ce914641f0d1e492612dcbd4e#file-dockerfile-debian) that worked previously.  I have verified that this change alone fixes the build under Debian; it seems that python2 is not also required (nor is `/usr/bin/python`, for that matter).
In Fedora, "python" already refers to python3, so no change was needed to that install line.
> Update doc: Installing from source now requires python3

- docs/administering/faq.md
This adds an FAQ entry we can refer to about #3512 
I'm not happy with where in Docs it's located, but other troubleshooting pages are presently for new installs or app development. We should probably break a selection of FAQ entries out into a more general troubleshooting section, but the key part for me is that Docs is searchable and this places it somewhere it can be found and referred to.
I am not positive I correctly described the nature of the inotify setting or it's behavior from a "How Linux works" standpoint, and of course, any notes on writing style would be appreciated.
> Docs: Provide fix for inotify limit issue

- shell/client/styles/_topbar.scss
...Filling the entire vertical space alotted for it.
I have found this difficult to press at its current size on mobile; this
essentially doubles the size, so it should be better.
Aesthetically it would be nice to also enlarge the grain icon for
symmetry, but just applying the same rule ends up with it overflowing
the bounds significantly.
I am trying to resist the temptation to redo this whole section with
flexbox & grid right now, but I might find time to actually do that later,
as I think it would make all this easier to reason about.
---
---
It looks the same on desktop as it did before.
> Make the grain close button bigger on mobile.

- src/sandstorm/update-tool.c++
I encountered this while testing #3603; as written, the `update-tool add`
subcommand does not print out the correct public key for the keypair
that it generates; instead, it prints out the seed used to generate the
keypair. This patch changes the code to actually generate the keypair
from the seed, and then print out the public key that should be added
to update-tool.capnp
I assume this code was not used to generate the current contents of that
file, since if it was loading the keyring would fail (which is the
problem I encountered).
> Fix a bug in the update tool's key generation.

- src/sandstorm/run-bundle.c++
Take 2 for fixing #3584; this follows @kentonv's suggestion (2). As it turns out, we were already creating a userns in the right spot, but it doesn't take effect until after a fork(), so we have to do some footwork to make sure the rest of the logic happens in a child process.
Caveat: a few tests still fail on my machine, but for reasons that don't seem to be related: things like: 
```
✖ tests/system-api
- Test system api (18.338s)
Timed out while waiting for element <.grainlog-contents > pre> to be present for 5000 milliseconds.  - expected "visible" but got: "not found"
at Object.module.exports.Test system api (/home/isd/src/foreign/sandstorm/tests/tests/system-api.js:38:6)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
Despite the fact that, when I run this …
> Don't map ourselves to root in the user namespace.

- src/sandstorm/test-app/shutdown.html
- src/sandstorm/test-app/static-index.html
- src/sandstorm/test-app/test-app.c++
- src/sandstorm/test-app/test-app.capnp
- src/sandstorm/test-app/test-app.html
- tests/apps/web-publishing.js
N.B. this includes the commits from #3603, which should be reviewed & merged first.
This fixes the `apps/web-publishing.js` test that has been failing since forever.
It folds the functionality from the https://github.com/jparyani/sandstorm-test-app/tree/web-publishing into the test app we maintain in-tree, and then implements the solution I suggested [here](https://github.com/sandstorm-io/sandstorm/issues/3240#issuecomment-1024863154), i.e. defer the exit() until the return message has been sent.
> Fix web-publishing test

- LICENSE
- shell/imports/client/shell.html
From some of the refactoring, the files referred to in the license have moved. One additional note, pnglib.js no longer exists in our project as far as I can tell: It was removed in #2268 back in 2016.
> Update file locations in license

- .github/workflows/build.yml
- Makefile
- shell/imports/client/backups.ts
- shell/package.json
I find myself wanting to just do the typechecking bit often, and especially with how much output eslint currently generates, this makes things nicer to work with.
This also fixes an import path that tsc was complaining about.
> Split `lint` target into separate `lint` and `typecheck-ts` targets.

- shell/i18n/en.i18n.json
So this is the most minor nitpick I've ever done: On desktop, the Grain Settings button does not show text, and shows the hint when you hover it. However, on mobile, where I've never before tried to view Grain Settings, it uses the "text" value on the sidebar menu, where it's the only not-capitalized option.
> Capitalize settings

- install.sh
This is another quick one: We refer people to an old wiki page which then tells people to go to the docs. Just updating this URL to be direct.
> Installer: Update help URL

- docs/developing/publishing-apps.md
I attempted to follow these instructions this evening, and gpg gave me an error claiming that "--export-options is not considered an option", and I had a fairly difficult time getting a search result to explain why. (I assumed it was removed/renamed/replaced.) As it turns out, an answer about the same error for a different option revealed... gpg is sort of picky about the order of arguments, and so I tried flipping the order here, and it worked without incident.
> Docs: Fix GPG export instructions

- docs/administering/sandcats-https.md
Just a random Asheesh comment I noticed. It looks like it was committed with the original creation of the page... commented out.
- We now get an A rating from Qualys SSL Test.
- This is no longer Sandcats-specific anyways.
- I don't think we should list this specifically in this page because the criteria regularly changes.
- If this was left here as a note we should improve the rating, commented out in docs is a bad place for it.
> Docs: Delete B rating comment

- docs/administering/config-file.md
This originally-temporary setting has existed for about two years now, and once we are comfortable with the new CSP, will still probably exist *a while*... we probably should have it documented.
> Document ALLOW_LEGACY_RELAXED_CSP

- .github/workflows/build.yml
- release-process.md
- shell/imports/server/install-server.js
- shell/imports/server/installer.js
This should fix #3429, and when installing apps I generally see stable memory usage now, though I haven't actually tried an install with all of the usual apps going at once.
This reworks the logic for uploading and downloading packages so that it applies some backpressure, instead of letting stuff build up in memory. It possibly applies *too much* backpressure, as it waits for each call to ByteStream.write(), but since it's generally reading from a network connection and writing to a local socket which is much faster I suspect this won't have much impact in practice. The "right" solution is probably to expose capnp-c++'s streaming support via node-capnp.
Along the way I did a few minor cleanups of nearby code, and fixed some warnings.
> Apply backpressure when installing packages.

- release.sh
Per discussion on IRC, the script currently pushes the tag, but does not
push to the master branch. This patch adds that logic to the script, so
hopefully Kenton won't have to remember to do this going forward.
Note that this is untested.
> release.sh: automatically push to master

- docs/administering/for-work.md
- shell/i18n/en.i18n.json
- shell/i18n/fi.i18n.json
- shell/i18n/fr.i18n.json
- shell/i18n/nl.i18n.json
- shell/i18n/zh-CN.i18n.json
- shell/i18n/zh-TW.i18n.json
Trying to keep up with Google's rebranding is probably a pointless endeavor, but our lang files didn't even all use the same Google branding, as two of them referred to G Suite, and the rest as Google Apps for Work. This PR updates our language in both the setup wizard and the admin panel that this is Google Workspace now.
> Google Apps for Work is Workspace

- src/sandstorm/web-session-bridge.c++
...when using ALLOW_LEGACY_RELAXED_CSP=false
Note that this doesn't actually work yet, because the browsers don't
implement this feature, but I've at least gotten it into the standards.
I will probably have to do the implementation work myself too.
But we may as well go ahead and add this to Sandstorm without waiting
for the browsers.
See also: https://github.com/sandstormports/community-project/issues/12
> Block webrtc

- src/sandstorm/backend.capnp
- src/sandstorm/run-bundle.c++
This patch:
- Partially documents the ShellCli interface in backend.capnp
- Exposes the path to the socket as a constant in the capnp schema.
There are two methods left un-documented, since I don't fully understand
what they do, and was hoping Kenton could shed some light on them, since
he wrote the code. In particular:
- I don't know what the directory argument to createAcmeAccount does.
- I'm generally fuzzy about how setAcmeChallenge is used.
If I can get clarification on those, I'll rebase and finish the job.
> Partially document ShellCli.

- src/sandstorm/app-index/app-index.c++
- src/sandstorm/sandstorm-http-bridge.c++
- src/sandstorm/supervisor.c++
I assumed that all membranes should have this enabled, but maybe that's not the case. Happy to change if so.
The reason this is necessary is because the default for this is being changed: https://github.com/capnproto/capnproto/pull/1530
> Override shouldResolveBeforeRedirecting to true in capnp membranes.

- docs/developing/troubleshooting.md
This improves our advice on modifying apps to open links in a new tab with a bit of JS that will only affect external links, while leaving relative links alone.
> Docs: Add JS to target external links

- .github/FUNDING.yml
I think we should make it easy for people checking out the repo to figure out where they can support the project. I'm not super-prepared to go plastering requests for donations across readmes and docs pages, but I think we should turn the built-in sponsor button on for those explicitly looking for it. There are a couple projects that I would love to find someone to do for us if we had the support.
> Add sponsor button to repo

- src/sandstorm/seccomp-bpf/filter.s
This patch updates the experimental (bpf_asm) seccomp filter so that it allows a few more syscalls, and no longer tries to filter specific arguments to setsockopt()/getsockopt(). This significantly improves compatibility; notably it makes mongo happy, and at this point *most* (but not all) apps in the market seem to work as expected.
> Improvements to experimental seccomp filter

- install.sh
Fixes #3625 
I don't totally want to shut this off, because this completely opt-in telemetry tells us A. if there's people installing Sandstorm at some vague rate (or at least trying and failing) and B. what issues they are running into. However, I could not rebuild the J(A)SON Datastore app, because it's a bitrotted meteor-spk app. https://github.com/sandstorm-io/sandstorm-error-collector is significantly simpler and more straightforward.
I've shared the grain I've pointed this at to both Kenton and Ian so everyone knows where it is.
> Report install failures to Alpha

- shell/imports/server/drivers/mail.js
Prior message implied the publicId was a grain name, not a grain mail id, and left it unclear where the id was coming from.
> Clarify email error message

- src/sandstorm/appid-replacements.capnp
It's been a half decade since WordPress on Sandstorm was updated, I am not inclined to chase people down for keys who may or may not have retained them that long. @JamborJan was the last keyholder, but a Sandstorm-the-company team member or two may have also held it.
The pending update I have does *not* bump the WordPress version forward at this time, but does clean up some package bitrot, updates the base box slightly, and most importantly, adds Ian's powerbox-http-proxy so that WordPress can grab media when importing a backup. (It's likely this will make many other plugins usable inside the sandbox, and very likely, allow updates for non-read-only plugins.)
I flubbed line 123 here, I will force-push the branch in a couple minutes.
> Replace WordPress app key

- docs/administering/ssl.md
This is intended to add better guidance for configuring HTTPS. Some providers have different requirements than `token`, but more often than not, it suffices. The examples I saw which also specified a `baseUrl` in the documentation specified that it was the default value, so I suspect we do not need to provide examples for every DNS provider listing it's baseUrl in our documentation.
I did want to specify, since it's a point of confusion if you go spelunking in the usage section of many of these providers, the format requirements of the Options JSON needing double quotes, as they are not present in any of the upstream examples, but multiple people have reported them as required for successful Sandstorm configuration.
> Docs: Add Options JSON instructions

- shell/i18n/en.i18n.json
- shell/imports/client/grain-client.js
I found several prompts that are not internationalized.  With this change (and a coming related PR to add the Russian localization,) we can localize additional prompts:
I will submit the Russian PR once #3697 is merged.
> I18n for grain renaming and grain deletion prompt

- .github/workflows/build.yml
- .github/workflows/doc-ci.yml
- .github/workflows/doc-prod.yml
The Github actions used by Sandstorm are quite out of a date. Some of the versions are being deprecated; it's generally good practice to update them as appropriate.
> Update github actions to latest

- .github/workflows/doc-ci.yml
It's kind of difficult to test whether doc-ci works on Ubuntu 22.04 (quick answer: it does!) without a workflow-dispatch event trigger. This adds workflow-dispatch so it can manually be run by a repo owner.
> Add workflow-dispatch to doc-ci to run manually

- shell/npm-shrinkwrap.json
- shell/package.json
- shell/tsconfig.json
When I run `npm run lint` I received an warning saying @typescript-eslint/typescript-estree (a dependency of @typescript-eslint/parser) did not support the version of Typescript used in the project. 
This updates @typescript-eslint/parser to a more modern version without touching eslint itself (since I don't know what the consequences are of that)
--
I rebased this on #3707 so I can prove that the lint process still runs. I'm happy to rearrange if preferred.
> Update @typescript-eslint/parser for compatibility with used typescript

- .well-known/funding-manifest-urls
This is a non-code change to indicate we have provenance and authority to submit funding requests for the project. To be clear, this refers to funding for the Sandstorm Community project, and will be implemented as a fork, not as a direct update to the original repository.
> Add funding-manifest-urls check

- docs/developing/path.md
Generally most users will see a ui- prefix in their ephemeral subdomains, so I added this to some here to make this obvious. Note that if someone has a wildcard host config like alpha-*.example.com, they might have a ephemeral domain that looks like alpha-ui-45sda64dsfsd464ggdsg5.example.com, but that is uncommon enough I am not worried about clarifying it here.
Also, people cannot try this on Oasis.
> Docs: Update ephemeral subdomains, remove Oasis link

- docs/developing.md
- docs/index.md
I hope these commits to the old repository are welcome. If they get pushed to the site then it will help users get to where the active development is taking place.
These link updates also include one change to the dev usergroup, which is now on dev.io instead of Google groups.
If these types of updates are welcome then I will try to spend more time updating documentation links. I'm not a professional dev, so I hope my pull requests are being done correctly; I welcome feedback if there's something I can improve.
> Update documentation links to point to the sandstorm.org domain instead of .io

- docs/administering/install-troubleshooting.md
We've had a bunch of people have weird reports of issues with Ubuntu 24.04, and so far this has been the solution to all of them. I think we should codify it in the documentation page.
@Michael-S found this solution, and deserves all the credit.
> Docs: Add Ubuntu 24.04 fix instructions

- docs/developing/publishing-apps.md
@neuroradiology pointed out this was not documented well. Considering we recommend people try apps in experimental before we publish them, and developers may want to make sure their app looks good on the market view, I think this would be a good place to point it out as well.
> Docs: Note experimental app market
